### DISCUSSION TITLE
WARNING message about dhparam.pem

### DISCUSSION THREAD

**Discussion by i13302** [nginx-proxy/nginx-proxy#1646] [Q&A]
## Bugs
Nginx-proxy container is logged WARNING message about dhparam.pem .
Maybe this message is cause that my container isn't access by https://... .

I can't access to `https://nextcloud.mydomain.mydns.jp:41443` and `https://whoami3 ...` , I read `docker logs` that found `"GET /remote/fgt_lang?lang=/../../../..//////////dev/cmdb/sslvpn_websession HTTP/1.1" 499 0 "-" "Python-urllib/3.5"`, I executed restart nginx-proxy container. so container logs is written WARNING message about dhparam.pem . 

after all, i can't access my Nextcloud.

### Logs
```
$ docker images |head
REPOSITORY                       TAG                  IMAGE ID            CREATED             SIZE
jwilder/nginx-proxy              latest               dc82a251b5c6        19 hours ago        156MB
```

```
$ docker logs
WARNING: /etc/nginx/dhparam/dhparam.pem was not found. A pre-generated dhparam.pem will be used for now while a new one
is being generated in the background.  Once the new dhparam.pem is in place, nginx will be reloaded.
forego     | starting dockergen.1 on port 5000
forego     | starting nginx.1 on port 5100
dockergen.1 | 2021/05/31 19:28:46 Generated '/etc/nginx/conf.d/default.conf' from 10 containers
dockergen.1 | 2021/05/31 19:28:46 Running 'nginx -s reload'
dockergen.1 | 2021/05/31 19:28:46 Watching docker events
dockergen.1 | 2021/05/31 19:28:48 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
2021/05/31 19:28:57 [notice] 41#41: signal process started
Generating DSA parameters, 4096 bit long prime
dhparam generation complete, reloading nginx
```
### Any files
`cat run.sh`
```
#!/bin/bash

docker run -d --restart=always \
	-p 41080:80 -p 41443:443 \
	-v /var/run/docker.sock:/tmp/docker.sock:ro \
	-v $(pwd)/certs:/etc/nginx/certs:ro \
	-v $(pwd)/custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf \
	--name nginx-proxy --net reverce-proxy jwilder/nginx-proxy
```

Virtual Hosts
```yaml
  whoami3:
    image: jwilder/whoami
    networks:
      - reverce-proxy
    environment:
      - VIRTUAL_HOST=whoami3.mydomain.mydns.jp
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
      - CERT_NAME=fullchain
        
networks:
  reverce-proxy:
    external: true
```
and In `Nextcloud docker-compose.yml`

```yaml
...
  app:
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - MYSQL_HOST=db
      - VIRTUAL_HOST=nextcloud.mydomain.mydns.jp
      - NEXTCLOUD_TRUSTED_DOMAINS=mydomain.mydns.jp nextcloud.mydomain.mydns.jp
    env_file:
      - db.env
      - app.env
...
```

**Comment by buchdag** [comment]
Hi.

First this has probably nothing to do with the dhparam warning. This warning is self explanatory: the container starts with a pre generated dhparam, generates a new one, then restart nginx to use the self generated one. The process complete normally as you can see in those two line:

```
Generating DSA parameters, 4096 bit long prime
dhparam generation complete, reloading nginx 
```

Second why are you using `VIRTUAL_PROTO` and `VIRTUAL_PORT` with jwilder/whoami ? I think you're confusing the frontend and backend protocols: 

- `VIRTUAL_PROTO=https` tells nginx-proxy that the communication **between the proxy and the jwilder/whoami container** should happen over https. jwilder/whoami does not support https by itself so this can't work.
- `VIRTUAL_PORT=443` tells the proxy that the communication **between the proxy and the jwilder/whoami container** should happen on the port 443 of jwilder/whoami. This port isn't exposed by jwilder/whoami and nothing listen on it so this can't work either.

Both of those variable aren't used to control how the communication **between the client (your browser) and the proxy** should happen. I'd suggest you re read [the SSL support documentation](https://github.com/nginx-proxy/nginx-proxy#ssl-support) carefully.

Third: container to be proxied need to be on the same network as the nginx-proxy container. Your `app` service in your Nextcloud `docker-compose.yml` does not appears to be configured on the same network (`reverce-proxy`) as nginx-proxy.

**Reply by buchdag** [reply]
Fourth: if you're going to user non standard HTTP and HTTPS ports, there is additional configuration to be made using two environment variable that aren't documented yet.

```console
docker run -d --restart=always \
	-p 41080:80 -p 41443:443 \
	-v /var/run/docker.sock:/tmp/docker.sock:ro \
	-v $(pwd)/certs:/etc/nginx/certs:ro \
	-v $(pwd)/custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf \
	--env HTTP_PORT=41080 \
	--env HTTPS_PORT=41443 \
	--name nginx-proxy --net reverce-proxy jwilder/nginx-proxy
```

**Reply by i13302** [reply]
I appreciate your help.

I was trial and error to rewrite command and script while referring your comments.

So, I can access to `nextcloud.mydomain.mydns.jp;41443` and `whoami1.mydomain.mydns.jp;41443` ~ `whoami3.mydomain.mydns.jp;41443`. 

Maybe my accessed way is that i accessed `nextcloud.mydomain.mydns.jp;41443` , next forwarded to server machine in reverse proxy and nextcloud container by port 41443 (haven't do port translation), next access reverse proxy container (nginx-proxy) , finally proxyed to nextcloud (or whoai) container while port forwarding from 41443 to 443 in  nginx-proxy container. 

This is my rewrited files.

in whoami docker-compose.yml
deleted  `VIRTUAL_PROTO=https` and `VIRTUAL_PORT=443`
```
version: '2'
services:
  whoami1:
    image: jwilder/whoami
    networks:
      - reverce-proxy
    environment:
      - VIRTUAL_HOST=whoami1.mydomain.mydns.jp
  whoami2:
~~~~~~~~~~~ generally whoami2,whoami3 is same settings. ~~~~
networks:
  reverce-proxy:
    external: true
```

run nginx-command.
I don't know reason , but i didn't need `--env HTTP_PORT`.
```
docker run -d --restart=always \
	-p 41080:80 -p 41443:443 \
	-v /var/run/docker.sock:/tmp/docker.sock:ro \
	-v $(pwd)/certs:/etc/nginx/certs:ro \
	-v $(pwd)/custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf \
	--name nginx-proxy --net reverce-proxy jwilder/nginx-proxy
```

and belonged same network as ` external: true` in Nextcloud `docker-compose.yml`
```
networks:
      - reverce-proxy
```

Thanks your great advices !
