### DISCUSSION TITLE
how to put htaccess on a proxied container for a certain subdir

### DISCUSSION THREAD

**Discussion by zanzara** [nginx-proxy/nginx-proxy#1652] [General]
I got a good description how to setup a nginx reverse proxy with letsencrypt from [here](https://linuxhandbook.com/nginx-reverse-proxy-docker/)
It works fine with the 2 container I'm running but for one of them I need a `htaccess`  for one subdir only and I don't know how to do it.

This is my docker-compose.yml for the reverse proxy:
```yml
version: "3.7"

services:

    reverse-proxy:
        image: "jwilder/nginx-proxy:latest"
        container_name: "reverse-proxy"
        volumes:
            - "html:/usr/share/nginx/html"
            - "dhparam:/etc/nginx/dhparam"
            - "vhost:/etc/nginx/vhost.d"
            - "certs:/etc/nginx/certs"
            - "/run/docker.sock:/tmp/docker.sock:ro"
        restart: "always"
        networks: 
            - "net"
        ports:
            - "80:80"
            - "443:443"
    letsencrypt:
        image: "jrcs/letsencrypt-nginx-proxy-companion:latest"
        container_name: "letsencrypt-helper"
        volumes:
            - "html:/usr/share/nginx/html"
            - "dhparam:/etc/nginx/dhparam"
            - "vhost:/etc/nginx/vhost.d"
            - "certs:/etc/nginx/certs"
            - "/run/docker.sock:/var/run/docker.sock:ro"
        environment:
            NGINX_PROXY_CONTAINER: "reverse-proxy"
            DEFAULT_EMAIL: "my@mail.net"
        restart: "always"
        depends_on:
            - "reverse-proxy"
        networks: 
            - "net"
volumes:
  certs:
  html:
  vhost:
  dhparam:

networks:
  net:
    external: true
```
and this is one of the container i use:

```yaml
version: "3.3"

services:
    mytools:
        image: "my/frontend-prod:latest"
        container_name: "mytools"
        restart: unless-stopped
        environment:
            APP_ENV: production
            VIRTUAL_HOST: "my.website.net"
            VIRTUAL_PORT: 80
            LETSENCRYPT_HOST: "my.website.net"
        networks: ["net"]
        volumes:
          - ./:/app

networks:
    net:
      external: true
```

What i understood so far from [here](https://hub.docker.com/r/jwilder/nginx-proxy) 
how to enable Basic Authentication Support putting  a /etc/nginx/htpasswd/$VIRTUAL_HOST  file .
This had worked fine, but it secures the whole domain (my.website.net). 
**But I only need one subdir!**  I.e. (my.website.net/api-docs) 

So how to do a  Custom Nginx Configuration Per-VIRTUAL_HOST with something like this inside?
```
location /api-docs {
    auth_basic           “Administrator’s Area”;
    auth_basic_user_file   /etc/nginx/htpasswd/my.website.net; 
}
```
If I add this nginx conf  into a file named "my.website.net"  loacated  in /etc/nginx/vhost.d 
the complete domain does not response anymore.
I can observe, that /etc/nginx/vhost.d/default i.e.  is dynamically created by the letsencrypt container.

Any ideas?
Appreciating any hints.

BR
