### DISCUSSION TITLE
Bad Gateway upgrading from annixa and nginx not working - Config file required?

### DISCUSSION THREAD

**Discussion by stevmon** [nginx-proxy/nginx-proxy#1658] [Q&A]
I have been trying to upgrade a customer who was set up by another company. 

They are using wordpress in a container that listens on port 9000.

It was also set up using (in the yml file):

```yaml
  nginx-backend:
      image: nginx:latest
      ports:
```

```yaml
  proxy:
      image : annixa/docker-nginx-letsencrypt-proxy
      ports:
```

There is also an nginx config file (default.conf) in a persistent directory containing:

```nginx
location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
}
```
I have exposed port 9000 in the wordpress service config but I still get "Bad Gateway" response in the browser.

It DOES pull the certificates and they are persistent as required from another discussion I started earlier.

Been pulling my hair out again trying to determine why this is for the last two weeks.
