### DISCUSSION TITLE
Custom configuration is not available in container

### DISCUSSION THREAD

**Discussion by stefanrinderle** [nginx-proxy/nginx-proxy#1666] [Q&A] [answered]
# Issue description

I want to use a Custom Nginx Configuration as described in the documentation. My Dockerfile is as follows:

```dockerfile
FROM jwilder/nginx-proxy
COPY conf/softvis3dcom.conf /etc/nginx/conf.d/softvis3dcom.conf
```

After the container start, i can not find the file in /etc/nginx/conf.d/. Only the default.conf.

To verify that the copy works i once change the destination path to something else and it worked.

Could it be that the /etc/nginx/conf.d/ gets "cleaned up" on start? Or do i miss something? I start the container via docker-compose:

```yaml
services:
  nginx-proxy:
    build: .
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /usr/share/nginx/html
    networks:
      - nginx-net
    restart: always
```

If you need more info, i am happy to provide it. Maybe i did something wrong?
