### DISCUSSION TITLE
Using on non-docker application

### DISCUSSION THREAD

**Discussion by atropos112** [nginx-proxy/nginx-proxy#1669] [Q&A]
Hi,

I wanted to write the question in google groups as told but I can't seem to access it so I will explain my issue/question here.

I wanted to run Docker nginx with a docker-compose.yml:
```
version: '3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /apps/proxy/conf:/etc/nginx/conf.d
      - /apps/proxy/vhost:/etc/nginx/vhost.d
      - /apps/proxy/html:/usr/share/nginx/html
      - /apps/proxy/dhparam:/etc/nginx/dhparam
      - /apps/proxy/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    depends_on:
      - nginx-proxy
    volumes:
      - /apps/proxy/vhost:/etc/nginx/vhost.d
      - /apps/proxy/html:/usr/share/nginx/html
      - /apps/proxy/dhparam:/etc/nginx/dhparam:ro
      - /apps/proxy/certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    restart: always

networks:
  default:
    external:
      name: nginx-proxy
```

and its running well on docker containers, the moment i include "nginx-proxy" so that it can detect them, fantastic tool. However I have an application (code-server to be specific, but it shouldn't matter) I cant simply paste something like this into default.conf (conf of nginx )
```
server {
    listen 80;
    listen [::]:80;
    server_name mydomain.com;

    location / {
      proxy_pass http://localhost:8080/;
      proxy_set_header Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection upgrade;
      proxy_set_header Accept-Encoding gzip;
    }
}
```
My guess is that what is "localhost" for me is not "localhost" for nginx given that it is inside a docker (im new to this docker stuff, so I might be talking shit). I saw the [issue](https://github.com/nginx-proxy/nginx-proxy/issues/998) where they mentioned many approaches, none of them worked for me. In particular I tried running a dummy docker as [CWempe](https://github.com/CWempe/nginx-proxy/tree/upstream_name#non-docker-host) suggested 
```
docker run -d \
    -e VIRTUAL_HOST=foo.bar.com \
    -e VIRTUAL_PORT=8080 \
    -e UPSTREAM_NAME=webserver.local \
    --rm \
    cwempe/docker-dummy:latest
```
This didnt't work, nginx didnt even detect it which made me think its probably because its not on the nginx-network so i added that (and turned it into docker-compose for convenience)
```
version: '3.3'
services:
    docker-dummy:
        environment:
            - VIRTUAL_HOST=mydomain.com
            - VIRTUAL_PORT=8080
            - UPSTREAM_NAME=127.0.0.1
        image: 'cwempe/docker-dummy:latest'

networks:
  default:
    external:
      name: nginx-proxy
```
Then looking at default.conf i get

```
# mydomain.com
upstream mydomain.com {
                                ## Can be connected with "nginx-proxy" network
                # code-server_docker-dummy_1
                        server 172.25.0.7 down;
}
server {
        server_name mydomain.com;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        include /etc/nginx/vhost.d/default;
        location / {
                proxy_pass http://mydomain.com;
        }
}
server {
        server_name mydomain.com;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        return 500;
        ssl_certificate /etc/nginx/certs/default.crt;
        ssl_certificate_key /etc/nginx/certs/default.key;
}
```
So sure it has seen it but it also believes it is down and doesn't include the VIRTUAL_PORT at all and obviously the 127.25.0.7 IP doesn't make sense to me either. Changing 127.25.0.7 -> 127.0.0.1:8080 does nothing. Any idea how I can remedy this ? Thank you for your input in advance.
