### DISCUSSION TITLE
Access proxied container by local network

### DISCUSSION THREAD

**Discussion by FrancescoSaverioZuppichini** [nginx-proxy/nginx-proxy#1689] [Q&A]
Hi guys,

I have the following docker-compose file

```yml
version: "3.8"
services:

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks: 
      - proxy

  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - VIRTUAL_HOST=heimdall.local
      - VIRTUAL_PORT=80
    volumes:
      - ./heimdall/config:/config
    # ports:
    #   - 7567:80
      # - 443:44x3
    networks: 
      - proxy
    restart: unless-stopped

networks:
  proxy:
```

I would like to specify the `location` directly. My goal is to access the `heimdall` container by doing something like `<IP>/heimdall` while still having all the traffic proxied by nginx so I can add a SSL certificate

Thanks

Francesco
