### DISCUSSION TITLE
Need help with docker-compose file: Run kirby with docker-compose behind reverse nginx proxy

### DISCUSSION THREAD

**Discussion by Pryla** [nginx-proxy/nginx-proxy#1713] [Q&A]
Hi guys, I am currently trying out [Kirby](https://getkirby.com/). It's really great and my customer loves it. Now i am trying to get it up and running on a server, which is already running and hosting multiple sites with the help of this great nginx reverse proxy by jwilder. But now I have issues to get this php code running. Maybe someone here can help me to see the issue. Currently the container starts and stops again after one second.

My `Dockerfile` looks like this (it is pretty much a copy from the [cookbook](https://getkirby.com/docs/cookbook/setup/kirby-meets-docker#example-3-sharing-a-filesystem__dockerfile), removed everything related to apache since I am using nginx):

```
# Use offical ubuntu:20.04 image
FROM ubuntu:20.04

# Set timezone
ENV TZ=Europe/Berlin

# Set geographic area using above variable
# This is necessary, otherwise building the image doesn't work
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Remove annoying messages during package installation
ARG DEBIAN_FRONTEND=noninteractive

# Install packages: web server & PHP plus extensions
RUN apt-get update && apt-get install -y \
  php \
  php-curl \
  php-dom \
  php-gd \
  php-intl \
  php-json \
  php-mbstring \
  php-xml \
  php-zip && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

# Remove default content (existing index.html)
RUN rm /var/www/html/*

# Change web server's user id to match local user, replace with your local user id
RUN usermod --uid 1000 www-data

# Tell container to listen to port 80 at runtime
EXPOSE 80

```

`docker-compose-yml`
```
version: '3'
services:
  webserver:
    build: .
    image: image_name
    networks:
      - proxy-tier
    container_name: kirbyserver
    ports:
      - "8099:80"
    environment:
      - VIRTUAL_HOST=sub.domain.tld
      - VIRTUAL_ROOT=/var/www/html
      - VIRTUAL_NETWORK=nginx-proxy
      - LETSENCRYPT_HOST=sub.domain.tld
      - LETSENCRYPT_EMAIL=my@email.tld
    volumes:
      - /srv/www/production/sub.domain.tld:/var/www/html
    env_file:
      - ./id.env

networks:
  proxy-tier:
    external:
      name: nginxproxy_default
```

The `id.env`-file
`USERID=1000`

The nginx proxy file is the standard docker-compose:
```
version: '2'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - ./certs:/etc/nginx/certs:ro
      - ./letsencrypt-acme:/etc/acme.sh
      - ./max_upload.conf:/etc/nginx/conf.d/max_upload.conf:ro
    restart: always

  letsencrypt-nginx-proxy-companion:
    image: nginxproxy/acme-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./certs:/etc/nginx/certs:rw
      - ./letsencrypt-acme:/etc/acme.sh
    volumes_from:
      - "nginx-proxy"
    restart: always
```

my root-user-id is 0 and I have read somewhere that in this case the id should be set to 1000. I have tried around many things in many days but without any luck. That is why I started this discussion. Any help is appreciated. 

Thanks a lot!
