### DISCUSSION TITLE
SSL for the custom VIRTUAL_PORT

### DISCUSSION THREAD

**Discussion by phken91** [nginx-proxy/nginx-proxy#1730] [Q&A]
hi, i got some problem during i using nginx-proxy for serving non standard port application with ssl

please have a look the `docker-compose.yml` below:
```
ghost:
    image: "ghost:alpine"
    container_name: "ghost"
    environment:
      - VIRTUAL_HOST=example.com
      - VIRTUAL_PORT=2368
      - url=https://example.com
      - LETSENCRYPT_HOST=example.com
```

if i set `url=http://example.com` it will work nicely but without https
when i change to `url=https://example.com` then will getting 404 on browser
what i guess maybe my service is listening port `2368`, so during redirect to `443` will getting error

i would like to add in my customize nginx.conf for upstream/forwarding my request to 2368, but have no idea how to make it
any one can guide me about that?

thanks advance!
