### DISCUSSION TITLE
access via IP not host

### DISCUSSION THREAD

**Discussion by mqliang** [nginx-proxy/nginx-proxy#1732] [Q&A]
Hi,  the docker-compose example need to access via host name:

```
$ docker-compose up
$ curl -H "Host: whoami.local" localhost
I'm 5b129ab83266
```

Is there anyway to configure so that I can access directly via IP, without specifying HOST?

**Comment by mqliang** [comment]
To be more specific:

I want a docker-compose.yaml file like:

```
version: '3'

services:
  webapp:
    restart: always
    image: webapp

  nginx:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    links:
      - webapp:webapp
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

```

I want `curl <nginx-IP>` to access webapp (without specifying HOST header)
