### DISCUSSION TITLE
Path based routing (VIRTUAL_PATH) needs tests and feedbacks.

### DISCUSSION THREAD

**Discussion by buchdag** [nginx-proxy/nginx-proxy#1733] [General]
The long requested path based routing feature is now available for tests in the `ninxproxy/nginx-proxy:dev` and `ninxproxy/nginx-proxy:dev-alpine` Docker images.

[The documentation forr the feature is available on the `dev` branch.](https://github.com/nginx-proxy/nginx-proxy/tree/dev#path-based-routing)

Tests and remarks are welcome and required before we can consider this feature ready to be merged to `main`.

 This feature is a combination of #599 + #1011 + #1083 + #1594 (in #1607),  plus #1699 for some additions.

**Comment by AlexanderLieret** [comment]
I have written two test cases. https://github.com/AlexanderLieret/nginx-proxy/tree/dev_more_tests

1. Test the SSL backend. 
2. Testcase for ef9cd4c

**Comment by junderw** [comment]
There should be a test for 16e0eed44f11fec616d3663323488f6e9f55c155 by making sure that:

1. `default_location` is used when alone
2. `VHOST_location` is used when both exist
3. `VHOST_PATHSHA1_location` is used when all 3 exist.

I don't think combinations of 1 + 3 and 2 + 3 pairs, or 2,3 alone need to be tested.

**Reply by AlexanderLieret** [reply]
The new test case in ce20ff2 should cover this.

**Comment by OliverRhyme** [comment]
http to https redirect does not work properly. Calling post request to http endpoint will instead call get method on the reverse proxy

See logs
```
nginx-proxy          | nginx.1     | <REDACTED> - - [18/Aug/2021:09:23:31 +0000] "POST /api/v1/register HTTP/1.1" 301 169 "-" "PostmanRuntime/7.28.2" "-"
asi-server           | 2021-08-18 09:23:32.081 [DefaultDispatcher-worker-1] TRACE ktor.application - 404 Not Found: GET - /register
nginx-proxy          | nginx.1     | <REDACTED> - - [18/Aug/2021:09:23:32 +0000] "GET /api/v1/register HTTP/1.1" 404 0 "http://<REDACTED>/api/v1/register" "PostmanRuntime/7.28.2" "172.19.0.5:8080"
```
But calling https directly works just fine

```
asi-server           | 2021-08-18 09:27:17.602 [DefaultDispatcher-worker-3] TRACE ktor.application - 400 Bad Request: POST - /register
nginx-proxy          | nginx.1     | <REDACTED> - - [18/Aug/2021:09:27:17 +0000] "POST /api/v1/register HTTP/1.1" 400 62 "-" "PostmanRuntime/7.28.2" "<REDACTED>"
```

My docker-compose env variables is 

```
- VIRTUAL_HOST=REDACTED
- VIRTUAL_PORT=8080
- VIRTUAL_PATH=/api/v1/
- VIRTUAL_DEST=/
```

**Reply by junderw** [reply]
This might be an issue with whatever is making the requests... what is making the requests?

The 301 is sent to the client, and the client is the one making the GET request to http... so I'm guessing this is a client issue unless there is something nginx-side we can do to prevent this kind of behavior.

**Reply by junderw** [reply]
Looks like 301 redirects can not forward POST requests.

https://stackoverflow.com/a/13628908

**Reply by junderw** [reply]
Looks like 307 is a temporary redirect, and will preserve POST data, the client will know how to re-send the POST.

https://stackoverflow.com/a/21821236

**Reply by OliverRhyme** [reply]
> This might be an issue with whatever is making the requests... what is making the requests?
> 
> The 301 is sent to the client, and the client is the one making the GET request to http... so I'm guessing this is a client issue unless there is something nginx-side we can do to prevent this kind of behavior.

Im testing it via postman

**Reply by OliverRhyme** [reply]
How can I enable http to https redirect while also preserving http method?

**Reply by OliverRhyme** [reply]
> Looks like 307 is a temporary redirect, and will preserve POST data, the client will know how to re-send the POST.
> 
> https://stackoverflow.com/a/21821236

If im right, does the nginx proxy automatically creates the 301 redirect to the https? How can I change it to 307 redirect only with non get requests?

**Reply by junderw** [reply]
IMO this should be default behavior.

since 301 always turns into GET, it should dynamically choose 301 or 307 based on whether the request method is GET or not.

I don't think you can do anything until a fix comes out.

**Reply by junderw** [reply]
I have made a PR addressing this issue. Can you test it? I am currently unable.

https://github.com/nginx-proxy/nginx-proxy/pull/1737

**Reply by junderw** [reply]
Doesn't look like it's working... I guess the only way is to use if {}... the documentation on how evil it is says a return or rewrite is the only exception... so maybe it's ok to be if {}

**Reply by junderw** [reply]
ok, this should work. Please try it out when you have the chance.

**Reply by OliverRhyme** [reply]
> I have made a PR addressing this issue. Can you test it? I am currently unable.
> 
> #1737

Okay I'll test it, and maybe also create a PR myself if it does not get fixed

**Reply by AlexanderLieret** [reply]
@OliverRhyme you might want to fix your API.

This sounds like your API embeds plain http links on the page. The client browser will then send all (potential private) data in plaintext to access the "secured" page and then gets a 301 request to use https. A malicious attacker can intercept these data and just access the page like the normal client.

**Reply by OliverRhyme** [reply]
> @OliverRhyme you might want to fix your API.
> 
> This sounds like your API embeds plain http links on the page. The client browser will then send all (potential private) data in plaintext to access the "secured" page and then gets a 301 request to use https. A malicious attacker can intercept these data and just access the page like the normal client.

yes all my api endpoint shall/should only use https

**Reply by OliverRhyme** [reply]
@junderw I think this should be 308 rather than 307 as per [RFC7238](https://tools.ietf.org/html/rfc7238) same with status 301 over 302

**Reply by OliverRhyme** [reply]
> @junderw I think this should be 308 rather than 307 as per [RFC7238](https://tools.ietf.org/html/rfc7238) same with status 301 over 302

also have a look at this for the possible decision tree https://stackoverflow.com/a/42138726/4952907

**Reply by junderw** [reply]
It looks like all browsers support 308...

Maybe we should just use 308 and drop 301 altogether?

**Reply by junderw** [reply]
IE 11, of course, does not support it however. (and is still used in some internal networks in corporate-land)
https://github.com/kubernetes/ingress-nginx/issues/1825

**Reply by junderw** [reply]
Google Drive uses a non-standard 308, "Resume Incomplete"...

Yeah, maybe the solution is: "don't use http to POST stuff"

(Edit: ... maybe the internet was a big mistake... *existential crisis*)

**Reply by OliverRhyme** [reply]
> Google Drive uses a non-standard 308, "Resume Incomplete"...
> 
> Yeah, maybe the solution is: "don't use http to POST stuff"
> 
> (Edit: ... maybe the internet was a big mistake... _existential crisis_)

what do you think we should do or workarounds?

**Reply by buchdag** [reply]
@junderw @OliverRhyme maybe we should keep the discussion about 301 vs 308 on #1737 ? 😅

**Comment by warren-ru** [comment]
I use all the functionality (two VIRTUAL_PATH services, one of them use VIRTUAL_DEST, a "default" file for configuring nginx location) in the project I mentioned in #1699
Everything is working properly, HTTP to HTTPS redirection either.

**Comment by AlexanderLieret** [comment]
I found another bug.The function `NETWORK_ACCESS=internal` is applied to the server block instead of the location block.
This sets this behavior for all locations.

**Comment by Rolly992** [comment]
Btw, are multiple paths supported?
For example
- VIRTUAL_PATH=/api/v1/,/assets

UPD: From the code I see, it is

**Comment by JMLX42** [comment]
I think I have a bug regarding `VIRTUAL_PROTO`:  I have two services, one with `VIRTUAL_PROTO=https` and another with `VIRTUAL_PROTO=http`.

```yml
services:
    gateway:
        image: nginxproxy/nginx-proxy:dev
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ../nginx-proxy/certs:/etc/nginx/certs
        networks:
            - reverse-proxy
    doc:
        image: smartshape-doc:10.7.0
        environment:
            - 'VIRTUAL_HOST=smartshape.io.test'
            - 'VIRTUAL_PATH=/documentation/'
            - 'VIRTUAL_PORT=80'
            - 'VIRTUAL_PROTO=http'
        networks:
            - reverse-proxy
    app:
        image: smartshape-app:next
        environment:
            - 'VIRTUAL_HOST=smartshape.io.test'
            - 'VIRTUAL_PATH=/app/'
            - 'VIRTUAL_PORT=80'
            - 'VIRTUAL_PROTO=http'
        networks:
            - reverse-proxy
    server:
        image: smartshape-server:next
        environment:
            - 'VIRTUAL_HOST=smartshape.io.test'
            - 'VIRTUAL_PATH=~^/(account|annotation|file|scene|streaming|update|webhook|live)/'
            - 'VIRTUAL_PORT=443'
            - 'VIRTUAL_PROTO=https'
```

For some reason, `nginx` always uses `http` and I get this error in my Web browser:

```
Bad Request

Your browser sent a request that this server could not understand.
Reason: You're speaking plain HTTP to an SSL-enabled server port.
Instead use the HTTPS scheme to access this URL, please.
Apache/2.4.41 (Ubuntu) Server at localhost Port 80
```

If I start only the `gateway` and `server` services though, the requests goes through.
We will remove the HTTPS from the `server` service backend, but IMHO that it still a bug.
