### DISCUSSION TITLE
Kirby CSM setup fails with fastcgi and custom _location block - do I need to override the default location block? If yes, how?

### DISCUSSION THREAD

**Discussion by Pryla** [nginx-proxy/nginx-proxy#1735] [Q&A]
Hello guys,

I have a working nginx server that already works and handles many different websites.

No I have a new test-subdomain where I am testing out the [kirby-cms ](https://getkirby.com/)which usually works best with apache (or at least the creators only really care about apache) but the documentation and the support forum gives some advice for the nginx-configuration.

The default template `default.conf` from `/etc/nginx/conf.d`

```
# sub.domain.tld
upstream sub.domain.tld-upstream {
				# Cannot connect to network of this container
				server 127.0.0.1 down;
				## Can be connected with "nginxproxy_default" network
			# name_subdomain_1
			server xxx.xx.0.2:80;
}
server {
	server_name sub.domain.tld;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	# Do not HTTPS redirect Let'sEncrypt ACME challenge
	location ^~ /.well-known/acme-challenge/ {
		auth_basic off;
		auth_request off;
		allow all;
		root /usr/share/nginx/html;
		try_files $uri =404;
		break;
	}
	location / {
		return 301 https://$host$request_uri;
	}
}
server {
	server_name sub.domain.tld;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/sub.domain.tld.crt;
	ssl_certificate_key /etc/nginx/certs/sub.domain.tld.key;
	ssl_dhparam /etc/nginx/certs/sub.domain.tld.dhparam.pem;
	ssl_stapling on;
	ssl_stapling_verify on;
	ssl_trusted_certificate /etc/nginx/certs/sub.domain.tld.chain.pem;
	add_header Strict-Transport-Security "max-age=31536000" always;
	include /etc/nginx/vhost.d/default;
	location / {
		root   /var/www/public;
		include fastcgi_params;
		fastcgi_pass sub.domain.tld-upstream;
		include /etc/nginx/vhost.d/sub.domain.tld_location;
	}
}
```

What I should add from [the docs from `kirby`](https://getkirby.com/docs/cookbook/setup/nginx#boilerplate-config):
```
server {
  listen 8080; # Can be omitted if Nginx runs on Port 80
  index index.php index.html;
  server_name localhost; # Adjust to your domain setup
  root /usr/share/nginx/html; # Adjust to your setup

  location / {
    try_files $uri $uri/ /index.php$is_args$args;
  }

  location ~* \.php$ {
    try_files $uri =404;
    fastcgi_pass php:9000; # Adjust to your setup
    include fastcgi.conf;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_param PATH_INFO $fastcgi_path_info;
    fastcgi_param SERVER_PORT 8080; # Only needed if external port is different from the listen port
  }
}
```
Maybe the first part can be omitted but the location-part seems pretty important. Unfortunately it is not possible to just override the default part. What should I do?

I have modified the above code many many times. Currently it looks like this:

```
location / {
    try_files $uri $uri/ /index.php$is_args$args;
  }

  location ~* \.php$ {
    try_files $uri =404;
    fastcgi_pass localhost:9001;
    include fastcgi.conf;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_param PATH_INFO $fastcgi_path_info;
 # fastcgi_param SERVER_PORT 9001; # Only needed if external port is different from the listen port
  }
```
---

My kirby `Dockerfile` looks like this:
```
FROM php:7.4-fpm

# Install packages: web server & PHP plus extensions
RUN apt-get update && apt-get install -y \
  git \
  curl \
  libpng-dev \
  libonig-dev \
  zip \
  unzip

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install pdo_mysql mbstring exif bcmath gd

#install composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
COPY composer.json composer.lock /var/www/html/
RUN composer install

WORKDIR /var/www/html

USER $user
```

And the `docker-compose.yml`:
```

version: '3'

services:

  name_subdomain:
    build:
      context: .
      dockerfile: Dockerfile
    image: myimage-image
    restart: always
    networks:
      - proxy-tier
      - kirby
    ports:
      - 9001:80
    expose:
      - 9001
    environment:
      - VIRTUAL_HOST=sub.domain.tld
      - VIRTUAL_PROTO=fastcgi
      - VIRTUAL_PORT=80
      - VIRTUAL_ROOT=/var/www/html
      - VIRTUAL_NETWORK=nginx-proxy
      - LETSENCRYPT_HOST=sub.domain.tld
      - LETSENCRYPT_EMAIL=mymail@gmail.com
    volumes:
      - ./:/var/www/html

networks:
  kirby:
  proxy-tier:
    external:
      name: nginxproxy_default
```

And finally the `docker-compose.yml`config for the proxy:
```
version: '2'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - ./certs:/etc/nginx/certs:ro
      - ./letsencrypt-acme:/etc/acme.sh
      - /srv/www/production/name.de/sub.domain.tld_location:/etc/nginx/vhost.d/sub.domain.tld_location:ro
    restart: always

  letsencrypt-nginx-proxy-companion:
    image: nginxproxy/acme-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./certs:/etc/nginx/certs:rw
      - ./letsencrypt-acme:/etc/acme.sh
    volumes_from:
      - "nginx-proxy"
    restart: always
```

I have tried many many hours and days to get it to work but I could not.

Currently with the shown setup the domain errors in a 404 with no content
`nginx.1    | sub.domain.tld xx.xxx.xxx.xxx - - [17/Aug/2021:17:29:20 +0000] "GET / HTTP/2.0" 404 556 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/xx.xxx.xxx.xxx Safari/537.36"`
