### DISCUSSION TITLE
Implementing nginx-proxy with IPv6

### DISCUSSION THREAD

**Discussion by rafalrozek** [nginx-proxy/nginx-proxy#1744] [Show and tell]
I'm totally newbie and I'm trying to introduce nginx-proxy on my server.
I had docker-compose.yml like that:
```yaml
version: '3'
services:
    web:
        container_name: ci4-web
        build:
            context: ./docker
        ports:
            - 80:80
        volumes:
            - .:/var/www/html/bank/

```
With apache config:
```apache
<VirtualHost [::]:80>
    DocumentRoot "/var/www/html/bank/public/"
    ServerName bank.local
    <Directory "/var/www/html/bank/public/">
        AllowOverride all
    </Directory>
</VirtualHost>
```
And everything worked fine. But I want to move this page to subdomain. I modified docker-compose.yml to that:
```yaml
version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - ENABLE_IPV6=true

  web:
    container_name: ci4-web
    build:
      context: ./bank-website/docker/
    expose:
      - "8000"
        
    volumes:
      - ./bank-website/:/var/www/html/bank/
    environment:
      - VIRTUAL_HOST=bank.local
      - VIRTUAL_PORT=8000
```

But now, bank.mywebsite.com is not working ("This site can’t be reached"). What I'm doing wrong? 
Thanks for any hint.

**Comment by buchdag** [comment]
Hi.

Your `ci4-web`'s apache config says it's listening on port `80` but on your second compose file you're exposing and using `VIRTUAL_PORT` with port `8000`. Which one is it ?

You're using `bank.local` as a `VIRTUAL_HOST` in your compose file and testing `bank.mywebsite.com`. Which one is it ?

Also `ENABLE_IPV6` is for IPv6 support between the nginx-proxy container and the proxied containers, not for IPv6 support between the outside world and the nginx-proxy container, are you sure that's what you want to achieve ?

**Reply by rafalrozek** [reply]
Thank you for response.

- Of course, I should expose and use port 80 on `ci4-web`
- Ok, so I understand that I should enter my public domain name in `VIRTUAL_HOST` (bank.mywebsite.com)
- I want to expose my nginx-proxy on IPv6 address of my server. But I think it's exposed correctly because `mywebsite.com` response is `503 Service Temporarily Unavailable`. Something is wrong with `ci4-web` configuration.

My current docker-compose.yml:
```yaml
version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  web:
    container_name: ci4-web
    build:
      context: ./bank-website/docker/
    expose:
      - "80"
    volumes:
      - ./bank-website/:/var/www/html/bank/
    environment:
      - VIRTUAL_HOST=bank.mywebsite.com
      - VIRTUAL_PORT=80
```

But bank.mywebsite.com still not responding.

**Reply by tkw1536** [reply]
> I want to expose my nginx-proxy on IPv6 address of my server. But I think it's exposed correctly because mywebsite.com response is 503 Service Temporarily Unavailable. Something is wrong with ci4-web configuration.

This sounds like ipv6 support is working correctly, but `nginx-proxy` cannot reach the `ci4-web` container.
I would expect the same failure to occur when using ipv4.

When a browser attempts to connect to `bank.mywebsite.com` `nginx-proxy` will receive the request (be it via ipv4 or via ipv6) and then internally forward it to `ci4-web`. 

This internal forwarding will always use the private addresses of the `web` and `nginx-proxy` containers, regardless of what the public protocol is. The private addresses are typically private ipv4 addresses. But that doesn't matter because the forwarding uses `http` and lives on the application layer - not on the network layer (see [OSI model](https://en.wikipedia.org/wiki/OSI_model) if you don't know what layers I am talking about).

To verify my hypothesis above, compare the output of ``` curl --ipv6 bank.example.com ``` and ``` curl --ipv4 bank.example.com ```. My guess is they will both show `503 Service Temporarily Unavailable`.

> I want to expose my nginx-proxy on IPv6 address of my server. But I think it's exposed correctly because mywebsite.com response is 503 Service Temporarily Unavailable. Something is wrong with ci4-web configuration.

Probably your hypothesis is correct - something is wrong with the ci4-web configuration. 
If I remember my apache configuration right it should be enough for apache to listen on port 80 like so:

```apache
Listen 80
<VirtualHost *:80>
    DocumentRoot "/var/www/html/bank/public/"
    ServerName bank.mywebsite.com
    <Directory "/var/www/html/bank/public/">
        AllowOverride all
    </Directory>
</VirtualHost>
```

It does not have to listen on ipv6 adresses, because your container doesn't have any.
It might also be `nginx-proxy` cannot connect to the container because it doesn't actually listen on that port.
Have you tried connecting to it directly and/or looking at the logs?

**Reply by rafalrozek** [reply]
Thank you a lot. I experimented a lot with `curl` and now I'm sure that `ci4-web` configuration is ok. I changed `docker-compose.yml` to this:
```
version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=bank.example.com

  web:
    container_name: ci4-web
    build:
      context: ./bank-website/docker/
    volumes:
      - ./bank-website/:/var/www/html/bank/
    environment:
      - VIRTUAL_HOST=bank.example.com
    
```
And now when i go to `http://www.example.com` I see my website correctly. But bank.example.com or any other subdomain still not working 
```
root@me:~# curl --ipv6 bank.example.com
curl: (6) Could not resolve host: bank.example.com
```
