### DISCUSSION TITLE
Help with docker-compose

### DISCUSSION THREAD

**Discussion by alextac98** [nginx-proxy/nginx-proxy#1748] [Q&A] [answered]
Hi everyone,

I am trying to get a container working behind an nginx-proxy, but I am having some issues. Namely, no-matter what port I put as the `VIRTUAL_PORT`, I still get the same `502 Bad Gateway` error returned, with the following output in the container:
```bash
nginx-proxy            | nginx.1     | 2021/08/25 08:15:43 [error] 84#84: *3 no live upstreams while connecting to upstream, client: 192.168.14.2, server: unifi.home.alextac.com, request: "GET / HTTP/1.1", upstream: "http://unifi.home.alextac.com/", host: "unifi.home.alextac.com"
nginx-proxy            | nginx.1     | unifi.home.alextac.com 192.168.14.2 - - [25/Aug/2021:08:15:43 +0000] "GET / HTTP/1.1" 502 559 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" "unifi.home.alextac.com"
```
 However, I know my container is outputting to the correct port, because when I specify the port in the URL I get the expected site. Does anyone know what I've done wrong? What is the `VIRTUAL_PORT` specifically for - the container side or the host side?

```yaml
version: '3'

services:
  unifi-controller:
    image: jacobalberty/unifi
    container_name: unifi_controller
    restart: always
    user: unifi
    volumes:
      - ./backup:/unifi/data/backup
    environment:
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=unifi.home.alextac.com
      - LETSENCRYPT_HOST=unifi.home.alextac.com
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8123:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery 
```

Thank you!

**Comment by alextac98** [comment, marked as answer]
5 minutes after posting this, I found the issue: I did not share the network with the container... Here is the correct `docker-compose.yml` for those who run into the same issue:
```yaml
version: '3'

services:
  unifi-controller:
    image: jacobalberty/unifi
    container_name: unifi_controller
    restart: always
    user: unifi
    volumes:
      - ./backup:/unifi/data/backup
    environment:
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=unifi.home.alextac.com
      - LETSENCRYPT_HOST=unifi.home.alextac.com
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery 

networks:
  default:
    external:
      name: nginx-proxy
```
