### DISCUSSION TITLE
I get 502 after pulling the latest docker image

### DISCUSSION THREAD

**Discussion by grwag** [nginx-proxy/nginx-proxy#1755] [Q&A]
Hey guys, i hope someone can help.

I had a working environment with

- jwilder/nginx-proxy
- letsencrypt-nginx-proxy-companion
- nextcloud
It was running for several years, and i updated the containers occasionally. However, after the last _docker pull jwilder/nginx-proxy_ I started getting only 502 responses.
I restarted every container, but nothing helped.
Here are my configs:

nginx docker-compose.yml:

```yaml
﻿version: '3'
services:
  nginx-proxy:
    container_name: 'nginx-proxy'
    image: 'jwilder/nginx-proxy:latest'
    ports:
      - '80:80'
      - '443:443'
    restart: always
    labels:
      - 'com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy'
    networks:
      - proxy
    volumes:
      - '/path/to/certs:/etc/nginx/certs:ro'
      - 'nginx-etc:/etc/nginx/vhost.d'
      - 'nginx-share:/usr/share/nginx/html'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - './conf/client_body.conf:/etc/nginx/conf.d/client_body.conf'

  nginx-proxy-le:
    container_name: 'nginx-proxy-le'
    image: 'jrcs/letsencrypt-nginx-proxy-companion:latest'
    restart: always
    networks:
      - proxy
    volumes:
      - '/path/to/certs:/etc/nginx/certs:rw'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - 'nginx-etc:/etc/nginx/vhost.d'
      - 'nginx-share:/usr/share/nginx/html'

networks:
  proxy:
    external:
      name: nginxproxy_nginx-proxy

volumes:
  nginx-etc:
  nginx-share:
```

nextcloud docker-compose.yml:

```yaml
﻿version: '3'

services:
  nextcloud:
    container_name: 'nextcloud'
    build: .
    restart: unless-stopped
    environment:
      - LETSENCRYPT_HOST=my.virtual.hostname
      - LETSENCRYPT_EMAIL=cert@mail.com
      - VIRTUAL_HOST=my.virtual.hostname
      - VIRTUAL_PORT=8080
    volumes:
      - '/data/nextcloud/data:/var/www/html'
    networks:
      - proxy
    ports:
      - '8081:80'

networks:
  proxy:
    external:
      name: nginxproxy_nginx-proxy
```

nginx default.conf:
```nginx
# my.host.com
upstream cloud.greshawag.com {
        ## Can be connected with "nginxproxy_nginx-proxy" network
        # nextcloud
        server 172.18.0.5:8080;
}
server {
        server_name my.host.com;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        # Do not HTTPS redirect Let'sEncrypt ACME challenge
        location ^~ /.well-known/acme-challenge/ {
                auth_basic off;
                auth_request off;
                allow all;
                root /usr/share/nginx/html;
                try_files $uri =404;
                break;
        }
        location / {
                return 301 https://$host$request_uri;
        }
}
server {
        server_name my.host.com;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/my.host.com.crt;
        ssl_certificate_key /etc/nginx/certs/my.host.com.key;
        ssl_dhparam /etc/nginx/certs/my.host.com.dhparam.pem;
        ssl_stapling on;
        ssl_stapling_verify on;
        ssl_trusted_certificate /etc/nginx/certs/my.host.com.chain.pem;
        add_header Strict-Transport-Security "max-age=31536000" always;
        include /etc/nginx/vhost.d/default;
        location / {
                proxy_pass http://my.host.com;
        }
}
```

The containers are all on the same network, a letsencrypt certificate was created, the nginx config was written, but when i try to access the site, I#m just getting a 502. In the nginx log i can find the following extry:
**nginx.1     | 2021/08/30 07:23:45 [error] 186#186: *103 connect() failed (111: Connection refused) while connecting to upstream, client: 84.57.251.233, server: my.host.com, request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.5:8080/favicon.ico", host: "my.host.com", referrer: "https://my.host.com/"**

Any help would be appreciated.
Thanks grwag
