### DISCUSSION TITLE
Why running laravel app I got 503 Service Temporarily Unavailable error ?

### DISCUSSION THREAD

**Discussion by sergeynilov** [nginx-proxy/nginx-proxy#1761] [Q&A]
Hello,

Running laravel project based on jwilder/nginx-proxy I got error in browser

```
503 Service Temporarily Unavailable
nginx/1.21.1
```

with url:
`http://127.0.0.1:80`

Running docker and checking containers in my OS I see :

```
$ docker-compose up -d
nginx-projectname is up-to-date
php-radius is up-to-date
mysql-projectname is up-to-date
php-userend is up-to-date
php-projectname is up-to-date
user@HostingOS:/ProjectPath/lml$ docker ps -a
CONTAINER ID   IMAGE                         COMMAND                  CREATED        STATUS                          PORTS                               NAMES
b4ccbc8fdeda   roneichiarandi/php71-alpine   "/entrypoint.sh php-…"   3 hours ago    Up 21 minutes                   0.0.0.0:32770->9000/tcp             php-projectname
0b16d2c805df   mysql:latest                  "docker-entrypoint.s…"   3 hours ago    Up 20 minutes                   0.0.0.0:3306->3306/tcp, 33060/tcp   mysql-projectname
8b9f111aa298   roneichiarandi/php71-alpine   "/entrypoint.sh php-…"   3 hours ago    Up 21 minutes                   0.0.0.0:32768->9000/tcp             php-radius
3ae492cfdd89   roneichiarandi/php71-alpine   "/entrypoint.sh php-…"   3 hours ago    Up 21 minutes                   0.0.0.0:32769->9000/tcp             php-userend
2db8d9b0901e   jwilder/nginx-proxy:latest    "/app/docker-entrypo…"   3 hours ago    Up 20 minutes                   0.0.0.0:80->80/tcp                  nginx-projectname
9b9bf003a1a3   jwilder/nginx-proxy           "/app/docker-entrypo…"   7 hours ago    Exited (2) 6 hours ago                                              inspiring_lovelace
05626a8da615   jwilder/nginx-proxy           "/app/docker-entrypo…"   7 hours ago    Created                                                             adoring_goldwasser
e5dddc493fe2   adminer                       "entrypoint.sh docke…"   8 months ago   Up 2 hours                      0.0.0.0:8095->8080/tcp              gotoconsult_adminer
0c6a52f43a8b   mysql:5.7.28                  "docker-entrypoint.s…"   8 months ago   Restarting (1) 44 seconds ago                                       gotoconsult_db


```

My docker-compose.yml :
```yaml
version: '2'

services:
  nginx: # NGINX-PROXY
    image: 'jwilder/nginx-proxy:latest'
    container_name: 'nginx-projectname'
    ports:
      - '80:80'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock
      - ./docker/nginx.tmpl:/app/nginx.tmpl
      - .:/var/www/html

  # PHP7-alpine fpm
  php:
    container_name: 'php-projectname'
    image: 'roneichiarandi/php71-alpine'
    ports:
      - "9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/var/www/html
      - ./logs:/tmp/logs
    environment:
      - VIRTUAL_HOST=projectname.dev
      - VIRTUAL_PORT=
      - PHP_FPM=1
    links:
      - 'radius'
    extra_hosts:
      - "radius.dev:172.18.0.1"

  # PHP7-alpine fpm
  userend:
    container_name: 'php-userend'
    # image: 'matriphe/alpine-php:fpm-5.6'
    image: 'roneichiarandi/php71-alpine'
    ports:
      - "9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../userend:/var/www/html
      - ../userend/logs:/tmp/logs
    environment:
      - VIRTUAL_HOST=userend.dev
      - VIRTUAL_PORT=
      - PHP_FPM=1

  # PHP7-alpine fpm
  radius:
    container_name: 'php-radius'
    image: 'roneichiarandi/php71-alpine'
    ports:
      - "9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../radius:/var/www/html
      - ../radius/logs:/tmp/logs
    environment:
      - VIRTUAL_HOST=radius.dev
      - VIRTUAL_PORT=
      - PHP_FPM=1

  mysql:
    container_name: 'mysql-projectname'
    image: 'mysql:latest'
    ports:
      - "3306:3306"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mysqlvolume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=projectname

volumes:
    mysqlvolume:

```

I suppose url is valid
`http://127.0.0.1:80
`
but what have I check in nginx options?

Thanks!
