### DISCUSSION TITLE
HTTPS Proxy for Proxy

### DISCUSSION THREAD

**Discussion by NilsBaumgartner1994** [nginx-proxy/nginx-proxy#1787] [Q&A]
Imagine this scenario:

I have developed a nice application consisting of an nginx-proxy, backend and frontend, like your everyday normal project. Now i want to add an extra nginx-proxy with an ssl (https) certificate.
So my goal is, that my underlaying application does not need to care about on which host it is.

Problem: When using multuple nginx-proxy behind each other it results in an loop. By not using https i can set a custom DEFAULT_HOST and use this to prevent looping.

My desired flow is:
```
       /                         /application1       /backend
OuterProxy --(adds https cert)---> InnerProxy ----> Application
```

ERROR: Too many cookies set. Yeah this results because, the inner proxy will forward the requests to itself, resulting in a loop.

Here is a docker-compose.yaml

```
services:

  outer:
    container_name: outer
    image: nginxproxy/nginx-proxy:dev
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DEFAULT_HOST=mydomain.de
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro # allow to read running dockers
      - ./certificate.crt:/etc/nginx/certs/mydomain.de.crt:ro
      - ./private.key:/etc/nginx/certs/mydomain.de.key:ro
    networks:
      - reverse-proxy

  inner:
    container_name: inner
    image: nginxproxy/nginx-proxy:dev
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=mydomain.de
      - DEFAULT_HOST=inner.bar.com
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro # allow to read running dockers
    networks:
      - reverse-proxy

  app:
    container_name: outer_app
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=inner.bar.com
      - VIRTUAL_PATH=/whoami
     networks:
      - reverse-proxy

```
