### DISCUSSION TITLE
client intended to send too large body

### DISCUSSION THREAD

**Discussion by chrisfoster121** [nginx-proxy/nginx-proxy#1790] [Q&A] [answered]
Hello, I am constantly getting this issue when uploading anything over like 1 MB while using this as my reverse proxy:

`2021/10/08 00:14:27 [error] 180#180: *827 client intended to send too large body: 10485760 bytes, client`

My docker compose looks like
```
proxy:
    image: jwilder/nginx-proxy:alpine
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    container_name: nextcloud-proxy
    networks:
      - nextcloud_network
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - ./proxy/certs:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

```

However, I tried editing a file in conf.d, default.conf I believe, to add `client_max_body_size 50M;` and it seems to get rewritten on container restart even though I have a bound volume for it. Have I done something wrong?
