### DISCUSSION TITLE
Dockerhub

### DISCUSSION THREAD

**Discussion by gyl89** [nginx-proxy/nginx-proxy#1804] [General]
It seems that nginx version in dockerhub is 1.19.3, unlike the latest github version. Is it possible to update the dockerhub with the latest version? 

Thanks,

**Comment by buchdag** [comment]
The images are up to date on Dockerhub, the nginx version thingy is just a badge I have to update by hand every time nginx is updated, so it might eventually be out of date.

Additionally the Docker registry readme is not automatically synced with the GitHub repository readme, so the two might be out sync. I've fixed this.

**Reply by gyl89** [reply]
Thanks for reply. However, I didn't base my observations on the badge but on the response header:
server: nginx/1.19.3

I have implemented the reverse proxy with docker compose v3. Before starting docker compose, I have emptied the cache with `docker system prune`

Relevant part of the docker compose file is

 ```
 nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ssl_certs:/etc/nginx/certs:ro
      - ssl_conf:/etc/nginx/conf.d
      - ssl_vhost:/etc/nginx/vhost.d
      - ssl_html:/usr/share/nginx/html
      - ssl_dhparam:/etc/nginx/dhparam
      - acme:/etc/acme.sh
      - ./api/nginx-proxy/nginx_proxy.conf:/etc/nginx/vhost.d/default_location:ro
      - ./api/nginx-proxy/status.conf:/etc/nginx/conf.d/status.conf:ro
    networks:
      - theNetwork
    environment:
      - ENABLE_IPV6=true
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
```

Any idea why I have version 1.19.3? Thanks for helping
