### DISCUSSION TITLE
Aliases that redirect instead of serving on all domains

### DISCUSSION THREAD

**Discussion by DreamTexX** [nginx-proxy/nginx-proxy#1825] [Ideas]
It would be nice to have an extra env variable like the `VIRTUAL_HOST` one, but domains added there just redirect to the main domain. For example:
```yml
version: '3.8'
services:
    test:
        image: nginxdemos/hello
        environment:
            - VIRTUAL_HOST=www.example.com
            - ALIAS=example.com,web.example.com
```
example.com will then redirect to www.example.com instead of servig the site on example.com.

Or is there already such a feature?
