### DISCUSSION TITLE
basic auth with htpasswd not working at all

### DISCUSSION THREAD

**Discussion by perler** [nginx-proxy/nginx-proxy#1830] [General]
I am a bit stumped here. I had this working following https://github.com/nginx-proxy/nginx-proxy#basic-authentication-support. I now try to launch another container with basic auth support and it just doesn't work.

this is (the relevant parts of) docker-compose.yml
```
proxy:
    container_name: proxy
    restart: always
    image: jwilder/nginx-proxy
    environment:
      - DEFAULT_HOST=proxy.domain.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /vol/raid/config/proxy/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro


# simple nginx test
  test:
    container_name: default
    restart: always
    image: nginx
    environment:
      - VIRTUAL_HOST=test.domain.com
      - LETSENCRYPT_HOST=test.domain.com
      - LETSENCRYPT_EMAIL=email@domain.com
      - SSL_POLICY=Mozilla-Modern
    volumes:
      - /vol/raid/data/test:/usr/share/nginx/html:ro
      - /vol/raid/config/proxy/htpasswd:/etc/nginx/htpasswd

```

and this is the resulting /etc/nginx/conf.d/default.conf _inside_ the container. I don't see any reference to htpasswd so, this can't work, but why?

```
# test.domain.com
upstream test.domain.com {
	## Can be connected with "nginx-proxy" network
	# default
	server 172.19.0.32:80;
}
server {
	server_name test.domain.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	# Do not HTTPS redirect Let'sEncrypt ACME challenge
	location ^~ /.well-known/acme-challenge/ {
		auth_basic off;
		auth_request off;
		allow all;
		root /usr/share/nginx/html;
		try_files $uri =404;
		break;
	}
	location / {
		return 301 https://$host$request_uri;
	}
}
server {
	server_name test.domain.com;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
		ssl_protocols TLSv1.3;
		ssl_ciphers HIGH:!aNULL:!MD5;
		ssl_prefer_server_ciphers off;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/test.domain.com.crt;
	ssl_certificate_key /etc/nginx/certs/test.domain.com.key;
	ssl_dhparam /etc/nginx/certs/test.domain.com.dhparam.pem;
	ssl_stapling on;
	ssl_stapling_verify on;
	ssl_trusted_certificate /etc/nginx/certs/test.domain.com.chain.pem;
	add_header Strict-Transport-Security "max-age=31536000" always;
	include /etc/nginx/vhost.d/default;
	location / {
		proxy_pass http://test.domain.com;
	}
}
```
