### DISCUSSION TITLE
All requests get 403: Forbidden reply

### DISCUSSION THREAD

**Discussion by CRCinAU** [nginx-proxy/nginx-proxy#1842] [General]
Hi all,

Overnight, my setup has stopped working - and I'm not sure why. Every request that I submit to the proxy for the domain in question returns a 403: Forbidden.

It was working ok yesterday - but I think it may have updated the docker container overnight.

My config is pretty basic, with only one host:
```yaml
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    environment:
      - TZ=Australia/Melbourne
      - SSL_POLICY=Mozilla-Modern
    networks:
      - homeassistant
    ports:
      - "80:80"
      - "443:443"
    restart: "on-failure"
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-dhparam:/etc/nginx/dhparam
      - nginx-certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    depends_on:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=<email address>
    container_name: nginx-proxy-acme
    networks:
      - homeassistant
    volumes_from:
      - nginx-proxy
    volumes:
      - nginx-certs:/etc/nginx/certs:rw
      - nginx-acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

```

I'm not exacly sure how this broke, as I can't see anything obvious that is wrong - and as I mentioned, it was working fine yesterday :\
