### DISCUSSION TITLE
Run Proxy Container as Non Root User

### DISCUSSION THREAD

**Discussion by ducarrozb** [nginx-proxy/nginx-proxy#1855] [Q&A]
Hi,

I would like to run the jwilder nginx-proxy as `user: www-data:www-data`, but this ends with the following error. Can someone please help me? I am new to docker. 

```
Starting jwilder-reverse-proxy                    ... error

Recreating jwilder-reverse-proxy-php-8.0.8-apache ... done
o matching entries in passwd file

ERROR: for nginx-proxy  Cannot start service nginx-proxy: unable to find user www-data: no matching entries in passwd file
```

**My docker-compose.yml**

```yaml
version: '3.9'

services:
  nginx-proxy:
    restart: always
    environment:
      - TZ=Europe/Zurich
    image: jwilder/nginx-proxy:alpine
    user: www-data:www-data
    container_name: jwilder-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    dns_search:
      - "myhost.com"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - /mypath:/etc/nginx/certs:ro
      - /mypath/nginx.conf:/etc/nginx/nginx.conf:ro
      - /mypath/dhparam.pem:/etc/nginx/dhparam/dhparam.pem:ro
      - /mypath/error.log:/var/log/nginx/error.log
  php8.0.8-apache:
    restart: always
    image: php:8.0.8-apache
    user: www-data:www-data
    container_name: jwilder-reverse-proxy-php-8.0.8-apache 
    environment:
      - VIRTUAL_HOST=myhost.com
    volumes:
      - /mypath:/var/www/html/:ro
```
