### DISCUSSION TITLE
503 on localhost

### DISCUSSION THREAD

**Discussion by paulbricman** [nginx-proxy/nginx-proxy#1910] [Q&A] [answered]
I don't think this warrants a full issue as I'm sure I missed something obvious

```yaml
version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "1212:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - whoami

  whoami:
    image: jwilder/whoami
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8000
```

Trying to make the example work on localhost with the latest nginx-proxy. `localhost:1212` gives `503 Service Temporarily Unavailable`. Changing `VIRTUAL_HOST` to `0.0.0.0` also doesn't help. Can this run locally without changing DNS?
