### DISCUSSION TITLE
IPv6: Seeing real IP behind proxy

### DISCUSSION THREAD

**Discussion by ontheair81** [nginx-proxy/nginx-proxy#1930] [Q&A]
Hello, I am trying to enable IPv6 on my websites behind nginx-proxy.

When using IPv4, the webserver sees the real IP as it is forwarded by nginx-proxy:
`172.19.0.2 - - [18/Mar/2022:09:46:20 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Android 10; Mobile; rv:98.0) Gecko/98.0 Firefox/98.0" "109.43.50.[XXX]"`

When accessing the server by IPv6, there is just the internal IP of nginx-proxy:
`172.19.0.2 - - [18/Mar/2022:09:47:48 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Android 10; Mobile; rv:98.0) Gecko/98.0 Firefox/98.0" "172.19.0.1"`

I followed the instructions mentioned in the readme and using [ipv6nat](https://github.com/robbertkl/docker-ipv6nat#usage).

daemon.json:
```
{
  "ipv6": true,
  "fixed-cidr-v6": "2a0c:2500:[XXXX]:[XXXX]:[XXXX]:[XXXX]:[XXXX]:[XXXX]/48",
  "userland-proxy": false
}
```

docker-compose.yml:
```
version: "3.7"
services:
    reverse-proxy:
        image: "nginxproxy/nginx-proxy:1.0"
        container_name: "reverse-proxy"
        volumes:
            - "html:/usr/share/nginx/html"
            - "dhparam:/etc/nginx/dhparam"
            - "vhost:/etc/nginx/vhost.d"
            - "/home/user/certstore:/etc/nginx/certs"
            - "/run/docker.sock:/tmp/docker.sock:ro"
        restart: "always"
        networks: 
            - "net"
        ports:
            - "80:80"
            - "443:443"
        environment:
            ENABLE_IPV6: "true"

    letsencrypt:
        image: "nginxproxy/acme-companion:2.2"
        container_name: "letsencrypt-helper"
        volumes:
            - "html:/usr/share/nginx/html"
            - "dhparam:/etc/nginx/dhparam"
            - "vhost:/etc/nginx/vhost.d"
            - "/home/user/certstore:/etc/nginx/certs"
            - "acme:/etc/acme.sh"
            - "/run/docker.sock:/var/run/docker.sock:ro"
        environment:
            NGINX_PROXY_CONTAINER: "reverse-proxy"
            DEFAULT_EMAIL: "[MyMail]"
        restart: "always"
        depends_on:
            - "reverse-proxy"
        networks: 
            - "net"

volumes:
  html:
  vhost:
  dhparam:
  acme:

networks:
  net:
    external: true
```

Then started ipv6nat by:
`docker run -d --name ipv6nat --privileged --network host --restart unless-stopped -v /var/run/docker.sock:/var/run/docker.sock:ro -v /lib/modules:/lib/modules:ro robbertkl/ipv6nat`

But no success. Any help would be very appreciated!

I am still learning docker and I am pretty new to IPv6, so please be forgiving if this is a stupid question and I missed something obvious.
Thank you!
