### DISCUSSION TITLE
Port Mapping freaking me out

### DISCUSSION THREAD

**Discussion by SantoDE** [nginx-proxy/nginx-proxy#1953] [Q&A]
Hey fellas,

I'm sure I'm missing something here but I could need some help :)

I currently have nginx-proxy running on my VM. I want to host other companies, such as e.g. (https://github.com/docker/distribution) on this vm as well and proxy it trough nginx-proxy.

However, port mapping is freaking me out. The Proxy listens on 80 and 443 which is fine. For the image above, I thought I could set the "VIRTUAL_HOST" to my desired one and bind port 443:5000 (as requested by expose on that image).

However, as 443 is already bound by the proxy I'm a little clueless on how to get that thing setuped. Any hints? :)

Thanks a lot!

Cheers,
Santo

**Comment by helderco** [comment]
Don't bind to 443, just use the port that the container responds to. That will be translated to an upstream of "container_ip:container_port" in your nginx config.

**Comment by SantoDE** [comment]
@helderco : that's what I tried at first.

`fa6e34b6612a        registry:2            "/bin/registry /etc/d"   6 seconds ago       Up 5 seconds        0.0.0.0:5000->5000/tcp                     data_registry_1`

However, my container is not accessible as you can check see here: https://registry.manuel-laufenberg.de/

**Comment by helderco** [comment]
You're binding 5000 to host, but as I said, you don't have to.

You need something like this:

```
version: '2'
services:
  nginx:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /path/to/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
  app:
    image: ...
    expose:
      - 5000
    environment:
      - VIRTUAL_HOST=your.domain.tld
```

You can remove the "expose" in the "app" service if it's already exposed in the Dockerfile.

You should only need to use VIRTUAL_PORT if you have more then 2 exposed ports.

Check your nginx config to see what if anything got written to the upstream.

```
docker exec -it <your_nginx_container> cat /etc/nginx/conf.d/default.conf
```

**Comment by helderco** [comment]
@SantoDE Don't forget that you need your certificates named the right way or nginx-proxy won't pickup ssl.

> The contents of /path/to/certs should contain the certificates and private keys for any virtual hosts in use. The certificate and keys should be named after the virtual host with a .crt and .key extension. For example, a container with VIRTUAL_HOST=foo.bar.com should have a foo.bar.com.crt and foo.bar.com.key file in the certs directory.

**Comment by SantoDE** [comment]
SSL is working just fine, it's "only" about port map mapping.

If i only have that block inside the compose.yml:

> registry:
>   restart: always
>   image: registry:2
>   ports:
>     - 5000
>   environment:
>     REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.manuel-laufenberg.de.crt
>     REGISTRY_HTTP_TLS_KEY: /certs/registry.manuel-laufenberg.de.key
>     REGISTRY_AUTH: htpasswd
>     REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
>     REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
>     VIRTUAL_HOST: registry.manuel-laufenberg.de
>     VIRTUAL_PROTO: https
>   volumes:
>     - /data/certs:/certs
>     - /data/registry/data/config.yml:/etc/docker/registry/config.yml
>     - /data/auth:/auth

it's mapped randomly to 32768 from the outside world, so accessing it would be done by my.hostname.org:32768. If I remove ports completely, it's not accessible at all.

What am I doing wrong? Thanks a lot @helderco !

**Comment by helderco** [comment]
@SantoDE The outside world will access the registry through nginx though, right? So you won't use it like "registry.manuel-laufenberg.de:5000" or anything with a port.

Shouldn't you bind your certificates to /etc/nginx/certs instead of /certs?

**Comment by helderco** [comment]
@SantoDE sorry, it's nginx that has to have the certificates in /etc/nginx/certs, how's your nginx-proxy container defined?

**Comment by helderco** [comment]
Are you trying to connect from nginx to registry through https? Are they in different machines?

**Comment by helderco** [comment]
Assuming nginx-proxy and registry are on the same machine, try this:

```
version: '2'
services:
  nginx:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /certs:/etc/nginx/certs
      - /auth:/etc/nginx/htpasswd
      - /var/run/docker.sock:/tmp/docker.sock:ro
  registry:
    image: registry:2
    restart: always
    environment:
      - VIRTUAL_HOST=registry.manuel-laufenberg.de
    volumes:
      - /data/registry/data/config.yml:/etc/docker/registry/config.yml
```

Make sure your htpasswd file is "/auth/registry.manuel-laufenberg.de".

This should be enough.

**Comment by helderco** [comment]
To explain, you don't have to setup https and htpasswd in the registry container, because nginx-proxy provides all of that, assuming that the files are correctly named and in the correct folder. Since in this setup, registry isn't bound to the host and the outside world, the connection is internal and in no need to have an https backend.

The outside world connects through nginx, which is where all that security is set through nginx-proxy.

What happens inside nginx-proxy is this:
1. docker-gen detects that there's a container with a **VIRTUAL_HOST** and uses that value to setup a virtual host in nginx. It can obviously inspect that container to figure some things about it; 
2. It has its internal ip that nginx should be able to access, because they're on the same (internal) network (in this case, the default network for this docker compose file);
3. Since the registry container only has the 5000 port exposed, it uses that one (see the registry [Dockerfile](https://github.com/docker/distribution-library-image/blob/master/Dockerfile));
4. Since there are certificates with the vhost name, it setups https and listens to port 443;
5. Since there's an htpasswd file with the vhost name, it uses that to provide authentication as well.

Hope it's clearer what happens.

**Comment by SantoDE** [comment]
hey @helderco. Thank's alot for your help. I finally understand how it is supposed to work. It's just not :( I followed your guideance. here is my docker ps -a:

> docker ps
> CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                                      NAMES
> 03127ccec128        registry:2            "/bin/registry /etc/d"   3 seconds ago       Up 2 seconds        5000/tcp                                   docker_registry_1
> abe49922adbc        jwilder/nginx-proxy   "/app/docker-entrypoi"   3 seconds ago       Up 3 seconds        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   docker_nginx_1

However, my container is not accessible no matter what I try :( https://registry.manuel-laufenberg.de

Maybe you could gimme a hint again :) Thanks!

**Comment by SantoDE** [comment]
here's my compose startup log. I guess the nginx error is my problem?

> docker-compose up
> Creating docker_nginx_1
> Creating docker_registry_1
> Attaching to docker_nginx_1, docker_registry_1
> nginx_1    | forego     | starting nginx.1 on port 5000
> nginx_1    | forego     | starting dockergen.1 on port 5100
> nginx_1    | dockergen.1 | 2016/03/13 07:08:38 Generated '/etc/nginx/conf.d/default.conf' from 1 containers
> nginx_1    | dockergen.1 | 2016/03/13 07:08:38 Running 'nginx -s reload'
> nginx_1    | dockergen.1 | 2016/03/13 07:08:38 Watching docker events
> nginx_1    | dockergen.1 | 2016/03/13 07:08:38 Received event start for container e399ffec9c29
> nginx_1    | dockergen.1 | 2016/03/13 07:08:38 Generated '/etc/nginx/conf.d/default.conf' from 2 containers
> nginx_1    | dockergen.1 | 2016/03/13 07:08:38 Running 'nginx -s reload'
> nginx_1    | dockergen.1 | 2016/03/13 07:08:38 Error running notify command: nginx -s reload, exit status 1

**Comment by SantoDE** [comment]
Alright, I guess the problem is the composer 2 syntax, because my containers are missing an IP. As stated on the repo start page, this syntax is not supported yet. Maybe I should try it with docker v1 syntax?

**Comment by SantoDE** [comment]
and it works ! :) Thanks a lot @helderco !

**Comment by cdaringe** [comment]
hey guys, useful dialog. thanks.

i have my registry setup here: https://registry.cdaringe.me/v2/_catalog

as you can see, it works when browsing thru the UI, SSL included.  however on `docker login <my-registry-url>`, irregardless of credentials, i receive: `Get https://registry.cdaringe.me/v1/users/: x509: certificate signed by unknown authority`

For example:

```sh
$ docker login registry.cdaringe.me
Username: bananas
Password:
Error response from daemon: Get https://registry.cdaringe.me/v1/users/: x509: certificate signed by unknown authority
```

my conf is pretty straightforward:

```yml
# docker-compose.yml
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /www/registry/auth:/etc/nginx/htpasswd
      - /www/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=$HOSTNAME
    restart: always

  docker_registry:
    image: registry:2
    expose:
      - 5000
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=registry.$HOSTNAME
      - VIRTUAL_PORT=5000
      - CERT_NAME=server
```

any tips would be great!  i opened an issue earlier trying to solve this over @ #672.  Close!
