### DISCUSSION TITLE
Multiple containers, problem with Jenkins images, firewall involved..

### DISCUSSION THREAD

**Discussion by svnhubhub** [nginx-proxy/nginx-proxy#1955] [Q&A]
Hi guys,

I have server machine with the latest docker and fresh Ubuntu 15.10 Server edition. Since this is a corporate network, I can access it only on ports 80 and 22. My goal is to setup multiple services behind nginx proxy on a different domains. This is how nginx proxy is run:

```
docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
```

Then, another docker containers are run like this:

```
docker run -d -e VIRTUAL_HOST=example1.example.com -d --expose 80 owncloud
docker run -d -e VIRTUAL_HOST=example2.example.com --expose=80 istepanov/dokuwiki
etc...
```

and everything is OK, I have access to every of this container by going to example1 and example2. The problem is with Jenkins image. I did try official [jenkins image](https://hub.docker.com/_/jenkins/) and [this one](https://hub.docker.com/r/aespinosa/jenkins/) with no success - after going to "jenkins.example.com" I'm getting gateway timeout or 502 bad gateway, depends of how I run jenkins image. Here are my tries: 

```
docker run -d -e VIRTUAL_HOST=jenkins.example.com -e VIRTUAL_PORT=8080 jenkins
docker run -d -e VIRTUAL_HOST=jenkins.example.com --expose=8080 50000 jenkins
docker run -d -e VIRTUAL_HOST=jenkins.example.com --expose=8080 jenkins
docker run -d -p 50000:50000 -e VIRTUAL_HOST=jenkins.example.com -e VIRTUAL_PORT=8080 jenkins
docker run -d -p 8080:8080 -p 50000:50000 -e VIRTUAL_HOST=jenkins.example.com -e VIRTUAL_PORT=8080 jenkins
```

I did prove on my localhost that this:

```
docker run -d -e VIRTUAL_HOST=jenkins.example.com -e VIRTUAL_PORT=8080 jenkins
```

is working fine and I have an access to Jenkins through nginx-proxy. 

Logs from jenkins docker:

```
Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
Mar 23, 2016 12:46:41 PM winstone.Logger logInternal
INFO: Beginning extraction from war file
Mar 23, 2016 12:46:43 PM org.eclipse.jetty.util.log.JavaUtilLog info
INFO: jetty-winstone-2.9
Mar 23, 2016 12:46:45 PM org.eclipse.jetty.util.log.JavaUtilLog info
INFO: NO JSP Support for , did not find org.apache.jasper.servlet.JspServlet
Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
Mar 23, 2016 12:46:46 PM org.eclipse.jetty.util.log.JavaUtilLog info
INFO: Started SelectChannelConnector@0.0.0.0:8080
Mar 23, 2016 12:46:46 PM winstone.Logger logInternal
INFO: Winstone Servlet Engine v2.0 running: controlPort=disabled
Mar 23, 2016 12:46:47 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started initialization
Mar 23, 2016 12:46:58 PM jenkins.InitReactorRunner$1 onAttained
INFO: Listed all plugins
Mar 23, 2016 12:46:59 PM jenkins.InitReactorRunner$1 onAttained
INFO: Prepared all plugins
Mar 23, 2016 12:47:00 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started all plugins
Mar 23, 2016 12:47:00 PM jenkins.InitReactorRunner$1 onAttained
INFO: Augmented all extensions
Mar 23, 2016 12:47:02 PM jenkins.InitReactorRunner$1 onAttained
INFO: Loaded all jobs
Mar 23, 2016 12:47:03 PM jenkins.util.groovy.GroovyHookScript execute
INFO: Executing /var/jenkins_home/init.groovy.d/tcp-slave-agent-port.groovy
Mar 23, 2016 12:47:05 PM hudson.model.AsyncPeriodicWork$1 run
INFO: Started Download metadata
Mar 23, 2016 12:47:05 PM org.jenkinsci.main.modules.sshd.SSHD start
INFO: Started SSHD at port 35625
Mar 23, 2016 12:47:05 PM jenkins.InitReactorRunner$1 onAttained
INFO: Completed initialization
Mar 23, 2016 12:47:05 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started initialization
Mar 23, 2016 12:47:05 PM jenkins.InitReactorRunner$1 onAttained
INFO: Listed all plugins
Mar 23, 2016 12:47:05 PM jenkins.InitReactorRunner$1 onAttained
INFO: Prepared all plugins
Mar 23, 2016 12:47:05 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started all plugins
Mar 23, 2016 12:47:05 PM jenkins.InitReactorRunner$1 onAttained
INFO: Augmented all extensions
Mar 23, 2016 12:47:05 PM jenkins.InitReactorRunner$1 onAttained
INFO: Loaded all jobs
Mar 23, 2016 12:47:05 PM jenkins.InitReactorRunner$1 onAttained
INFO: Completed initialization
Mar 23, 2016 12:47:05 PM hudson.WebAppMain$3 run
INFO: Jenkins is fully up and running
--> setting agent port for jnlp
--> setting agent port for jnlp... done
```

And ngingx's default.conf, after running:

```
docker run -d -e VIRTUAL_HOST=jenkins.example.com -e VIRTUAL_PORT=8080 jenkins
```

```
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
server {
    server_name _; # This is just an invalid value which will never trigger on a real hostname.
    listen 80;
    access_log /var/log/nginx/access.log vhost;
    return 503;
}
upstream jenkins.example.com {
            # drunk_kare
            server 172.17.0.3:8080;
}
server {
    server_name jenkins.example.com;
    listen 80 ;
    access_log /var/log/nginx/access.log vhost;
    location / {
        proxy_pass http://jenkins.example.com;
    }
}
```

Related nginx's logs:

```
nginx.1    | 2016/03/23 13:16:15 [error] 51#51: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: MY_INTERNAL_IP_HERE, server: jenkins.example.com, request: "GET / HTTP/1.1", upstream: "http://172.17.0.3:8080/", host: "jenkins.example.com"
nginx.1    | jenkins.example.com MY_INTERNAL_IP_HERE - - [23/Mar/2016:13:16:15 +0000] "GET / HTTP/1.1" 504 183 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
```

What can be wrong here? Am I missing something?

**Comment by pascalandy** [comment]
Look at this trend. I had challenges to make it work but now it working!

https://github.com/jwilder/nginx-proxy/issues/304#issuecomment-199567943

**Comment by svnhubhub** [comment]
@pascalandy I've tried with this yml. Now I don't have access to any container. Is there something wrong?

```
version: '2'
services:
    proxy:
        image: rckrdstrgrd/nginx-proxy
        ports:
            - "80:80"
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock:ro"
        networks:
            - frontend
            - backend

    owncloud:
        image: owncloud
        #ports:
        #    - "80:80"
        networks:
            - backend
        environment:
            VIRTUAL_HOST: cloud.example.com
            VIRTUAL_PORT: 80

    jenkins:
        image: jenkins
        ports:
            - "8080:8080"
            - "50000:50000"
        networks:
            - backend
        environment:
            VIRTUAL_HOST: jenkins.example.com
            VIRTUAL_PORT: 8080
networks:
    frontend:
    # driver: bridge
    external:
    #    name: nginx-proxy
    backend:
        driver: bridge
```

EDIT

However with this yml, I have access to owncloud, but still not to Jenkins.

```
version: '2'
services:
    proxy:
        image: rckrdstrgrd/nginx-proxy
        ports:
            - "80:80"
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock:ro"

    owncloud:
        image: owncloud
        environment:
            VIRTUAL_HOST: cloud.example.com
            VIRTUAL_PORT: 80

    jenkins:
        image: jenkins
        environment:
            VIRTUAL_HOST: jenkins.example.com
            VIRTUAL_PORT: 8080
```

**Comment by pascalandy** [comment]
Have you created your networks before lauching, https://github.com/duck1123/jiksnu/blob/feature/cucumber/docker-compose.yml ??

To do so:
`docker network create --driver bridge nginx-proxy`

**Comment by svnhubhub** [comment]
@pascalandy

Now I did create it. With following yml it's not working either (only owncloud avilable):

```
docker network ls
NETWORK ID          NAME                       DRIVER
c01071c0f17f        host                       host                
058c78d7f303        nginx-proxy                bridge              
d932d28ccb08        servicescompose_frontend   bridge              
7a734f9fad4a        servicescompose_backend    bridge              
a403f427e320        bridge                     bridge              
de6c4eb73960        none                       null                
```

`servicecompose` is my yml.

```
version: '2'
services:
    proxy:
        image: rckrdstrgrd/nginx-proxy
        ports:
            - "80:80"
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock:ro"
        networks:
            - frontend
            - backend

    owncloud:
        image: owncloud
        networks:
            - backend
        environment:
            VIRTUAL_HOST: cloud.example.com
            VIRTUAL_PORT: 80
            VIRTUAL_NETWORK: nginx-proxy
    jenkins:
        image: jenkins
        networks:
            - backend
        environment:
            VIRTUAL_HOST: jenkins.example.com
            VIRTUAL_PORT: 8080
            VIRTUAL_NETWORK: nginx-proxy
networks:
    frontend:
    # driver: bridge
    external:
        #name: nginx-proxy
    backend:
        driver: bridge
```

Also tried without setting `VIRTUAL_PORT` in both services -> I could access nginx server welcome page when going to jenkins.example.com and cloud.example.com.
Any other ideas?

One update; I run the last example with wrong `networks` settings:

```
networks:
    frontend:
    # driver: bridge
    external:
        #name: nginx-proxy
    backend:
        driver: bridge
```

Fixed it to:

```
networks:
    frontend:
      external:
        name: nginx-proxy
    backend:
        driver: bridge
```

but now don't have access to both of my services. Just gateway timeout. 
Docker networks looks like this after yml run:

```
NETWORK ID          NAME                      DRIVER
de6c4eb73960        none                      null                
c01071c0f17f        host                      host                
1bd61e6c7087        nginx-proxy               bridge              
51afb756bf57        servicescompose_backend   bridge              
a403f427e320        bridge                    bridge  
```

**Comment by thomasleveil** [comment]
@svnhubhub be aware that nginx-proxy does not support docker-compose yml syntax v2:https://github.com/jwilder/nginx-proxy/blob/master/README.md#docker-compose

**Comment by pascalandy** [comment]
@thomasleveil correct. But since then a solution has been found and it's rock solid since a week I'm using it. https://github.com/jwilder/nginx-proxy/issues/304#issuecomment-199567943

**Comment by svnhubhub** [comment]
@pascalandy

Can you show your docker-compose yml file?

**Comment by pascalandy** [comment]
@svnhubhub take a look at the comment from **fakt** here https://github.com/jwilder/nginx-proxy/issues/304#issuecomment-197051129

**Comment by svnhubhub** [comment]
@pascalandy 
I really don't know how this could help here. I've already removed exposing ports from my jenkins and owncloud; and added "networks" part to my docker-compose. Maybe we can try this way: is it correct in your opinion (of course there is nginx-proxy network created)?

```
version: '2'
services:
    proxy:
        image: rckrdstrgrd/nginx-proxy
        ports:
            - "80:80"
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock:ro"
        networks:
            - frontend
            - backend

    owncloud:
        image: owncloud
        networks:
            - backend
        environment:
            VIRTUAL_HOST: cloud.example.com
            VIRTUAL_PORT: 80
            VIRTUAL_NETWORK: nginx-proxy
    jenkins:
        image: jenkins
        networks:
            - backend
        environment:
            VIRTUAL_HOST: jenkins.example.com
            VIRTUAL_PORT: 8080
            VIRTUAL_NETWORK: nginx-proxy
networks:
    frontend:
      external:
        name: nginx-proxy
    backend:
        driver: bridge
```

If yes, then I should give up, because it is clearly problem of my internal network. If no, what is wrong?
