### DISCUSSION TITLE
Getting 404 on the root path when VIRTUAL_PATH is set

### DISCUSSION THREAD

**Discussion by akicookz** [nginx-proxy/nginx-proxy#1993] [Q&A]
I have been trying to set `VIRTUAL_PATH=/ws` to serve websocket connection from second container.
I got it working but the now the main container does not seem to be forwarded any requests.
It would be a great help if someone can point what I am doing wrong.

Compose file:

```
version: "3.7"

services:
  nginx-proxy:
    # build: nginx
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/server/staticfiles
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
      - ws
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379
  ws:
    container_name: ws
    image: web:staging
    command: daphne -b 0.0.0.0 -p 8001 server.asgi:application
    depends_on:
      - web
      - redis
    env_file:
      - .env.local
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PATH=/ws
    expose:
      - 8001
  web:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: web
    image: web:staging
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/server/staticfiles
      - ./server:/home/app/server/
    env_file:
      - .env.local
    expose:
      - 8000
    environment:
      - VIRTUAL_HOST=localhost
volumes:
  static_volume:

```

Output of `docker exec nginx-proxy cat /etc/nginx/conf.d/default.conf`

```
# nginx-proxy version : 1.0.1-6-gc4ad18f
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Apply fix for very long server names
server_names_hash_bucket_size 128;
# Default dhparam
ssl_dhparam /etc/nginx/dhparam/dhparam.pem;
# Set appropriate X-Forwarded-Ssl header based on $proxy_x_forwarded_proto
map $proxy_x_forwarded_proto $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent" '
                 '"$upstream_addr"';
access_log off;
		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
		ssl_prefer_server_ciphers off;
error_log /dev/stderr;
resolver 127.0.0.11;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
proxy_set_header X-Original-URI $request_uri;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	server_tokens off;
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
		# localhost/ws
upstream localhost-a70b33c6ff5b3c4ea91eaa80d93fee148b263f26 {
        ## Can be connected with "server_default" network
        # ws
        server 172.24.0.4:8001;
}
server {
	server_name localhost;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location /ws {
		proxy_pass http://localhost-a70b33c6ff5b3c4ea91eaa80d93fee148b263f26;
}
			location / {
				return 404;
			}
}
```
