### DISCUSSION TITLE
backend rest api

### DISCUSSION THREAD

**Discussion by joshbenz** [nginx-proxy/nginx-proxy#1998] [Q&A]
Hello, I am trying to put a backend REST API on port 8000 behind this proxy, but there is no entry generated for it in the resulting nginx config. I was just wondering if I am missing something or if this is an actual issue. I have tried various configurations and tried VIRTUAL_PORT and HTTP_PORT.

This is my docker compose (the container in question is lockbox-api, api.lockbox.lab.domain.com (I redacted the actual domain)):

```
version: '3'

services:
  lockbox:
    image: lockbox-frontend:alpine
    container_name: lockbox-frontend
    environment:
      VIRTUAL_HOST: lockbox.lab.domain.com
      CERT_NAME: lockbox.lab.domain.com
  lockbox-api:
    image: lockbox-api:distroless
    container_name: lockbox-api
    expose:
      - 8000
    environment:
      VIRTUAL_HOST: api.lockbox.lab.domain.com
      VIRTUAL_PORT: 8000
      CERT_NAME: api.lockbox.lab.domain.com
      APP_ENVIRONMENT: production
  lockbox-db:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - /opt/mongodb_data/:/data/db
    ports:
      - 27017:27017


networks:
  default:
    external:
      name: nginx-proxy

```

The Dockerfile used to create the container is:

```
FROM rust:latest AS builder

RUN update-ca-certificates

# Create appuser
ENV USER=api
ENV UID=10001

RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    "${USER}"


WORKDIR /api

COPY ./ .

# We no longer need to use the x86_64-unknown-linux-musl target
RUN cargo build --release

FROM gcr.io/distroless/cc

# Import from builder.
COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /etc/group /etc/group

WORKDIR /api

# Copy our build
COPY --from=builder /api/target/release/api ./
COPY --from=builder /api/config ./config

# Use an unprivileged user.
USER api:api
EXPOSE 8000

CMD ["/api/api"]
```

Does anyone see any problems with what I am doing?
