### DISCUSSION TITLE
[error] 35#35: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.3, server: subdomain.domain.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.17.0.1:1234/favicon.ico", host: "subdomain.domain.com", referrer: "http://subdomain.domain.com/dss/aform.jsp"

### DISCUSSION THREAD

**Discussion by oepres** [nginx-proxy/nginx-proxy#2001] [Q&A]
How to redirect subdomain.domain.com to localhost:1234 ?
Before I used apache with this config:

```
<VirtualHost *:8080> 
    ServerAdmin admin@domain.com
    ServerName subdomain.domain.com
    ProxyPreserveHost On
    <Proxy *>
        Order allow,deny
        Allow from all
    </Proxy>
    ProxyPass / http://localhost:1234/
    ProxyPassReverse / http://localhost:1234/
</VirtualHost>
```

Now on new server I would like to do the same with jwilder/nginx-proxy:alpine with docker-compose.
docker-compose.yml:
```
my_app:
    image: nginx:alpine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./my_app/subdomain.domain.com.conf:/etc/nginx/conf.d/zzzz_subdomain.domain.com.conf:ro
    environment:
      - VIRTUAL_HOST=subdomain.domain.com
    networks:
      - proxy-tier
    restart: unless-stopped
```

subdomain.domain.com.conf:
```
server {
        server_name subdomain.domain.com;
        listen       80;
        location / {
            proxy_pass   http://host.docker.internal:1234/;
        }
    }
```
