### DISCUSSION TITLE
cannot get unifi to be proxyed

### DISCUSSION THREAD

**Discussion by Hr46ph** [nginx-proxy/nginx-proxy#2005] [Q&A]
I have about 10 containers including several that work on custom ports, they are all proxying fine through nginx-proxy with acme companion and get lets encrypt certificates. Examples are gitlab, duplicati, syncthing.

The Unifi controller is giving me headaches, I hope someone here can help me get it working. I have done my homework, hence I got all the others working with new certificates and I found a thread about unifi but that was about incorrect network config.

The docker-compose:
```
version: '2.3'
services:
  mongo:
    image: mongo:3.6
    container_name: unifi_mongo
#    networks:
#      - unifi
    restart: always
    volumes:
      - db:/data/db
      - dbcfg:/data/configdb
  controller:
    image: "jacobalberty/unifi:${TAG:-latest}"
    container_name: unifi_controller
    depends_on:
      - mongo
    init: true
#    networks:
#      - unifi
    restart: always
    volumes:
      - dir:/unifi
      - data:/unifi/data
      - log:/unifi/log
      - cert:/unifi/cert
      - init:/unifi/init.d
      - run:/var/run/unifi
      # Mount local folder for backups and autobackups
      - /data/docker-data/unifi/backup:/unifi/data/backup
    user: unifi
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    environment:
      - DB_URI=mongodb://mongo/unifi
      - STATDB_URI=mongodb://mongo/unifi_stat
      - DB_NAME=unifi
      - VIRTUAL_HOST=unifi.internal.mydomain.net
      - VIRTUAL_PORT=8080
#      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=duplicati.internal.mydomain.net
      - LETSENCRYPT_EMAIL=nginx-proxy-acme@mydomain.net
#    expose:
#      - "8080"
#      - "8443"
#      - "8880"
#      - "8843"
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
  logs:
    image: bash
    container_name: unifi_logs
    depends_on:
      - controller
    command: bash -c 'tail -F /unifi/log/*.log'
    restart: always
    volumes:
      - log:/unifi/log
#    networks:
#      - unifi
volumes:
  db:
  dbcfg:
  data:
  log:
  cert:
  init:
  dir:
  run:

networks:
  default:
    external:
      name: nginx-proxy_default
```
The items commented out are items I have experimented with in different combinations in an attempt to make things work.

The http url redirects to https but I get the `letsencrypt-nginx-proxy-companion` certificate with a `500 Internal Server Error`.

The nginx-proxy logs the following when I try to access the site:
```
nginx.1     | unifi.internal.mydomain.net 1.2.3.168 - - [27/Jun/2022:12:55:31 +0000] "GET /manage HTTP/2.0" 500 579 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.136 Safari/537.36" "-"
nginx.1     | unifi.internal.mydomain.net 1.2.3.168 - - [27/Jun/2022:12:55:31 +0000] "GET /favicon.ico HTTP/2.0" 500 579 "https://unifi.internal.mydomain.net/manage" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.136 Safari/537.36" "-"
```
The unifi controller is accessible on its old fdqn and port, 8443.

When I access one of the other sites, I see this in the logging:
```
nginx.1     | duplicati.internal.mydomain.net 1.2.3.168 - - [27/Jun/2022:13:07:10 +0000] "GET /api/v1/serverstate/?lasteventid=-1&longpoll=false&duration=299s HTTP/2.0" 200 639 "https://duplicati.internal.mydomain.net/ngax/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.136 Safari/537.36" "192.168.224.7:8200"
nginx.1     | duplicati.internal.mydomain.net 1.2.3.168 - - [27/Jun/2022:13:07:10 +0000] "GET /api/v1/notifications HTTP/2.0" 200 5 "https://duplicati.internal.mydomain.net/ngax/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.136 Safari/537.36" "192.168.224.7:8200"
nginx.1     | duplicati.internal.mydomain.net 1.2.3.168 - - [27/Jun/2022:13:07:10 +0000] "GET /api/v1/backups HTTP/2.0" 200 5946 "https://duplicati.internal.mydomain.net/ngax/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.136 Safari/537.36" "192.168.224.7:8200"
nginx.1     | duplicati.internal.mydomain.net 1.2.3.168 - - [27/Jun/2022:13:07:10 +0000] "GET /api/v1/systeminfo HTTP/2.0" 200 244791 "https://duplicati.internal.mydomain.net/ngax/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.136 Safari/537.36" "192.168.224.7:8200"
```
I noticed in this loggin that unifi is not redirecting to the docker internal ip and port, as duplicati does: `"192.168.224.7:8200"` in this example.

Last but not least, the default.conf from nginx container:
```
default.conf 
# nginx-proxy version : 1.0.1-6-gc4ad18f
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Apply fix for very long server names
server_names_hash_bucket_size 128;
# Default dhparam
ssl_dhparam /etc/nginx/dhparam/dhparam.pem;
# Set appropriate X-Forwarded-Ssl header based on $proxy_x_forwarded_proto
map $proxy_x_forwarded_proto $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent" '
                 '"$upstream_addr"';
access_log off;
		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
		ssl_prefer_server_ciphers off;
error_log /dev/stderr;
resolver 127.0.0.11;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
proxy_set_header X-Original-URI $request_uri;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	server_tokens off;
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	server_tokens off;
	listen 443 ssl http2;
	access_log /var/log/nginx/access.log vhost;
	return 503;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/default.crt;
	ssl_certificate_key /etc/nginx/certs/default.key;
}
	# duplicati.internal.mydomain.net
upstream duplicati.internal.mydomain.net {
        ## Can be connected with "nginx-proxy_default" network
        # duplicati
        server 192.168.224.7:8200;
}
server {
	server_name duplicati.internal.mydomain.net;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	# Do not HTTPS redirect Let'sEncrypt ACME challenge
	location ^~ /.well-known/acme-challenge/ {
		auth_basic off;
		auth_request off;
		allow all;
		root /usr/share/nginx/html;
		try_files $uri =404;
		break;
	}
	location / {
		return 301 https://$host$request_uri;
	}
}
server {
	server_name duplicati.internal.mydomain.net;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/duplicati.internal.mydomain.net.crt;
	ssl_certificate_key /etc/nginx/certs/duplicati.internal.mydomain.net.key;
	ssl_dhparam /etc/nginx/certs/duplicati.internal.mydomain.net.dhparam.pem;
	ssl_stapling on;
	ssl_stapling_verify on;
	ssl_trusted_certificate /etc/nginx/certs/duplicati.internal.mydomain.net.chain.pem;
	add_header Strict-Transport-Security "max-age=31536000" always;
	include /etc/nginx/vhost.d/default;
	location / {
		proxy_pass http://duplicati.internal.mydomain.net;
}
}
	# gitlab.internal.mydomain.net
upstream gitlab.internal.mydomain.net {
        ## Can be connected with "nginx-proxy_default" network
        # gitlab_web_1
        server 192.168.224.8:80;
}
server {
	server_name gitlab.internal.mydomain.net;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	# Do not HTTPS redirect Let'sEncrypt ACME challenge
	location ^~ /.well-known/acme-challenge/ {
		auth_basic off;
		auth_request off;
		allow all;
		root /usr/share/nginx/html;
		try_files $uri =404;
		break;
	}
	location / {
		return 301 https://$host$request_uri;
	}
}
server {
	server_name gitlab.internal.mydomain.net;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/gitlab.internal.mydomain.net.crt;
	ssl_certificate_key /etc/nginx/certs/gitlab.internal.mydomain.net.key;
	ssl_dhparam /etc/nginx/certs/gitlab.internal.mydomain.net.dhparam.pem;
	ssl_stapling on;
	ssl_stapling_verify on;
	ssl_trusted_certificate /etc/nginx/certs/gitlab.internal.mydomain.net.chain.pem;
	add_header Strict-Transport-Security "max-age=31536000" always;
	include /etc/nginx/vhost.d/default;
	location / {
		proxy_pass http://gitlab.internal.mydomain.net;
}
}
	# syncthing.internal.mydomain.net
upstream syncthing.internal.mydomain.net {
        ## Can be connected with "nginx-proxy_default" network
        # syncthing
        server 192.168.224.9:8384;
}
server {
	server_name syncthing.internal.mydomain.net;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	# Do not HTTPS redirect Let'sEncrypt ACME challenge
	location ^~ /.well-known/acme-challenge/ {
		auth_basic off;
		auth_request off;
		allow all;
		root /usr/share/nginx/html;
		try_files $uri =404;
		break;
	}
	location / {
		return 301 https://$host$request_uri;
	}
}
server {
	server_name syncthing.internal.mydomain.net;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/syncthing.internal.mydomain.net.crt;
	ssl_certificate_key /etc/nginx/certs/syncthing.internal.mydomain.net.key;
	ssl_dhparam /etc/nginx/certs/syncthing.internal.mydomain.net.dhparam.pem;
	ssl_stapling on;
	ssl_stapling_verify on;
	ssl_trusted_certificate /etc/nginx/certs/syncthing.internal.mydomain.net.chain.pem;
	add_header Strict-Transport-Security "max-age=31536000" always;
	include /etc/nginx/vhost.d/default;
	location / {
		proxy_pass http://syncthing.internal.mydomain.net;
}
}
	# unifi.internal.mydomain.net
upstream unifi.internal.mydomain.net {
        ## Can be connected with "nginx-proxy_default" network
        # unifi_controller
        server 192.168.224.5:8080;
}
server {
	server_name unifi.internal.mydomain.net;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	include /etc/nginx/vhost.d/default;
	location / {
		proxy_pass http://unifi.internal.mydomain.net;
}
}
server {
	server_name unifi.internal.mydomain.net;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	return 500;
	ssl_certificate /etc/nginx/certs/default.crt;
	ssl_certificate_key /etc/nginx/certs/default.key;
```

Any help is appreciated!
Thanks!
