### DISCUSSION TITLE
nginx-proxy with crowdsec - log path

### DISCUSSION THREAD

**Discussion by coaperator** [nginx-proxy/nginx-proxy#2030] [Q&A] [answered]
Hi I'm trying to get https://github.com/crowdsecurity/crowdsec to work with nginx-proxy
The logs(error_log and an access_log) from the proxy are written to /dev/stdout and /dev/stderr as usual to access them via docker logs. But for crowdsec I need a (persistent) path to the logs.
What setting should be added to completely move all nginx logs to a directory?

```yaml
services:
  nginx-proxy:
    environment:
      - LOG_PATH=/var/log/nginx_logs # something like this?
    volumes:
      - logs:/var/log/nginx_logs
```
