### DISCUSSION TITLE
VIRTUAL_HOST Configuration - Where do I put the location config !?

### DISCUSSION THREAD

**Discussion by ArthegaAsdweri** [nginx-proxy/nginx-proxy#2039] [Q&A]
Hey guys - I'm really frustrated atm.

I'm trying to figure out how to control the caching inside of containers. So far I'm just getting 404 as soon as I insert a location config.

I have the following setup:

docker-compose.yml

```
version: "3.9"

services:

  lisahahn.de:
    build:
      context: ./apache/phoenix-php
      dockerfile: Dockerfile
    container_name: lisahahn.de
    restart: unless-stopped
    volumes:
      - ./../lisahahn.de:/var/www/html
      - ./../phoenix-php:/var/www/html/vendor/arthega-asdweri/phoenix-php:ro
      - ./logs/phoenix:/var/log/phoenix
      - ./apache/apache2.conf:/etc/apache2/apache2.conf
      - ./apache/extensions.ini:/usr/local/etc/php/conf.d/extensions.ini
    environment:
      TZ: Europe/Berlin
      VIRTUAL_HOST: www.soul-empowerment.de
      LETSENCRYPT_HOST: www.soul-empowerment.de,soul-empowerment.de,www.lisahahn.de,lisahahn.de
      LETSENCRYPT_EMAIL: admin@hahn-webdesign.de
    depends_on:
      - mariadb
      
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy/certs:/etc/nginx/certs/:ro
      - ./nginx-proxy/vhost:/etc/nginx/vhost.d
      - ./nginx-proxy/html:/usr/share/nginx/html/
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/nginx/proxy.conf:/etc/nginx/conf.d/custom.conf:ro
      - ./config/nginx/default_location.conf:/etc/nginx/vhost.d/default_location:ro
      - ./config/nginx/www.soul-empowerment.de.conf:/etc/nginx/vhost.d/www.soul-empowerment.de:ro
    environment:
      TZ: Europe/Berlin
```

default_location.conf:
```
expires 1y;
add_header Cache-Control "public";
```

www.soul-empowerment.de.conf
```
location ~* \.(css)$ {
    add_header Last-Modified $date_gmt;
    add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
    if_modified_since off;
    expires off;
    etag off;
    proxy_no_cache 1;
    proxy_cache_bypass 1;
}
```

As soon as I insert whatever location config - whatever matches the regexp won't be found any longer. If I just add
```
location \ {
   expires 1d;
}
```

nothing works any more.

The following results in a 404 of every css and webp files:
```
location ~* \.(css|webp)$ {
   expires 1d;
}
```

As soon as I move everything into the root of the file - it works as expected - but I need a caching only for typical static file extensions.

Please throw the hammer at my head that makes me see what I'm doing wrong for 8 hours now.
