### DISCUSSION TITLE
help debugging kuma installation

### DISCUSSION THREAD

**Discussion by brunovianna** [nginx-proxy/nginx-proxy#2044] [Q&A]
Has anyone tried to install kuma to monitor the sites under nginx-proxy?
https://github.com/louislam/uptime-kuma

I have this issue I can't figure out: it works fine when I check the websites outside my own proxy (even if they're also run by nginx-proxy) and also for the websites in the own proxy with a different tld (for instance, up.example.com check nicely all etc.otherexample.com).

But when I try to ask kuma to monitor the websites running on its own subdomain, like up,example.com monitoring abd.example.com, it routes to the internal ip:port (172...) and gives me a conn refused message:

`  connect ECONNREFUSED 172.31.0.8:443`

What I suspect is that  when nginx-proxy looks the table up to find the website and finds it is in own domain, it returns the ip instead of full address. And then, since kuma uses websockets, it doesn't proxy the websocket request. Does it make any sense? Any ideas of how to solve this?

**Comment by brunovianna** [comment]
I made a hack in Kuma's docker-compose file, adding an extra_hosts setting

in the kuma service, I added:
extra_hosts:
  tld_domain: tld_ip

**Comment by phken91** [comment]
just fyi,
i have a quick test for my `uptime-kuma`, it's ok to work tgt with same domain / same server but diff container.

maybe you can share your's `docker-compose` / `docker` command here?

**Reply by brunovianna** [reply]
of course, here it is:

```
version: "3"

services:
  kuma:
    image: louislam/uptime-kuma:1.18.0-beta.0
    container_name: kuma
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      VIRTUAL_PORT: 3001
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: ${EMAIL}
    restart: always
    extra_hosts:
      myown.tld: xx.xx.xx.xx

networks:
    default:
        name: nginx-proxy
        external: true

volumes:
  uptime-kuma:

```
