### DISCUSSION TITLE
Rabbitmq and Encoding %2F

### DISCUSSION THREAD

**Discussion by ghost** [nginx-proxy/nginx-proxy#2068] [Q&A]
Hello, I'm experiencing a problem when trying to proxy rabbitmq with nginx-proxy. It seems that rabbitmq encodes slashes (/) in the URI as %2F. nginx-proxy will decode this %2F to / when providing the request to rabbitmq, which causes rabbitmq to break in some cases. Is there a way I can modify my current compose file so as to prevent nginx from performing this decoding? The compose file for my case is below.

Thanks for any help you can provide!

```yaml
version: "3.7"

services:

  nginx-proxy:
    container_name: nginx
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/me/Docker/certificates/nginx-cicd:/etc/nginx/certs
    networks:
      - my-util

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      - VIRTUAL_HOST=my.website.com
      - VIRTUAL_PORT=15672
      - VIRTUAL_PATH=/rabbitmq/
      - VIRTUAL_DEST=/
      - RABBITMQ_DEFAULT_USER=itsme
      - RABBITMQ_DEFAULT_PASS=itsme
    volumes:
        - rabbitmq:/var/lib/rabbitmq
    restart: always      
    networks:
      - my-util

volumes:
  rabbitmq:
    name: rabbitmq

networks:
  my-util:
    name: my-util
```
