### DISCUSSION TITLE
How to proxy different ports and different protocols?

### DISCUSSION THREAD

**Discussion by coaperator** [nginx-proxy/nginx-proxy#2086] [Q&A]
How to proxy different ports and different protocols?

```
  # vpn
  wg-easy:
    container_name: wg-easy
    image: weejewel/wg-easy
    environment:
      WG_HOST: my_host
      VIRTUAL_PORT: 51821
      VIRTUAL_HOST: my_host.xyz
      LETSENCRYPT_HOST: my_host.xyz
    volumes:
      - ./wg-easy/:/etc/wireguard
    ports:
      - "51821:51821/tcp"
      - "51820:51820/udp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```

how can i forward both ports on both protocols in nginx-proxy?
