### DISCUSSION TITLE
Unable to access Nefarious through reverse proxy

### DISCUSSION THREAD

**Discussion by Baanor** [nginx-proxy/nginx-proxy#2093] [Q&A] [answered]
Hello,

First of all, thanks for this solution. It work wonderfully. 

I'm creating a nefarious solution (https://github.com/lardbit/nefarious) and wanted to put it behind a reverse proxy.
I've managed to create the reverse proxy for transmission and jackett without much problem.
But for a reason that I can't find, I'm unable to access nefarious. I endup with an error 502.  I've looked at the issue already present in both project and can't find a solution. For now i'm only trying to make it work over http (https later, but not a priority).

I'm new to docker so the configuration might be completely wrong and i'm an idiot ^^

Here is my configuration:

 docker-compose.yml:

```
version: '2.4'
 
 services:
 
   # nefarious main application
   nefarious:
     extends:
       service: nefarious-app-base
       file: docker-compose.base.yml
     depends_on:
       - redis
       - jackett
       - celery
 
   # nefarious background task queue
   celery:
     extends:
       service: celery-base
       file: docker-compose.base.yml
     depends_on:
       - redis
 
   # database for task queue
   redis:
     image: redis
     restart: always
     mem_limit: 200m
     # NOTE: use "ports" when developing so locaal dev server can access redis
     #ports:
     #  - "6379:6379"
     expose:
       - "6379"
 
   # torrent indexer service
   jackett:
     extends:
       service: jackett-base
       file: docker-compose.base.yml
 
   # torrent server
   transmission:
     extends:
       service: transmission-base
       file: docker-compose.base.yml
     image: linuxserver/transmission
 
   # Reverse proxy
   nginx:
     extends :
       service: nginx-base
       file: docker-compose.base.yml
     image: nginxproxy/nginx-proxy
 
   # auto update service
   watchtower:
     extends:
       service: watchtower-base
       file: docker-compose.base.yml
 
 volumes:
   nefarious-db:
   jackett-config:
```

docker-compose.base.yml:

```
version: '2.4'

services:

  # nefarious base service (to be extended)
  nefarious-base:
    image: lardbit/nefarious

  # nefarious base app service (to be extended)
  nefarious-app-base:
    extends:
      service: nefarious-base
    expose:
      - "80"
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: always
    environment:
      # https://github.com/kennethreitz/dj-database-url
      - DATABASE_URL="sqlite:////nefarious-db/db.sqlite3"
      - REDIS_HOST="redis"
      - NEFARIOUS_USER=${NEFARIOUS_USER:-admin}
      - NEFARIOUS_PASS=${NEFARIOUS_PASS:-admin}
      - HOST_DOWNLOAD_PATH=${HOST_DOWNLOAD_PATH:-/tmp/}
      - CONFIG_PATH=/nefarious-db
      - VIRTUAL_HOST=nefarious.domain.com
      - VIRTUAL_PORT=80
      - SHA1_UPSTREAM_NAME=true
    volumes:
      # persistent named volume for sqlite database
      - nefarious-db:/nefarious-db
    logging:
      options:
        max-size: 10m

  # celery base service (to be extended)
  celery-base:
    extends:
      service: nefarious-base
    restart: always
    entrypoint: /app/entrypoint-celery.sh
    environment:
      # https://github.com/kennethreitz/dj-database-url
      DATABASE_URL: "sqlite:////nefarious-db/db.sqlite3"
      REDIS_HOST: "redis"
      HOST_DOWNLOAD_PATH: ${HOST_DOWNLOAD_PATH:-/tmp}
      INTERNAL_DOWNLOAD_PATH: /downloads
    volumes:
      - ${HOST_DOWNLOAD_PATH:-/tmp}:/downloads
      # persistent named volume for sqlite database
      - nefarious-db:/nefarious-db
    logging:
      options:
        max-size: 10m
    labels:
      - com.centurylinklabs.watchtower.enable=true

  # jackett base service (to be extended)
  jackett-base:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: linuxserver/jackett
    mem_limit: 200m
    restart: always
    logging:
      options:
        max-size: 10m
    environment:
      - VIRTUAL_HOST=jackett.domain.com
      - VIRTUAL_PORT=9117
    volumes:
      - ./jackett-config:/config


  # transmission base service (to be extended)
  transmission-base:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    expose:
      - "9091"
      - "51413"  # peer port
    restart: always
    environment:
      - PUID=${HOST_DOWNLOAD_UID:-1000}
      - PGID=${HOST_DOWNLOAD_GID:-1000}
      - VIRTUAL_HOST=transmission.domain.com
      - VIRTUAL_PORT=9091
    volumes:
      - ${HOST_DOWNLOAD_PATH:-/tmp}:/downloads
      - ./transmission-settings.json:/config/settings.json:ro


  # Reverse proxy base service
  nginx-base:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-conf:/etc/nginx/conf.d

  # auto update service (to be extended)
  # https://github.com/containrrr/watchtower
  watchtower-base:
    image: containrrr/watchtower
    restart: always
    command: --label-enable --cleanup
    environment:
      - WATCHTOWER_POLL_INTERVAL=3600
    logging:
      options:
        max-size: 10m
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  nefarious-db:
  jackett-config:
```

nginx config:
```
# nginx-proxy version : 1.0.1-6-gc4ad18f
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Apply fix for very long server names
server_names_hash_bucket_size 128;
# Default dhparam
ssl_dhparam /etc/nginx/dhparam/dhparam.pem;
# Set appropriate X-Forwarded-Ssl header based on $proxy_x_forwarded_proto
map $proxy_x_forwarded_proto $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent" '
                 '"$upstream_addr"';
access_log off;
                ssl_protocols TLSv1.2 TLSv1.3;
                ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
                ssl_prefer_server_ciphers off;
error_log /dev/stderr;
resolver 127.0.0.11;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
proxy_set_header X-Original-URI $request_uri;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        server_tokens off;
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        return 503;
}
        # jackett.domain.com
upstream jackett.domain.com {
        ## Can be connected with "nefarious_default" network
        # nefarious-jackett-1
        server 172.26.0.6:9117;
}
server {
        server_name jackett.domain.com;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://jackett.domain.com;
}
}
        # nefarious.domain.com
upstream nefarious.domain.com {
        ## Can be connected with "nefarious_default" network
        # nefarious-nefarious-1
        server 172.26.0.8:80;
}
server {
        server_name nefarious.domain.com;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://nefarious.domain.com;
}
}
        # transmission.domain.com
upstream transmission.domain.com {
        ## Can be connected with "nefarious_default" network
        # nefarious-transmission-1
        server 172.26.0.5:9091;
}
server {
        server_name transmission.domain.com;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://transmission.domain.com;
}
}
```
