### DISCUSSION TITLE
Podman ERROR: you need to share your Docker host socket with a volume at /tmp/docker.sock

### DISCUSSION THREAD

**Discussion by JasonLing95** [nginx-proxy/nginx-proxy#2103] [Q&A]
### Podman and Podman-Compose version
```
docker-compose --version
Docker Compose version v2.11.2
docker --version
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
podman version 4.0.2
```

### docker-compose.yml
```
version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  default:
    name: nginx_default
    external: true
```

### Errors
```
sudo podman-compose up
[sudo] password for lingj1:
['podman', '--version', '']
using podman version: 4.0.2
** excluding:  set()
['podman', 'network', 'exists', 'nginx_default']
podman create --name=ngx_proxy_nginx-proxy_1 --label io.podman.compose.config-hash=123 --label io.podman.compose.project=ngx_proxy --label io.podman.compose.version=0.0.1 -- label com.docker.compose.project=ngx_proxy --label com.docker.compose.project.working_dir=/appdata/ngx_proxy --label com.docker.compose.project.config_files=docker-compose.y ml --label com.docker.compose.container-number=1 --label com.docker.compose.service=nginx-proxy -v /run/podman/podman.sock:/tmp/docker.sock:ro --net nginx_default --network- alias nginx-proxy -p 80:80 --privileged nginxproxy/nginx-proxy
Error: error creating container storage: the container name "ngx_proxy_nginx-proxy_1" is already in use by "ddfe69af263d84d563a6c431c7e737d72df504b96e7842ef3fd93fa522eec22a" . You have to remove that container to be able to reuse that name.: that name is already in use
exit code: 125
podman start -a ngx_proxy_nginx-proxy_1
Info: running nginx-proxy version 1.0.1-6-gc4ad18f
ERROR: you need to share your Docker host socket with a volume at /tmp/docker.sock
Typically you should run your nginxproxy/nginx-proxy with: `-v /var/run/docker.sock:/tmp/docker.sock:ro`
See the documentation at: https://github.com/nginx-proxy/nginx-proxy/#usage
```

The volume /var/run/docker.sock is mounted as shown in docker-compose.yml but I'm still getting Error on sharing Docker host socket. Any idea what went wrong?

**Comment by hairmare** [comment]
The following seems to work for podman-compose (note the `security_opts` configuration).
```yaml
version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /run/podman/podman.sock:/tmp/docker.sock:ro
    security_opt:
      - 'label=type:docker_t'
```

Sources:
* https://github.com/nginx-proxy/nginx-proxy/discussions/1845#discussioncomment-2520666
* https://github.com/containers/podman-compose/issues/263#issuecomment-757589069
