### DISCUSSION TITLE
SocketIO disconnects behind proxy

### DISCUSSION THREAD

**Discussion by TannerGabriel** [nginx-proxy/nginx-proxy#2117] [General]
I have a SocketIO setup with a Javascript server that runs behind `nginx-proxy` and the `letsencrypt-nginx-proxy-companion`. The server has two clients (one in JS and one in Python). The python client occasionally disconnects when connected over HTTPS and domain e.g. `wss://DOMAIN/socket.io` (sometimes up to 100 disconnects an hour). This does not happen when running using `ws://IP:PORT`; therefore, I reason that it has something to do with my proxy configuration.

```yaml
version: '2'
services:
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/certs"
      - "./proxy.conf:/etc/nginx/proxy.conf"
  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"
```

Here is the extra configuration for the Nginx proxy:

```
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;

# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";

proxy_connect_timeout 86400s;
proxy_send_timeout 86400s;
proxy_read_timeout 86400s;
send_timeout 86400s;
```

Are there any configuration changes to fix this issue?
