### DISCUSSION TITLE
Cannot get nginx-proxy to work with gluetun and mullvad port forwarding

### DISCUSSION THREAD

**Discussion by capsel22** [nginx-proxy/nginx-proxy#2142] [Q&A]
Hi,

Would someone be able to help me work out how to connect all the pieces here, please?
I cant find a way out of this, feel like I've tried everything. I've never used reverse-proxy and only using docker for a week, so probably missing some knowledge somewhere.

The idea is that I've got gluetun VPN container which all other containers are routed through. Mullvad VPN provides me with port forwarding. So the idea is to point that port to proxy and proxy at other container.
I can confirm the port is hitting proxy, however it is not forwarding traffic to the other container. I am getting 502 Gateway error and stream error in proxy logs.

The obvious issue with this setup could be network_mode: "service:gluetun" with this I cannot use Expose=5055 environmental value, but I can use the VIRTUAL_HOST and _PORT.

Dont know, if you have any ideas, I'd greatly appreciate.

my cut down docker-compose

```yaml
---
version: "3.6"
services:

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    network_mode: bridge
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTPProxy
      - 5055:5055 # overseerr
    environment:
      - TZ=Europe/London
      - PUID=1001
      - PGID=1001
      - HTTPPROXY=on
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=redacted
      - WIREGUARD_ADDRESSES=redacted
      - SERVER_CITIES=redacted
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
      - FIREWALL_VPN_INPUT_PORTS=57160
    restart: always 

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
     - HTTP_PORT=57160
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/London
      - PORT=5055
      - VIRTUAL_HOST=redacted.duckdns.org
      - VIRTUAL_PORT=5055
    volumes:
      - /mnt/data/config/overseerr:/config
    restart: unless-stopped
```
