### DISCUSSION TITLE
Is there a way to run nginx in debug mode?

### DISCUSSION THREAD

**Discussion by alibeyram** [nginx-proxy/nginx-proxy#2171] [Q&A] [answered]
I was wondering if there is a way to use nginx-debug too from https://hub.docker.com/_/nginx

this is what they said to put in the docker-compose.yml
```
web:
  image: nginx
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  command: [nginx-debug, '-g', 'daemon off;']
```

I have already added 
`error_log /var/log/nginx/error.log debug;` 
to the `/etc/nginx/vhost.d/default` file but I cannot see debug output. 

The reason I want the output is to find out why my `proxy_pass` does not work. 

here is my `default` file:

```
error_log /var/log/nginx/error.log debug;
```
