### DISCUSSION TITLE
Logging for nginx-proxy?

### DISCUSSION THREAD

**Discussion by jesuisme** [nginx-proxy/nginx-proxy#2174] [Q&A]
I'm trying to debug my Gunicorn setup and would like to see what's happening with the proxy. How can we turn on/set logging for nginx-proxy?

My docker-compose.yml looks like this:

```
nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - helloworld

helloworld:
    build:
      context: ./hello_world/
    volumes:
      - /hello_world
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=helloworld.local
      - VIRTUAL_PORT=8000
```
