### DISCUSSION TITLE
Standalone Docker Image Proxying for Stack

### DISCUSSION THREAD

**Discussion by AlexOConnorHub** [nginx-proxy/nginx-proxy#2204] [Q&A]
I am hoping to run a standalone Docker instance of nginx-proxy/acme-companion (copied from the `docker -d...` startups from the acme-companion readme). I would like it to proxy to a docker stack/docker compose (the one at the end of this). I currently have the `ports` section just for testing, and the service is running properly, but intend to not keep that long, since my understanding is that just having the `expose` section is enough for the proxy. Anyway, the problem is I'm just getting a 502, and the log on the proxy image has
```
nginx.1     | 2023/03/21 23:30:03 [warn] 60#60: no resolver defined to resolve r3.o.lencr.org while requesting certificate status, responder: r3.o.lencr.org, certificate: "/etc/nginx/certs/domain.tld.crt"
nginx.1     | 2023/03/21 23:30:03 [error] 60#60: *633 no live upstreams while connecting to upstream, client: IP_ADDRESS_HERE, server: domain.tld, request: "GET / HTTP/2.0", upstream: "http://domain.tld/", host: "domain.tld"
```
```
version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.2-fpm-nginx
    volumes:
      - /usr/local/share/foss-url-shortener/.composer-docker/cache:/root/.composer/cache:delegated
      - /usr/local/share/foss-url-shortener/:/app:delegated
    expose:
      - "8000"
    ports:
      - '8000:80'
    environment:
      - VIRTUAL_HOST=domain.tld
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=domain.tld
```
