### DISCUSSION TITLE
How to configure nginx-proxy with an nginx server inside a container

### DISCUSSION THREAD

**Discussion by gobnat** [nginx-proxy/nginx-proxy#2218] [Q&A]
I have a docker-compose setup with nginx-proxy exposed to the web and forwarding traffic to some containers. 

One of my containers is a vue3/node app built with an nginx image to serve the built image. 

I cannot for the life of my get nginx-proxy and the vue/nginx server talking correctly with each other. How is such a setup supposed to be configured? 

NOTE: This was working fine with the webpack dev server, it's only when i moved to the deployment build with nginx I ran into trouble. 

No issues with my other containers behind the proxy. 

my docker-compose:

```yaml
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: dockerfiles/Stage.Dockerfile
    restart: always
    volumes:
      - ./frontend/:/code/dist/
    environment:
      - VIRTUAL_HOST=myapp.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=myapp.com 
    expose:
      - 8080
      
  ...
  
  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    restart: always
    dns: 
      - 8.8.8.8
    ports:
      - 443:443
      - 80:80
    environment:
       - RESOLVERS=8.8.8.8
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - backend
      - frontend   
```  

my nginx conf in my vue app:

```nginx
server {
  listen       8080;
  server_name  myapp.com;
  location / {
    root /usr/share/nginx/html;
    index  index.html;
    try_files $uri $uri/ /index.html;
  }
  error_page   500 502 503 504  /50x.html;
  location = /50x.html {
    root   /usr/share/nginx/html;
  }
}
```

The proxy is trying to communicate with the container but - depending on what setting I try changing - I just get some form or other of `failed (111: Connection refused) while connecting to upstream`

I've had trouble finding good documentation on setups like mine. Is it a bad setup? Should I not being doing it this way? 

And of course, any suggestions as to how this should be configured?
