### DISCUSSION TITLE
Adding headers

### DISCUSSION THREAD

**Discussion by rgerbranda** [nginx-proxy/nginx-proxy#2253] [Q&A]
I want to add some headers. To do so, I added a configuration file to ```/etc/nginx/conf.d```

I tried the file names
- my_config.conf
- VIRTUAL_HOST
- VIRTUAL_HOST.conf

But nothing seems to work. The headers are not added.

In the folder ```/etc/nginx/conf.d``` are the following files:
- ```default.conf``` (created by the docker instance)
- the extra file

The extra file contains
```
add_header X-Frame-Options "SAMEORIGIN";
add_header X-Content-Type-Options nosniff;
add_header X-XSS-Protection "1; mode=block";
```

What I'm doing wrong?

**Comment by rgerbranda** [comment]
The proxy is started like this:

```
  proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    networks:
      homenetwork:
        ipv4_address: 172.32.0.10
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /local/certs:/etc/nginx/certs
      - /local/nginx/extra.conf:/etc/nginx/conf.d/VIRTUAL_HOST:ro
```
