### DISCUSSION TITLE
Proxying minecraft servers

### DISCUSSION THREAD

**Discussion by antoKeinanen** [nginx-proxy/nginx-proxy#2262] [Q&A]
Hey! 
I'm trying to have multiple Minecraft servers running on the same host. But it isn't working for some reason. I cannot connect to either of the servers through the proxy. The servers work fine without the proxy. I have created a network with the name `proxy-net`. The port `25565` is forwarded and I have DNS A record pointing to the server for the subdomain.
# Minecraft server's docker-compose.yml file:
```yml
version: "3.9"
services:
  minecraft:
    image: "marctv/minecraft-papermc-server:latest"
    restart: always
    container_name: "server1"
    environment:
      - MEMORYSIZE=4G
      - PAPERMC_FLAGS=
      - VIRTUAL_HOST=server1.antok.dev
      - VIRTUAL_PORT=25565
    volumes:
      - "/home/ubuntu/server1:/data:rw"
    expose:
      - 25565
    networks:
      - proxy-net
    # The following allow `docker attach minecraft` to work
    stdin_open: true
    tty: true

networks:
  proxy-net:
    name: proxy-net
    external: true
```
# nginx-proxy docker-compose.yml file:
```
services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - 25565:25565
      - 80:80
    volumes:
      - /home/ubuntu/nginx-proxy/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock
    networks:
      - proxy-net

networks:
  proxy-net:
    name: proxy-net
    external: true
```
# Nmap scan results:
```
Starting Nmap 7.80 ( https://nmap.org ) at 2023-06-23 21:27 EEST
Nmap scan report for server1.antok.dev (129.151.207.134)
Host is up (0.018s latency).

PORT      STATE  SERVICE
25565/tcp closed minecraft

Nmap done: 1 IP address (1 host up) scanned in 0.11 seconds
```

Am I doing something wrong or is Minecraft not supported? Thank you in advance!
