### DISCUSSION TITLE
nginx-proxy path based routing gives 404 error for application assets

### DISCUSSION THREAD

**Discussion by paulheil** [nginx-proxy/nginx-proxy#2291] [Q&A] [answered]
I'm attempting to use the path based routing feature of `nginxproxy/nginx-proxy` to host [dozzle ](https://dozzle.dev/) at http://media.local/dozzle/. 

```
version: "3"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./nginx/vhost.d:/etc/nginx/vhost.d"

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=media.local
      - VIRTUAL_PATH=/dozzle/
      - VIRTUAL_PORT=8080
```

When I load http://media.local/dozzle/ in chrome, I get a blank page with the dozzle favicon. The chrome dev tools report

```
/dozzle/:15     GET http://media.local/assets/main-aeb02c57.css net::ERR_ABORTED 404 (Not Found)
/dozzle/:16     GET http://media.local/assets/main-299e3767.js net::ERR_ABORTED 404 (Not Found)
```

obviously, I want the browser to request `http://media.local/dozzle/assets/main-aeb02c57.css` instead

I've tried this with services other than dozzle and the result is the same, so I do not think this is a dozzle-specific issue. How can I get the path based routing to include all of the application assets?
