### DISCUSSION TITLE
How to export the full access.log to host as file?

### DISCUSSION THREAD

**Discussion by Emporea** [nginx-proxy/nginx-proxy#2298] [Q&A] [answered]
I am using nginx-proxy (nginx + dockergen) and acme_companion.

docker logs nginx-proxy provides me with logs but its not only access log and only a limited amount of time.

How to export the full access.log to the host?

/var/log/nginx/access.log is just a symbolic link to /dev/stdout.

**Comment by SchoNie** [comment]
Make a bind mount from `/var/log/nginx/` to a location on your host. Then the access.log is written to a persistent location.
Something like:
```yaml
    volumes:
      - "./accesslogs/:/var/log/nginx/"
```

Be carefull that you need to do some kind of logrotation on the access.log/error.log else the file will grow indefinitely.

**Reply by Emporea** [reply]
Yes I know, and would use logration.

But your suggestion doesn't work. 
Even on my host directory i can only see this
```
lrwxrwxrwx 1 root root   11 Aug 29 02:37 access.log -> /dev/stdout
lrwxrwxrwx 1 root root   11 Aug 29 02:37 error.log -> /dev/stderr
```

**Reply by SchoNie** [reply]
Do you have your full compose so I can recreate on my side?

**Reply by Emporea** [reply]
```
  proxy_nginx:
    container_name: proxy_nginx
    image: nginxproxy/nginx-proxy:alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - proxy_nginx_conf:/etc/nginx/conf.d
      - proxy_nginx_vhost:/etc/nginx/vhost.d
      - proxy_nginx_html:/usr/share/nginx/html
      - proxy_nginx_dhparam:/etc/nginx/dhparam
      - proxy_nginx_certs:/etc/nginx/certs:ro
      - proxy_nginx_logs:/var/log/nginx/ # this volume should be for the logs
      - /var/run/docker.sock:/tmp/docker.sock:ro

  proxy_acme:
    container_name: proxy_acme
    image: nginxproxy/acme-companion:latest
    restart: unless-stopped
    volumes_from:
      - proxy_nginx
    volumes:
      - proxy_nginx_certs:/etc/nginx/certs
      - proxy_nginx_acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
      
volumes:
  proxy_nginx_conf:
  proxy_nginx_vhost:
  proxy_nginx_html:
  proxy_nginx_dhparam:
  proxy_nginx_certs:
  proxy_nginx_acme:
  proxy_nginx_logs:

networks:
  default:
    external: true
    name: main
```
