### DISCUSSION TITLE
Subcontainer ssl certification

### DISCUSSION THREAD

**Discussion by HerrMagiic** [nginx-proxy/nginx-proxy#2312] [Q&A]
Hello,

Is it possible to have a single subcontainer handle SSL certification for a subdomain? I currently have one container that generates its own SSL certificate(panel), and I have a container(whoami) that utilize a cloudflare certificate.
The panel container creates its own certificate the certbot.

There might be a easer way, but I'm not very experienced with proxy servers.

Thanks for help🙏

My docker compose file:
```yaml
version: '3.9'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    environment:
      - ENABLE_IPV6=true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/volumes/nginx-proxy-conf/certs:/etc/nginx/certs:ro
    networks:
      - internal
      - default

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=test.orizon-surf.de
      - CERT_NAME=orizon-surf.de
    volumes:
      - ./nginx/volumes/nginx-proxy-conf/certs:/etc/nginx/certs:ro
    networks:
      - internal
      - default

  panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: always
    links:
      - database
      - cache
    volumes:
      - "./nginx/volumes/pterodactyl/var/:/app/var/"
      - "./nginx/volumes/pterodactyl/nginx/:/etc/nginx/http.d/"
      - "./nginx/volumes/pterodactyl/nginx/certs/:/etc/letsencrypt/"
      - "./nginx/volumes/pterodactyl/logs/:/app/storage/logs"
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      DB_PORT: "3306"
      VIRTUAL_HOST: panel.orizon-surf.de,node.orizon-surf.de
    networks:
      - default
networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
  internal:
    driver: bridge
```
