### DISCUSSION TITLE
containerd support

### DISCUSSION THREAD

**Discussion by minixxie** [nginx-proxy/nginx-proxy#2314] [Q&A]
Hi,

I've been using this image for long time even in production environment (thanks for the support).
Now I have a question - when I'm trying on my local laptop with "colima" (using lima as underlying VM engine), and specify "containerd" runtime, I got the following error:
```
Info: running nginx-proxy version 1.3.1-40-g67ab97e
ERROR: you need to share your Docker host socket with a volume at /tmp/docker.sock
Typically you should run your nginxproxy/nginx-proxy with: `-v /var/run/docker.sock:/tmp/docker.sock:ro`
See the documentation at: https://github.com/nginx-proxy/nginx-proxy/#usage
```

I believe it's because containerd doesn't have /var/run/docker.sock. May I know what I should do to run this on containerd?
Thanks a lot.

P.S.:
docker-compose.yml
```yaml
---
version: '3.3'
services:
  nginx-proxy:
    image: ${PULL_THRU_CACHE}jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    hostname: nginx-proxy
    restart: always
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/tmp/docker.sock:ro
    ports:
      - 80:80
    networks:
      - local_network
    healthcheck:
      test: nc -zv 127.0.0.1 80
      interval: 5s
      timeout: 4s
      retries: 36
networks:
  local_network:
    name: local_network
```

command:
```
DOCKER_SOCK=/run/containerd/containerd.sock PULL_THRU_CACHE= nerdctl compose up -d
```

Simon
