### DISCUSSION TITLE
Need help: docker compose question to properly setup nginx reverse proxy

### DISCUSSION THREAD

**Discussion by LarsHill** [nginx-proxy/nginx-proxy#2317] [Q&A]
Hi everyone,

I currently use docker-compose to deploy 2 services that listen on different ports on server A with example IP 1.2.3
Let's say "service 1" listens on port 3000 and "service 2" listens on port 4000. 
Since both ports, 3000 and 4000, are opened on server A, I can access the respective endpoints from outside the server, e.g. by sending POST requests to `http://1.2.3:3000/endpoint` (service 1) and `http://1.2.3:4000/endpoint` (service 2). 
This setup works without any problem.

However, since opening multiple ports for different services is not really a nice and scalable option, I figured I could use a reverse-proxy (no experience what so ever) to only open 1 port on server A, e.g. 8000 and forward the requests based on a given path to the respective ports (not open anymore) of the deployed services. 

So sending a post request to `http://1.2.3:8000/service-1/endpoint` and `http://1.2.3:8000/service-2/endpoint` should be forwarded by the proxy to the respective endpoints listening on local ports 3000 and 4000.

Reading the `README.md` of this repo I figured such a `docker-compose.yml` should work.
However, when sending post requests after the services are created I always receive connection timeout errors.

```yaml
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    restart: always
    ports:
      - "8000:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  service-1:
    image: image1
    container_name: service-1
    expose:
     - "3000"
    environment:  # 1.2.3 is the IP of the server, the wildcard is necessary since the service defines multiple endpoints
      - VIRTUAL_HOST=1.2.3
      - VIRTUAL_PATH=/service-1/*
      - VIRTUAL_PORT=3000

  service-2:
    image: image2
    container_name: service-2
    expose:
     - "4000"
    environment:
      - VIRTUAL_HOST=1.2.3
      - VIRTUAL_PATH=/service-2/*
      - VIRTUAL_PORT=4000
```

Can someone maybe help me find the mistake? How do I have to tweak the docker-compose yaml file in order to get my desired setup to work?

Thanks a lot and best regards
