### DISCUSSION TITLE
nginx-proxy on QNAP NAS

### DISCUSSION THREAD

**Discussion by st0rm3rd** [nginx-proxy/nginx-proxy#2342] [Q&A] [answered]
Hi all, this container seems to do what I am looking for, i.e. creating simple shortcuts to my containers, e.g. portainer.qnap.nas.
However, before I delve into this, I know that port 80 is an issue on QNAP as it is defined for internal use by QNAP NAS.
Therefore, will this container work on my QNAP NAS? It is as simple as just remapping the 80 port in the docker compose file to another port?

**Comment by buchdag** [comment, marked as answer]
Hi.

Yes it'll work, you'll need to follow the instruction for [Custom external HTTP/HTTPS ports](https://github.com/nginx-proxy/nginx-proxy?tab=readme-ov-file#custom-external-httphttps-ports).

Be advised though that `acme-companion` [probably won't work](https://github.com/nginx-proxy/acme-companion?tab=readme-ov-file#requirements).

**Reply by st0rm3rd** [reply]
Thanks buchdag, I had a look at that.

I ran it with the indicated ports in your link, but still do no get access to the nginx user interface. I checked the log in Portainer and see the below with no idea how to troubleshoot.

**docker-compose:**

```yaml
version: '2'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "1080:1080"
      - "10443:10443"
    environment:
      - HTTP_PORT=1080
      - HTTPS_PORT=10443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro 
```

**log**:

```console
Info: running nginx-proxy version 1.4.0-69-g6f04285
Setting up DH Parameters..
Warning: TRUST_DOWNSTREAM_PROXY is not set; defaulting to "true". For security, you should explicitly set TRUST_DOWNSTREAM_PROXY to "false" if there is not a trusted reverse proxy in front of this proxy.
Warning: The default value of TRUST_DOWNSTREAM_PROXY might change to "false" in a future version of nginx-proxy. If you require TRUST_DOWNSTREAM_PROXY to be enabled, explicitly set it to "true".
forego      | starting dockergen.1 on port 5000
forego      | starting nginx.1 on port 5100
nginx.1     | 2024/01/13 12:43:58 [notice] 21#21: using the "epoll" event method
nginx.1     | 2024/01/13 12:43:58 [notice] 21#21: nginx/1.25.3
nginx.1     | 2024/01/13 12:43:58 [notice] 21#21: built by gcc 12.2.0 (Debian 12.2.0-14) 
nginx.1     | 2024/01/13 12:43:58 [notice] 21#21: OS: Linux 5.10.60-qnap
nginx.1     | 2024/01/13 12:43:58 [notice] 21#21: getrlimit(RLIMIT_NOFILE): 65535:65535
nginx.1     | 2024/01/13 12:43:58 [notice] 21#21: start worker processes
nginx.1     | 2024/01/13 12:43:58 [notice] 21#21: start worker process 26
nginx.1     | 2024/01/13 12:43:58 [notice] 21#21: start worker process 27
nginx.1     | 2024/01/13 12:43:58 [notice] 21#21: start worker process 28
nginx.1     | 2024/01/13 12:43:58 [notice] 21#21: start worker process 29
dockergen.1 | 2024/01/13 12:43:58 Template error: open /etc/nginx/certs: no such file or directory
dockergen.1 | 2024/01/13 12:43:58 Generated '/etc/nginx/conf.d/default.conf' from 24 containers
dockergen.1 | 2024/01/13 12:43:58 Running 'nginx -s reload'
dockergen.1 | 2024/01/13 12:43:58 Error running notify command: nginx -s reload, exit status 1
dockergen.1 | 2024/01/13 12:43:58 Watching docker events
dockergen.1 | 2024/01/13 12:43:58 Template error: open /etc/nginx/certs: no such file or directory
dockergen.1 | 2024/01/13 12:43:58 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload
```

**Reply by buchdag** [reply]
Could you try adding a Docker volume mounted to `/etc/nginx/certs` ?

```yaml
version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "1080:1080"
      - "10443:10443"
    environment:
      - HTTP_PORT=1080
      - HTTPS_PORT=10443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs

volumes:
  certs:
```
