### DISCUSSION TITLE
Virtual Host Alias 301 Redirection

### DISCUSSION THREAD

**Discussion by dannycarrera** [nginx-proxy/nginx-proxy#2414] [Ideas]
PRs #1369 and #1563 are both solving the same problem and are in unfinished states. Both PRs only introduce alias redirection for the first virtual host. Multiple aliases for multiple virtual hosts should be supported.

Before continuing working on either PR, I think it will be beneficial to have a group discussion on the syntax to achieve this.

My proposal is to use the REDIRECT environment variable with the value consisting of  vhosts separated by commas and each vhost defines its aliases following a colon, separated by pipes.

Example:
```
environment:
    - VIRTUAL_HOST: site-a.com,site-b.com
    - REDIRECT: site-a.com:www.site-a.com|old.site-a.com,site-b.com:www.site
    - LETSENCRYPT_HOST: site-a.com,www.site-a.com,old.site-a.com,site-b.com,www.site-b.com
```
