### DISCUSSION TITLE
Understanding usage of VIRTUAL_PATH

### DISCUSSION THREAD

**Discussion by Ripper346** [nginx-proxy/nginx-proxy#2418] [Q&A]
Hi, I have a NestJS backend served on port 3000, and an nginx angular frontend served on port 80. I am using nginx-proxy in a compose to route everything. By using 3rd level domain, it works; now, I wanted to redirect the backend to a path of the frontend. I have written the following:
```yaml
services:
  nginx-proxy:
    restart: unless-stopped
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-proxy/conf.d:/etc/nginx/conf.d
      - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - ./nginx-proxy/html:/usr/share/nginx/html
      - ./nginx-proxy/dhparam:/etc/nginx/dhparam
      - ./nginx-proxy/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - web

  frontend:
    container_name: frontend
    image: frontend
    restart: unless-stopped
    environment:
      TZ: UTC
      VIRTUAL_HOST: beta.mydomain.com
      VIRTUAL_PATH: /
    networks:
      - web

  backend:
    container_name: backend
    image: backend
    restart: unless-stopped
    environment:
      TZ: UTC
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: beta.mydomain.com
      VIRTUAL_PATH: /api/
    networks:
      - web

networks:
  web:
    external: true
    name: web-network
```
Why am I getting error 502 on both? Am I missing something? From the documentation and some examples I found, I should have done everything. On nginx-proxy container, I see that the requests arrived and it gives me this:

```
nginx.1     | 2024/03/31 18:46:47 [error] 29#29: *5 no live upstreams while connecting to upstream, client: 1.0.0.0, server: beta.mydomain.com, request: "GET /api/ HTTP/1.1", upstream: "http://beta.mydomain.com-357322ae39f93f572e23cd9edd3307e2ac5a321f/", host: "beta.mydomain.com"
nginx.1     | beta.mydomain.com 1.0.0.0 - - [31/Mar/2024:18:46:47 +0000] "GET /api/ HTTP/1.1" 502 559 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "beta.mydomain.com-357322ae39f93f572e23cd9edd3307e2ac5a321f"
```

Thank you.
