### DISCUSSION TITLE
VIRTUAL_HOST_MULTIPORTS question

### DISCUSSION THREAD

**Discussion by RomeSilvanus** [nginx-proxy/nginx-proxy#2487] [Q&A]
Hi,

I'm having trouble understanding how to properly use VIRTUAL_HOST_MULTIPORTS (from https://github.com/nginx-proxy/nginx-proxy/tree/main/docs#virtual-ports).

As far as I understand the documentation it should allow me to expose multiple ports on one domain name. What I want to do is use the Sftpgo container, which exposes a web interface on port 9014 and a webdav server on port 9015 (ports chosen by myself). So I should be able to connect to webday.domain.com (for the web interface) and webdav.domain.com:9015 (for the webdav server).

Is this how VIRTUAL_HOST_MULTIPORTS is intended to be used? I tried to make something out of the JSON example but it never worked.

**Comment by SchoNie** [comment]
Did you try? Maybe post your compose?

If you add something like this:
```
    environment:
      VIRTUAL_HOST_MULTIPORTS: |-
        webday.domain.com:
          "/":
            port: 9014
        webdav.domain.com:
          "/":
            port: 9015
```
You should have a config to handle this:

`webday.domain.com` -> `multiport-container:9014` (the webgui)
`webdav.domain.com` -> `multiport-container:9015` (webdav)
