### DISCUSSION TITLE
I am testing nginx proxy and specifically the ACLs and these are not working as expected, I always get 403.

### DISCUSSION THREAD

**Discussion by elico** [nginx-proxy/nginx-proxy#2508] [Q&A]
I am using nginx proxy in docker with a very simple docker-compose:
```
services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./rate-limit.conf:/etc/nginx/conf.d/rate-limit.conf
```

But for some in the logs I see the source ip of the client as the ip of the docker hypervisor.
I am not sure how to look at this issue to understand what is causing this to happen.
I have a dual stack and the host sits in the DMZ.
It only happens for hair pinned nat local traffic.
I have dual stack(v4+6) network.
From the outside network it works as expected.
