### DISCUSSION TITLE
Why does nginx-proxy not creating a domain in Docker network

### DISCUSSION THREAD

**Discussion by Kenya-West** [nginx-proxy/nginx-proxy#2521] [Q&A] [answered]
Run this:

```sh
docker network create -d bridge xui_network
```

and then up these to services:

```yaml
version: "3.8"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.6
    container_name: nginx-proxy
    cpus: "0.5"
    mem_limit: 200m
    environment:
      - DEFAULT_HOST=web.lan
    networks:
      - xui_network
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
  dummy:
    image: nginx:latest
    container_name: dummy
    cpus: "0.5"
    mem_limit: 200m
    environment:
      - VIRTUAL_HOST=DEFAULT_HOST
      - VIRTUAL_PATH=/
    networks:
      - xui_network
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html:ro
    restart: unless-stopped
  checking:
    command: tail -f /dev/null
    networks:
      - xui_network

networks:
  xui_network:
    external: true
```

config for `dummy` service:

```nginx
events {}

http {
    server {
        listen 80 http2;
        server_name dummy;

        location / {
            root /usr/share/nginx/html;
            index index.html;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $proxy_protocol_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
```

Go inside `docker exec -it checking /bin/sh` container and try to wget `web.lan` resource:

```sh
wget -qO- http://web.lan:80
```

\- it does not find the domain:

```stderr
wget: bad address 'web.lan:80'
```

... while `dummy` domain works, as Docker creates a name for it in DNS:

```sh
wget -qO- http://dummy:80

# <HTML content goes here>
```

Why does `nginx-proxy` not creating `web.lan` domain inside Docker network?
