### DISCUSSION TITLE
Why does `nginx-proxy` returns 503 from other `nginx`?

### DISCUSSION THREAD

**Discussion by Kenya-West** [nginx-proxy/nginx-proxy#2522] [Q&A]
Let's create 3 services and a network:

```sh
docker network create -d bridge xui_network
```

and then up these to services:

```yaml
version: "3.8"

services:
  nginx:
    image: nginxproxy/nginx-proxy:1.6
    container_name: nginx
    cpus: "0.5"
    mem_limit: 200m
    environment:
      - DEFAULT_HOST=nginx # points to itself
    networks:
      - xui_network
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
  dummy:
    image: nginx:latest
    container_name: dummy
    cpus: "0.5"
    mem_limit: 200m
    environment:
      - VIRTUAL_HOST=DEFAULT_HOST
      - VIRTUAL_PATH=/
    networks:
      - xui_network
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html:ro
    restart: unless-stopped
  checking:
    command: tail -f /dev/null
    networks:
      - xui_network

networks:
  xui_network:
    external: true
```

config for `dummy` service:

```nginx
events {}

http {
    server {
        listen 80 http2;
        server_name dummy;

        location / {
            root /usr/share/nginx/html;
            index index.html;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $proxy_protocol_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
```

`nginx-proxy` gives me the following config on `nginx -T` command:

```nginx
# dummy/
upstream dummy {
    # Container: dummy
    #     networks:
    #         xui_network (reachable)
    #     IP address: 172.20.0.5
    #     exposed ports (first ten): 80/tcp
    #     default port: 80
    #     using port: 80
    server 172.20.0.5:80;
}
server {
    server_name dummy;
    access_log /var/log/nginx/access.log vhost;
    http2 on;
    listen 80 ;
    location /.well-known/acme-challenge/ {
        auth_basic off;
        allow all;
        root /usr/share/nginx/html;
        try_files $uri =404;
        break;
    }
    listen 443 ssl ;
    # No certificate for this vhost nor default certificate found, so reject SSL handshake.
    ssl_reject_handshake on;
    location / {
        proxy_pass http://dummy;
        set $upstream_keepalive false;
    }
}
```

Go inside `docker exec -it checking /bin/sh` container and try to wget `nginx` resource:

```sh
wget -qO- http://nginx/
```

\- it gives HTTP 503 error:

```stderr
wget: server returned error: HTTP/1.1 503 Service Temporarily Unavailable
```

\- `docker compose logs nginx` give the same string without any explanation

... while `dummy` domain returns correct static page:

```sh
wget -qO- http://dummy

# <HTML content goes here>
```

Why does `nginx-proxy` (available inside network as `nginx`) gives 503 given from another nginx instance `dummy`, which gives us correct static page, if it was accessed directly?

**Comment by Kenya-West** [comment]
Well actually it routes if I give it "Host: <Docker service name>" header:

```sh
root@933f1d9278f7:/app# curl -H "Host: dummy" http://nginx
<!-- You can deploy your app here in /static -->

<!DOCTYPE html>
<html>
  <head>
    <title>My Web Page</title>
  </head>
  <body>
    <h1>Just some web page</h1>
  </body>
</html>

root@933f1d9278f7:/app# curl http://nginx
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>
root@933f1d9278f7:/app#
```

See? Without `Host` header it gives 503 error.

The problem now is: I do not control what header to give.

There is [X-UI Go server](https://github.com/alireza0/x-ui) built on [XRay core](https://github.com/XTLS/Xray-core) in front of `nginx-proxy`, and it fallbacks to `nginx-proxy` instance without knowing what `Host` header to set.

Problem cannot be solved, can it?

**Comment by buchdag** [comment]
Hi
```yaml
services:
  nginx:
    #[...]
    container_name: nginx
    environment:
      - DEFAULT_HOST=nginx # points to itself
    #[...]
  dummy:
    #[...]
    environment:
      - VIRTUAL_HOST=DEFAULT_HOST
```
I don't understand what you are trying to accomplish with the `DEFAULT_HOST` and `VIRTUAL_HOST` environment variables here.

[`DEFAULT_HOST`](https://github.com/nginx-proxy/nginx-proxy/tree/main/docs#default-host) tells nginx-proxy which `VIRTUAL_HOST` should be considered the default one. It has to be a host name that is currently configured as a `VIRTUAL_HOST` on at least one of your proxied containers. You can't reference a container name or "point to itself" here.

`VIRTUAL_HOST` should be a host name or a comma separated list of host name. It tells nginx proxy to route incoming request for those host names to this / those specific containers. It's unclear to me if this is what you understood or not but there is no magical `DEFAULT_HOST` value you can use here.

On the application container: `VIRTUAL_HOST=test.foo.com` means incoming request to test.foo.com (ie request that have the `Host` header set to `foo.test.com`) will be proxied by nginx-proxy to this container.

On the nginx-proxy container: `DEFAULT_HOST=test.foo.com` means incoming request to unkown (by ninx-proxy) hosts will be proxied to the application container that have `VIRTUAL_HOST=test.foo.com` set. If there is no container with `VIRTUAL_HOST=test.foo.com`, you'll get a 503 error.
