### DISCUSSION TITLE
Separate error pages for 500, 501, 502, 503 etc?

### DISCUSSION THREAD

**Discussion by slidenerd** [nginx-proxy/nginx-proxy#2523] [Q&A]
- I am trying to get nginx-proxy version 1.6.2 working with my node.js express backend via docker-compose

Here is a part of the docker-compose.yml file

```
...
    container_name: ch_api_sta_nginx_proxy
    environment:
      - LOG_JSON=true
      - RESOLVERS=8.8.8.8
    image: nginxproxy/nginx-proxy:1.6.2
    logging:
      driver: awslogs
      options:
        awslogs-group: ch-api-sta-group
        awslogs-region: us-east-1
        awslogs-stream: ch-api-sta-acme-companion-stream
    networks:
      - network
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /home/ec2-user/api/docker/staging/nginx_server/errors/500.html:/usr/share/nginx/html/errors/500.html:ro
      - /home/ec2-user/api/docker/staging/nginx_server/errors/501.html:/usr/share/nginx/html/errors/501.html:ro
      - /home/ec2-user/api/docker/staging/nginx_server/errors/502.html:/usr/share/nginx/html/errors/502.html:ro
      - /home/ec2-user/api/docker/staging/nginx_server/errors/503.html:/usr/share/nginx/html/errors/503.html:ro
      - /home/ec2-user/api/docker/staging/nginx_server/errors/520.html:/usr/share/nginx/html/errors/520.html:ro
      - /home/ec2-user/api/docker/staging/nginx_server/errors/521.html:/usr/share/nginx/html/errors/521.html:ro
      - /home/ec2-user/api/docker/staging/nginx_server/errors/533.html:/usr/share/nginx/html/errors/533.html:ro
      - /home/ec2-user/api/docker/staging/nginx_server/ratelimit.conf:/etc/nginx/conf.d/ratelimit.conf:ro
      - /home/ec2-user/api/docker/staging/nginx_server/www.api.example.com_location:/etc/nginx/vhost.d/www.api.example.com_location:ro
      - /home/ec2-user/api/docker/staging/nginx_server/www.example.com_location:/etc/nginx/vhost.d/www.example.com_location:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_certs:/etc/nginx/certs:ro
      - nginx_conf:/etc/nginx/conf.d
      - nginx_html:/usr/share/nginx/html
      - nginx_vhost:/etc/nginx/vhost.d
...
```
The generated nginx config seems to be expecting a single 50x.html file as per the [documentation](https://github.com/nginx-proxy/nginx-proxy/tree/main/docs#custom-error-page)

- I honestly don't know how to add a dynamic message inside the 50x.html that nginx will automatically substitute for different 50x errors like 501, 502, 503 etc

- Apart from modifying the nginx.tmpl file manually is there no way to achieve different custom error pages for different errors?
