### DISCUSSION TITLE
Certificate error when specifying VIRTUAL_HOST with a port.

### DISCUSSION THREAD

**Discussion by vsfomin** [nginx-proxy/nginx-proxy#2527] [Q&A] [answered]
There is a problem with binding a wildcard certificate to a domain name. 
I have a minIO up and it has two domain names: `VIRTUAL_HOST: uploads-syn.example.gg:9002, s3-syn.example.gg` 
Port 9002 is accessible by the name uploads-syn.example.gg
When accessing it an error ERR_SSL_PROTOCOL_ERROR occurs.
My certs folder contain certificates:
example.gg.crt  example.gg.key (for *.example.gg) 
example_gg.crt example_gg.key (for example.gg)
In the nginx config I see the following:

```nginx
server {
    server_name uploads-syn.example.gg;
    access_log /var/log/nginx/access.log vhost;
    http2 on;
    listen 443 ssl  ;
    # No certificate found for this vhost, so force nginx to emit a TLS error if
    # the client connects via https.
    ssl_ciphers aNULL;
    set $empty "";
    ssl_certificate data:$empty;
    ssl_certificate_key data:$empty;
    if ($https) {
        return 444;
    }
```

```yaml
 environment:
      MINIO_BROWSER_REDIRECT_URL: https://s3-syn.example.gg
      MINIO_DOMAIN: uploads-syn.example.gg
      MINIO_SERVER_URL: https://uploads-syn.example.gg
      MINIO_API_CORS_ALLOW_ORIGIN: '*'
      MINIO_ROOT_USER: example
      MINIO_ROOT_PASSWORD: 123456789
      **VIRTUAL_HOST: uploads-syn.example.gg:9002, s3-syn.example.gg**
      LETSENCRYPT_HOST: uploads-syn.example.gg, s3-syn.example.gg
      VIRTUAL_PORT: 9001

```
