### DISCUSSION TITLE
How to Set Up Moodle to Work from a Subdirectory Using nginx-proxy

### DISCUSSION THREAD

**Discussion by raphaeldallorto** [nginx-proxy/nginx-proxy#2532] [Q&A]
Hello everyone,

I’m trying to configure Moodle (v4.5) to run from a subdirectory (/ead) using nginx-proxy in a Docker setup, and I’m running into issues.

Here is my docker-compose.yml file that works without the subdirectory:

```yaml
services:

  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  db:
    image: bitnami/mariadb:11.4
    container_name: moodle_db
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - ./moodle/mariadb_data:/bitnami/mariadb

  moodle:
    image: bitnami/moodle:4.5
    container_name: moodle
    environment:
      - VIRTUAL_HOST=moodle.example.com
      #- VIRTUAL_PATH=/ead
      - VIRTUAL_PORT=8080
      - MOODLE_DATABASE_TYPE=mariadb
      - MOODLE_DATABASE_HOST=db
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./moodle/moodle_data:/bitnami/moodle
    depends_on:
      - db
volumes:
  db_data:
  moodle_data:
```

To make Moodle accessible at http://moodle.example.com/ead, I tried adding VIRTUAL_PATH=/ead in the Moodle container’s environment, but this results in a "Not Found" error.

I also tried updating the config.php file, located at moodle/moodle_data/config.php according to the docker-compose.yml setup, by appending /ead to $CFG->wwwroot as follows:

`$CFG->wwwroot = 'http://' . $_SERVER['HTTP_HOST'] . '/ead';`

However, that didn’t work either.

One additional note: For the database to function correctly with this setup, I needed to run the following command to adjust permissions:

`sudo chown -R 1001:1001 moodle/mariadb_data/`

Does anyone know the correct way to configure Moodle with nginx-proxy to serve from a subdirectory? Any guidance would be greatly appreciated.
