### DISCUSSION TITLE
Multiple networks in docker compose make 502 bad gateway

### DISCUSSION THREAD

**Discussion by tirenucci** [nginx-proxy/nginx-proxy#2539] [Q&A]
Hello, 

My docker-compose : 

```yaml
services:
    carb0-db-recette:
        image: postgres:13
        container_name: carb0-db-recette
        restart: always
        user: 1000:1000
        volumes:
            - ./db-recette:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD', 'pg_isready', '--host=localhost', '--username=directus']
            interval: 10s
            timeout: 5s
            retries: 5
            start_interval: 5s
            start_period: 30s
        networks:
            - databaseRecette

    carb0-db-test:
        image: postgres:13
        container_name: carb0-db-test
        restart: always
        environment:
            POSTGRES_DB: ${DB_DATABASE_TEST}
            POSTGRES_USER: ${DB_USER_TEST}
            POSTGRES_PASSWORD: ${DB_PASSWORD_TEST}
            PGPORT: 5433
        expose:
            - '5433'
        user: 1000:1000
        volumes:
            - ./db-test:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD', 'pg_isready', '--host=localhost', '--username=directus']
            interval: 10s
            timeout: 5s
            retries: 5
            start_interval: 5s
            start_period: 30s
        networks:
            - databaseTest

    carb0-next-recette:
        image: registry.gitlab.com/tkg8805906/front-carb0:recette
        container_name: carb0-next-recette
        restart: always
        expose:
            - '3000'
        environment:
            #Variable nom de domaine
            - VIRTUAL_HOST=$NEXTJS_VIRTUAL_HOST_RECETTE
            - LETSENCRYPT_HOST=$NEXTJS_LETSENCRYPT_HOST_RECETTE
            - LETSENCRYPT_EMAIL=$NEXTJS_LETSENCRYPT_EMAIL_RECETTE
            #Others
            - NODE_TLS_REJECT_UNAUTHORIZED=0
        networks:
            - proxy-tier
            - databaseRecette

    carb0-next-test:
        image: registry.gitlab.com/tkg8805906/front-carb0:test
        container_name: carb0-next-test
        restart: always
        expose:
            - '3000'
        environment:
            #Variable nom de domaine
            - VIRTUAL_HOST=$NEXTJS_VIRTUAL_HOST_TEST
            - LETSENCRYPT_HOST=$NEXTJS_LETSENCRYPT_HOST_TEST
            - LETSENCRYPT_EMAIL=$NEXTJS_LETSENCRYPT_EMAIL_TEST
            #Others
            - NODE_TLS_REJECT_UNAUTHORIZED=0
        networks:
            - proxy-tier
            - databaseTest

    carb0-directus-recette:
        image: registry.gitlab.com/tkg8805906/back-carb0:recette
        container_name: carb0-directus-recette
        restart: always
        depends_on:
            carb0-db-recette:
                condition: service_healthy
            carb0-cache-recette:
                condition: service_healthy
        volumes:
            - ./upload-recette:/directus/uploads
            - ./templates-recette:/directus/templates
        environment:
            #Variable nom de domaine
            - VIRTUAL_HOST=$DIRECTUS_VIRTUAL_HOST_RECETTE
            - LETSENCRYPT_HOST=$DIRECTUS_LETSENCRYPT_HOST_RECETTE
            - LETSENCRYPT_EMAIL=$DIRECTUS_LETSENCRYPT_EMAIL_RECETTE
        networks:
            - proxy-tier
            - databaseRecette

    carb0-directus-test:
        image: registry.gitlab.com/tkg8805906/back-carb0:test
        container_name: carb0-directus-test
        restart: always
        depends_on:
            carb0-db-test:
                condition: service_healthy
            carb0-cache-test:
                condition: service_healthy
        environment:
            #Variable nom de domaine
            - VIRTUAL_HOST=$DIRECTUS_VIRTUAL_HOST_TEST
            - LETSENCRYPT_HOST=$DIRECTUS_LETSENCRYPT_HOST_TEST
            - LETSENCRYPT_EMAIL=$DIRECTUS_LETSENCRYPT_EMAIL_TEST
        networks:
            - proxy-tier
            - databaseTest

    carb0-cache-recette:
        image: redis:6
        container_name: carb0-cache-recette
        healthcheck:
            test: ['CMD-SHELL', "[ $$(redis-cli ping) = 'PONG' ]"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_interval: 5s
            start_period: 30s
        networks:
            - databaseRecette

    carb0-cache-test:
        image: redis:6
        container_name: carb0-cache-test
        healthcheck:
            test: ['CMD-SHELL', "[ $$(redis-cli ping) = 'PONG' ]"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_interval: 5s
            start_period: 30s
        networks:
            - databaseTest

    carb0-proxy:
        image: nginxproxy/nginx-proxy:alpine
        container_name: carb0-proxy
        restart: always
        ports:
            - 80:80
            - 443:443
        labels:
            com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: 'true'
        volumes:
            - ./certs:/etc/nginx/certs
            - ./vhost.d:/etc/nginx/vhost.d
            - ./html:/usr/share/nginx/html
            - /var/run/docker.sock:/tmp/docker.sock
        networks:
            - proxy-tier

    carb0-letsencrypt-companion:
        image: nginxproxy/acme-companion
        container_name: carb0-letsencrypt-companion
        restart: always
        volumes:
            - ./certs:/etc/nginx/certs
            - ./acme:/etc/acme.sh
            - ./vhost.d:/etc/nginx/vhost.d
            - ./html:/usr/share/nginx/html
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - proxy-tier
        depends_on:
            - carb0-proxy

networks:
    proxy-tier:
        driver: bridge
    databaseRecette:
        driver: bridge
    databaseTest:
        driver: bridge
```

I cant' acess to my app : 
- carb0-next-test -> 502 bad gateway
- carb0-next-recette -> 502 bad gateway
- carb0-directus-test -> 502 bad gateway
- carb0-directus-recette -> 502 bad gateway

I don't know why, i see in the doc : 

> At the time of this writing, only a single network can be specified at container creation time.

Something with this ? 

Can someone help me :) thank's by advance ;)
