### DISCUSSION TITLE
Different VIRTUAL_PATH/DEST config for each host

### DISCUSSION THREAD

**Discussion by AhmedKamal20** [nginx-proxy/nginx-proxy#2542] [Q&A] [answered]
Hi, 

I have two services that kinda than I sometimes need to access them with the same domain (frontend) but other times I need to access them separately (API)

The Docker-Compose:

```yaml
services:

  reverse:
    image: "nginxproxy/nginx-proxy"
    container_name: "reverse"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  foo:
    image: "jwilder/whoami"
    hostname: "foo"
    domainname: "example.io"
    container_name: "foo"
    tty: true
    stdin_open: true
    networks:
      default:
        aliases:
          - "foo.example.io"
    ports:
      - 8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      VIRTUAL_HOST: "foo.example.io"
      VIRTUAL_PORT: 8000
      VIRTUAL_PATH: /

  bar:
    image: "jwilder/whoami"
    hostname: "bar"
    domainname: "example.io"
    container_name: "bar"
    tty: true
    stdin_open: true
    networks:
      default:
        aliases:
          - "bar.example.io"
    ports:
      - 8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      VIRTUAL_HOST: "foo.example.io,bar.example.io"
      VIRTUAL_PORT: 8000
      VIRTUAL_PATH: /bar/
      VIRTUAL_DEST: /bar/
```

So , what I need is the following 

- http://foo.example.io ->> "I'm foo" :heavy_check_mark: Done
- http://foo.example.io/bar ->> "I'm Bar" :heavy_check_mark: Done
- http://bar.example.io ->> "I'm Bar" :x: Can't do it

The third point is not achieved with this configuration because it's waiting for path `/bar/`
So is there a way when I have multiple hosts, that allow me to configure different `VIRTUAL_PATH`, `VIRTUAL_DEST`  for each host ? 

I would really appreciate some help

**Comment by SchoNie** [comment, marked as answer]
I think you can configure this by using the [multiports](https://github.com/nginx-proxy/nginx-proxy/tree/main/docs#multiple-ports) function on the bar service.

```yaml
    environment:
      VIRTUAL_HOST_MULTIPORTS: |-
        bar.example.com:
          "/":
            port: 8000
            dest: "/"
        foo.example.com:
          "/bar":
            port: 8000
            dest: "/bar"
```

**Reply by AhmedKamal20** [reply]
@SchoNie Thank you, but unfortunately, it didn't work for me
It seems that it doesn't see this configuration at all, I can't reach the bar service anymore

```
curl http://foo.example.io/ -> I'm foo
curl http://bar.example.io/ -> 503
curl http://foo.example.io -> I'm foo
curl http://bar.example.io -> 503
curl http://foo.example.io/bar -> I'm foo
curl http://foo.example.io/bar/ -> I'm foo
```

The Docker-Compose:
```yaml
services:

  reverse:
    image: "nginxproxy/nginx-proxy"
    container_name: "reverse"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  foo:
    image: "jwilder/whoami"
    hostname: "foo"
    domainname: "example.io"
    container_name: "foo"
    tty: true
    stdin_open: true
    networks:
      default:
        aliases:
          - "foo.example.io"
    ports:
      - 8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      VIRTUAL_HOST: "foo.example.io"
      VIRTUAL_PORT: 8000
      VIRTUAL_PATH: /

  bar:
    image: "jwilder/whoami"
    hostname: "bar"
    domainname: "example.io"
    container_name: "bar"
    tty: true
    stdin_open: true
    networks:
      default:
        aliases:
          - "bar.example.io"
    ports:
      - 8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # VIRTUAL_HOST: "foo.example.io,bar.example.io"
      # VIRTUAL_PORT: 8000
      # VIRTUAL_PATH: /bar/
      # VIRTUAL_DEST: /bar/
      VIRTUAL_HOST_MULTIPORTS: |-
        bar.example.io:
          "/":
            port: 8000
            dest: "/"
        foo.example.io:
          "/bar":
            port: 8000
            dest: "/bar"

```

Any Idea ?
