### DISCUSSION TITLE
how to allow additional inbound ssl ports?

### DISCUSSION THREAD

**Discussion by amy-langley** [nginx-proxy/nginx-proxy#2597] [Ideas]
I am trying to set up a Matrix server called `synapse`. Matrix federation wants to use port `8448`. On my VPS, I want to accept inbound SSL traffic on port `443` for all containers, but additionally on port `8448` just for my matrix container. How can I accomplish this? Following the docs, I attempted to add container-specific config 

```nginx
listen 8448 ssl ;
```

in `/etc/nginx/vhost.d/matrix.my-domain.com`, but this didn't work. I then thought I would try to make it work as a proxy-wide setting so I added the following as `/etc/nginx/conf.d/matrix-extra.conf`:

```nginx
map $server_port $host_port {
    default :$server_port;
    80 '';
    443 '';
    8448 '';
}

log_format vhost2 escape=default '$host $remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$upstream_addr"';

server {
    server_name matrix.my-domain.com;
    access_log /var/log/nginx/access.log vhost2;
    http2 on;
    listen 8448 ssl ;
    ssl_session_timeout 5m;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;
    ssl_certificate [known correct path to my cert];
    ssl_certificate_key [known correct path to my key];
    ssl_stapling on;
    ssl_stapling_verify on;
    ssl_trusted_certificate [known correct path to my chain.pem];
    set $sts_header "";
    if ($https) {
        set $sts_header "max-age=31536000";
    }
    add_header Strict-Transport-Security $sts_header always;
    location / {
        proxy_pass http://matrix.my-domain.com;
        set $upstream_keepalive false;
    }
}

# (note that this is pretty much just a copy and paste from the `default.conf` 
# that was generated for my container with port `443` replaced by `8448`)
```

but this did not work either--the requests in either case time out at the client side and are not even logged by nginx according to the container logs.

Is there a setting to do what I'm trying to do more easily? If not, can anyone suggest what I'm doing wrong? I'm not particularly experienced with nginx config, which is why I was excited to use this project.

**Comment by wkelton** [comment]
I need to do the same thing. Haven't got it setup yet. A couple of notes:
* Matrix needs to listen on 8448 of the root domain, so:
```
example.com:8448 # matrix federation port
matrix.example.com:443/_matrix
matrix.example.com:443/_synapse/client
```
* Also, be sure that your nginx-proxy container is binding to 8448 (just like it does 80 and 443)

Not sure how to do this. You have any luck?

**Reply by amy-langley** [reply]
> Matrix needs to listen on 8448 of the root domain

I wasn't aware of this--I was assuming that synapse/matrix would listen on 8448 at matrix.mydomain.com. Have I missed something in the documentation? I was trying to use https://federationtester.matrix.org/# to test my configuration but it really wants it to be running on 8448.

**Reply by wkelton** [reply]
Yeah: https://element-hq.github.io/synapse/latest/reverse_proxy.html
>You should remember that Matrix clients and other Matrix servers do not necessarily need to connect to your server via the same server name or port. Indeed, clients will use port 443 by default, whereas servers default to port 8448.

They go on with an example:
>Let's assume that we expect clients to connect to our server at https://matrix.example.com, and other servers to connect at https://example.com:8448.

The spec itself is a bit obtuse. I _think_ it allows for you to use the subdomain (matrix.example.com). However, I believe that is technically the definition of the homeserver. So, your users would be `@user:matrix.example.com` instead of `@user:example.com`.

**Reply by amy-langley** [reply]
Ah right, I'd forgotten about that because the tutorial I was following did matrix.example.com first and then later example.com; I didn't make it far enough to try that.

**Comment by buchdag** [comment]
@amy-langley @wkelton I don't think that what you want to do is currently possible with nginx-proxy (not 100% sure, I'll have to take a look at the code again), but it might intersect with an already asked for feature.

Correct me if I'm wrong but from what I understood, you want to be able to tell nginx-proxy _"for this specific proxied service, listen for https on port N instead of the default 443 port"_ ?

**Reply by amy-langley** [reply]
For my use case, I could also accept "listen on port `8448` in addition to `443`", either for *just* the synapse container or for *all* proxied containers. It is possible that at this point I might be better off just standing up a separate `nginx` instance on port `8448` within my `docker-compose.yml` for synapse and its database, but I am struggling to understand how to adapt the the `default.conf` generated by `nginx-proxy` for this purpose.

Also echoing wkelton, thank you for your reply!

**Reply by amy-langley** [reply]
So I guess in other words, my asked for features in order of priority are:

1. The ability to specify multiple HTTP and HTTPS ports inbound to the proxy
2. The ability to map specific inbound HTTP and HTTPS ports to particular containers

Of the two, I can get by with only the first one, but the second one would be super nice in terms of limiting attack surfaces

**Comment by wkelton** [comment]
@buchdag thanks for replying!

I think ideally, something like this:
```yaml
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
      - "8448:8448"
...

  synapse:
    environment:
      VIRTUAL_HOST_MULTIPORTS: |-
        example.org:
          "/":
            port: 8448
            host_https_port: 8448
        matrix.example.org:
          "/":
            port: 8080
```

**Reply by buchdag** [reply]
@wkelton I've played a bit with that suggestion but unfortunately the HTTP / HTTPS port nginx is listening on isn't really an information that is a "child" of the virtual path.

In other words something like that would not work without major refactor of the template logic:

```yaml
synapse:
    environment:
      VIRTUAL_HOST_MULTIPORTS: |-
        example.org:
          "/":
            port: 8448
            host_https_port: 8448
          "/path"
            host_https_port: 443
        matrix.example.org:
          "/":
            port: 8080
```

The expected behavior here would be:
- `https://example.org:8448` => `synapse:8448`
- `https://example.org/path` => `synapse:443`
- `https://matrix.example.org` => `synapse:8080`

But the template is looping on the hostnames, creating a `server` block with the appropriate `listen` directive(s), then looping over the paths to create the corresponding `location` block for them. By the time it's accessing the data inside each path dict, the listen directive with the external HTTP / HTTPS port has already been generated.

I think however that something link this would be easily possible, with the external / host port being set at the hostname level:

```yaml
 synapse:
    environment:
      VIRTUAL_HOST_MULTIPORTS: |-
        example.org:
          host_https_port: 8448
          "/":
            port: 8448
          "/path"
        matrix.example.org:
          "/":
            port: 8080
```

In this scenario, the following would be happening:
- `https://example.org:8448` => `synapse:8448`
- `https://example.org:8448/path` => `synapse:80`
- `https://matrix.example.org` => `synapse:8080`

I'm not sure which way to take here.

**Reply by wkelton** [reply]
For matrix/synapse, the second is sufficient. For the root domain, only the root path is needed. So, something like this would be great:
```yaml
 synapse:
    environment:
      VIRTUAL_HOST_MULTIPORTS: |-
        example.org:
          host_https_port: 8448
          "/":
            port: 8448
        matrix.example.org:
          "/":
            port: 8080
```
In this scenario, the following would be happening:
- `https://example.org:8448` => `synapse:8448`
- `https://matrix.example.org` => `synapse:8080`

**Reply by wkelton** [reply]
@buchdag, is this something that might be possible in the near future?

**Comment by wkelton** [comment]
I wonder if we can kind of hack it now with something like:
```yaml
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
      - "8448:8448"
...

  synapse:
    environment:
      VIRTUAL_HOST_MULTIPORTS: |-
        example.org:
          "/_unused": # just some path that isn't used
        matrix.example.org:
          "/":
            port: 8080
```
And then add some conf.d for `example.org` that has the appropriate nginx details like the `listen 8448 ssl` directive?

**Comment by amy-langley** [comment]
I have found a resolution for my issue, but my solution is not particularly intellectually satisfying. I ended up doing the following:

### What I Did
1. Continue using `nginx-proxy` for forwarding `matrix.example.net:80` and `matrix.example.net:443`
2. Obtain the generated `nginx.conf` and `default.conf` from inside the `nginx-proxy` container and editing them together into a new `nginx.conf`
3. Remove everything related to my other containers from the new `nginx.conf`
4. Replace every occurrence of `matrix.example.net` with `example.net` in the new `nginx.conf`
5. Add another `nginx` container called `proxy` to my `synapse` docker compose to handle `example.net`
6. Give  the new `nginx.conf` to the new `nginx` container
7. Ensure that a strict initialization order was specified in the `docker-compose.yml` for synapse. this way the IP addresses will always be assigned the same way.
8. Use `docker inspect network synapse-default` to find the internal IP address used by the `synapse-app-1` container
9. Edit the upstream for `example.net` to contain that IP address

### Notes about my `nginx-proxy` setup:
I use an external network called `backplane` to connect all of my containers that `nginx-proxy` needs to proxy for. The new `synapse-proxy-1` container connects directly to `synapse-app-1` via the `synapse_default` network and ignores the `backplane` network

### Complaints
Obviously this is brittle and I'd rather be able to dynamically resolve the IP address of `synapse-app-1` instead of forcing it to be generated in a specific way. If anyone has any insights about how to improve this I'd be happy to hear them!

### My config files

```yaml
# synapse/docker-compose.yml
services:
  app:
    image: matrixdotorg/synapse:latest
    volumes:
      - ./data:/data
    networks:
      - default
      - backplane
    expose:
      - "8008"
    environment:
      - VIRTUAL_HOST=matrix.example.net
      - VIRTUAL_PORT=8008
    depends_on:
      - db
  db:
    image: postgres:17
    shm_size: 128mb
    env_file: ./postgres.env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  proxy:
    image: nginx:1.27.2
    ports:
      - "8448:8448"
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dhparam:/etc/nginx/dhparam:ro
    depends_on:
      - app

networks:
  backplane:
    external: true
```

```nginx
# synapse-proxy/nginx.conf
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  10240;
}
worker_rlimit_nofile 20480;


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;

    # nginx-proxy version : 1.6.4
    # Networks available to the container running docker-gen (which are assumed to
    # match the networks available to the container running nginx):
    #     backplane
    # If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
    # scheme used to connect to this server
    map $http_x_forwarded_proto $proxy_x_forwarded_proto {
        default $scheme;
        '' $scheme;
    }
    map $http_x_forwarded_host $proxy_x_forwarded_host {
        default $host;
        '' $host;
    }
    # If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
    # server port the client connected to
    map $http_x_forwarded_port $proxy_x_forwarded_port {
        default $server_port;
        '' $server_port;
    }
    map $server_port $host_port {
        default :$server_port;
        8448 '';
    }
    # If the request from the downstream client has an "Upgrade:" header (set to any
    # non-empty value), pass "Connection: upgrade" to the upstream (backend) server.
    # Otherwise, the value for the "Connection" header depends on whether the user
    # has enabled keepalive to the upstream server.
    map $http_upgrade $proxy_connection {
        default upgrade;
        '' $proxy_connection_noupgrade;
    }
    map $upstream_keepalive $proxy_connection_noupgrade {
        # Preserve nginx's default behavior (send "Connection: close").
        default close;
        # Use an empty string to cancel nginx's default behavior.
        true '';
    }
    # Abuse the map directive (see <https://stackoverflow.com/q/14433309>) to ensure
    # that $upstream_keepalive is always defined.  This is necessary because:
    #   - The $proxy_connection variable is indirectly derived from
    #     $upstream_keepalive, so $upstream_keepalive must be defined whenever
    #     $proxy_connection is resolved.
    #   - The $proxy_connection variable is used in a proxy_set_header directive in
    #     the http block, so it is always fully resolved for every request -- even
    #     those where proxy_pass is not used (e.g., unknown virtual host).
    map "" $upstream_keepalive {
        # The value here should not matter because it should always be overridden in
        # a location block (see the "location" template) for all requests where the
        # value actually matters.
        default false;
    }
    # Apply fix for very long server names
    server_names_hash_bucket_size 128;
    # Default dhparam
    ssl_dhparam /etc/nginx/dhparam/dhparam.pem;
    # Set appropriate X-Forwarded-Ssl header based on $proxy_x_forwarded_proto
    map $proxy_x_forwarded_proto $proxy_x_forwarded_ssl {
        default off;
        https on;
    }
    gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
    log_format vhost escape=default '$host $remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$upstream_addr"';
    access_log off;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1
305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305';
        ssl_prefer_server_ciphers off;
    error_log /dev/stderr;
    resolver 127.0.0.11;
    # HTTP 1.1 support
    proxy_http_version 1.1;
    proxy_set_header Host $host$host_port;
    proxy_set_header Host $host$host_port;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $proxy_connection;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $proxy_x_forwarded_host;
    proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
    proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
    proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
    proxy_set_header X-Original-URI $request_uri;
    # Mitigate httpoxy attack (see README for details)
    proxy_set_header Proxy "";
    # example.net/
    upstream example.net {
        # Container: synapse-app-1
        #     networks:
        #         backplane (reachable)
        #         synapse_default (reachable)
        #     IP address: 172.20.0.3
        #     exposed ports (first ten): 8008/tcp 8009/tcp 8448/tcp
        #     default port: 80
        #     using port: 8008
	server 172.20.0.3:8008;  # find this value from docker network inspect synapse_default
    }
    server {
        server_name example.net;
        access_log /var/log/nginx/access.log vhost;
        http2 on;
        listen 8448 ssl ;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/example.net.crt;
        ssl_certificate_key /etc/nginx/certs/example.net.key;
        ssl_stapling on;
        ssl_stapling_verify on;
        ssl_trusted_certificate /etc/nginx/certs/example.net.chain.pem;
        set $sts_header "";
        if ($https) {
            set $sts_header "max-age=31536000";
        }
        add_header Strict-Transport-Security $sts_header always;
        location / {
            proxy_pass http://example.net;
            set $upstream_keepalive false;
        }
    }
}

include /etc/nginx/toplevel.conf.d/*.conf;
```

**Reply by buchdag** [reply]
@amy-langley if you want to change the HTTP / HTTPS port nginx is listening on for ALL proxied containers, there's already a pair of environment variables for that: https://github.com/nginx-proxy/nginx-proxy/tree/main/docs#custom-external-httphttps-ports

**Comment by buchdag** [comment]
I lost a lot of time on this, believing that having per-virtual path external port was possible and pausing development until I had time to tackle the necessary refactor, while it's actually not possible with nginx.

A draft PR for per-virtual host configurable external ports has been opened [here](https://github.com/nginx-proxy/nginx-proxy/pull/2678).

The image is available as [`nginxproxy/nginx-proxy:2678`](https://hub.docker.com/repository/docker/nginxproxy/nginx-proxy/tags/2678) or [`nginxproxy/nginx-proxy:2678-alpine`](https://hub.docker.com/repository/docker/nginxproxy/nginx-proxy/tags/2678-alpine) for test.

It uses this approach:

```yaml
services:
  synapse:
    environment:
      VIRTUAL_HOST_MULTIPORTS: |-
        example.org:
          exernal_https_port: 8448
          "/":
            port: 8448
          "/path"
        matrix.example.org:
          "/":
            port: 8080
```

- `https://example.org:8448` => `synapse:8448`
- `https://example.org:8448/path` => `synapse:80`
- `https://matrix.example.org` => `synapse:8080`

`external_http_port` and / or `external_https_port` can be defined at the virtual host level, and will be used for all of the virtual paths of this virtual host.

For containers that don't use `VIRTUAL_HOST_MULTIPORTS`, two new environment variables serve the same purpose : `EXTERNAL_HTTP_PORT` and `EXTERNAL_HTTPS_PORT`, ie:

```yaml
services:
  synapse:
    environment:
      VIRTUAL_HOST: "example.org"
      VIRTUAL_PORT: "8448"
      EXTERNAL_HTTPS_PORT: "8448"
```

- `https://example.org:8448` => `synapse:8448`

ping @amy-langley @wkelton @Murazaki @agostop

**Reply by Murazaki** [reply]
I'm sorry, it's kinda hard to test without breaking my setup, but it seems like this might not resolve the main issue I had in mind, which is non-http redirections.
They were why I made the ticket https://github.com/nginx-proxy/nginx-proxy/issues/2637. it seems possible to handle those though in the same manner, but I feel like it would've been easier if the proto was another variable, and not in the name of the port variable (`ext_port` and `proto` instead of `external_http_port`).

**Reply by wkelton** [reply]
This looks like it would be great!

I ended up working-around this situation. I figured out you can tell synapse to send the federation requests (port 8448) to a different url by responding with a .well-known. I created a `vhost.d/example.org` with:
```
location /.well-known/matrix/client {
    default_type application/json;
    add_header Access-Control-Allow-Origin *;
    return 200 '{"m.homeserver": {"base_url": "https://matrix.example.org"}}';
}
```
With my synapse container:
```
services:
  synapse:
    environment:
      VIRTUAL_HOST: "example.org,matrix.example.org"
      VIRTUAL_PORT: "8008"
```
This avoids the need for the extra https port.

I think I prefer this approach, and am concerned about testing this change with my working setup. But, if you need this change tested, I could probably setup a fresh matrix stack and test it eventually if that would help you.
