### DISCUSSION TITLE
How to redirect to host?

### DISCUSSION THREAD

**Discussion by NikoQT** [nginx-proxy/nginx-proxy#2619] [Q&A] [answered]
While I want most of my adresses routed to a container, I also have one service which runs directly on the host

so how can I redirect test.example.com to port 8080 of my docker host system?

**Comment by SchoNie** [comment, marked as answer]
This is not possible out the box. But a manual config file of course is possible.
You can find multiple issues and discussions like #2575 #998 which give some hints to use a dummy container and use [Overriding location blocks](https://github.com/nginx-proxy/nginx-proxy/tree/main/docs#overriding-location-blocks)

**Comment by Bob-le-pirate** [comment]
This is one way to do it :
```yaml
  relay:
    image: alpine/socat
    read_only: true
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 64M
        reservations:
          memory: 32M
    restart: unless-stopped
    command: "TCP-LISTEN:61208,fork,reuseaddr TCP:192.168.1.102:61208"
    expose:
      - "61208"
    environment:
      - VIRTUAL_HOST=foo.fr
      - VIRTUAL_PORT=61208
```
