### ISSUE TITLE
How to use any custom SSL certificate (i.e., not from Let's Encrypt)?

### ISSUE THREAD

**Issue by amankapoor** [nginx-proxy/nginx-proxy#1072]
Hey there,

On 27th Feb, 2018, it is expected that Let's Encrypt will make wildcard certificates accessible for public. My current setup uses https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion, but it won't support wildcard certificates for the reasons mentioned here - https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/319. 

Because I want to use wildcard certificate on my domain, I am planning to invest time and learn how I can generate certs myself and then manually add them. In this process, I tried understanding the readme on this repo, but it's not clear to me where should I put the certificate files.

My current docker-compose.yml file for the nginx and LE setup looks like this - 

```
version: '2'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    depends_on:
      - nginx-proxy
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    environment:
      - ACME_TOS_HASH=cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:

networks:
  default:
    external:
      name: nginx-proxy
```

So, do I have to access the nginx-proxy container (through docker exec .....) and then put certificate files inside it, or I have to do something else?

We can make this question more general by asking how would you people use the Let's Encrypt services if https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion this companion didn't exist? Or, how would we use custom ssl certificates (like from GeoTrust, GoDaddy etc) with nginx-proxy?
