### ISSUE TITLE
nginx with pihole, nextcloud, openhab - only error 503

### ISSUE THREAD

**Issue by Friday13th87** [nginx-proxy/nginx-proxy#1169]
i like to run pihole, openhab and nextcloud with mariadb with ssl encryption on my homeserver but i dont get it to run probably.

i know there are some 503 error issues already but nothing helful for me.
i hope someone can help me and tell me what i am doing wrong

i always get only an 503 error, i tried it with and without lets encrypt and with https redirection and without
 
here is my compose file

```
version: '3.7' 

services:

  nginx:
    image: jwilder/nginx-proxy:alpine
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx_network
    volumes:
      - /home/server/docker/nginx/conf.d:/etc/nginx/conf.d
      - /home/server/docker/nginx/vhost.d:/etc/nginx/vhost.d
      - /home/server/docker/nginx/html:/usr/share/nginx/html
      - /home/server/docker/nginx/certs:/etc/nginx/certs:ro
      - /home/server/docker/nginx/htpasswd:/etc/nginx/htpasswd
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

    environment:
      - DEFAULT_HOST=pihole.domain1.de
      - HTTPS_METHOD=noredirect

    restart: always
  
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    depends_on:
      - nginx
    networks:
      - nginx_network

    volumes:
      - /home/server/docker/nginx/certs:/etc/nginx/certs:rw
      - /home/server/docker/nginx/vhost.d:/etc/nginx/vhost.d:rw
      - /home/server/docker/nginx/html:/usr/share/nginx/html:rw
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    networks:
      - nginx_network
    volumes:
      - /home/server/docker/mariadb/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_PASSWORD=mysql_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    depends_on:
      - letsencrypt
      - nginx
      - mariadb
    networks:
      - nginx_network
    volumes:
      - /home/server/docker/nextcloud/html:/var/www/html
      - /home/server/docker/nextcloud/config:/var/www/html/config
      - /home/server/docker/nextcloud/custom_apps:/var/www/html/custom_apps
      - /media/Daten/Nextcloud:/var/www/html/data
      - /home/server/docker/nextcloud/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=mycloud.domain1.de,mycloud.domain2.de
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=mycloud.domain1.de,mycloud.domain2.de
      - LETSENCRYPT_EMAIL=my@email.address


  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    depends_on:
      - letsencrypt
      - nginx
    networks:
      - nginx_network
    volumes:
      - /home/server/docker/pihole/log/pihole.log:/var/log/pihole.log
      - /home/server/docker/pihole:/etc/pihole
      - /home/server/docker/pihole/dnsmasq.d:/etc/dnsmasq.d
  #net: host
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=Europe/Berlin
      - WEBPASSWORD=pihole
      - DNS1=46.182.19.48
      - DNS2=194.150.168.168
      - DNSMASQ_LISTENING=all
      - ServerIP=192.168.13.5
      - PROXY_LOCATION=pihole
      - VIRTUAL_HOST=pihole.domain1.de,pihole.domain2.de
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=pihole.domain1.de,pihole.domain2.de
      - LETSENCRYPT_EMAIL=my@email.address



  openhab:
    image: openhab/openhab:2.3.0-amd64-debian
    container_name: openhab
    restart: always
    depends_on:
      - letsencrypt
      - nginx
    networks:
      - nginx_network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/server/docker/openhab/addons:/openhab/addons
      - /home/server/docker/openhab/conf:/openhab/conf
      - /home/server/docker/openhab/userdata:/openhab/userdata
    environment:
      #OPENHAB_HTTP_PORT=8080
      #OPENHAB_HTTPS_PORT=8443
      - USER_ID=9001
      - GROUP_ID=9001
      - VIRTUAL_HOST=openhab.domain1.de,,openhab2.domain2.de
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=openhab.domain1.de,,openhab2.domain2.de
      - LETSENCRYPT_EMAIL=my@email.address



networks:
  nginx_network:
    driver: bridge
```

**Comment by Friday13th87** [comment]
i was able to setup nginx with letsencrypt, openhab and portainer.
i needed to run every container in a seperated compose file and wait a littlebit in between.

openhab and portainer is working because i am using the same internal and external ports (portainer 9000, openhab 8080/8443)

my pihole and nextcloud is not working for my proxy "pihole/nextcloud.mydomain.com"
Both are working from the specified ports with the homeserver IP.

How should it be with the port configuration (internal and external) and virtual port?

here are my compose files:

nginx
```
version: '3.7' 

services:

  nginx:
    image: jwilder/nginx-proxy:alpine
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx_network
    volumes:
      - /home/zotac/docker/nginx/conf.d:/etc/nginx/conf.d:rw
      - /home/zotac/docker/nginx/vhost.d:/etc/nginx/vhost.d:rw
      - /home/zotac/docker/nginx/html:/usr/share/nginx/html:rw
      - /home/zotac/docker/nginx/certs:/etc/nginx/certs:ro
      - /home/zotac/docker/nginx/htpasswd:/etc/nginx/htpasswd
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=pihole.mydomain.com
      #- HTTPS_METHOD=noredirect

networks:
  nginx_network:
    name: nginx_network
```

openhab (working via https://openhab.mydomain.com with ssl)
```
version: '3.7' 

  openhab:
    image: openhab/openhab:2.3.0-amd64-debian
    container_name: openhab
    restart: always
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      - nginx_network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/zotac/docker/openhab/addons:/openhab/addons
      - /home/zotac/docker/openhab/conf:/openhab/conf
      - /home/zotac/docker/openhab/userdata:/openhab/userdata
    environment:
      - OPENHAB_HTTP_PORT=8080
      - OPENHAB_HTTPS_PORT=8443
      - USER_ID=9001
      - GROUP_ID=9001
      - VIRTUAL_HOST=openhab.mydomain.com,openhab.mydomain.com
      #- VIRTUAL_PROTO=https
      - VIRTUAL_PORT=8443
      #- VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=openhab.mydomain.com,openhab.mydomain2.com
      - LETSENCRYPT_EMAIL=freitag13th@gmail.com
    expose:
      #- 8080
      - 8443
networks:
  nginx_network:
    name: nginx_network
```

pihole (not working from extern, workin intern on "serverip:7070")
```
version: '3.7' 

services:

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    networks:
      - nginx_network
    volumes:
      - /home/zotac/docker/pihole/log/pihole.log:/var/log/pihole.log
      - /home/zotac/docker/pihole:/etc/pihole
      - /home/zotac/docker/pihole/dnsmasq.d:/etc/dnsmasq.d
  #net: host
    cap_add:
      - NET_ADMIN
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 7070:80/tcp
      - 7443:443/tcp
    environment:
      - TZ=Europe/Berlin
      - WEBPASSWORD=test123
      - DNS1=46.182.19.48
      - DNS2=194.150.168.168
      - DNSMASQ_LISTENING=all
      - ServerIP=192.168.13.5
      - PROXY_LOCATION=pihole
      - VIRTUAL_HOST=pihole.fearox.de,pihole.goip.de
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
      #- VIRTUAL_PORT=7070
      - LETSENCRYPT_HOST=pihole.fearox.de,pihole.goip.de
      - LETSENCRYPT_EMAIL=freitag13th@gmail.com
    #expose:
      #- 7070
      #- 7443

networks:
  nginx_network:
    name: nginx_network
```

nextcloud (not working from outside, working with server ip and port 7000)
```
version: '3.7' 

services:

  nextcloud:
    #image: nextcloud:latest
    image: nextcloud:fpm
    container_name: nextcloud
    restart: always
    ports:
      - 7000:9000
    networks:
      - nginx_network
    volumes:
      - /home/zotac/docker/nextcloud/html:/var/www/html
      - /home/zotac/docker/nextcloud/config:/var/www/html/config
      - /home/zotac/docker/nextcloud/custom_apps:/var/www/html/custom_apps
      - /media/Daten/Nextcloud:/var/www/html/data
      - /home/zotac/docker/nextcloud/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=mycloud.fearox.de,mycloud.goip.de
      #- VIRTUAL_PROTO=https
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=mycloud.fearox.de,mycloud.goip.de
      - LETSENCRYPT_EMAIL=freitag13th@gmail.com
    expose:
      - 9000

networks:
  nginx_network:
    name: nginx_network
```

**Comment by bkraul** [comment]
I started to say, that kind of looked massive to be in one single compose file...the whole point of docker is containerization. It makes sense to group containers that will be performing the task collectively. As far as what you got going, I can only give you how I run my set up. You might choose to use some or none and that's fine, but I can tell you it works.

**nginx-proxy**
Here is my nginx-proxy compose:
```yml
version: '3.1'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /root/docker-persist/nginx-proxy/certs:/etc/nginx/certs
      - /root/docker-persist/nginx-proxy/dhparam:/etc/nginx/dhparam
      - /root/docker-persist/nginx-proxy/vhost.d:/etc/nginx/vhost.d
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
```
What this does, you already know, as yours looks pretty similar. However, one thing to keep in mind is that I am creating a ```reverse-proxy``` network that is independent of any container, so that it will not be destroyed when the proxy container gets destroyed. I do it with the following script which I execute only once.

```bash
#!/bin/sh

if [ ! $(docker network ls -q -f name=reverse-proxy) ]; then
  docker network create --driver bridge reverse-proxy
fi
```

**How I handle certs**
Because I own a single domain, and the ever changing nature of LetsEncrypt cerbot scripts kept driving me insane, what I do now is that I get a wildcard let's encrypt certificate from http://www.sslforfree.com (using DNS verification), and then I just replace it every 3 months in the /certs folder. A lot less headache for me. I understand this might not work for you, but it works well for me.

**pihole**
If you are using pihole as your local network's DNS/DHCP server, and you use a virtualized environment, I would greatly recommend separating it onto another host (paired with nginx-proxy, of course). The reason for this is, you will have a hard time updating, because the moment pihole is down for updates, your DNS resolution will be out, and if you have to restart the host, resolution on your whole network will go down as well. For me, having it separated allows me to minimize the downtime of my network, as I only update the pihole host when absolutely needed. Anyway, this is my pihole compose:

```yml
version: '3.1'

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    volumes:
      - /root/docker-persist/pihole/:/etc/pihole/
      - /root/docker-persist/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    ports:
      - '53:53/tcp'
      - '53:53/udp'
    environment:
      - ServerIP=192.168.0.128
      - PROXY_LOCATION=pihole
      - VIRTUAL_HOST=pi-hole.belmankraul.com,pi.hole
      - TZ=America/Chicago
      - WEBPASSWORD=mypassword
      - DNS1=192.168.0.254 #my router's address
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external:
      name: reverse-proxy
```
For reference, I am using my pihole instance to define static DNS entries for all the servers I run in my docker environment (using a ```02-custom.conf``` file in ```/dnsmasq.d```).

**nextcloud**
My nextcloud is a little different. I prefer the fpm-alpine implementation due to its minimal size and greater speed. As such, I created my own extended images that derive from official latest to add capabilities, etc.

```yml
version: '3.1'

services:
  redis:
    image: redis:alpine
    sysctls:
      - net.core.somaxconn=511
    volumes:
      - nextcloud_redis:/data
    restart: always
    networks:
      - default
  app:
    image: bkraul/nextcloud
    restart: always
    volumes:
      - nextcloud_html:/var/www/html
      - /mnt/nfs/nas.belmankraul.com/nextcloud/data:/var/www/html/data
      - /mnt/nfs/nas.belmankraul.com/nextcloud/config:/var/www/html/config
      - /mnt/nfs/nas.belmankraul.com/nextcloud/custom_apps:/var/www/html/custom_apps
    environment:
      - MYSQL_HOST=docker.belmankraul.com
    depends_on:
      - redis
    networks:
      - default
  cron:
    image: bkraul/nextcloud
    restart: always
    volumes:
      - nextcloud_html:/var/www/html
      - /mnt/nfs/nas.belmankraul.com/nextcloud/data:/var/www/html/data
      - /mnt/nfs/nas.belmankraul.com/nextcloud/config:/var/www/html/config
      - /mnt/nfs/nas.belmankraul.com/nextcloud/custom_apps:/var/www/html/custom_apps
    entrypoint: /cron.sh
    depends_on:
      - redis
    networks:
      - default
  web:
    image: bkraul/nginx-nextcloud
    restart: always
    volumes:
      - nextcloud_html:/var/www/html
      - /mnt/nfs/nas.belmankraul.com/nextcloud/data:/var/www/html/data
      - /mnt/nfs/nas.belmankraul.com/nextcloud/config:/var/www/html/config
      - /mnt/nfs/nas.belmankraul.com/nextcloud/custom_apps:/var/www/html/custom_apps
    environment:
      - VIRTUAL_HOST=nextcloud.belmankraul.com
    depends_on:
      - app
    networks:
      - reverse-proxy
      - default

volumes:
  nextcloud_html:
  nextcloud_redis:

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
```

**Considerations**
Not sure about the correctness of this, but it is my understanding that if you are running a container through nginx-proxy, you do not have to list its port in the ```ports``` section, you either expose it, or use the VIRTUAL_PORT env variable to tell the proxy where to find it.

I know this is not much, but even if a little bit helps, that's good right?
