### ISSUE TITLE
https without letsencrypt

### ISSUE THREAD

**Issue by Starli0n** [nginx-proxy/nginx-proxy#1180]
Hi,

I am behind a corporate proxy that could not resolve the ACME challenge.
Therefore, I would like to run the application with auto generated SSL certificates:

```
openssl req -new -x509 -nodes -newkey rsa:2048 -keyout .certs/${NGINX_HOSTNAME}.key -out .certs/${NGINX_HOSTNAME}.crt \
		-subj "/C=FR/ST=France/L=Paris/O=Private/CN=${NGINX_HOSTNAME}"
```

Then I used a docker-compose.yml

```
version: '2.1'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy:${NGINX_PROXY_TAG}
    container_name: nginx-proxy
    ports:
      - '${NGINX_PROXY_HTTP}:80'
      - '${NGINX_PROXY_HTTPS}:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
    restart: always

  whoami:
    image: jwilder/whoami
    container_name: whoami
    environment:
      - VIRTUAL_HOST=${NGINX_HOSTNAME}

networks:
  default:
    external:
      name: ${NGINX_PROXY_NET}
```

The http works fine: http://${NGINX_HOSTNAME}:${NGINX_PROXY_HTTP}

but not the https version: https://${NGINX_HOSTNAME}:${NGINX_PROXY_HTTPS}

I do not manage to find the cause.

Plus the logs are empty
```
docker-compose logs -f
Attaching to nginx-proxy, whoami

```

Could you please help me on this ?

Thank you
