### ISSUE TITLE
 503 Service Temporarily Unavailable (Tried all the methods but still failed)

### ISSUE THREAD

**Issue by ericwang915** [nginx-proxy/nginx-proxy#1182]
Hi, I am trying to use the nginix-proxy to expose the different containers to use the same port 80 for external connection.

I tried to follow the standard suggestion in https://cloud.google.com/community/tutorials/nginx-reverse-proxy-docker

Step 1:  

```
docker run -d \
    --name nginx-proxy \
    -p 80:80 \
    -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
```

Step 2:

```
docker run -d --name site-a -e VIRTUAL_HOST=a.example.com nginx
```

However, I kept got the error "503 Service Temporarily Unavailable" when accessing "example.com" and 

"This site can’t be reached a.example.com’s server IP address could not be found." when accessing
"a.example.com"

Following 

https://github.com/jwilder/nginx-proxy/issues/582#issuecomment-249425260

I tried to 

```
docker run -d -p 80:80 -e DEFAULT_HOST=a.example.com -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy:latest
```

Still cannot make it.

Following   https://github.com/jwilder/nginx-proxy/issues/749

I tried to use the docker compose

### 

```yaml
version: '2'

services:

  blog:
    image: wordpress 
    container_name: wordpress
    environment:
      - VIRTUAL_HOST=blog.robota.asia
    expose:
      - "80"
    restart: always

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  default:
    external:
      name: nginx-proxy
```

but same error remains, this is really quite frustrating, can anyone help on this?

This is what I see from the logs of the proxy container:

dockergen.1 | 2018/10/24 04:42:01 Received event die for container 66b3131df8e6
dockergen.1 | 2018/10/24 04:42:01 Generated '/etc/nginx/conf.d/default.conf' from 1 containers
dockergen.1 | 2018/10/24 04:42:01 Running 'nginx -s reload'
dockergen.1 | 2018/10/24 04:42:01 Received event stop for container 66b3131df8e6
dockergen.1 | 2018/10/24 04:42:01 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2018/10/24 04:42:09 Received event start for container 83c86489b047
dockergen.1 | 2018/10/24 04:42:09 Generated '/etc/nginx/conf.d/default.conf' from 2 containers
dockergen.1 | 2018/10/24 04:42:09 Running 'nginx -s reload'
dockergen.1 | 2018/10/24 04:42:09 Error running notify command: nginx -s reload, exit status 1
dockergen.1 | 2018/10/24 04:42:09 2018/10/24 04:42:09 [emerg] 33#33: no host in upstream ":80" in /etc/nginx/conf.d/default.conf:59

**Comment by ericwang915** [comment]
Docker version 18.03.1-ce, build 9ee9f40

Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-62-generic x86_64)

**Comment by alexanderadam** [comment]
I'm having the same problem since I updated to a recent image.

@ericwang915 I can recommend you to try an older build for now. `09e51a95c52b` is working for me.

**Comment by ericwang915** [comment]
@alexanderadam Could you share your cmd here?

**Comment by ericwang915** [comment]
@alexanderadam  what do you mean by 09e51a95c52b？ Is this your docker container ID？whats your docker image version？

**Comment by anselal** [comment]
Same issue here.

**Comment by alexanderadam** [comment]
@ericwang915 sure, I just used the [standard command](https://github.com/jwilder/nginx-proxy#usage):

```bash
$ docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
```

And I meant the hash of the image, although probably any older image would do — just try [an older tag](https://hub.docker.com/r/jwilder/nginx-proxy/tags/).

**Comment by jamesstidard** [comment]
I believe I'm experiencing the same problem. I've tried using a earlier image (apline-0.6.0 as opposed to apline-0.7.0) but no success.

I'm using a configuration that is posted as an example, so I assume it had worked at some point.

I've also opened an issue on that repo just in case it's not a nginx-proxy issue. Here's [that issue](https://github.com/nextcloud/docker/issues/565).

**Comment by Ricool06** [comment]
Have a look at `/etc/nginx/conf.d/default.conf` in your jwilder/nginx-proxy container. You might find that the `upstream` blocks are empty. Happening to me too, can't figure out why.

**Comment by MarkPare** [comment]
This happens to me frequently (40% of the time I start it up) while running on my local machine.  After viewing the `/etc/nginx/conf.d/default.conf` when it does happen, looks like nothing is loaded into that file. It just has a single server block:

```
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
```

I haven't noticed any particular pattern as to why it happens sometimes and not others. Any thoughts? Should I try out an older version of image?

**Comment by MarkPare** [comment]
The issue for me was solved by making sure that any containers that specify `VIRTUAL_HOST` are running before the `nginx-proxy` container runs. With docker-compose, this can be achieved by adding to `depends_on` config of the `nginx-proxy` container:

```
my-nginx-proxy:
    image: jwilder/nginx-proxy
    depends_on:
      - my-conainter-that-specifies-virtual-host
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
```

**Comment by kimraz** [comment]
Same issue here. Adding the "depends_on" parameter didn't help.

**Comment by MarkPare** [comment]
Anyone also still getting this? Seems to be related to startup timing.

**Comment by gk017** [comment]
I have this 503 error too. Immediately after the containers are started I see a nginx default page that says nginx is working, 1 second later I get this 503 error. The network I created with `docker network create web`.

This is my docker-compose.yml:
```
version: '2'
services:
  nginxnextcloud:
    container_name: nginxnextcloud
    image: nginx
    restart: always
    expose:
      - 80
    volumes:
      - /srv/container/nginxnextcloud/content:/usr/share/nginx/html # the index.html just contains 'nextcloud'
    networks:
      - web
    environment:
      - VIRTUAL_HOST=nextcloud.myname.ddns.net

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginxproxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - web

networks:
  web:
    external: true
```
When I comment out the nginx-proxy service and add `ports: - "80:80"` to the nginxnextcloud service it is accessible via myname.ddns.net.

Any ideas?

**Comment by gaving** [comment]
I narrowed this issue down to this block in /etc/nginx/conf.d/default.conf (at my end anyway):-

https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L140

```
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
         .....
}
```

Before my other server stuff.

Removing the block allowed things to behave as I'd expect, but I'm at a loss why or how to remove this section without hacking the tmpl file and passing it in.

**Comment by andreafspeziale** [comment]
Hi everyone I think I jumped in the same issue of yours.
I was playing with my NodeJS BE API service in order to scale it up.

**First approach**: using nginx to reverse proxy a specific replica amount of my api service

```
version: "3.8"

x-api-service: &default-api-service
  ...

services:
  3rd-party-services:
    ...

  nginx:
    image: nginx:1.19.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    links:
      - api-service-1
      - api-service-2
      - api-service-3
      - api-service-4

  api-service-1:
    <<: *default-api-service

  api-service-2:
    <<: *default-api-service

  api-service-3:
    <<: *default-api-service

  api-service-4:
    <<: *default-api-service

volumes:
  ...

```

nginx.conf

```
worker_processes 1;

events {
    worker_connections 1024;
}

http {
    upstream localhost {
        server api-service-1:3000;
        server api-service-2:3000;
        server api-service-3:3000;
        server api-service-4:3000;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://localhost;
            proxy_set_header Host $host;
        }
    }
}
```

It works as expected, all my endpoints are hit as expected as well as the round-robin balancing. I'm able to see api requests logged on each api-service container.

(**Second approach**) Then I found out `jwilder/nginx-proxy` and I've thought to use it in combination with `docker-compose up scale api-service=N` and avoid the api-service duplication in the `docker-compose` itself.

```
version: "3.8"

services:
  3rd-party-services:
    ...

  proxy:
    image: jwilder/nginx-proxy:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 8080:80
    environment:
      HTTPS_METHOD: nohttps
    links:
      - api-service

  api-service:
    ...
    environment:
      VIRTUAL_HOST: api-service.local
    
volumes:
  ...

```

Running it in plain, so with no `docker-compose scale` option, the containers are created as expected and the generated configuration seems to be correct

```
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Apply fix for very long server names
server_names_hash_bucket_size 128;
# Default dhparam
ssl_dhparam /etc/nginx/dhparam/dhparam.pem;
# Set appropriate X-Forwarded-Ssl header
map $scheme $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
		ssl_prefer_server_ciphers off;
resolver 127.0.0.11;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
# api-service.local
upstream api-service.local {
				## Can be connected with "scale_default" network
			# scale_api-service_1
			server 172.29.0.6:3000;
}
server {
	server_name api-service.local;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://api-service.local;
	}
}
```

But if I try to hit my endpoints, even with postman with something like `http://localhost:8080/v1/healthz` I got back

```
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx/1.17.6</center>
</body>
</html>
```

and the `proxy` container logs say

```
docker container logs -f scale_proxy_1                                 (andrea.speziale/italian-accountswitch)
WARNING: /etc/nginx/dhparam/dhparam.pem was not found. A pre-generated dhparam.pem will be used for now while a new one
is being generated in the background.  Once the new dhparam.pem is in place, nginx will be reloaded.
forego     | starting dockergen.1 on port 5000
forego     | starting nginx.1 on port 5100
dockergen.1 | 2020/07/29 21:19:15 Generated '/etc/nginx/conf.d/default.conf' from 6 containers
dockergen.1 | 2020/07/29 21:19:16 Running 'nginx -s reload'
dockergen.1 | 2020/07/29 21:19:16 Watching docker events
dockergen.1 | 2020/07/29 21:19:16 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2020/07/29 21:19:19 Received event die for container 7a52e1b6f011
dockergen.1 | 2020/07/29 21:19:19 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
2020/07/29 21:19:50 [notice] 50#50: signal process started
Generating DH parameters, 2048 bit long safe prime, generator 2
This is going to take a long time
dhparam generation complete, reloading nginx




nginx.1    | localhost 172.29.0.1 - - [29/Jul/2020:21:23:49 +0000] "GET /v1/healthz HTTP/1.1" 503 197 "-" "PostmanRuntime/7.25.0"
```

Hope all this details can help to find a solution or where I'm doing wrong.

Thanks!
