### ISSUE TITLE
Generating an incomplete default.conf

### ISSUE THREAD

**Issue by MichaelJCole** [nginx-proxy/nginx-proxy#1239]
Hello, nginx-proxy seems to be generating an incomplete default.conf.  Similar to #772

The code snippets are long, and below is the docker compose file and the generated default.conf.

The issues are with `stage-sync`:

1) `http://stage-sync.myapp.io/`  shows the `stage-sync`, but `HTTPS_METHOD=redirect` should redirect to https.  This isn't generated in the default.conf below.
2) `https://stage-sync.myapp.io` proxies the `stage-core` app.  Maybe because of `DEFAULT_HOST=stage.evanx.io`?

Here is the generated `/etc/nginx/conf.d/default.conf`.  

It get's interesting around "upstream stage-sync.myApp.io".  Notice how the "server {}" directives are different for that and "upstream stage.myApp.io"

```
docker ps
# find id
docker exec -i -t 29193f415dbc /bin/bash

root@29193f415dbc:/etc/nginx# cat conf.d/default.conf 
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Apply fix for very long server names
server_names_hash_bucket_size 128;
# Default dhparam
ssl_dhparam /etc/nginx/dhparam/dhparam.pem;
# Set appropriate X-Forwarded-Ssl header
map $scheme $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
resolver 127.0.0.11;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
# stage-sync.myApp.io
upstream stage-sync.myApp.io {
				## Can be connected with "stage_default" network
			# stage-sync
			server 172.24.0.7:80;
}
server {
	server_name stage-sync.myApp.io;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://stage-sync.myApp.io;
	}
}
# stage.myApp.io
upstream stage.myApp.io {
				## Can be connected with "stage_default" network
			# stage-core
			server 172.24.0.8:80;
}
server {
	server_name stage.myApp.io;
	listen 80 default_server;
	access_log /var/log/nginx/access.log vhost;
	return 301 https://$host$request_uri;
}
server {
	server_name stage.myApp.io;
	listen 443 ssl http2 default_server;
	access_log /var/log/nginx/access.log vhost;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
	ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:!DSS';
	ssl_prefer_server_ciphers on;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/stage.myApp.io.crt;
	ssl_certificate_key /etc/nginx/certs/stage.myApp.io.key;
	location / {
		proxy_pass http://stage.myApp.io;
	}
}
```

It's not clear to me why the config is different.  letsencrypt is commented out because the containers are run behind a firewall.  Here is the docker-compose file:

```
version: '3'
services:

  stage-nginx:
    container_name: stage-nginx
    restart: always
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/myApp/stage/certs:/etc/nginx/certs
      - /opt/myApp/stage/vhost.d:/etc/nginx/vhost.d
      - /opt/myApp/stage/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    environment:
      - DEFAULT_HOST=stage.myApp.io
    restart: always

  # Automatically manages HTTPS certs in nginx-proxy

  # stage-letsencrypt:
  #   container_name: stage-letsencrypt
  #   restart: always
  #   image: jrcs/letsencrypt-nginx-proxy-companion
  #   depends_on:
  #     - stage-nginx
  #   volumes:
  #     - /opt/myApp/stage/certs:/etc/nginx/certs
  #     - /opt/myApp/stage/vhost.d:/etc/nginx/vhost.d
  #     - /opt/myApp/stage/html:/usr/share/nginx/html
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     # AND
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   environment:

  # Send Logs to Papertrail

  stage-logspout:
    container_name: stage-logspout
    image: gliderlabs/logspout:latest
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      syslog+tls://logs7.papertrailapp.com:33333
    restart: always

  # Our applications

  stage-core:
    container_name: stage-core
    image: myAppio/core:$VERSION_MYAPP_CORE
    ports:
      - 80
    depends_on:
      - stage-mongo-configure-replicaset
    environment:
      - NODE_ENV=production
      - PORT=80
      - ROOT_URL=https://stage.myApp.io
      - MONGO_URL=mongodb://stage-mongo1:27017,stage-mongo2:27017,stage-mongo3:27017/meteor?replicaSet=rs0
      - MONGO_OPLOPG_URL=mongodb://stage-mongo1:27017,stage-mongo2:27017,stage-mongo3:27017/meteor?replicaSet=rs0
      - VIRTUAL_HOST=stage.myApp.io
      - HTTPS_METHOD=redirect
      - LETSENCRYPT_HOST=stage.myApp.io
      - LETSENCRYPT_EMAIL=letsencrypt@myApp.io
    restart: always

  stage-sync:
    container_name: stage-sync
    image: myAppio/sync:$VERSION_MYAPP_SYNC
    ports:
      - 80
    depends_on:
      - stage-mongo-configure-replicaset
    environment:
      - NODE_ENV=production
      - PORT=80
      - MONGO_URL=mongodb://stage-mongo1:27017,stage-mongo2:27017,stage-mongo3:27017/meteor?replicaSet=rs0
      - MSSQL_URL=mssql://xxx:xxx@stage-xxx.myApp.io:1433/xxx
      - VIRTUAL_HOST=stage-sync.myApp.io
      - HTTPS_METHOD=redirect
      - LETSENCRYPT_HOST=stage-sync.myApp.io
      - LETSENCRYPT_EMAIL=letsencrypt@myApp.io
    restart: always

   # mongo replica set
```
