### ISSUE TITLE
Reverse proxy to another machine

### ISSUE THREAD

**Issue by comassky** [nginx-proxy/nginx-proxy#1245]
Hi all,

I have 2 servers, A and B, in the smae local network, nginx-proxy works well on B.

But i have one service (Pihole) on A that i wish to reverse proxy with B.

So A (Pihole, exposed on 80:80) and B (nginx-proxy and many containers, B is my network entry).

How can i redirect pihole.exemple.com to the A:80 server ?

Something like this 👍 

```
server {
        # Redirection vers HTTPS
        # Ici, je spécifie que toute requête vers le port 80 (HTTP) sera renvoyée vers le même hôte, en HTTPS.
        listen 80;
        return 301 https://$host$request_uri;
}

server {
        # Service 1
        listen 443;
        # J'active SSL
        ssl on;

        server_name service1.chezmoi.exemple.fr; # Ici, c'est le nom de domaine qui sera appelé dans le navigateur
        location / { # pour le dossier racine (/), on active le mode proxy vers l'adresse spécifiée, sur le port spécifié
                proxy_pass http://premieremachine:1081/;
        }
}

server {
        # Service 2
        listen 443;
        ssl on;

        # On peut spécifier 2 noms de domaine différents qui auront le même comportement
        server_name service2.chezmoi.exemple.fr;
        server_name chezmoi.exemple.fr;
        location / {
                proxy_pass https://secondemachine:443/;
        }
}
```

Thanks ! :)

**Comment by kaipaysen** [comment]
One option would be to create a proxy service on B like this:

docker-compose.yml
```
scm-proxy:
    container_name: nas-scm-proxy
    build: 
      context: ./scm-proxy
    restart: always
    mem_limit: 64m
    environment:
      VIRTUAL_HOST: <VIRTUAL_HOST>
      LETSENCRYPT_HOST: <LETSENCRYPT_HOST>
      LETSENCRYPT_EMAIL: <LETSENCRYPT_EMAIL>
    expose:
      - 80    
```
scm-proxy/Dockerfile
```
FROM nginx:1.15-alpine
COPY nginx.conf /etc/nginx/nginx.conf
```
scm-proxy/nginx.conf
```
worker_processes 1;

events {
  worker_connections 1024;
}

http {
    
    sendfile on;
    client_max_body_size 0;
    chunked_transfer_encoding on;

    server {
        listen 80;
        location / {
            proxy_pass        http://A:80;
            proxy_redirect    off;
            proxy_set_header  Host              $http_host;   # required for docker client's sake
            proxy_set_header  X-Real-IP         $remote_addr; # pass on real client's IP
            proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header  X-Forwarded-Host $http_host;
            proxy_set_header  X-Forwarded-Proto $scheme;
        }
    }
}
```
