### ISSUE TITLE
Support for multiple certificate names in CERT_NAME

### ISSUE THREAD

**Issue by applusplus** [nginx-proxy/nginx-proxy#1273]
It would be nice, if we could set multiple certificate names in CERT_NAME, like we doing it with VIRTUAL_HOST, separated by comma.

I have following case:
We use two different domains for the same application and we got one wildcard certificate per domain.
**Exmaple:**
Domain 1: foo.bar.com
Domain 2: foo.bar.net
Certificate 1: wildcard.bar.com.crt
Certificate 2: wildcard.bar.net.crt

In our docker-compose.yml I would like to use it this way:
```
version: '3.7'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/ssl/certs:/etc/nginx/certs
    network_mode: bridge

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      VIRTUAL_HOST: grafana.bar.com,grafana.bar.net
      CERT_NAME: wildcard.bar.com,wildcard.bar.net
    ports:
     - 3000:3000
    network_mode: bridge
```

We have a lot of different applications with different docker-compose files, this is the reason why I don't want to copy & paste or create symlinks for each new domain we got.
