### ISSUE TITLE
Remove colour codes from syslog messages

### ISSUE THREAD

**Issue by vik-y** [nginx-proxy/nginx-proxy#1281]
What am I trying to achieve
* Use syslog logging driver while running the container
* Send logs to logstash and then elasticsearch 

Problems faced: 
Forego uses colors in its logs so the final logs look somewhat like  this: 
```
<30>May 28 19:35:54 ssdnodes-93039 b33af29363a8[27451]: [0;33;1mnginx.1    | #033[0mexample.com 172.93.55.140 - - [28/May/2019:14:05:54 +0000] "GET /sdf HTTP/1.1" 301 185 "-" "curl/7.47.0"
```

Notice the `#033[0m` -> This looks like some sort of colour code - which after debugging I believe is added by forego. 

Is there anyway to prevent this? 

I see that a few users made some attempts here in Issue #503 but is there a cleaner solution available?

**Comment by tekaeren** [comment]
The color codes are inserted by the container watchdog forego with no option to disable it. 
That project is not actively maintained, and did not accept two pull request to fix that problem in the past.

No simple (without changing the watchdog tool in the nginx-proxy container or attaching external extrenal cleanup scripts to log pipeline) fix is available afaik.

**Comment by harobed** [comment]
@tekaeren you can use this docker image : https://hub.docker.com/r/binfalse/nginx-proxy/

from https://github.com/binfalse/nginx-proxy with [patched](https://github.com/binfalse/forego/commit/340b0531004c6ee45ab2c7061af27cb6deeed70a) `forego`.

**Comment by jonathanhacker** [comment]
I was facing the same issue when using filebeat to collect the logs from nginx-proxy for elasticsearch. I could solve it with some filebeat config:
```yaml
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
processors:
  - script:
      lang: javascript
      source: >
        function process(event) {
            var message = event.Get("message");
            if (message !== null) {
              // https://github.com/chalk/ansi-regex/blob/main/index.js#L3
              message = message.replace(/[\u001b\u009b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]/g, '');
              event.Put("message", message);
            }
        }
```
And then label nginx-proxy in the docker-compose.yml to tell filebeat it's an nginx service:
```yaml
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ...
    labels:
      co.elastic.logs/module: nginx
      co.elastic.logs/fileset.stdout: access
      co.elastic.logs/fileset.stderr: error
```
A `NO_COLOR` option as in https://github.com/ddollar/forego/pull/124 would be preferable, but this solves the problem for a filebeat setup.
