### ISSUE TITLE
Trying to proxy to another nginx docker seems to be doomed to failure

### ISSUE THREAD

**Issue by Z-a-r-a-k-i** [nginx-proxy/nginx-proxy#1351]
docker-compose.yml
```
version: '3.7'

services:
  nginx-proxy:
    restart: unless-stopped
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - service-proxy
  
  homepage:
    image: gatsbyjs/gatsby
    environment:
      - VIRTUAL_HOST=home.local
    depends_on:
      - nginx-proxy
    networks:
      - service-proxy

  forum:
    build: forum
    volumes:
      - ./forum/www:/usr/share/nginx/html/
      - ./forum/forum.conf:/etc/nginx/conf.d/forum.conf
    environment:
      - VIRTUAL_HOST=forum.local
    links:
      - php
    depends_on:
      - nginx-proxy
    networks:
      - service-proxy

  php:
    image: php:7-fpm
    volumes:
      - ./forum/www:/usr/share/nginx/html/
    expose:
      - 9000
    networks:
      - service-proxy

  mysql:
    build: mysql
    environment:
      - NETWORK_ACCESS=internal
    expose:
      - 3306
    networks:
      - service-proxy

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local
    depends_on:
      - nginx-proxy
    networks:
      - service-proxy

networks:
  service-proxy:
    external: true
```

forum.conf
```
server {
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

  # php-fpm configuration
  location ~ .php$ {
      root /usr/share/nginx/html/;
      try_files $uri =404;
      fastcgi_pass   php:9000;
      fastcgi_index  index.php;
      fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
      include        fastcgi_params;
      fastcgi_buffer_size 128k;
      fastcgi_buffers 256 4k;
      fastcgi_busy_buffers_size 256k;
      fastcgi_temp_file_write_size 256k;
  }

}
```

When I try to access http://forum.local/index.php the file is downloaded.
