### ISSUE TITLE
Avoid reboot when a docker container is launched / stopped

### ISSUE THREAD

**Issue by PapsOu** [nginx-proxy/nginx-proxy#1354]
I'm using the 3 containers in this docker-compose : 
```yaml
version: '3'

services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        restart: always
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - conf:/etc/nginx/conf.d
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - certs:/etc/nginx/certs:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
        network_mode: bridge

    docker-gen:
        image: jwilder/docker-gen
        container_name: nginx-gen
        command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        volumes:
            - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
            - conf:/etc/nginx/conf.d
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - certs:/etc/nginx/certs:rw
            - /var/run/docker.sock:/tmp/docker.sock:ro
        environment:
            - "NGINX_PROXY_CONTAINER=nginx"
        network_mode: bridge

    nginx-proxy-companion:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: nginx-companion
        volumes:
            - conf:/etc/nginx/conf.d
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - certs:/etc/nginx/certs:rw
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            - "DEFAULT_EMAIL=<email>"
            - "NGINX_PROXY_CONTAINER=nginx"
        network_mode: bridge

volumes:
    conf:
    certs:
    html:
    vhost:
        driver: local
        driver_opts:
            type: none
            device: $PWD/nginx/vhost.d
            o: bind
```

When a `docker-compose up` is executed by jenkins (or by any regular user), the nginx proxy container restarts. But, the restart time is visible when following a build in Jenkins build console.

Each time a `docker-compose up` or `docker-compose down` is executed, the console display freeze (because of nginx restart).

Is it possible to avoid a reboot of the nginx container to discover new containers ? Or is there any way to ignore some new containers (e.g. containers without env var `VIRTUAL_HOST`) ?

More informations : Jenkins get a `ERR_CONNECTION_CLOSED` when the nginx restarts.
