### ISSUE TITLE
Expose multiple ports cause error 502

### ISSUE THREAD

**Issue by stephane-r** [nginx-proxy/nginx-proxy#1372]
Hello community,

I try to setup new Docker app using your very nice nginx-proxy. For only 1 services, my proxy work good. But i would like proxy 2 services (or 2 ports). After add new port, all proxy return error 502 with this log :

`nginx.1 | 2019/12/19 06:33:41 [error] 2227#2227: *151845 no live upstreams while connecting to upstream, client: xx.xxx.xxx.xx, server: myapp.mydomain.com, request: "GET /favicon.ico HTTP/2.0", upstream: "http://myapp.mydomain.com/favicon.ico", host: "myapp.mydomain.com", referrer: "https://myapp.mydomain.com/"`

You can see my docker-compose file : 

```
version: '3.4'

x-common-variables: &common-variables #NODE_ENV: production
  LOCAL_USER_ID: $USER_ID
  LOCAL_GROUP_ID: $GROUP_ID
  PGID: 1000
  PUID: 1000
  TZ: Europe/London
  LETSENCRYPT_EMAIL: ${MAILER_DEFAUT_SENDER_ADDRESS}

services:
  app:
    build: ./config/docker
    container_name: app
    environment:
      <<: *common-variables
      VIRTUAL_HOST: app.${SITE_URL}
      VIRTUAL_PORT: 3339
      LETSENCRYPT_HOST: app.${SITE_URL}
    ports:
      - 3339:3000
    command: yarn web:dev
    volumes:
      - .:/app

  api:
    build: ./config/docker
    container_name: api
    environment:
      <<: *common-variables
      VIRTUAL_HOST: api.${SITE_URL}
      VIRTUAL_PORT: 3340
      LETSENCRYPT_HOST: api.${SITE_URL}
    ports:
      - 3340:1337
    command: yarn api:dev
    volumes:
      - .:/app

networks:
  default:
    external:
      name: nginx-proxy
```

I see multiple ports is supported from docs. Maybe i've wrong configuration ? If i use only 1 services, proxy work good !

Anyone have already use multiple ports ?

Thank you community :)

**Comment by samip5** [comment]
Basically the same error as you, the sonarr one works, but deluge one does not?

It's unable to find it's correct port, and the resutling config has no port attached to it, which is why it fails. Sonarr has upstream server correctly set.

You can see the config by executing:  `docker exec proxy_container_name cat /etc/nginx/conf.d/default.conf`.

```
version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
     - 27000:80
    networks:
     - backend
     - default
    restart: always
    privileged: true
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    hostname: sonarr
    depends_on:
      - deluge
      - jackett
    volumes:
      - /opt/docker/appdata/sonarr:/config
      - /opt/docker/scripts:/scripts
    ports:
      - 27021:8989
    expose:
      - 8989
    networks:
      - backend
      - default
    dns:
      - 192.168.2.1
      - 1.1.1.1
    restart: always
    environment:
      - PUID=112
      - PGID=100
      - TZ=Europe/Helsinki
      - VIRTUAL_HOST=sonarr.plex-server.local
      - VIRTUAL_PORT=8989
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    hostname: deluge
    networks:
     - vlan
     - backend
    volumes:
     - /opt/docker/appdata/deluge/config/:/config
     - /etc/localtime:/etc/localtime:ro
    ports:
     - 27025:8112
     - 7002:7002
     - 7002:7002/udp
    expose:
     - 8112
    dns:
      - 1.1.1.1
    environment:
      - PUID=112
      - GUID=100
      - TZ=Europe/Helsinki
      - VIRTUAL_HOST=deluge.plex-server.local
      - VIRTUAL_PORT=8112

networks:
  default:
     external:
        name: backend
  vlan:
     external:
        name: vlan20
  backend:
     external:
        name: my_isolated_net
```
