### ISSUE TITLE
Doesn't work in swarm mode

### ISSUE THREAD

**Issue by LuisEnMarroquin** [nginx-proxy/nginx-proxy#1374]
I have the following files:

* .env
```env
DOMAIN=localhost.com
```

* docker-whoami.yml
```yml
version: '3.7'

networks:
  default:
    name: nginx-proxy

volumes:
  certs:
  dhpar:
  vhost:
  htmls:

services:
  nginx:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - dhpar:/etc/nginx/dhparam
      - vhost:/etc/nginx/vhost.d
      - htmls:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
  whoami:
    environment:
      VIRTUAL_HOST: whoami.${DOMAIN}
    image: jwilder/whoami
    ports:
      - 8000
```

When I run this in compose mode it works

```shell
docker-compose --project-name whoami -f docker-whoami.yml up -d --force-recreate --remove-orphans
```

![image](https://user-images.githubusercontent.com/35376824/71367379-810b8b80-256a-11ea-9dc1-63d4cae3c3ee.png)

But in swarm mode it just says 503

```shell
docker stack deploy -c docker-whoami.yml nginx
```

![image](https://user-images.githubusercontent.com/35376824/71367412-97b1e280-256a-11ea-8e81-33b2307a389e.png)
