### ISSUE TITLE
no live upstreams while connecting to upstream

### ISSUE THREAD

**Issue by CrestApps** [nginx-proxy/nginx-proxy#1381]
I am trying to run an image using the nginx-proxy image. I created the following `docker-compose.yml` file to make executing the commands easier

```
version: '3.4'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/certificates:/etc/nginx/certs

  private_package_name:
    image: crestapps/private_package_name:latest
    container_name: private_package_name
    command: tail -f /dev/null
    environment:
      - VIRTUAL_HOST=private_package_name.crestapps.com
      - VIRTUAL_PORT=51736
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 51736:80
      - 44344:443
    volumes:
      - /app/storage:/storage
```

When I run `docker-compose up`, both apps run as expected. However, when I make a request to `https://private_package_name.crestapps.com` I get 
 > 502 Bad Gateway

When I look at the logs I see the following

```
nginx-proxy          | nginx.1    | 2020/01/20 23:49:40 [error] 42#42: *1 no live upstreams while connecting to upstream, client: PersonalIpAddress, server: private_package_name.crestapps.com, request: "GET / HTTP/2.0", upstream: "http://private_package_name.crestapps.com/", host: "private_package_name.crestapps.com"
nginx-proxy          | nginx.1    | private_package_name.crestapps.com PersonalIpAddress - - [20/Jan/2020:23:49:40 +0000] "GET / HTTP/2.0" 502 157 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
nginx-proxy          | nginx.1    | 2020/01/20 23:49:41 [error] 42#42: *1 no live upstreams while connecting to upstream, client: PersonalIpAddress, server: private_package_name.crestapps.com, request: "GET /favicon.ico HTTP/2.0", upstream: "http://private_package_name.crestapps.com/favicon.ico", host: "private_package_name.crestapps.com"
nginx-proxy          | nginx.1    | private_package_name.crestapps.com PersonalIpAddress - - [20/Jan/2020:23:49:41 +0000] "GET /favicon.ico HTTP/2.0" 502 157 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
```

When I execute `docker ps` I get the following

```
CONTAINER ID        IMAGE                                COMMAND                  CREATED              STATUS              PORTS                                           NAMES
d661d4bff1f3        crestapps/private_package_name:latest   "tail -f /dev/null"      9 seconds ago        Up 6 seconds        0.0.0.0:51736->80/tcp, 0.0.0.0:44344->443/tcp   private_package_name
0bd0da4141f8        jwilder/nginx-proxy                  "/app/docker-entrypo…"   About a minute ago   Up About a minute   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp        nginx-proxy
```

running `docker logs nginx-proxy` gives me the following
```
WARNING: /etc/nginx/dhparam/dhparam.pem was not found. A pre-generated dhparam.pem will be used for now while a new one
is being generated in the background.  Once the new dhparam.pem is in place, nginx will be reloaded.
forego     | starting dockergen.1 on port 5000
forego     | starting nginx.1 on port 5100
dockergen.1 | 2020/01/21 00:00:51 Generated '/etc/nginx/conf.d/default.conf' from 2 containers
dockergen.1 | 2020/01/21 00:00:51 Watching docker events
dockergen.1 | 2020/01/21 00:00:51 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
2020/01/21 00:01:08 [notice] 53#53: signal process started
Generating DH parameters, 2048 bit long safe prime, generator 2
This is going to take a long time
dhparam generation complete, reloading nginx
dockergen.1 | 2020/01/21 00:02:27 Received event die for container 274d6e739fd8
dockergen.1 | 2020/01/21 00:02:29 Received event stop for container 274d6e739fd8
dockergen.1 | 2020/01/21 00:02:29 Generated '/etc/nginx/conf.d/default.conf' from 1 containers
dockergen.1 | 2020/01/21 00:02:30 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2020/01/21 00:02:33 Received event start for container d661d4bff1f3
dockergen.1 | 2020/01/21 00:02:33 Generated '/etc/nginx/conf.d/default.conf' from 2 containers
dockergen.1 | 2020/01/21 00:02:33 Running 'nginx -s reload'

```

running `docker logs private_package_name` gives me nothing.

Is there something I am doing wrong here or is this some sort of a bug? Help would me much appreciated.

**Comment by CrestApps** [comment]
I also tried to make a change and use only HTTP to reduce the complexity so I change my `docer-compose.yml` file to the following

```
version: '3.4'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  private_package_name:
    image: crestapps/private_package_name:latest
    container_name: private_package_name
    command: tail -f /dev/null
    environment:
      - VIRTUAL_HOST=private_package_name.crestapps.com
      - VIRTUAL_PORT=51736
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 51736:80
    volumes:
      - /app/storage:/storage
```

That gives me the following error

 >  [error] 73#73: *9 connect() failed (111: Connection refused) while connecting to upstream

while browsing to `http://private_package_name.crestapps.com` gives ne a `502 Bad Gateway`
