### ISSUE TITLE
nginx-proxy not forwarding to ghost blog

### ISSUE THREAD

**Issue by Danieo6** [nginx-proxy/nginx-proxy#1408]
Hi!
I have a little problem with running my ghost blog on Docker with nginx-proxy. I want to host multiple websites on my VPS so I thought that I can use docker and nginx-proxy to handle this. The issue is that I cant make ghost working with nginx-proxy. I followed many tutorials and tried many ways, and nothing is working but when I try to run my static website with nginx-proxy on docker everything is doing fine, only Ghost is refusing to cooperate.

Heres my current docker-compose:
```
version: '3'

services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  makerplace:
    image: ghost
    container_name: makerplace
    expose:
      - 2368
    environment:
      - url="http://makerplace.pl"
      - VIRTUAL_HOST=makerplace.pl
      - VIRTUAL_PORT=2368
networks:
  default:
    external:
      name: nginx-proxy
```
