### ISSUE TITLE
Proxy to different containers based on a cookie

### ISSUE THREAD

**Issue by Zorinik** [nginx-proxy/nginx-proxy#1422]
Good morning,

I don't know if there is already a feature like this; I have two containers that are accessible with the same virtual host; something like this:

```yaml
container1:
  image: blabla
  environment:
    - VIRTUAL_HOST=test.com
container2:
  image: blabla
  environment:
    - VIRTUAL_HOST=test.com
```

Now, I would like to redirect to the second one ONLY if a particular cookie is set to a particular value, otherwise it should pick the first one.

I tried to run nginx-proxy as two separate containers and edit the template myself but, well, I don't know Go....
How could I achieve this?
