### ISSUE TITLE
Uploaded files permissions

### ISSUE THREAD

**Issue by MIRAMAXED** [nginx-proxy/nginx-proxy#1423]
Hi! Can somebody explain me why files with size more than 5Mb after upload have different permissions from files that have less 5Mb. And how to fix it? As result, when I try to read large file I have the "403 Forbidden" error. Help me please!
```
-rw------- 1 root     root     5245437   Apr 17 16:26 08e322a16c.png  <---- X
-rw-r--r-- 1 root     root     68792     Apr 17 16:42 d773be5142.jpeg
```
![error](https://user-images.githubusercontent.com/5852641/79596362-21bd2280-80e9-11ea-86e7-d8340e1e686b.png)

docker-compose.proxy.yml:
```
version: "3"
#   ____  ____   _____  ____   __
#  |  _ \|  _ \ / _ \ \/ /\ \ / /
#  | |_) | |_) | | | \  /  \ V /
#  |  __/|  _ <| |_| /  \   | |
#  |_|   |_| \_\\___/_/\_\  |_|
#
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: "proxy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - ./nginx/max_size.conf:/etc/nginx/conf.d/max_size.conf:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    environment:
      NGINX_PROXY_CONTAINER: proxy
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/max_size.conf:/etc/nginx/conf.d/max_size.conf:ro
volumes:
  conf: {}
  vhost: {}
  html: {}
  dhparam: {}
  certs: {}
```
docker-compose.dev.yml:
```
version: "3"
#   ____  _______     __
#  |  _ \| ____\ \   / /
#  | | | |  _|  \ \ / /
#  | |_| | |___  \ V /
#  |____/|_____|  \_/
#
services:
  # ...................... some services before ....................
  #   _   _  ____ ___ _   ___  __
  #  | \ | |/ ___|_ _| \ | \ \/ /
  #  |  \| | |  _ | ||  \| |\  /
  #  | |\  | |_| || || |\  |/  \
  #  |_| \_|\____|___|_| \_/_/\_\
  #
  nginx-dev:
    container_name: nginx_dev
    build:
      context: .
      dockerfile: nginx/Dockerfile
    environment:
      VIRTUAL_HOST: sitename-example.com
      LETSENCRYPT_HOST: sitename-example.com
      LETSENCRYPT_EMAIL: myemail@gmail.com
    volumes:
      - static_dev:/static_dev
      - media_dev:/media_dev
      - react_build_dev:/frontend_dev/build
    depends_on:
      - backend-dev
volumes:
  react_build_dev: {}
  media_dev: {}
  static_dev: {}
  redis_dev: {}
  pgdata: {}
```
