### ISSUE TITLE
nginx-proxy with jrcs/letsencrypt-nginx-proxy-companion and portainer?

### ISSUE THREAD

**Issue by AlphaComposite** [nginx-proxy/nginx-proxy#1428]
Have any of you gotten this trio to work together? 

I've gotten nginx-proxy and portainer to work together, but not all three. To get nginx-proxy and portainer working together, in addition to the compose file below, you have to add a file (named in this convention: host.tld) to the nginx-proxy directory /etc/nginx/vhost.d/ as mentioned here: https://github.com/portainer/portainer-compose/tree/master/nginx-proxy

Those two work together in the above mentioned capacity, but as soon as I add jrcs/letsencrypt-nginx-proxy-companion helper to the mix nothing works. There's another conversation here but it's a bit beyond my current Docker skills (only two weeks in.): https://github.com/nginx-proxy/nginx-proxy/issues/705

```
version: "2"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    networks:
      - proxy
    ports:
      - "8989:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/volumes/nginx/vhost.d:/etc/nginx/vhost.d:ro"

  portainer:
    image: portainer/portainer
    restart: always
    environment:
      - VIRTUAL_HOST=portainer.domain.me
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

networks:
  proxy:

volumes:
  portainer_data:
```
