### ISSUE TITLE
Curl Container A to Container B using virtual_host

### ISSUE THREAD

**Issue by dmarcos89** [nginx-proxy/nginx-proxy#1434]
Hi, 

I currently use docker-compose for a php+nginx project, im serving an api and a frontend and it all works fine.

My config looks something like this using virtual hosts:
```
services:
  nginx:
    container_name: nginx
    network_mode: "bridge"
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    links:
      - php
    external_links:
      - proxy
    environment:
      - VIRTUAL_HOST=test.local,api.test.local,backend.test.local
      - HTTPS_METHOD=noredirect

php:
    container_name: php
    network_mode: "bridge"
    build:
      context: ./docker/php
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www/html
    links:
      - mysql:db-host
    env_file:
      - ".env"
```

I am trying to run some phpunit tests agains the api, running it inside the container... but, how can a make a request to the API? 

I am not being able to CURL from inside the php, all i get is `Failing to connect to port 80, connection refused`. Any help or guidance will be kindly appreciated..

Thanks
