### ISSUE TITLE
Fix Swarm mode's load balancer not used by nginx-proxy.

### ISSUE THREAD

**Issue by francoiscolas** [nginx-proxy/nginx-proxy#1436]
When using Swarm Mode the load balancer is not used.
You can reproduce by having a stack with nginx-proxy and a stack for replicated whoami service.
```yaml
# proxy.yml
version: '3.8'

networks:
  proxy:
    driver: overlay
    name: proxy

services:
  nginx:
    image: jwilder/nginx-proxy:latest
    networks:
      - proxy
    environment:
      - HTTPS_METHOD=noredirect
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # - ${CLU_ROOT}/proxy/certs:/etc/nginx/certs:ro
    ports:
      - 80:80
      # - 443:443
    deploy:
      placement:
        constraints:
          - node.role == manager
```
```yaml
# whoami.yml
version: '3.8'

networks:
  proxy:
    external: true

services:
  whoami:
    image: jwilder/whoami:latest
    networks:
      - proxy
    environment:
      - VIRTUAL_HOST=whoami.dev.interne.eseo.fr
    deploy:
      replicas: 3
```

The generated `default.conf` file contains the following settings. nginx-proxy use only one container instead of `server whoami_whoami:8000` to use the Swarm mode load balancer.
```
upstream whoami.dev.interne.eseo.fr {
				# Cannot connect to network of this container
				server 127.0.0.1 down;
				# Cannot connect to network of this container
				server 127.0.0.1 down;
				# Cannot connect to network of this container
				server 127.0.0.1 down;
				## Can be connected with "proxy" network
			# whoami_whoami.2.in0w2m0e4v3j71d1yj6i1nbkh
			server 10.0.2.30:8000;
}
```

To fix it:
  **1. Update the stack file to mount a custom nginx.tmpl:**
```yaml
# proxy.yml

...

services:
  nginx:
    image: jwilder/nginx-proxy:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/app/nginx.tmpl:ro  # <=== Add this line to your service.
    ...
```
  **2. Update the "define upstream" section in the nginx.tmpl file.**
```yaml
{{ define "upstream" }}
  server {{ index .Container.Labels "com.docker.swarm.service.name" }}:{{ .Address.Port }};
#   {{ if .Address }}
#       {{/* If we got the containers from swarm and this container's port is published to host, use host IP:PORT */}}
#       {{ if and .Container.Node.ID .Address.HostPort }}
#           # {{ .Container.Node.Name }}/{{ .Container.Name }}
#           server {{ .Container.Node.Address.IP }}:{{ .Address.HostPort }};
#       {{/* If there is no swarm node or the port is not published on host, use container's IP:PORT */}}
#       {{ else if .Network }}
#           # {{ .Container.Name }}
#           server {{ .Network.IP }}:{{ .Address.Port }};
#       {{ end }}
#   {{ else if .Network }}
#       # {{ .Container.Name }}
#       {{ if .Network.IP }}
#           #server {{ .Network.IP }} down;
#       {{ else }}
#           server 127.0.0.1 down;
#       {{ end }}
#   {{ end }}
{{ end }}
```
