### ISSUE TITLE
Access a site with another domain

### ISSUE THREAD

**Issue by Coosos** [nginx-proxy/nginx-proxy#1439]
Hi,

I'm not sure how to explain the problem, but I can access one of the sites with a different domain.

Example

```
- First website : default.local (no use https)
- Second website : test.local (access with https)

curl -k https://default.local --> Get test.local
curl -k http://default.local --> Get default.local
curl -k https://test.local --> Get test.local
curl -k http://test.local --> Get test.local (301)
```

I looked at the generated nginx file, and it contains the correct ip

```
# Run in docker
curl 192.168.176.4 --> get content from default.local
curl 192.168.176.3 --> get content from test.local
```

But if I run a curl with domains in the docker, we find the scenario mentioned above.

Nginx config :

```
proxy_set_header Proxy "";
server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        return 503;
}
# default.local
upstream default.local {
                                # Cannot connect to network of this container
                                server 127.0.0.1 down;
                                ## Can be connected with "nginx-proxy" network
                        # default_nginx
                        server 192.168.176.4:80;
}
server {
        server_name default.local;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://default.local;
        }
}
# test.local
upstream test.local {
                                ## Can be connected with "nginx-proxy" network
                        # test_nginx
                        server 192.168.176.3:80;
                                # Cannot connect to network of this container
                                server 127.0.0.1 down;
}
server {
        server_name test.local;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        # Do not HTTPS redirect Let'sEncrypt ACME challenge
        location /.well-known/acme-challenge/ {
                auth_basic off;
                allow all;
                root /usr/share/nginx/html;
                try_files $uri =404;
                break;
        }
        location / {
                return 301 https://$host$request_uri;
        }
}
server {
        server_name test.local;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/test.local.crt;
        ssl_certificate_key /etc/nginx/certs/test.local.key;
        add_header Strict-Transport-Security "max-age=31536000" always;
        location / {
                proxy_pass http://test.local;
        }
}
```

It seems that nginx gives access to the second site if the first is not accessible

Docker file (proxy)

```
version: "3"
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ${CERTS_PATH}:/etc/nginx/certs:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
networks:
    default:
        external:
            name: nginx-proxy
```

Docker file (default & test)

```
version: "3"
services:
    php:
        container_name: ${PROJECT_NAME}_php
        build: ./php-fpm
        ports:
            - "9000"
        volumes:
            - ./../:/var/www/symfony:rw
        networks:
            - php
    web:
        container_name: ${PROJECT_NAME}_nginx
        build: ./nginx
        ports:
            - "80"
            - "443"
        volumes:
            - ./../:/var/www/symfony:rw
            - ${CERTS_PATH}/:/etc/nginx/certs:ro
        environment:
            - VIRTUAL_HOST=${PROJECT_DOMAIN}
            - NGINX_HOST=${PROJECT_DOMAIN}
            - CERT_NAME=${CERT_NAME}
        depends_on:
            - php
        networks:
            - php
            - nginx-proxy
networks:
    php:
    nginx-proxy:
        external: true
```
