### ISSUE TITLE
Why need add "not-watch" volume to `nginx-gen` container?

### ISSUE THREAD

**Issue by dinhanhhuy** [nginx-proxy/nginx-proxy#1449]
As my understanding: when there an update in file `nginx.tmpl`, **nginx-gen** container will generate new file at `/etc/nginx/conf.d/default.conf` then send HUB signal to **nginx-web** container.
But why we need to volume "not-watch" folder to container **nginx-gen**:
>      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
>      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
>      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
>      - ${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
Does this volume have any use that Im missing?

```
nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup ${NGINX_WEB:-nginx-web} -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: ${DOCKER_GEN:-nginx-gen}
    restart: always
    environment:
      SSL_POLICY: ${SSL_POLICY:-Mozilla-Intermediate}
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    logging:
      driver: ${NGINX_GEN_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_GEN_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_GEN_LOG_MAX_FILE:-10}
```
