### ISSUE TITLE
Logrotate

### ISSUE THREAD

**Issue by azlux** [nginx-proxy/nginx-proxy#1455]
# Features Requests
Is that possible to add an environnement variable to enable logrotate ?
I see defaults config files are already present in `/etc/logrotate.d`

Of course I can create another container to do that, but in this case I need the docker socket to send USR1 to nginx (https://nginx.org/en/docs/control.html). What's your opinion ?

Azlux

**Comment by ghostiam** [comment]
You can use logrotate with the "copytruncate" option. 
I've just made a container and it works the way I wanted it to.

```dockerfile
FROM alpine:latest

ENV CRON="*/30 * * * *"

RUN apk --update add logrotate
RUN echo "${CRON} /usr/sbin/logrotate -v /etc/logrotate.conf" >> /etc/crontabs/root && \
    mkdir -p /etc/logrotate.d && \
    echo "/var/log/nginx/*.log" > /etc/logrotate.d/nginx && \
    echo "{" >> /etc/logrotate.d/nginx && \
    echo "  dateext" >> /etc/logrotate.d/nginx && \
    echo "  dateformat -%Y-%m-%d-%s" >> /etc/logrotate.d/nginx && \
    echo "  size 10M" >> /etc/logrotate.d/nginx && \
    echo "  compress" >> /etc/logrotate.d/nginx && \
    echo "  missingok" >> /etc/logrotate.d/nginx && \
    echo "  notifempty" >> /etc/logrotate.d/nginx && \
    echo "  copytruncate" >> /etc/logrotate.d/nginx && \
    echo "  rotate 10" >> /etc/logrotate.d/nginx && \
    echo "}" >> /etc/logrotate.d/nginx

CMD ["crond", "-f"]
```

docker-compose
```yaml
version: '2.2'
services:
  logrotate:
    build:
      context: .
      dockerfile: Dockerfile.logrotate
    container_name: nginx-logrotate
    restart: always
    volumes:
      - ./data/logs:/var/log/nginx
```
