### ISSUE TITLE
Backend and Frontend containers under a single domain, both with HTTPS issue. 

### ISSUE THREAD

**Issue by minenkod** [nginx-proxy/nginx-proxy#1469]
I'm having issues with having multiple containers working with a reverse proxy. My docker-compose.yml is below. If I try to access api.example.com then the address would not be found. I want it to route to my backend instead.

 If someone could give me some pointers I would be extremely grateful.

version: '3.5'
services:
  frontend:
    container_name: frontend
    image: nginx
    restart: unless-stopped
    volumes:
      - './build:/usr/share/nginx/html'
    networks:
      - webproxy
    environment:
      - VIRTUAL_HOST=example.com
      - LETSENCRYPT_HOST=example.com
      - LETSENCRYPT_EMAIL=email@example.com

  backend:
    restart: on-failure
    image: 'registry.gitlab.com/minenkod/backend:latest'
    depends_on:
      - mongo
    networks:
      - webproxy
    environment:
      - VIRTUAL_HOST=api.example.com
      - LETSENCRYPT_EMAIL=email@example.com
      - VIRTUAL_PORT=4000

  mongo:
    restart: always
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=mydb
    ports:
      - '27017:27017'
    networks:
      - webproxy
    volumes:
      - type: bind
        source: ./mongodata
        target: /data/db

networks:
  webproxy:
    driver: bridge
    name: webproxy

**Comment by tkw1536** [comment]
At first glance the configuration looks correct, however it seems to be missing the `nginx-proxy` and `letsencrypt-nginx-proxy-companion` containers. Both should also be connected to the `webproxy` network. 

You said:
> If I try to access api.example.com then the address would not be found.

What is the error you are getting? HTTP 502 (Service not available), HTTP 404 (Not Found) or something else?

**Comment by minenkod** [comment]
> At first glance the configuration looks correct, however it seems to be missing the `nginx-proxy` and `letsencrypt-nginx-proxy-companion` containers. Both should also be connected to the `webproxy` network.
> 
> You said:
> 
> > If I try to access api.example.com then the address would not be found.
> 
> What is the error you are getting? HTTP 502 (Service not available), HTTP 404 (Not Found) or something else?

Thanks so much for replying. Ive solved the issue where I was only relying on the conf file within the proxy companion. However by creating a seperate reverse proxy and placing its conf file inside I was able to achieve what I wanted. Within the new conf file I create every location block necessary to redirect to the correct container. 

If someone else faces this challenge to have front end and backend on the same server under same domain name , hit me up.

**Comment by kidnapkin** [comment]
@minenkod Facing similar issue while trying to use nginx-proxy for multiple services (frontend and backend).
The front-end is next.js app that runs on port 3000 and communicates with wordpress backend via graphql, however after running `docker-compose up` I'm able to access `http://api.my-domain.io` and `http://api.my-domain.io/qraphql` with the browser or staging frontend deployed to heroku everything is ok, I see wp-admin and qraphql are working well, but when trying to access the root `http://my-domain.io` I'm get 504 Gateway Time-out. Can't understand why api host is unreachable from the frontend container. Any response will be helpful. Tnx.

In the logs I see next:

```
nextjs_1       | 2020-07-12T14:16:01: PM2 error: (node:1) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
nextjs_1       | (Use `node --trace-deprecation ...` to show where the warning was created)
nextjs_1       | react-i18next:: i18n.languages were undefined or empty undefined
nginx-proxy_1  | nginx.1    | 2020/07/12 14:17:49 [error] 39#39: *5 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 78.137.7.108, server: my-domain.io, request: "GET / HTTP/1.1", upstream: "http://192.168.0.4:3000/", host: "my-domain.io"
nginx-proxy_1  | nginx.1    | my-domain.io 78.137.7.108 - - [12/Jul/2020:14:17:49 +0000] "GET / HTTP/1.1" 504 569 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
nextjs_1       | Error while running `getDataFromTree` ApolloError: Network error: request to http://api.my-domain.io/graphql failed, reason: connect ETIMEDOUT 46.101.206.171:80
nextjs_1       |     at new ApolloError (/usr/app/node_modules/apollo-client/bundle.umd.js:92:26)
nextjs_1       |     at /usr/app/node_modules/apollo-client/bundle.umd.js:1588:34
nextjs_1       |     at /usr/app/node_modules/apollo-client/bundle.umd.js:2008:15
nextjs_1       |     at Set.forEach (<anonymous>)
nextjs_1       |     at /usr/app/node_modules/apollo-client/bundle.umd.js:2006:26
nextjs_1       |     at Map.forEach (<anonymous>)
nextjs_1       |     at QueryManager.broadcastQueries (/usr/app/node_modules/apollo-client/bundle.umd.js:2004:20)
nextjs_1       |     at /usr/app/node_modules/apollo-client/bundle.umd.js:1483:29
nextjs_1       |     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
nextjs_1       |   graphQLErrors: [],
nextjs_1       |   networkError: FetchError: request to http://api.my-domain.io/graphql failed, reason: connect ETIMEDOUT 46.101.206.171:80
nextjs_1       |       at ClientRequest.<anonymous> (/usr/app/node_modules/next/dist/compiled/node-fetch/index.js:1:147710)
nextjs_1       |       at ClientRequest.emit (events.js:314:20)
nextjs_1       |       at Socket.socketErrorListener (_http_client.js:469:9)
nextjs_1       |       at Socket.emit (events.js:314:20)
nextjs_1       |       at emitErrorNT (internal/streams/destroy.js:100:8)
nextjs_1       |       at emitErrorCloseNT (internal/streams/destroy.js:68:3)
nextjs_1       |       at processTicksAndRejections (internal/process/task_queues.js:80:21) {
nextjs_1       |     type: 'system',
nextjs_1       |     errno: 'ETIMEDOUT',
nextjs_1       |     code: 'ETIMEDOUT'
nextjs_1       |   },
nextjs_1       |   extraInfo: undefined
nextjs_1       | }
nginx-proxy_1  | nginx.1    | api.my-domain.io 78.137.7.108 - - [12/Jul/2020:14:19:24 +0000] "GET /graphql HTTP/1.1" 200 154 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
```

My docker-compose is next:

```yaml
version: '3'
services:
  nextjs:
    build: ./frontend
    environment:
      VIRTUAL_HOST: my-domain.io

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  db:
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    image: mariadb
    ports:
      - '3307:3306'

  wordpress:
    container_name: wordpress
    depends_on:
      - db
    image: wordpress:latest
    expose:
      - 80
    volumes:
      - ./wp-content:/var/www/html/wp-content
    restart: always
    environment:
      VIRTUAL_HOST: api.my-domain.io
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    expose:
      - 80
    restart: always
    environment:
      VIRTUAL_HOST: phpmyadmin.my-domain.io
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password

networks:
  default:
    external:
      name: nginx-proxy
```

the generated `default.conf`
```nginx
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
# api.my-domain.io
upstream api.my-domain.io {
				## Can be connected with "nginx-proxy" network
			# wordpress
			server 192.168.0.6:80;
}
server {
	server_name api.my-domain.io;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://api.my-domain.io;
	}
}
# my-domain.io
upstream my-domain.io {
				## Can be connected with "nginx-proxy" network
			# freezmi_nextjs_1
			server 192.168.0.4:3000;
}
server {
	server_name my-domain.io;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://my-domain.io;
	}
}
# phpmyadmin.my-domain.io
upstream phpmyadmin.my-domain.io {
				## Can be connected with "nginx-proxy" network
			# phpmyadmin
			server 192.168.0.5:80;
}
server {
	server_name phpmyadminmy-domain.io;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://phpmyadmin.my-domain.io;
	}
}
```
