### ISSUE TITLE
Need Help: How to configure nginx correctly, nginx responds 502

### ISSUE THREAD

**Issue by meness** [nginx-proxy/nginx-proxy#1472]
**nginx-proxy-compose.yml**
```
version: '3.8'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
    networks:
      - proxynet

networks:
  proxynet:
    name: mynetwork
```
***Note:** Run the Nginx proxy container first.*

**app-compose.yml**
```
version: '3.8'

services:
  stage:
    container_name: xxx-website-stage
    image: registry.gitlab.com/xxx.us/website:latest
    build:
      context: .
      target: stage
      dockerfile: Dockerfile
    expose:
      - "80"
    restart: always
    volumes:
      - /etc/nginx/conf.d/staging.xxx.us.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      VIRTUAL_HOST: staging.xxx.us
    networks:
      - my-proxy-net

networks:
  my-proxy-net:
    external:
      name: mynetwork
```

**/etc/nginx/conf.d/staging.xxx.us.conf**
```
server {

  listen 80;
  listen [::]:80;

  server_name localhost;

  root /usr/share/nginx/html;

  access_log /var/log/nginx/localhost.access.log;
  error_log /var/log/nginx/localhost.error.log debug;

  index index.html index.htm;

  location / {
    try_files $uri $uri/ =404;

    expires -1;
  }

  location ~* \.(?:css|js)$ {
    access_log off;
    log_not_found off;

    add_header Cache-Control "no-cache, public, must-revalidate, proxy-revalidate";
  }

  location ~* \.(?:jpg|jpeg|gif|png|ico|xml)$ {
    access_log off;
    log_not_found off;

    add_header Cache-Control "public";
  }

  location ~* \.(?:eot|woff|woff2|ttf|svg|otf) {
    access_log off;
    log_not_found off;

    add_header Cache-Control "public";

    add_header Access-Control-Allow-Origin *;

    types {
      font/opentype otf;
    }
    types {
      application/vnd.ms-fontobject eot;
      }
    types {
      font/truetype ttf;
    }
    types {
      application/font-woff woff;
    }
    types {
      font/x-woff woff2;
    }
}

location ~ /\. {
    access_log off;
    log_not_found off;
    deny all;
  }

}
```

**Dockerfile**
```
# dev stage
FROM node:14.4.0-alpine AS dev

# set working directory
WORKDIR /var/www/

# install app dependencies
COPY package.json package-lock.json ./
RUN npm ci --silent

# add app
COPY . ./

# builder stage
FROM dev AS builder

RUN npm run build:app

# stage stage
FROM nginx:1.19.1-alpine AS stage

# Remove default files created by Nginx
RUN rm -rvf /usr/share/nginx/html/*
RUN rm -vf /etc/nginx/conf.d/default.conf

COPY --from=builder /var/www/build/ /usr/share/nginx/html

CMD ["nginx-debug", "-g", "daemon off;"]
```

**sudo docker ps**
```
CONTAINER ID        IMAGE                                          COMMAND                  CREATED             STATUS              PORTS                NAMES
...        ...   "/docker-entrypoint.…"   ...      ...       80/tcp               xxx-website-stage
...        jwilder/nginx-proxy                            "/app/docker-entrypo…"   ...   ...       0.0.0.0:80->80/tcp   docker-composes_nginx-proxy_1
```

**/etc/hosts**
```
127.0.0.1 localhost
127.0.0.1 staging.xxx.us

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
```

P.S. I tried the Google Group, but I don't have enough access to post a question, so I decided to post it here.

**Comment by tkw1536** [comment]
Most likely the issue arises because `nginx-proxy` and `stage` are not on the same docker network. 
See [the docker-compose documentation](https://docs.docker.com/compose/networking/) on how networking in compose works.

**Comment by tkw1536** [comment]
You probably want to either put them both in the same `.yml` file, or explicitly declare an external network they both connect to.

**Comment by meness** [comment]
@tkw1536 You saved me! I was searching and trying to fix the issue for 2 weeks! I also updated my question to help others

**Comment by fluffyst** [comment]
I've tried putting 
```
networks:
  default:
    external:
      name: nginx-proxy_default
```
In my second containers docker-compose.yml and i'm still getting a 502 over http, are you able to shed some light on this issue please?

**Comment by meness** [comment]
@fluffyst Create a named network instead of default at nginx-proxy level then put other containers in that network, this solved my issue, but it may be something else in your case, so I write you my configurations. Hope it helps.

**nginx-proxy.yml**

Here is the nginx-proxy level docker-compose file. You should run this file first using `docker-compose -f nginx-proxy.yml up -d`

```
version: '3.8'

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - proxynet
    environment:
      SSL_POLICY: Mozilla-Modern

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DEFAULT_EMAIL: youremail@gmail.com
      NGINX_PROXY_CONTAINER: nginx-proxy
    networks:
      - proxynet
    restart: always
    depends_on:
      - nginx-proxy

networks:
  proxynet:
    name: mynetwork
```

When you run the above command, you should see one green `Done` word for each one (2 words in total). If something didn't go well, you should investigate using `docker logs nginx-proxy` and `docker logs letsencrypt` commands.

**app-compose.yml**

Now you can build and up this compose file.

```
version: '3.8'

services:
  stage:
    container_name: xxx-website-stage
    image: registry.gitlab.com/xxx.us/website:latest-stage
    expose:
      - "80"
      - "443"
    restart: always
    environment:
      VIRTUAL_HOST: staging.xxx.us
      LETSENCRYPT_HOST: staging.xxx.us
    networks:
      - my-proxy-net

  master:
    container_name: xxx-website-master
    image: registry.gitlab.com/xxx.us/website:latest-master
    expose:
      - "80"
      - "443"
    restart: always
    environment:
      VIRTUAL_HOST: xxx.us,www.xxx.us
      LETSENCRYPT_HOST: www.xxx.us
    networks:
      - my-proxy-net

networks:
  my-proxy-net:
    external:
      name: mynetwork
```

Finally, you must modify `/etc/hosts` to add these lines:

```
127.0.0.1 xxx.us www.xxx.us
127.0.0.1 staging.xxx.us
```

You should have a customized conf file for each one of your frontend apps. You can start with this one and you should put it in their containers at `/etc/nginx/conf.d/` path if you use Nginx.

```
server {

  listen 80;
  listen [::]:80;

  server_name www.xxx.us;

  root /usr/share/nginx/html;

  access_log /var/log/nginx/app.access.log;
  error_log /var/log/nginx/app.error.log;

  index index.html index.htm;

  location / {
    try_files $uri $uri/ /index.html =404;

    # The Expires HTTP header is a basic means of controlling caches; it tells all caches how long
    # the associated representation is fresh for. After that time, caches will always check back with
    # the origin server to see if a document is changed.
    #
    # "If a request includes the no-cache directive, it SHOULD NOT include min-fresh, max-stale, or max-age."
    # (source: http://www.ietf.org/rfc/rfc2616.txt, p114)
    #
    # A negative value means that the response expires immediately.
    # Nginx automatically sets the `Cache-Control: no-cache` header, if `expires` is negative
    expires -1;
  }

  # this block will catch files that might need to change immediately (e. g. to deploy hotfixes), such as js or css
  # The ?: prefix is a 'non-capturing' mark, meaning we do not require
  # the pattern to be captured into $1 which should help improve performance
  location ~* \.(?:css|js)$ {
    access_log off;
    log_not_found off;

    # no-cache:         forces caches to submit the request to the origin server for validation before releasing a
    #                   cached copy, every time. This is useful to assure that authentication is respected
    #                   (in combination with public), or to maintain rigid freshness, without sacrificing all of the
    #                   benefits of caching.
    #
    # public:           marks authenticated responses as cacheable; normally, if HTTP authentication is required,
    #                   responses are automatically private.
    #
    # must-revalidate:  tells caches that they must obey any freshness information you give them about a
    #                   representation. HTTP allows caches to serve stale representations under special conditions;
    #                   by specifying this header, you’re telling the cache that you want it to strictly follow
    #                   your rules.
    #
    # proxy-revalidate: similar to must-revalidate, except that it only applies to proxy caches.
    add_header Cache-Control "no-cache, public, must-revalidate, proxy-revalidate";
  }

  # This block will catch static file requests, such as images and videos
  # The ?: prefix is a 'non-capturing' mark, meaning we do not require
  # the pattern to be captured into $1 which should help improve performance
  location ~* \.(?:jpg|jpeg|gif|png|ico|xml|svg|svgz|mp4|webm|webp)$ {
    access_log off;
    log_not_found off;
    # The Expires HTTP header is a basic means of controlling caches; it tells all caches how long
    # the associated representation is fresh for. After that time, caches will always check back with
    # the origin server to see if a document is changed.
    #
    # "If a request includes the no-cache directive, it SHOULD NOT include min-fresh, max-stale, or max-age."
    # (source: http://www.ietf.org/rfc/rfc2616.txt, p114)
    #
    # Nginx automatically sets the `Cache-Control: max-age=t` header, if `expires` is present, where t is a time
    # specified in the directive, in seconds. Shortcuts for time can be used, for example 1M for 1 month.
    expires 1M;

    # public:           marks authenticated responses as cacheable; normally, if HTTP authentication is required,
    #                   responses are automatically private.
    add_header Cache-Control "public";
  }

  # This block will catch static file requests of fonts and allows fonts to be requested via CORS
  # The ?: prefix is a 'non-capturing' mark, meaning we do not require
  # the pattern to be captured into $1 which should help improve performance
  location ~* \.(?:eot|woff|woff2|ttf|svg|otf) {
    access_log off;
    log_not_found off;

    # The Expires HTTP header is a basic means of controlling caches; it tells all caches how long
    # the associated representation is fresh for. After that time, caches will always check back with
    # the origin server to see if a document is changed.
    #
    # "If a request includes the no-cache directive, it SHOULD NOT include min-fresh, max-stale, or max-age."
    # (source: http://www.ietf.org/rfc/rfc2616.txt, p114)
    #
    # Nginx automatically sets the `Cache-Control: max-age=t` header, if `expires` is present, where t is a time
    # specified in the directive, in seconds. Shortcuts for time can be used, for example 5m for 5 minutes.
    expires 1M;

    # public:           marks authenticated responses as cacheable; normally, if HTTP authentication is required,
    #                   responses are automatically private.
    add_header Cache-Control "public";

    # allow CORS requests
    add_header Access-Control-Allow-Origin *;

    types {
      font/opentype otf;
    }
    types {
      application/vnd.ms-fontobject eot;
      }
    types {
      font/truetype ttf;
    }
    types {
      application/font-woff woff;
    }
    types {
      font/x-woff woff2;
    }
  }

  # this prevents hidden files (beginning with a period) from being served
  location ~ /\. {
    access_log off;
    log_not_found off;
    deny all;
  }
}

server {
  server_name xxx.us;
  return 301 $scheme://www.xxx.us$request_uri;
}
```
