### ISSUE TITLE
Need help: How to configure the backend container to use a domain over https?

### ISSUE THREAD

**Issue by meness** [nginx-proxy/nginx-proxy#1473]
**docker-compose.yml**
```
version: '3.8'

services:
  redis-stage:
    container_name: redis-stage
    image: redis:6.0.5-alpine
    ports:
      - '7075:6379'
    restart: always
    networks:
      - my-proxy-net

  stage:
    container_name: xxx-backend-stage
    image: registry.gitlab.com/xxx.us/backend:latest-stage
    expose:
      - '7070'
    restart: always
    networks:
      - my-proxy-net
    depends_on:
      - redis-stage
    environment:
      VIRTUAL_HOST: backend.xxx.us
      VIRTUAL_PROTO: https
      LETSENCRYPT_HOST: backend.xxx.us

networks:
  my-proxy-net:
    external:
      name: mynetwork
```

While my frontend apps use the same network as above, but they cannot access the backend.

**Update 1**

I allowed port `7070` using `ufw allow 7070`.

**Update 2**

I added `127.0.0.1 backend.xxx.us` to `/etc/hosts`.

**Update 3**

The backend is up and running, `docker ps` proves this.

P.S. I couldn't post my question in Google Groups because I don't have access.
