### ISSUE TITLE
Using nginx-proxy with cloudflare full ssl config

### ISSUE THREAD

**Issue by TheMisir** [nginx-proxy/nginx-proxy#1475]
I'm unable to use cloudflare with nginx-proxy. Because I'm using full ssl config (which requires HTTPS connection between server and cloudflare) there's something that's not working.

Here's simple network graph:

```
                                                                          +----HTTP----> Virtual host 1
                                                                          |
User ------ HTTPS -----> Cloudflare ------ HTTPS ------> nginx-proxy -----|----HTTP----> Virtual host 2
                                                                          |
                                                                          +----HTTP----> Virtual host 3
```

Here's my compose config:

```yml
version: '3.4'

services:
  db:
    image: mdillon/postgis
    volumes:
      - "/var/docker/postgresql/.sock:/var/run/postgres/postgres.sock"
      - "/var/docker/postgresql/data:/var/lib/postgresql/data"
      - "/var/docker/postgresql/initdb:/docker-entrypoint-initdb.d/"

  proxy:
    image: jwilder/nginx-proxy
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/var/docker/certs:/etc/nginx/certs"
    ports:
      - "80:80"
      - "443:443"

# virtual servers ...
```

Result:

![image](https://user-images.githubusercontent.com/29130291/88076683-6b575680-cb8b-11ea-8398-66f9da3361d9.png)
