### ISSUE TITLE
502 Bad gateway only with SSL, working connecting with http

### ISSUE THREAD

**Issue by ruky87** [nginx-proxy/nginx-proxy#1476]
I have a container running a webapp (nodeJS, angular) not written by me. I added to docker compose file the following variables
VIRTUAL_PORT: 18283
HTTPS_METHOD: noredirect
VIRTUAL_HOST: subdomain.example.com
LETSENCRYPT_HOST: subdomain.example.com
I added the "noredirect" option because I was unable to connect to https://subdomain.example.com (502 bad gateway)
With the "noredirect" enabled I can connect to HTTP version without issues: http://subdomain.example.com
But I get the 502 bad gateway error if I try the HTTPS version.

The strange thing is that if I stop the webapp inside my container and open a simple webserver (for example with python simpleHTTPServer) showing the directory files list, I can connect to this service both with HTTP and HTTPS (aslo without the "noredirect" option).

What could be the issue? Any suggestions? 
I don't know how/what to modify in the webapp code, but I suppose that the problem is in the Nginx configuration. Currently I'm using the ENV variables, without providing custom configurations.

**Comment by ruky87** [comment]
If I force the configuration with a readonly bind mount and remove this part
```
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 443 ssl http2;
	access_log /var/log/nginx/access.log vhost;
	return 503;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/default.crt;
	ssl_certificate_key /etc/nginx/certs/default.key;
}
```
The HTTPS starts working also with the webapp. No problems with other apps (eg. wordpress). Why disabling this solved the problem only for this case?

**Comment by ruky87** [comment]
Edit: Now it works also with the code above, but I had to remove the `http2`  in the listen setting.
Is there a way to disable http2 only for certain virtual hosts? I don't know why this is working with wordpress but not for my nodejs app. And why the code above interact with the whole thing

**Comment by ruky87** [comment]
I ended removing http2 from the template `nginx.tmpl` file manually

```bash
sudo sed -i "s/ssl http2/ssl/g" nginx.tmpl
```

A variable should be created to disable HTTP2 globally (as default settings) and maybe override (enable HTTP2) per single virtual host.

**Comment by n3me5is-git** [comment]
In my case I'm using docker compose to run the container. I have a service running on the HOST that does not support HTTP2 (the Web app is not written by me). I created a socat container used for the redirect

```yml
version: "3"

services:
   # Socat service for port redirect: redirects the container local 80 port to the destination ip:port. In this case the destination is the nginx-proxy gateway IP, to reach the web app (binded to 0.0.0.0 on the host)
   website-socat:
     # Image used: https://hub.docker.com/r/ajoergensen/socat
     image: ajoergensen/socat
     container_name: website-socat
     restart: always
     expose:
       - 80
     environment:
       # Socat configuration: forward container_localhost:80 to destination:port
       LOCAL_PORT: 80
       TARGET: 172.18.0.1
       TARGET_PORT: 18283
       PROTO: TCP
       # Nginx-proxy variables for the subdomain
       #HTTPS_METHOD: noredirect  # Use if you want to enable access also with HTTP. Set to nohttps to disable HTTPS completely for the subdomain. Keep commented (default) to redirect HTTP to HTTPS
       # Virtual host for Nginx configuration
       VIRTUAL_HOST: example.com
       # Virtual host for Nginx configuration
       LETSENCRYPT_HOST: example.com
       # Mail for ACME Let's encrypt Account
       LETSENCRYPT_EMAIL: admin@example.com

# External network to connect with (optional, used with nginx-proxy for example)
networks:
  default:
    external:
      name: nginx-proxy
```

It started working only when disabling the HTTP2 in `nginx.tmpl`. It should be interesting to be able to control this feature in a better way (like I wrote in my precedent comment). 
However in my case I'm using Let's encrypt and not self signed certificates. You should also check nginx logs inside the container (`/var/log/nginx`)
