### ISSUE TITLE
The wildcard subdomain environment variable cause issues

### ISSUE THREAD

**Issue by imfaisalkh** [nginx-proxy/nginx-proxy#1478]
I'm using this image as following in my `docker-compose.yml` file:

```
version: "3"

services:
  # Server
  server:
    environment:
      VIRTUAL_HOST: server.example.com
      LETSENCRYPT_HOST: server.example.com

  # Dashboard
  dashboard:
    environment:
      VIRTUAL_HOST: dashboard.example.com
      LETSENCRYPT_HOST: dashboard.example.com

  # Sites
  sites:
    environment:
      VIRTUAL_HOST: *.example.com <------ THIS IS CAUSING ISSUE
      LETSENCRYPT_HOST: *.example.com <------ THIS IS CAUSING ISSUE

  # Root
  root:
    environment:
      VIRTUAL_HOST: example.com
      LETSENCRYPT_HOST: example.com

```

The reverse-proxy works fine if I don't use the wildcard subdomain under `sites` container. Once wildcard environment variable is included it does not work at all. Am I doing something wrong here? I want to catch all subdomains under `sites` container (provided that subdomain is not specifically assigned to any other container)
