### ISSUE TITLE
Setting up HTTPS with self signed cert on non-standard port

### ISSUE THREAD

**Issue by dylanparry** [nginx-proxy/nginx-proxy#1479]
Hi,

I'm trying to set up nginx as a proxy for a Mediawiki container. I am only able to use port 8080, but would still like to use HTTPS.

Here's what I have in my Docker Compose file:

```
version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 8080:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - $HOME/volumes/mediawiki/certs:/etc/nginx/certs

  mediawiki:
    container_name: wiki
    image: mediawiki
    restart: always
    environment:
      - VIRTUAL_HOST=dylanparry.ddns.net
    links:
      - database
    volumes:
      - $HOME/volumes/mediawiki/images:/var/www/html/images
      - $HOME/volumes/mediawiki/LocalSettings.php:/var/www/html/LocalSettings.php

  database:
    image: mariadb
    container_name: db
    restart: always
    ports:
        - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: [redacted]
    volumes:
       - $HOME/volumes/mysql/data:/var/lib/mysql
```

This works fine over HTTP, but I cannot get HTTPS to work. I've tried numerous different settings in addition to the above, but to no avail, so have stripped it back to a working HTTP config for now.

I have a self-signed certificate in the `$HOME/volumes/mediawiki/certs` directory, called `dylanparry.ddns.net.crt`.

I'm not bothered about having the HTTP version at all, as I'd prefer all traffic for the site to be over HTTPS.

Can anyone guide me as to what I need to add to the above config to make it work?

Thanks.
