### ISSUE TITLE
Not working with .app domain

### ISSUE THREAD

**Issue by imfaisalkh** [nginx-proxy/nginx-proxy#1481]
I've a `docker-compose` file with following definitions (trimmed down version):

```
version: "3"

services:
  # Server
  server:
    environment:
      VIRTUAL_HOST: server.example.app
      LETSENCRYPT_HOST: server.example.app

  # Dashboard
  dashboard:
    environment:
      VIRTUAL_HOST: dashboard.example.app
      LETSENCRYPT_HOST: dashboard.example.app

  # Root
  root:
    environment:
      VIRTUAL_HOST: example.app
      LETSENCRYPT_HOST: example.app
```

Now, when I initialize the this docker-compose file no domain is actually linking to the correct web service. Infact, it shows this error: 

![image](https://user-images.githubusercontent.com/10553273/88418086-77961a80-cdfc-11ea-9883-467f08c14749.png)

Now, the strange thing is that if i user a .net domain (instead of .app domain) and all other things remains constant. It works without any issue.

Can you please tell me if you know something about this issue?
