### ISSUE TITLE
🤷‍♂️ Pihole and nginx-proxy

### ISSUE THREAD

**Issue by segersniels** [nginx-proxy/nginx-proxy#1484]
### Issue
For some reason I am unable to get `nginx-proxy` working with `pihole`. It seems like `nginx-proxy` doesn't detect the containers connected to the same docker network somehow. None of the `VIRTUAL_HOST`'s I set are resolving.

```
# pihole.local
upstream pihole.local {
                                ## Can be connected with "networking_default" network.
                        # networking_pihole_1
                        server 172.20.0.4:80;
}
server {
        server_name pihole.local;
        listen 80 default_server;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://pihole.local;
        }
}
# status.local
upstream status.local {
                                ## Can be connected with "networking_default" network 
                        # monitoring_dashboard_1
                        server 172.20.0.5:80;
}
server {
        server_name status.local;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://status.local;
        }
}
```

### What should happen
It should correctly detect all containers in the `networking_default` network and resolve the local domain names. 
eg. http://pihole.local should correctly resolve.

#### Monitoring
Below is an example `monitoring/docker-compose.yml` that just runs a basic nginx dashboard on port `8080`. I enforce the container's network to `networking_default` which is created by my networking stack.

```
version: "3"

services:
  dashboard:
    image: tobi312/alpine-nginx-php
    hostname: foo
    expose:
      - 80
    ports:
      - 8080:80
    environment:
      VIRTUAL_HOST: status.local
      VIRTUAL_PORT: 80 # not needed but here for debugging purposes
    volumes:
      - /home/foo/monitoring/dashboard:/var/www/html
    restart: unless-stopped
    privileged: true
    network_mode: networking_default # needed for reverse proxy
```

#### Networking
Then I have another `networking/docker-compose.yml` file which has some basic networking stuff like OpenVPN, Pihole, etc. These use the default network created called `networking_default`

```
version: "3"
  
services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 8081:80/tcp
    environment:
      ServerIP: 10.0.0.5
      VIRTUAL_HOST: pihole.local
      VIRTUAL_PORT: 80 # not needed but here for debugging purposes
    volumes:
       - /home/foo/networking/pihole/pihole:/etc/pihole
       - /home/foo/networking/pihole/dnsmasq.d:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
    extra_hosts:
      - 'pihole pihole.local:10.0.0.5'
      - 'status status.local:10.0.0.5'
    privileged: true

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    environment:
      DEFAULT_HOST: pihole.local
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
    privileged: true
```

### Reproducing
I guess you could use the `networking/docker-compose.yml` to reproduce this issue with slight adjustments. I took a lot of configuration from https://github.com/pi-hole/docker-pi-hole/blob/master/docker-compose-jwilder-proxy.yml.

**EDIT:** I have noticed that I am able to access the local DNS records on my Windows PC but unable to access them from any Apple device (phones, tablets, macbook, etc.)
