### ISSUE TITLE
Using a VIRTUAL_HOST with a FQDN without a hostname randomly causes default nginx webpage to be displayed

### ISSUE THREAD

**Issue by Ruin0x11** [nginx-proxy/nginx-proxy#1486]
I have a static webpage I want to serve on a domain without a hostname, like `domain.xyz`. This is how my `docker-compose.yml` is setup:

```
   site:
      build: ./site
      ports:
        - 8080:8080
      networks:
        - home
      environment:
        - VIRTUAL_HOST=domain.xyz
        - VIRTUAL_PORT=8080
        - LETSENCRYPT_HOST=domain.xyz
        - UID=1000
        - GID=1000
```

However, if I set `VIRTUAL_HOST` to `domain.xyz` without a hostname (as in `sub.domain.xyz`), then when I try to visit `https://domain.xyz` I randomly get back the default nginx page. There is no error, but I was expecting the content of `site` to be returned.

If I change `VIRTUAL_HOST` to be `sub.domain.xyz` instead, rebuild/restart the container and `nginx-proxy` and visit `https://sub.domain.xyz`, then this issue never occurs. It only occurs when leaving off the hostname.
