### ISSUE TITLE
Feature request: Shared vhosts

### ISSUE THREAD

**Issue by alekna** [nginx-proxy/nginx-proxy#1494]
As a user I'd like to run multiple services on a same vhost.

Proposed configuration:
```
services:
  svc1:
    ...
    environment:
      - VIRTUAL_HOST=domain.tld
      - VIRTUAL_LOC="/svc1"
  svc2:
    ...
    environment:
      - VIRTUAL_HOST=domain.tld
      - VIRTUAL_LOC="/svc2"
```

Request to `http://domain.tld/svc1` would be proxied to `svc1` webroot and requests to `http://domain.tld/svc2` would be proxied to `svc2` webroot.
