### ISSUE TITLE
proxy_pass in always return 502 bad gateway error

### ISSUE THREAD

**Issue by goog4peace** [nginx-proxy/nginx-proxy#1501]
I have a server and I want to deploy a website with a few docker containers. with this config, `example.com` is working fine in the browser:

```
version: "3"

networks:
  nginx-proxy:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - ./vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx-proxy

  letsencrypt-nginx-proxy-companion:
    container_name: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - certs:/etc/nginx/certs
      - ./vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DEFAULT_EMAIL: email@gmail.com
      NGINX_PROXY_CONTAINER: nginx-proxy
    restart: always
    networks:
      - nginx-proxy

  auth-service:
    image: auth-service
    restart: always
    command: "bash -c python3 manage.py makemigrations && python3 manage.py migrate"
    volumes:
      - /home/ubuntu/projects/project/microservices/auth/:/home/Fitness/auth
    networks:
      - nginx-proxy
    environment:
      VIRTUAL_HOST: auth
      VIRTUAL_PORT: 80

  plans-service:
    image: salemfit-plans-service
    restart: always
    command: "bash -c python3 manage.py makemigrations && python3 manage.py migrate"
    volumes:
      - /home/ubuntu/projects/project/microservices/plans/:/home/Fitness/plans
    networks:
      - nginx-proxy
    environment:
      VIRTUAL_HOST: plans
      VIRTUAL_PORT: 80

  web-ui:
    image: web-ui
    expose:
      - 80
    volumes:
      - /home/ubuntu/projects/project/example.com/src/:/var/www/example.com
    restart: always
    environment:
      VIRTUAL_HOST: example.com
      LETSENCRYPT_HOST: example.com
      LETSENCRYPT_EMAIL: email@gmail.com
    container_name: web-ui
    networks:
      - nginx-proxy
volumes:
  certs:
  html:

```

I want to pass `example.com/auth` to the VIRTUAL_HOST `auth` and `example.com/plans` to the VIRTUAL_HOST `plans`. so in `vhostd` folder I have a file named `example.com_location` and I put these into it:

```
location /auth {
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_pass http://auth;
}

location /plans {
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_pass http://plans;
}

```

These configuration it seems to be OK, I run the first `docker-compose.yml` via `sudo docker-compose up -d`. containers starts successfully. to test it, in the `Postman` App, I call a url like this:

```
https://example.com/auth/getsms
```

and I expect a response from server that I implemented. But every time I get `server error 502. Bad gateway`. I changed this config to any state I know and I research about it but all I get 502 error.

this is `nginx-proxy` container's `/etc/nginx/conf.d/default.conf` content:

```
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Apply fix for very long server names
server_names_hash_bucket_size 128;
# Default dhparam
ssl_dhparam /etc/nginx/dhparam/dhparam.pem;
# Set appropriate X-Forwarded-Ssl header
map $scheme $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
		ssl_prefer_server_ciphers off;
resolver 127.0.0.11;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 443 ssl http2;
	access_log /var/log/nginx/access.log vhost;
	return 503;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/default.crt;
	ssl_certificate_key /etc/nginx/certs/default.key;
}
# auth
upstream auth {
				## Can be connected with "controller_nginx-proxy" network
			# controller_auth-service_1
			server 172.18.0.8:80;
}
server {
	server_name auth;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://auth;
	}
}
server {
	server_name auth;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	return 500;
	ssl_certificate /etc/nginx/certs/default.crt;
	ssl_certificate_key /etc/nginx/certs/default.key;
}
# plans
upstream plans {
				## Can be connected with "controller_nginx-proxy" network
			# controller_plans-service_1
			server 172.18.0.7:80;
}
server {
	server_name plans;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://plans;
	}
}
server {
	server_name plans;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	return 500;
	ssl_certificate /etc/nginx/certs/default.crt;
	ssl_certificate_key /etc/nginx/certs/default.key;
}
# example.com
upstream example.com {
				## Can be connected with "controller_nginx-proxy" network
			# web-ui
			server 172.18.0.4:80;
}
server {
	server_name example.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	# Do not HTTPS redirect Let'sEncrypt ACME challenge
	location /.well-known/acme-challenge/ {
		auth_basic off;
		allow all;
		root /usr/share/nginx/html;
		try_files $uri =404;
		break;
	}
	location / {
		return 301 https://$host$request_uri;
	}
}
server {
	server_name example.com;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/example.com.crt;
	ssl_certificate_key /etc/nginx/certs/example.com.key;
	ssl_dhparam /etc/nginx/certs/example.com.dhparam.pem;
	ssl_stapling on;
	ssl_stapling_verify on;
	ssl_trusted_certificate /etc/nginx/certs/example.com.chain.pem;
	add_header Strict-Transport-Security "max-age=31536000" always;
	include /etc/nginx/vhost.d/example.com;
	location / {
		proxy_pass http://example.com;
		include /etc/nginx/vhost.d/example.com_location;
	}
}

```

Also this is `nginx-proxy` containers log:

```
dockergen.1 | 2020/09/19 15:35:28 Generated '/etc/nginx/conf.d/default.conf' from 8 containers
dockergen.1 | 2020/09/19 15:35:28 Watching docker events
dockergen.1 | 2020/09/19 15:35:28 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
.
.
.

```
I don't know how to overcome this. It will be great if you help me.
