### ISSUE TITLE
Need Nginx RTMP Module Support

### ISSUE THREAD

**Issue by vamsiduranc** [nginx-proxy/nginx-proxy#1503]
@jwilder 

I am using this nginx proxy in congestion with ```jrcs/letsencrypt-nginx-proxy-companion``` in docker and it is working pretty fine. Now we need to integrate Nginx RTMP module in nginx. Can you please help us with a docker file with existing work flow and RTMP on 1935 port.

Thank You!

**Comment by tkw1536** [comment]
I am not familiar with RTMP, but a quick search tells me that it is a module which needs to be explicitly compiled into nginx. 

A rough approach to achieving what you want could be:
1. Create a standalone nginx docker container with RTMP enabled.
2. Switch your nginx-proxy installation to make use of [Seperate Containers](https://github.com/nginx-proxy/nginx-proxy#separate-containers), making sure to replace the default nginx container with the one created in step 1. 
3. Make any configuration changes as described in the [custom nginx configuration](https://github.com/nginx-proxy/nginx-proxy#custom-nginx-configuration) section of the README.

**Comment by vamsiduranc** [comment]
Dear Tom @tkw1536 

Thank you very much for your reply!
I have followed your suggestions and created docker compose files as follows

**_docker-compose-loadbalancer.yml:_**
```
version: '3'
services:
  nginx:
    build: ./nginx/
    image: duranc_nginx
    restart: always
    ports:
      - 80:80
      - 443:443
      - 1935:1935
    volumes:      
      - vhost:/etc/nginx/vhost.d
      - vhost:/etc/nginx
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
      - ./nginx/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
    container_name: duranc_nginx
    networks:
      duranc-network:
        ipv4_address: 18.19.0.2
  
  dockergen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - nginx
    volumes:
      - vhost:/etc/nginx/vhost.d
      - vhost:/etc/nginx
      - html:/usr/share/nginx/html
      - /home/user/tools/nginx_webproxy/certificats:/etc/nginx/certs:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
      - ./nginx/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
    container_name: duranc_dockergen
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      duranc-network:
        ipv4_address: 18.19.0.8

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    depends_on:
      - nginx
      - dockergen
    volumes:
      - vhost:/etc/nginx/vhost.d
      - vhost:/etc/nginx
      - html:/usr/share/nginx/html
      - /home/user/tools/nginx_webproxy/certificats:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
      - ./nginx/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=duranc_dockergen
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    container_name: duranc_ssl
    networks:
      duranc-network:
        ipv4_address: 18.19.0.3

networks:
  duranc-network:
    external: true

volumes:
  vhost:
    external:
      name: virtual-hosts
  html:
    external:
      name: html-files
```

**_docker-compose-apps.yml:_**
```
version: "3"
services:
   mongodb:
     build: ./docker-durancdb/
     image: duranc_database
     ports:
      - 27017:27017
     restart: unless-stopped
     volumes:
      - db_data:/data/db
     container_name: duranc_db
     command: mongod
     networks:
      duranc-network:
        ipv4_address: 18.19.0.4

   portal:
     depends_on:
        - mongodb
     build: ./docker-portal
     image: duranc_portal
     ports:
        - 3000:3000
     restart: unless-stopped
     volumes:
      - portal_data:/var/www/duranc
     environment:
        DEFAULT_HOST: dockerssl.duranc.com
        WIKI_ADMIN_EMAIL: img@duranc.com
        VIRTUAL_HOST: dockerssl.duranc.com
        VIRTUAL_PORT: 3000
        LETSENCRYPT_HOST: dockerssl.duranc.com
        LETSENCRYPT_EMAIL: img@duranc.com
     container_name: duranc_portal
     networks:
      duranc-network:
        ipv4_address: 18.19.0.5
   
   messenger:
     depends_on:
        - mongodb
        - portal
     build: ./docker-messenger
     image: duranc_messenger
     ports:
        - 3001:3001
     restart: unless-stopped
     volumes:
      - messenger_data:/var/www/duranc
     environment:
        VIRTUAL_HOST: dockermsg.duranc.com
        VIRTUAL_PORT: 3001
        LETSENCRYPT_HOST: dockermsg.duranc.com
        LETSENCRYPT_EMAIL: img@duranc.com
     container_name: duranc_messenger
     networks:
      duranc-network:
        ipv4_address: 18.19.0.6

   streamer:
     depends_on:
        - mongodb
        - portal
        - messenger
     build: ./docker-streamer
     image: duranc_streamer
     ports:
        - 3002:3002
     restart: unless-stopped
     volumes:
      - streamer_data:/var/www/duranc
     environment:
        VIRTUAL_HOST: dockerstr.duranc.com
        VIRTUAL_PORT: 3002
        LETSENCRYPT_HOST: dockerstr.duranc.com
        LETSENCRYPT_EMAIL: img@duranc.com
     container_name: duranc_streamer
     networks:
      duranc-network:
        ipv4_address: 18.19.0.7

volumes:
  db_data:
    external:
      name: duranc-db
  portal_data:
    external:
      name: duranc-portal
  messenger_data:
    external:
      name: duranc-messenger
  streamer_data:
    external:
      name: duranc-streamer

networks:
  duranc-network:
    external: true
```
nginx docker file: [nginx.zip](https://github.com/nginx-proxy/nginx-proxy/files/5317699/nginx.zip)

All letsencrypt certificates are getting generated as per LETSENCRYPT_HOST variable in docker-compose file and we can see upstreams are getting created in /etc/nginx/conf.d: [default_conf.zip](https://github.com/nginx-proxy/nginx-proxy/files/5317847/default_conf.zip)

We are able browse the application using url http://dockerssl.duranc.com:3000 and rtmp module is also working fine. **Can you please help us how to adjust nginx to make urls redirect to https automatically and all applications work with below urls**:
- https://dockerssl.duranc.com
- https://dockermsg.duranc.com
- https://dockerstr.duanc.com

Using below docker-compose file everything is working as expected but WITHOUT - RTMP module...
Just for your reference:

**_docker-compose-loadbalancer-old.yml_**
```
version: '3'
services:
  proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
      - 1935:1935
    volumes:      
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /home/user/tools/nginx_webproxy/certificats:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    container_name: duranc_nginx
    networks:
      duranc-network:
        ipv4_address: 18.19.0.2
  
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    depends_on:
      - proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /home/user/tools/nginx_webproxy/certificats:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
    container_name: duranc_ssl
    networks:
      duranc-network:
        ipv4_address: 18.19.0.3

networks:
  duranc-network:
    external: true

volumes:
  vhost:
    external:
      name: virtual-hosts
  html:
    external:
      name: html-files
```

Expecting a reply ASAP. Thank you in advance!

**Comment by tkw1536** [comment]
It looks to me like there are two seperate issues here. 

1. nginx-durac not loading the `/etc/nginx/conf.d/default.conf`
2. letsencrypt not generating certificates

To resolve the first issue,  the nginx.conf should include something along the lines of:

```
include "/etc/nginx/conf.d/*.conf";
```

Furthermore, the `default.conf` that is generated by `docker-gen` will conflict with some lines in the original `nginx.conf`. Instead of `cat /rmtpconf/rtmp.conf >> /etc/nginx/nginx.conf` you should just overwrite `/etc/nginx/nginx.conf`. 

After that it should be possible to directly access the websites via ports 80 / 443. 

The second issue I can not directly help with, the configuration looks correct. 
It could be because nginx is not picking up on the /etc/nginx/conf.d/ directory the certificate generation process fails. 
I suspect that once the first issue above is fixed, they should start working. 

If that doesn't work, could you share the log files of the letsencrypt and nginx-proxy containers? Those might indicate as to what is wrong.

**Comment by vamsiduranc** [comment]
Dear Tom @tkw1536 

Thank you for your reply.

I have updated nginx.conf like this: [nginx_conf.zip](https://github.com/nginx-proxy/nginx-proxy/files/5322001/nginx_conf.zip)
Updated Docker file: [Dockerfile.zip](https://github.com/nginx-proxy/nginx-proxy/files/5322003/Dockerfile.zip) and used below docker-compose file:

```
version: '3'
services:
  nginx:
    build: ./nginx/
    image: duranc_nginx
    restart: always
    ports:
      - 80:80
      - 443:443
      - 1935:1935
    volumes:      
      - vhost:/etc/nginx/vhost.d
      - vhost:/etc/nginx
      - html:/usr/share/nginx/html
      - /home/user/tools/nginx_webproxy/certificats:/etc/nginx/certs:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
    container_name: duranc_nginx
    networks:
      duranc-network:
        ipv4_address: 18.19.0.2
  
  dockergen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - nginx
    volumes:      
      - vhost:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /home/user/tools/nginx_webproxy/certificats:/etc/nginx/certs:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - ./nginx/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
    container_name: duranc_dockergen
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      duranc-network:
        ipv4_address: 18.19.0.8

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    depends_on:
      - nginx
      - dockergen
    volumes:      
      - vhost:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /home/user/tools/nginx_webproxy/certificats:/etc/nginx/certs:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=duranc_dockergen
      - DEFAULT_EMAIL=img@duranc.com
      - DHPARAM_GENERATION=false
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    container_name: duranc_ssl
    networks:
      duranc-network:
        ipv4_address: 18.19.0.3

networks:
  duranc-network:
    external: true

volumes:
  vhost:
    external:
      name: virtual-hosts
  html:
    external:
      name: html-files
```
and it worked like a charm!!!
Thank you once again for your support...
I will get back to you if I need any help... best regards!

**Comment by vamsiduranc** [comment]
Dear Tom @tkw1536 

A small observation....

I have deleted all previously created containers, volumes and images. Recreated all of them using docker-compose file provide in previous post then it did **NOT** work. So, I have adjusted docker-compose-loadbalancer.yml file as below:

```
version: '3'
services:
  nginx:
    build: ./nginx/
    image: duranc_nginx
    restart: always
    ports:
      - 80:80
      - 443:443
      - 1935:1935
    volumes:
      - vhost:/etc/nginx/vhost.d
      - vhost:/etc/nginx
      - html:/usr/share/nginx/html
      - /home/user/tools/nginx_webproxy/certificats:/etc/nginx/certs:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
    container_name: duranc_nginx
    networks:
      duranc-network:
        ipv4_address: 18.19.0.2
  
  dockergen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - nginx
    volumes:      
      - vhost:/etc/nginx/vhost.d
      - vhost:/etc/nginx
      - html:/usr/share/nginx/html
      - /home/user/tools/nginx_webproxy/certificats:/etc/nginx/certs:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - ./nginx/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
    container_name: duranc_dockergen
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      duranc-network:
        ipv4_address: 18.19.0.8

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    depends_on:
      - nginx
      - dockergen
    volumes:      
      - vhost:/etc/nginx/vhost.d
      - vhost:/etc/nginx
      - html:/usr/share/nginx/html
      - /home/user/tools/nginx_webproxy/certificats:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - ./nginx/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=duranc_dockergen
      - DEFAULT_EMAIL=img@duranc.com
      - DHPARAM_GENERATION=false
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    container_name: duranc_ssl
    networks:
      duranc-network:
        ipv4_address: 18.19.0.3

networks:
  duranc-network:
    external: true

volumes:
  vhost:
    external:
      name: virtual-hosts
  html:
    external:
      name: html-files
```
When I run ```docker-compose -f docker-compose-loadbalancer.yml up --build``` for the first time, I received below messages in logs and web page _**https://dockerssl.duranc.com**_ did NOT load:

```
duranc_dockergen | 2020/10/04 19:27:03 Generated '/etc/nginx/conf.d/default.conf' from 7 containers
duranc_dockergen | 2020/10/04 19:27:03 Sending container 'nginx' signal '1'
duranc_dockergen | 2020/10/04 19:27:03 Error sending signal to container: No such container: nginx
duranc_dockergen | 2020/10/04 19:27:03 Watching docker events
duranc_dockergen | 2020/10/04 19:27:03 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
duranc_dockergen | 2020/10/04 19:27:06 Received event start for container d1ac5697d3ba
duranc_dockergen | 2020/10/04 19:27:06 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
duranc_ssl     | Info: Custom Diffie-Hellman group found, generation skipped.
duranc_ssl     | Reloading nginx docker-gen (using separate container duranc_dockergen)...
duranc_dockergen | 2020/10/04 19:27:07 Received signal: hangup
duranc_dockergen | 2020/10/04 19:27:07 Received signal: hangup
duranc_ssl     | Reloading nginx (using separate container d1ac5697d3ba7d0630ee821fe1612de7a40e7d757afd644924ea8654b504aaf0
duranc_ssl     | f456448794d1a41dab41982b5505a9554844c772b14f40d0499c9087dfb0f0a6)...
duranc_dockergen | 2020/10/04 19:27:07 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
duranc_ssl     | 2020/10/04 19:27:07 Generated '/app/letsencrypt_service_data' from 8 containers
duranc_ssl     | 2020/10/04 19:27:07 Running '/app/signal_le_service'
duranc_ssl     | 2020/10/04 19:27:07 Watching docker events
duranc_ssl     | 2020/10/04 19:27:07 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
duranc_ssl     | 2020/10/04 19:27:07 Error: nginx-proxy container d1ac5697d3ba7d0630ee821fe1612de7a40e7d757afd644924ea8654b504aaf0
duranc_ssl     | f456448794d1a41dab41982b5505a9554844c772b14f40d0499c9087dfb0f0a6 isn't running.
duranc_ssl     | Sleep for 3600s
```
I stopped the containers and started once again, then below error message disappeared and everything started working... **Wanted to understand why are we getting below error messages for the first time and everything starts working after restart?**
```
duranc_dockergen | 2020/10/04 19:27:03 Sending container 'nginx' signal '1'
duranc_dockergen | 2020/10/04 19:27:03 Error sending signal to container: No such container: nginx
```

Also, can you please let us know why are we receiving below errors in logs...
```
duranc_ssl     | 2020/10/04 19:27:07 Error: nginx-proxy container d1ac5697d3ba7d0630ee821fe1612de7a40e7d757afd644924ea8654b504aaf0
duranc_ssl     | f456448794d1a41dab41982b5505a9554844c772b14f40d0499c9087dfb0f0a6 isn't running.
```
Thank you and appreciate your support regarding this!
