### ISSUE TITLE
Proxy pass 404 error

### ISSUE THREAD

**Issue by Quadriphobs1** [nginx-proxy/nginx-proxy#1507]
I have been trying to do this for few days now but its not working.
How do I proxy pass from two different apps. I have one running on its own nginx-proxxy as `api.loc` and another one running as `*.frontend.loc`, I want to `proxy_pass` from frontend on any `/api/***` request to `api.loc/***`.
I have tried several approach but it always returns `404` error and not even sending out any request to `api.loc`

my `vhost.d` file contains

```
proxy_http_version 1.1;
proxy_set_header Connection "";

location /api/client-settings {
    proxy_pass http://api.loc/client-settings;
    proxy_set_header Host $host;
}

location ~ ^/api/(.*)$ {
  proxy_pass http://api.loc/$1$is_args$args;
  rewrite ^\/api\/(.*) /$1 break;
  proxy_set_header Host $host;
}
```

and my `docker-compose.yml`

```

  app-nginx:
    image: jwilder/nginx-proxy:alpine
    restart: always
    ports:
      - "90:80"
    networks:
      - ui-network
    environment:
      - VIRTUAL_HOST=frontend.loc
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./vhost.d:/etc/nginx/vhost.d/api.loc_location

networks:
  ui-network:
    driver: bridge
  default:
    external:
      name: app-network

```
