### ISSUE TITLE
VIRTUAL_PORt don´t work

### ISSUE THREAD

**Issue by leonardoborlot** [nginx-proxy/nginx-proxy#1515]
# Hi guys.

I´ve try run this docker compose stack: 

> n8n:
>   container_name: n8n
>   image: n8nio/n8n
>   volumes:
>      - n8n:/root/.n8n    
>      - /var/run/docker.sock:/var/run/docker.sock
>   restart: always
>   environment:
>       N8N_PORT: "5678"
>       VIRTUAL_HOST: n8n.leoborlot.com.br
>       VIRTUAL_PORT: 5678
>       LETSENCRYPT_HOST: n8n.leoborlot.com.br
>       LETSENCRYPT_EMAIL: leonardoborlot@gmail.com

But I can´t access the aplication when I access the domain, it return: "Error 521. Web server is down."
This aplication runn on the 5678 port? I have another aplications running on this server on the 80 port, they are running very well.
This is the right method to use the VIRTUAL_PORT?

**Comment by vidurb** [comment]
Can you add the part of your docker-compose with the `nginx-proxy` container also please? Might help.

**Comment by leonardoborlot** [comment]
This is my compose for Nginx + Letsencrypt

```

# Nginx Reverse Proxy
docker run --detach \
    --restart always \
    --name nginx-proxy \
    --network=Public \
    --publish 80:80 \
    --publish 443:443 \
    --volume nginx_certs:/etc/nginx/certs \
    --volume nginx_vhost:/etc/nginx/vhost.d \
    --volume nginx_usr:/usr/share/nginx/html \
    --volume nginx_dhparam:/etc/nginx/dhparam \
    --volume /var/run/docker.sock:/tmp/docker.sock:ro \
    jwilder/nginx-proxy

docker run --detach \
    --name letsencrypt \
    --restart always \
    --network=Public \
    --volumes-from nginx-proxy \
    --volume /var/run/docker.sock:/var/run/docker.sock:ro \
    jrcs/letsencrypt-nginx-proxy-companion 
```

**Comment by vidurb** [comment]
That configuration looks fine to me, but I'm no expert. I can confirm that setting the `VIRTUAL_PORT` environment variable is the correct way to indicate which port should be proxied. 521 errors are only returned from Cloudflare - have you tried accessing the site without the Cloudflare proxy disabled to eliminate the possibility of something on the Cloudflare end causing the problem? Also, have you checked the logs for the nginx-proxy container to see whether it is receiving any connections from Cloudflare at all? (`docker-compose logs -f <servicename>`)

**Comment by ChaseGuru** [comment]
I also have this issue:
docker-compose:
```
...
    proxy:
        image: jwilder/nginx-proxy:alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./certs:/etc/nginx/certs
            - ./hosts:/etc/nginx/vhost.d
            - ./custom.conf:/etc/nginx/conf.d/custom.conf
            - ./html:/usr/share/nginx/html
        labels:
            - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    api:
        build:
            context: ./
            dockerfile: Dockerfile
        env_file: .env
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=8000
...
```

My .env:
```
VIRTUAL_HOST=staging-api.MYDOMAIN.com,api.MYDOMAIN.com
VIRTUAL_PORT=8000
LETSENCRYPT_HOST=staging-api.MYDOMAIN.com,api.MYDOMAIN.com
DJANGO_ALLOWED_HOST=staging-api.MYDOMAIN.com,api.MYDOMAIN.com
```

After running:
```
docker-compose exec proxy bash
apk add vim
vim /etc/nginx/conf.d/default.conf
```
I see the following:
```
# staging-api.MYDOMAIN.com
upstream staging-api.MYDOMAIN.com {
				## Can be connected with "api_default" network
		# api_api_1
			server 172.30.0.3 down;
}
# api.MYDOMAIN.com
upstream api.MYDOMAIN.com {
				## Can be connected with "api_default" network
		# api_api_1
			server 172.30.0.3 down;
}
```

I have to remove the down and add the port in both locations every time I down up.
