### ISSUE TITLE
Two proxied containers, getting sent to random host on each request

### ISSUE THREAD

**Issue by tomtko** [nginx-proxy/nginx-proxy#1516]
Hi, so I've setup two nginx containers also with the letsencrypt companion, when I have one nginx container started it works fine, when I start the second, I can send a request to for example domain1 and it will route me to either domain1 or domain2 seemingly randomly, same goes when trying to request domain2, i can be sent to domain1 or domain2 (but the url stays the same) after every request.

The whoami proxy works flawlessly though, not exactly sure what the issue is.

Simple docker-compose.yml:
```
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local
```

Generated config: https://pastebin.com/gbqjpbEQ
