### ISSUE TITLE
Unable to set up https-connections (Error 502) with self-signed certificates

### ISSUE THREAD

**Issue by AlGr-IH** [nginx-proxy/nginx-proxy#1520]
Hello,
I am trying to set up a nginx reverse proxy on a CentOS 8 server for managing the routing (within our internal network) to single services that run in docker-containers on this CentOS 8 server. I tried to use the jwilder/nginx-proxy image and the jwilder/nginx-proxy:latest for that purpose. The connection should be established via https using self-signed certificates. If I try to reach a service of a portainer container that runs on the server I get the following behavior:
Console-command:
```console
curl https://portainer.mydomain.com/
```
Console-output:
```console
 <html>
 <head><title>502 Bad Gateway</title></head>
 <body>
 <center><h1>502 Bad Gateway</h1></center>
 <hr><center>nginx/1.17.6</center>
 </body>
 </html>
```
nginx-server-log-output:
```
nginx.1    | 2020/10/30 11:09:40 [error] 115#115: *2611 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.188.89, server: portainer.mydomain.com, request: "GET / HTTP/2.0", upstream: "https://172.23.0.3:9000/", host: "portainer.mydomain.com"
nginx.1    | portainer.mydomain.com 192.168.188.89 - - [30/Oct/2020:11:09:40 +0000] "GET / HTTP/2.0" 502 157 "-" "curl/7.64.1"
```

 or when trying to use a http-connection:
Console command:
```console
 curl http://portainer.mydomain.com/
```
Console-output:
```console
 <html>
 <head><title>301 Moved Permanently</title></head>
 <body>
 <center><h1>301 Moved Permanently</h1></center>
 <hr><center>nginx/1.17.6</center>
 </body>
 </html>
```

# Container Setup

The nginx-container is started with the following docker-compose.yml file:

```
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/pki/tls/certs:/etc/nginx/certs
    networks:
      - exposed

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local

networks:
  exposed:
    external:
      name: exposed
```
The portainer-container is set up with the following docker-compose.yml file:

```
version: '2'
  
services:
  portainer:
    image: portainer/portainer
    container_name: portainer-composed
    command: --ssl --sslcert /certs/portainer.mydomain.com.crt --sslkey /certs/portainer.mydomain.com.key
    restart: always
    expose:
      - "9000"
    ports:
      - 9000:9000
        #- 8000:8000
    environment:
      - VIRTUAL_HOST=portainer.mydomain.com
      - VIRTUAL_PORT=9000
      - VIRTUAL_PROTO=https
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /media/dataserver/containerData/portainer_data:/data
      - /etc/pki/tls/certs:/certs
    networks:
      - exposed

networks:
  exposed:
    external:
      name: exposed
```
# nginx-configuration
I did not make any manual nginx-configuration. The nginx-proxy container creates the following nginx-configuraion file (located in `/etc/nginx/conf.d/default.conf` within the nginx-proxy container filesystem):

```
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Apply fix for very long server names
server_names_hash_bucket_size 128;
# Default dhparam
ssl_dhparam /etc/nginx/dhparam/dhparam.pem;
# Set appropriate X-Forwarded-Ssl header
map $scheme $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_ciphers #deleted before publishing
		ssl_prefer_server_ciphers off;
resolver 127.0.0.11;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
# portainer.mydomein.com
upstream portainer.mydomain.com {
				## Can be connected with "exposed" network
			# portainer-composed
			server 172.23.0.3:9000;
}
server {
	server_name portainer.mydomain.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	# Do not HTTPS redirect Let'sEncrypt ACME challenge
	location /.well-known/acme-challenge/ {
		auth_basic off;
		allow all;
		root /usr/share/nginx/html;
		try_files $uri =404;
		break;
	}
	location / {
		return 301 https://$host$request_uri;
	}
}
server {
	server_name portainer.mydomain.com;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/portainer.mydomain.com.crt;
	ssl_certificate_key /etc/nginx/certs/portainer.mydomain.com.key;
	add_header Strict-Transport-Security "max-age=31536000" always;
	location / {
		proxy_pass https://portainer.mydomain.com;
	}
}
# whoami.local
upstream whoami.local {
				# Cannot connect to network of this container
				server 127.0.0.1 down;
}
server {
	server_name whoami.local;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://whoami.local;
	}
}

```
# SSL-certificates:

The ssl-certificates (portainer.mydomain.com.crt, portainer.mydomain.com.key, Root-CA.crt (used for signing the portainer certificate)) are located in the folder `/etc/pki/tls/certs/`

Can somebody tell me what I am doing wrong here?
Thanks in advance.
Best regards
