### ISSUE TITLE
Containers with overloaded virtual hosts do not work as expected

### ISSUE THREAD

**Issue by cmargroff** [nginx-proxy/nginx-proxy#1528]
### The environment

```
version: "3.4"

services:
  ...
  wp_test:
    image: wordpress:5.5
    expose:
      - "80"
    volumes:
      - "./htdocs/wp-content/:/var/www/html/wp-content/"
    environment:
      VIRTUAL_HOST: test.local.dev
      ...
    container_name: test_wp
  wpack_test:
    image: "node:10"
    depends_on:
      - wp_test
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./htdocs/wp-content/themes/test:/home/node/app
    expose:
      - "8080"
      - "8880"
    environment:
      VIRTUAL_HOST: test.local.dev
      VIRTUAL_PORT: 8080
    command: "npm start"
    container_name: test_wpack

networks:
  default:
    external:
      name: nginx-proxy
```

### The Issue

What I expect is to now have a domain test.local.dev with port 80 hosting wordpress and port 8080 hosting wpack for browser sync, it seems as though nginx-proxy disregards the second rule. I believe this is a issue not only with overloading virtual hosts but also with how external ports are passed from a container as it seems that VIRTUAL_PORT only means what port to bind on the upstream.

### Suggestion

nginx-proxy needs a way to serve containers on specialized ports for services. Looking through the template file it seems that Listen rules will only ever be bound to 80 or 443 which is limited.

I suggest there be an environment variable that defines a containers public ports perhaps like this:
```
services:
  custom_server:
    environment:
      LISTEN_PORTS:
        - "8080"
        - "8880:8880"
      # or
      LISTEN_PORTS: "exposed"
```
Honestly this is just the ports key for a container but it allows the container to be passed through nginx so they can be applied to a host name and multiple custom applications on the same port can be hosted.
