### ISSUE TITLE
Is it possible to use nginx-proxy without subdomains?

### ISSUE THREAD

**Issue by HugoSPT** [nginx-proxy/nginx-proxy#1531]
Hi,

Can't access the google groups so will make the question here.

Is it possible to setup nginx-proxy to work without subdomains?

So instead of `branch-a.domain.com`, `branch-a.domain.com` we have `domain.com/branch-a/`, `domain.com/branch-b/`. Is it possible to achieve?

The reason behind this is because in my use case I cannot have wildcards in cname so I need to register alias before hand which is not convenient/doable when doing branch based deployments.

Thank you for your time!

**Comment by scriptcoded** [comment]
Hey! You can do this using the custom config feature of nginx-proxy (https://github.com/nginx-proxy/nginx-proxy#custom-nginx-configuration).

Create a file, say `proxy.conf`:
```nginx
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;

# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";

server {
  server_name domain.com;

  location /branch-a {
    proxy_pass http://branch-a:8080;
  }

  location /branch-b {
    proxy_pass http://branch-b:8080;
  }
}
```

And then include it in your `docker-compose.yml` (assuming you use compose):
```yml
services:
  branch-a:
    image: example/image
    restart: always
  branch-b:
    image: example/image
    restart: always
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy.conf:/etc/nginx/proxy.conf:ro
```
