### ISSUE TITLE
nginx-proxy                | nginx.1    | 2020/12/17 05:34:04 [error] 101#101: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 49.36.35.208, server: rkfootwear.in, request: "GET / HTTP/2.0", upstream: "http://172.20.0.2:8000/", host: "rkfootwear.in"

### ISSUE THREAD

**Issue by abhimal** [nginx-proxy/nginx-proxy#1543]
Using AWS EC2 
Logs

```
nginx-proxy                | nginx.1    | rkfootwear.in 49.36.35.208 - - [17/Dec/2020:05:34:00 +0000] "GET / HTTP/1.1" 301 169 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
nginx-proxy                | nginx.1    | 2020/12/17 05:34:04 [error] 101#101: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 49.36.35.208, server: rkfootwear.in, request: "GET / HTTP/2.0", upstream: "http://172.20.0.2:8000/", host: "rkfootwear.in"
nginx-proxy                | nginx.1    | rkfootwear.in 49.36.35.208 - - [17/Dec/2020:05:34:04 +0000] "GET / HTTP/2.0" 502 559 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
nginx-proxy                | nginx.1    | 2020/12/17 05:34:05 [error] 101#101: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 49.36.35.208, server: rkfootwear.in, request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.20.0.2:8000/favicon.ico", host: "rkfootwear.in", referrer: "https://rkfootwear.in/"
nginx-proxy                | nginx.1    | rkfootwear.in 49.36.35.208 - - [17/Dec/2020:05:34:05 +0000] "GET /favicon.ico HTTP/2.0" 502 559 "https://rkfootwear.in/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
nginx-proxy                | nginx.1    | 2020/12/17 05:34:06 [error] 101#101: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 49.36.35.208, server: rkfootwear.in, request: "GET / HTTP/2.0", upstream: "http://172.20.0.2:8000/", host: "rkfootwear.in"
nginx-proxy                | nginx.1    | rkfootwear.in 49.36.35.208 - - [17/Dec/2020:05:34:06 +0000] "GET / HTTP/2.0" 502 559 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
nginx-proxy                | nginx.1    | 2020/12/17 05:34:06 [error] 101#101: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 49.36.35.208, server: rkfootwear.in, request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.20.0.2:8000/favicon.ico", host: "rkfootwear.in", referrer: "https://rkfootwear.in/"
nginx-proxy                | nginx.1    | rkfootwear.in 49.36.35.208 - - [17/Dec/2020:05:34:06 +0000] "GET /favicon.ico HTTP/2.0" 502 559 "https://rkfootwear.in/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
nginx-proxy                | nginx.1    | 2020/12/17 05:34:48 [error] 101#101: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 217.27.176.227, server: rkfootwear.in, request: "HEAD /.git/config HTTP/1.1", upstream: "http://172.20.0.2:8000/.git/config", host: "rkfootwear.in"
nginx-proxy                | nginx.1    | rkfootwear.in 217.27.176.227 - - [17/Dec/2020:05:34:48 +0000] "HEAD /.git/config HTTP/1.1" 502 0 "-" "python-requests/2.12.4"
```
thsi is my yml fiel docker-compose.staging.yml

```
version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn buznestBackend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - .env.staging
  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - .env.staging.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
    depends_on:
      - nginx-proxy

volumes:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
```
my nginx directory look like this

└── nginx
    ├── Dockerfile
    ├── custom.conf
    └── vhost.d
        └── default

* inside vhost.d directory add a file called default file
```
location /staticfiles/ {
  alias /home/app/web/staticfiles/;
  add_header Access-Control-Allow-Origin *;
}

location /mediafiles/ {
  alias /home/app/web/mediafiles/;
  add_header Access-Control-Allow-Origin *;
}
```
* Dockerfile
```
FROM jwilder/nginx-proxy
COPY vhost.d/default /etc/nginx/vhost.d/default
COPY custom.conf /etc/nginx/conf.d/custom.conf
```
* custom.conf
`client_max_body_size 10M;`
