### ISSUE TITLE
nginx-proxy gitlab container

### ISSUE THREAD

**Issue by Pezhvak** [nginx-proxy/nginx-proxy#1545]
not sure about @Srinivasa381224's problem but i can't get gitlab to work with nginx-proxy as well, it gives me 502 Bad Gateway all the time, here's what i have tried:

```
web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
#  hostname: 'my.domain.tld'
  container_name: gitlab
  environment:
    VIRTUAL_HOST:my.domain.tld
    hsts: 0
    HTTPS_METHOD: noredirect
    LETSENCRYPT_HOST: my.domain.tld
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://my.domain.tld'
      #registry_external_url 'https://registry.domain.tld'
      #nginx['listen_port'] = 80
      #nginx['listen_https'] = false
      letsencrypt['enable'] = true
      letsencrypt['contact_emails'] = ['support@my.domain']
      gitlab_rails['gitlab_shell_ssh_port'] = 2224
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    #- '80:80'
    #- '443:443'
    - '2224:22'
    - '5050:5050'
  volumes:
    - '$GITLAB_HOME/config:/etc/gitlab'
    - '$GITLAB_HOME/logs:/var/log/gitlab'
    - '$GITLAB_HOME/data:/var/opt/gitlab'
```

as you can see i even tried to turn off https inside the container but it didn't work so i commented it out.

**Comment by Pezhvak** [comment]
I've just realized upstream is not generated for gitlab:

```
upstream gitlab.my.domain {
                                # Cannot connect to network of this container
                                server 127.0.0.1 down;
}
```

any suggestion how to fix it?

**Comment by kiddhustle** [comment]
I had this problem recently.

The problem in my place was caused by this line:

`external_url 'https://my.domain.tld`

Drop the the `https` and use `http` in config. From what I understand internal communication isn't encrypted so it won't work.

Now however I am getting a problem where the LETSENCRYPT certificate is not working. The issuer is showing as:

`letsencrypt-nginx-proxy-companion`


Which isn't right. I think I got the setup into a bad state whilst changing configuration on now I am not sure how to get it back into a good place.

When I try to `force_renew` the script is stuck at the problem domain. Not sure how to proceed at this point.

Let me know if you have better luck.

**Comment by kiddhustle** [comment]
Also bear in mind that although the container may be running, gitlab won't necessarily be available right away.

It may take a couple of minutes for the service to be ready and accessible.

You might have to log into the container (NGINX proxy) shell and run the `start.sh` script to update certificates again.

**Comment by Pezhvak** [comment]
just to make it clear for anyone else i solved my issue after fixing my network between docker-compose files. here is my docker-compose file for nginx-proxy (and certificate):

**Comment by Pezhvak** [comment]
I solved my issue after fixing my network between my docker-compose files. here is my docker-compose file for nginx-proxy (and certificate):

```
version: '2'

services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        restart: always
        container_name: nginx-proxy
        networks:
            - web
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - conf:/etc/nginx/conf.d
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - dhparam:/etc/nginx/dhparam
            - certs:/etc/nginx/certs:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro

    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: always
        container_name: nginx-proxy-le
        networks:
            - web
        volumes_from:
            - nginx-proxy
        volumes:
            - certs:/etc/nginx/certs:rw
            - acme:/etc/acme.sh
            - /var/run/docker.sock:/var/run/docker.sock:ro

    gitlab:
        image: 'gitlab/gitlab-ce:latest'
        restart: always
        hostname: 'gitlab.domain.tld'
        container_name: gitlab
        networks:
            - web
        environment:
            VIRTUAL_HOST: gitlab.domain.tld,registry.domain.tld
            LETSENCRYPT_HOST: gitlab.domain.tld,registry.domain.tld
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'https://gitlab.domain.tld'
                registry_external_url 'https://registry.domain.tld'
                nginx['listen_port'] = 80
                nginx['listen_https'] = false
                registry_nginx['listen_port'] = 80
                registry_nginx['listen_https'] = false
                nginx['proxy_set_headers'] = {  "X-Forwarded-Proto" => "https", "X-Forwarded-Ssl" => "on" }
                letsencrypt['enable'] = true
                letsencrypt['contact_emails'] = ['support@echosoft.ir']
                nginx['client_max_body_size'] = "0"
                # Add any other gitlab.rb configuration here, each on its own line
                manage_accounts['enable']=true
                user['username'] = 'git'
                user['group'] = 'git'
                user['uid'] = 1234
                user['gid'] = 1234

        ports:
            - '5050:5050'
        volumes:
            - '$GITLAB_HOME/config:/etc/gitlab'
            - '$GITLAB_HOME/logs:/var/log/gitlab'
            - '$GITLAB_HOME/data:/var/opt/gitlab'

networks:
    default:
        external:
            name: nginx-proxy
    web:
        external:
            name: web

volumes:
    conf:
    vhost:
    html:
    dhparam:
    certs:
    acme:
```

Here is an [article](https://pezhvak.medium.com/how-to-spin-up-gitlab-on-docker-reusable-host-ports-2cfd220c74b0) I wrote to explain everything needed to be known
