### ISSUE TITLE
Nginx is not working

### ISSUE THREAD

**Issue by vamsiduranc** [nginx-proxy/nginx-proxy#1547]
Dear @tkw1536

Wishing you a happy new year in advance!

Some how I am not able make web page work with below configuration. Can you please let us know what might be the issue?

```
version: "3"
services:
  nginx:
    image: index.docker.io/durancai/staging-nginx:latest
    container_name: duranc_nginx
    restart: always
    ports:
      - 80:80
      - 443:443
      - 1935:1935
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - html:/var/www/html
      - acme:/etc/acme.sh
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      duranc-network:
        ipv4_address: 18.19.0.2
  
  dockergen:
    image: jwilder/docker-gen
    container_name: duranc_dockergen
    command: notify-sighup duranc_nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - nginx
    volumes:      
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      duranc-network:
        ipv4_address: 18.19.0.8

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: duranc_ssl
    restart: always
    depends_on:
      - nginx
      - dockergen
    volumes:      
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=duranc_dockergen
      - NGINX_PROXY_CONTAINER=duranc_nginx
      - DEFAULT_EMAIL=img@duranc.com
      - DHPARAM_GENERATION=false
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      duranc-network:
        ipv4_address: 18.19.0.3

  mongodb:
    image: index.docker.io/durancai/staging-durancdb:latest
    container_name: duranc_db
    depends_on:
      - nginx
      - dockergen
      - letsencrypt
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - db_data:/data/db
    command: mongod
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      duranc-network:
        ipv4_address: 18.19.0.4

  portal:
    image: index.docker.io/durancai/staging-portal:latest
    container_name: duranc_portal
    depends_on:
      - nginx
      - dockergen
      - letsencrypt
      - mongodb
    ports:
       - 3000:3000
    restart: unless-stopped
    command: /bin/sh -c "/tmp/start.sh && exec /usr/bin/supervisord"
    volumes:
      - portal_data:/persistent:rw
    environment:
        DEFAULT_HOST: dockertest.duranc.com
        WIKI_ADMIN_EMAIL: img@duranc.com
        VIRTUAL_HOST: dockertest.duranc.com
        VIRTUAL_PORT: 3000
        LETSENCRYPT_HOST: dockertest.duranc.com
        LETSENCRYPT_EMAIL: img@duranc.com
        PORTAL_URL: dockertest.duranc.com
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      duranc-network:
        ipv4_address: 18.19.0.5
   
  autoupdater:
    image: containrrr/watchtower
    container_name: duranc_autoupdater
    depends_on:
      - nginx
      - dockergen
      - letsencrypt
      - mongodb
      - portal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/auth.json:/config.json:ro
    ports:
      - 9080:8080
    command: watchtower duranc_nginx duranc_db duranc_portal --schedule "0 0 0 * * *" --cleanup --debug
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      duranc-network:
        ipv4_address: 18.19.0.10

volumes:
  vhost:
    external:
      name: stg-virtual-hosts
  conf:
    external:
      name: stg-virtual-conf
  certs:
    external:
      name: stg-virtual-certs
  acme:
    external:
      name: stg-virtual-acme
  html:
    external:
      name: stg-html-files
  db_data:
    external:
      name: stg-duranc-db
  portal_data:
    external:
      name: stg-duranc-portal

networks:
  duranc-network:
    external: true
```

Logs:
````
duranc_ssl     | {"message":"Cannot kill container: duranc_dockergen: Container 1ea16d9654c7105295605205ca826f4697346988a02cea035f16ea848eb2f29b is not running"}
duranc_ssl     | Reloading nginx (using separate container 3b53bf3bede9b7631097711b0317df2daa74372896b6ffd7276046c71a875460)...
duranc_ssl     | Creating/renewal dockertest.duranc.com certificates... (dockertest.duranc.com)
duranc_ssl     | [Thu Dec 31 15:44:37 UTC 2020] Using CA: https://acme-v02.api.letsencrypt.org/directory
duranc_ssl     | [Thu Dec 31 15:44:37 UTC 2020] Creating domain key
duranc_ssl     | [Thu Dec 31 15:44:38 UTC 2020] The domain key is here: /etc/acme.sh/img@duranc.com/dockertest.duranc.com/dockertest.duranc.com.key
duranc_ssl     | [Thu Dec 31 15:44:38 UTC 2020] Single domain='dockertest.duranc.com'
duranc_ssl     | [Thu Dec 31 15:44:39 UTC 2020] Getting domain auth token for each domain
duranc_ssl     | 2020/12/31 15:44:39 Received event start for container 2fd56ea4047f
duranc_autoupdater | time="2020-12-31T15:44:38Z" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
duranc_autoupdater | time="2020-12-31T15:44:39Z" level=debug msg="Retrieving running containers"
duranc_autoupdater | time="2020-12-31T15:44:39Z" level=debug msg="There are no additional watchtower containers"
duranc_autoupdater | time="2020-12-31T15:44:39Z" level=info msg="Starting Watchtower and scheduling first run: 2021-01-01 00:00:00 +0000 UTC"
duranc_ssl     | [Thu Dec 31 15:44:42 UTC 2020] Getting webroot for domain='dockertest.duranc.com'
duranc_ssl     | [Thu Dec 31 15:44:42 UTC 2020] Verifying: dockertest.duranc.com
duranc_ssl     | 2020/12/31 15:44:44 Debounce minTimer fired
duranc_ssl     | 2020/12/31 15:44:44 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
duranc_ssl     | [Thu Dec 31 15:44:47 UTC 2020] dockertest.duranc.com:Verify error:Fetching http://dockertest.duranc.com/.well-known/acme-challenge/T4mgTGhjvkOWTrFxVS6kFb84qY4W8Sa_V4h4uCEQMts: Connection refused
duranc_ssl     | [Thu Dec 31 15:44:47 UTC 2020] Please check log file for more details: /dev/null
duranc_ssl     | Sleep for 3600s
```
