### ISSUE TITLE
Bad Gateway 502

### ISSUE THREAD

**Issue by jonit-dev** [nginx-proxy/nginx-proxy#1570]
Hey folks, I've got my SSL setup, but no matter what I do on docker-compose, I always end up getting a nginx error 502 (Bad Gateway)

Here's my project root docker-compose.yml for analysis

```
version: "3"
services:
  psa-api:
    container_name: psa-api
    restart: always
    build: .
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    env_file: .env
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      FORCE_COLOR: "true"
      VIRTUAL_PORT: ${SERVER_PORT}
      VIRTUAL_HOST: api.blueshipapp.com
      LETSENCRYPT_HOST: api.blueshipapp.com
      LETSENCRYPT_EMAIL: joaopaulofurtado@live.com
    links:
      - psa-db
    depends_on:
      - psa-db
    networks:
      - psa-network

  psa-db:
    container_name: psa-db
    image: mongo
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./docker_scripts/:/docker-entrypoint-initdb.d
    ports:
      - "$MONGO_PORT:$MONGO_PORT"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - psa-network

  psa-web:
    container_name: psa-web
    image: nginx:alpine
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=blueshipapp.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=blueshipapp.com
      - LETSENCRYPT_EMAIL=joaopaulofurtado@live.com
    volumes:
      - /home/olex/static/files:/usr/share/nginx/html:ro
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx-proxy
  psa-network:
    driver: bridge

```

And this is my nginx-proxy docker-compose config.

```
version: "3"

services:
  nginx:
    image: nginx:1.13.1
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"

  dockergen:
    image: jwilder/docker-gen:0.7.3
    container_name: nginx-proxy-gen
    depends_on:
      - nginx
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    depends_on:
      - nginx
      - dockergen
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      NGINX_DOCKER_GEN_CONTAINER: nginx-proxy-gen
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  conf:
  vhost:
  html:
  certs:

# Do not forget to 'docker network create nginx-proxy' before launch, and to add '--network nginx-proxy' to proxied containers.

networks:
  default:
    external:
      name: nginx-proxy
```

I honestly have no idea what to do. 

letsencrypt-nginx-proxy-companion image version: 1.13.1
-----------------

Please provide the container version that should be printed to the first line of log at container startup:
```
Info: running letsencrypt-nginx-proxy-companion version v2.0.2-29-gdf13071
``` 
Please provide the configuration (either command line, compose file, or other) of your nginx-proxy stack and your proxied container(s).

You can obfuscate information you want to keep private (and should obfuscate configuration secrets) such as domain(s) and/or email adress(es), but other than that please provide the full configurations and not the just snippets of the parts that seem relevants to you.

Containers logs
-----------------

 

```
nginx-proxy    | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-proxy    | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-proxy    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-proxy    | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-proxy    | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
nginx-proxy    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-proxy    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-proxy    | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx-proxy-gen | 2021/03/21 07:07:29 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx-proxy-gen | 2021/03/21 07:07:29 Watching docker events
nginx-proxy-gen | 2021/03/21 07:07:29 Error inspecting container: c637fe6b14dcf4c3f1a4be4807547f123aa8d1d062c3c95037cc93326aa5e88e: No such container: c637fe6b14dcf4c3f1a4be4807547f123aa8d1d062c3c95037cc93326aa5e88e
nginx-proxy-gen | 2021/03/21 07:07:29 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx-proxy-gen | 2021/03/21 07:07:32 Received event start for container c637fe6b14dc
nginx-proxy-gen | 2021/03/21 07:07:32 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx-proxy-le | Info: running letsencrypt-nginx-proxy-companion version v2.0.2-29-gdf13071
nginx-proxy-le | Info: Custom Diffie-Hellman group found, generation skipped.
nginx-proxy-le | Reloading nginx docker-gen (using separate container 36336af4876ca81f5809aa34848668a929b32b07fd712480cfbda6e6d24a3aa7)...
nginx-proxy-gen | 2021/03/21 07:07:33 Received signal: hangup
nginx-proxy-gen | 2021/03/21 07:07:33 Received signal: hangup
nginx-proxy-le | Reloading nginx (using separate container nginx-proxy)...
nginx-proxy-gen | 2021/03/21 07:07:33 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx-proxy-le | 2021/03/21 07:07:33 Generated '/app/letsencrypt_service_data' from 5 containers
nginx-proxy-le | 2021/03/21 07:07:33 Running '/app/signal_le_service'
nginx-proxy-le | 2021/03/21 07:07:33 Watching docker events
nginx-proxy-le | 2021/03/21 07:07:34 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
nginx-proxy-le | Reloading nginx docker-gen (using separate container 36336af4876ca81f5809aa34848668a929b32b07fd712480cfbda6e6d24a3aa7)...
nginx-proxy-gen | 2021/03/21 07:07:34 Received signal: hangup
nginx-proxy-gen | 2021/03/21 07:07:34 Received signal: hangup
nginx-proxy-le | Reloading nginx (using separate container nginx-proxy)...
nginx-proxy-le | Creating/renewal api.blueshipapp.com certificates... (api.blueshipapp.com)
nginx-proxy-gen | 2021/03/21 07:07:34 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx-proxy-le | [Sun Mar 21 07:07:35 UTC 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
nginx-proxy-le | [Sun Mar 21 07:07:35 UTC 2021] Creating domain key
nginx-proxy-le | [Sun Mar 21 07:07:37 UTC 2021] The domain key is here: /etc/acme.sh/joaopaulofurtado@live.com/api.blueshipapp.com/api.blueshipapp.com.key
nginx-proxy-le | [Sun Mar 21 07:07:37 UTC 2021] Single domain='api.blueshipapp.com'
nginx-proxy-le | [Sun Mar 21 07:07:37 UTC 2021] Getting domain auth token for each domain
nginx-proxy-le | [Sun Mar 21 07:07:38 UTC 2021] Create new order error. Le_OrderFinalize not found. {
nginx-proxy-le |   "type": "urn:ietf:params:acme:error:rateLimited",
nginx-proxy-le |   "detail": "Error creating new order :: too many certificates already issued for exact set of domains: api.blueshipapp.com: see https://letsencrypt.org/docs/rate-limits/",
nginx-proxy-le |   "status": 429
nginx-proxy-le | }
nginx-proxy-le | [Sun Mar 21 07:07:38 UTC 2021] Please check log file for more details: /dev/null
nginx-proxy-le | Creating/renewal db.blueshipapp.com certificates... (db.blueshipapp.com)
nginx-proxy-le | [Sun Mar 21 07:07:39 UTC 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
nginx-proxy-le | [Sun Mar 21 07:07:39 UTC 2021] Creating domain key
nginx-proxy-le | [Sun Mar 21 07:07:43 UTC 2021] The domain key is here: /etc/acme.sh/joaopaulofurtado@live.com/db.blueshipapp.com/db.blueshipapp.com.key
nginx-proxy-le | [Sun Mar 21 07:07:43 UTC 2021] Single domain='db.blueshipapp.com'
nginx-proxy-le | [Sun Mar 21 07:07:43 UTC 2021] Getting domain auth token for each domain
nginx-proxy-le | [Sun Mar 21 07:07:44 UTC 2021] Create new order error. Le_OrderFinalize not found. {
nginx-proxy-le |   "type": "urn:ietf:params:acme:error:rateLimited",
nginx-proxy-le |   "detail": "Error creating new order :: too many certificates already issued for exact set of domains: db.blueshipapp.com: see https://letsencrypt.org/docs/rate-limits/",
nginx-proxy-le |   "status": 429
nginx-proxy-le | }
nginx-proxy-le | [Sun Mar 21 07:07:44 UTC 2021] Please check log file for more details: /dev/null
nginx-proxy-le | Sleep for 3600s
nginx-proxy    | api.blueshipapp.com 96.55.130.188 - - [21/Mar/2021:07:09:28 +0000] "GET / HTTP/1.1" 502 157 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0"
nginx-proxy    | 2021/03/21 07:09:28 [error] 41#41: *1 no live upstreams while connecting to upstream, client: 96.55.130.188, server: api.blueshipapp.com, request: "GET / HTTP/1.1", upstream: "http://api.blueshipapp.com/", host: "api.blueshipapp.com"
nginx-proxy    | 2021/03/21 07:09:29 [error] 41#41: *1 no live upstreams while connecting to upstream, client: 96.55.130.188, server: api.blueshipapp.com, request: "GET / HTTP/1.1", upstream: "http://api.blueshipapp.com/", host: "api.blueshipapp.com"
nginx-proxy    | api.blueshipapp.com 96.55.130.188 - - [21/Mar/2021:07:09:29 +0000] "GET / HTTP/1.1" 502 157 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0"
nginx-proxy    | api.blueshipapp.com 96.55.130.188 - - [21/Mar/2021:07:09:29 +0000] "GET / HTTP/1.1" 502 157 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0"
nginx-proxy    | 2021/03/21 07:09:29 [error] 41#41: *1 no live upstreams while connecting to upstream, client: 96.55.130.188, server: api.blueshipapp.com, request: "GET / HTTP/1.1", upstream: "http://api.blueshipapp.com/", host: "api.blueshipapp.com"
nginx-proxy    | api.blueshipapp.com 96.55.130.188 - - [21/Mar/2021:07:09:30 +0000] "GET / HTTP/1.1" 502 157 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0"
nginx-proxy    | 2021/03/21 07:09:30 [error] 41#41: *1 no live upstreams while connecting to upstream, client: 96.55.130.188, server: api.blueshipapp.com, request: "GET / HTTP/1.1", upstream: "http://api.blueshipapp.com/", host: "api.blueshipapp.com"
nginx-proxy    | 2021/03/21 07:09:30 [error] 41#41: *1 no live upstreams while connecting to upstream, client: 96.55.130.188, server: api.blueshipapp.com, request: "GET / HTTP/1.1", upstream: "http://api.blueshipapp.com/", host: "api.blueshipapp.com"
nginx-proxy    | api.blueshipapp.com 96.55.130.188 - - [21/Mar/2021:07:09:30 +0000] "GET / HTTP/1.1" 502 157 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0"
nginx-proxy    | api.blueshipapp.com 96.55.130.188 - - [21/Mar/2021:07:09:30 +0000] "GET / HTTP/1.1" 502 157 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0"
nginx-proxy    | 2021/03/21 07:09:30 [error] 41#41: *1 no live upstreams while connecting to upstream, client: 96.55.130.188, server: api.blueshipapp.com, request: "GET / HTTP/1.1", upstream: "http://api.blueshipapp.com/", host: "api.blueshipapp.com"
nginx-proxy    | api.blueshipapp.com 96.55.130.188 - - [21/Mar/2021:07:09:31 +0000] "GET / HTTP/1.1" 502 157 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0"
nginx-proxy    | 2021/03/21 07:09:31 [error] 41#41: *1 no live upstreams while connecting to upstream, client: 96.55.130.188, server: api.blueshipapp.com, request: "GET / HTTP/1.1", upstream: "http://api.blueshipapp.com/", host: "api.blueshipapp.com"
nginx-proxy    | api.blueshipapp.com 96.55.130.188 - - [21/Mar/2021:07:09:31 +0000] "GET / HTTP/1.1" 502 157 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0"
nginx-proxy    | 2021/03/21 07:09:31 [error] 41#41: *1 no live upstreams while connecting to upstream, client: 96.55.130.188, server: api.blueshipapp.com, request: "GET / HTTP/1.1", upstream: "http://api.blueshipapp.com/", host: "api.blueshipapp.com"
nginx-proxy    | 2021/03/21 07:09:31 [error] 41#41: *1 no live upstreams while connecting to upstream, client: 96.55.130.188, server: api.blueshipapp.com, request: "GET / HTTP/1.1", upstream: "http://api.blueshipapp.com/", host: "api.blueshipapp.com"
nginx-proxy    | api.blueshipapp.com 96.55.130.188 - - [21/Mar/2021:07:09:31 +0000] "GET / HTTP/1.1" 502 157 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 
```

PS: Yeah, I know that api.blueshipp.com is failing due to multiple successive requests that blocked me from generate new SSL for now. But the issue was happening EVEN when I got the SSL working.  I still encounter a Bad Gateway issue, anyways.

Docker host
-----------------

 - OS: Ubuntu 18
 - Docker version: output of `docker version`

```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:05 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```

Linux firewall output:
-----------------------------
```
Status: active

To                         Action      From
--                         ------      ----
OpenSSH                    ALLOW       Anywhere                  
443                        ALLOW       Anywhere                  
3000                       ALLOW       Anywhere                  
3002                       ALLOW       Anywhere                  
27017                      ALLOW       Anywhere                  
80                         ALLOW       Anywhere                  
OpenSSH (v6)               ALLOW       Anywhere (v6)             
443 (v6)                   ALLOW       Anywhere (v6)             
3000 (v6)                  ALLOW       Anywhere (v6)             
3002 (v6)                  ALLOW       Anywhere (v6)             
27017 (v6)                 ALLOW       Anywhere (v6)             
80 (v6)                    ALLOW       Anywhere (v6)   
```

Bonus Info
------------------

It works if I access http://api.blueshipapp.com:3002/ directly, without HTTPS.

docker ps
```
CONTAINER ID   IMAGE                                    COMMAND                  CREATED          STATUS          PORTS                                      NAMES
95f2f0cb5b54   api_psa-api                              "docker-entrypoint.s…"   19 minutes ago   Up 18 minutes   0.0.0.0:3002->3002/tcp                     psa-api
c969aec0672b   nginx:alpine                             "/docker-entrypoint.…"   23 minutes ago   Up 19 minutes   80/tcp, 443/tcp                            psa-web
436425488bde   mongo                                    "docker-entrypoint.s…"   25 minutes ago   Up 18 minutes   0.0.0.0:27017->27017/tcp                   psa-db
fd2745b1c0df   jrcs/letsencrypt-nginx-proxy-companion   "/bin/bash /app/entr…"   26 minutes ago   Up 10 minutes                                              nginx-proxy-le
f9ad2442b1a5   jwilder/docker-gen:0.7.3                 "/usr/local/bin/dock…"   26 minutes ago   Up 10 minutes                                              nginx-proxy-gen
4928cd7a89b2   nginx:1.13.1                             "nginx -g 'daemon of…"   26 minutes ago   Up 10 minutes   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   nginx-proxy

```
