### ISSUE TITLE
VIRUTAL_PORT and EXPOSE doesn't work as exspected

### ISSUE THREAD

**Issue by Tockra** [nginx-proxy/nginx-proxy#1575]
Hi Guys,

I want to use a docker container, which hosts his web server on port 8000 .
Now I want to reach this server via https with the subdomain scan.my-domain.com .

So the proxy shall route the content from port 80/443 to the docker container port 8000.

I tried this:
```
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: jonaswinkler/paperless-ng:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    expose:
        - "8000"
    environment:
        - VIRTUAL_HOST= scan.mydomain.com       
        - LETSENCRYPT_HOST=scan.mydomain.com     
        - LETSENCRYPT_EMAIL=mymail
        - VIRTUAL_PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
networks:
    proxy-tier:
        external:
            name: proxy-tier

```

But this doesn't work. What do I wrong?

T
