### ISSUE TITLE
Invalid docker network setup

### ISSUE THREAD

**Issue by aakldey** [nginx-proxy/nginx-proxy#1581]
Hey, I've been using nginx-proxy for past 4 years and I faced a problem one year ago.
So, I have a website running on localhost:9000 in docker and I set up nginx-proxy + let's encrypt container for SSL,
It was working fine but for last year I faced a bug.
Problem is that nginx-proxy generates such part of config in template:

```
{{ if .Network.IP }}
    server {{ .Network.IP }} down;
{{ else }}
    server 127.0.0.1 down;
{{ end }}
```

instead of 

```
{{ if .Network.IP }}
    server {{ .Network.IP }}:9000;
{{ else }}
    server 127.0.0.1 down;
{{ end }}
```

everytime I restart all of my containers I have to manually edit nginx template file inside nginx-proxy container to fix this problem

I use ansible to deploy containers and here is my config file:

```
---
- hosts: all
  user: ubuntu

  vars:
    project_name: "website"
    image: "something/website:latest"
    domain: "{{DOMAIN}}"

  tasks:
    - name: Create proxy directory
      file: path=/home/ubuntu/proxy state=directory

    - name: Copy nginx conf
      copy:
        src: proxy.conf
        dest: /home/ubuntu/proxy/{{DOMAIN}}
        owner: ubuntu
        group: ubuntu
        mode: 0644

    - name: Create certs directory
      file: path=certs state=directory

    - name: Application
      docker_container:
        name: "website"
        image: "{{ image }}"
        state: started
        pull: true
        restart_policy: always
        ports:
          - 9000:9000
        expose:
          - 9000
        env:
          MYSQL_LINK: "mysql"
          APP_ENV: "{{APP_ENV}}"
          VIRTUAL_HOST: "{{ domain }}"
          LETSENCRYPT_HOST: "{{ domain }}"
          LETSENCRYPT_EMAIL: email@gmail.com
        log_driver: json-file
        log_options:
          max-size: "10g"
          max-file: "4"
          labels: "website_logs"

    - name: Reverse Proxy
      docker_container:
        name: "nginx-proxy"
        image: "jwilder/nginx-proxy"
        state: started
        pull: true
        restart_policy: always
        labels: "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
        env:
          MAX_UPLOAD_SIZE: "2GB"
        volumes:
          - /root/certs:/etc/nginx/certs:rw
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - /usr/share/nginx/html
          - /home/ubuntu/proxy:/etc/nginx/vhost.d:rw
        ports:
          - 80:80
          - 443:443
        expose:
          - 443
          - 80
        log_driver: json-file
        log_options:
          max-size: "10g"
          max-file: "4"
          labels: "website_nginx"

    - name: Let's Encrypt
      docker_container:
        name: "nginx-letsencrypt"
        image: "jrcs/letsencrypt-nginx-proxy-companion"
        state: started
        pull: true
        restart_policy: always
        volumes:
          - /root/certs:/etc/nginx/certs:rw
          - /var/run/docker.sock:/var/run/docker.sock:ro
        volumes_from:
          - nginx-proxy

```

it was working fine before, but what's the problem now?

**Comment by tkw1536** [comment]
Not sure if this will fix your issue, but try setting "VIRTUAL_PORT=9000" on your application container. 

Also, as of letsencrypt companion version 2.x you should mount a volume at "/etc/acme.sh" in the LE container. See https://github.com/nginx-proxy/acme-companion#step-2---acme-companion.

**Comment by buchdag** [comment]
@aakldey afaik this happens when the `nginx-proxy` or `docker-gen` and proxied containers aren't sharing at least one docker network, or when the `docker-gen` process is unable to get its own ID (which in turn makes it unable to find it own network and lead to the same issue with docker networks).

Also, containers networking behaviour with Ansible is due to change / have changed recently, this might or might not come into play :

> Please note that the default value for `network_mode` will change from not specified (which is equal to `default`) to the name of the first network in `networks` if `networks` has at least one entry and `networks_cli_compatible` is `true`. You can change the behavior now by explicitly setting `network_mode` to the name of the first network in `networks`,  and remove this warning by setting `network_mode` to `default`. Please make sure that the value you set to `network_mode` equals the inspection result for existing containers, otherwise the  module will recreate them. You can find out the correct value by running "docker inspect --format '{{.HostConfig.NetworkMode}}' <container_name>". This feature will be removed from  community.docker in version 2.0.0. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

I'm using Ansible to deploy nginx-proxy too and I don't have any issue so far. Here is the role I use for a three container nginx-proxy :

```yaml
---
- name: Install git
  apt:
    name: git
  become: true
  tags: nginx-proxy

- name: Get docker-gen from GitHub
  git:
    repo: 'https://github.com/jwilder/docker-gen.git'
    dest: /home/someuser/git/docker-gen
  tags: nginx-proxy

- name: Build docker-gen from git sources
  docker_image:
    source: build
    build:
      path: /home/someuser/git/docker-gen
      pull: yes
    name: jwilder/docker-gen
    tag: git
  tags: nginx-proxy

- name: Create nginx-proxy directory
  file:
    path: /home/someuser/nginx-proxy
    state: directory
  tags: nginx-proxy

- name: Download nginx.tmpl
  get_url:
    url: https://raw.githubusercontent.com/jwilder/nginx-proxy/master/nginx.tmpl
    dest: /home/someuser/nginx-proxy/nginx.tmpl
  tags: nginx-proxy

- name: Create the nginx-proxy network
  docker_network:
    name: nginx-proxy
    driver_options:
      com.docker.network.bridge.name: nginx-proxy
  tags: nginx-proxy

- name: Create the nginx-proxy certs volume
  docker_volume:
    name: nginx-proxy-certs
  tags: nginx-proxy

- name: Create the nginx-proxy conf volume
  docker_volume:
    name: nginx-proxy-conf
  tags: nginx-proxy

- name: Create the nginx-proxy html volume
  docker_volume:
    name: nginx-proxy-html
  tags: nginx-proxy

- name: Create the nginx-proxy vhost volume
  docker_volume:
    name: nginx-proxy-vhost

- name: Create the nginx-proxy acme volume
  docker_volume:
    name: nginx-proxy-acme
  tags: nginx-proxy

- name: Create nginx container
  docker_container:
    name: nginx-proxy
    image: nginxproxy/nginx-proxy
    restart_policy: always
    env:
      TZ: Europe/Paris
    volumes:
      - nginx-proxy-conf:/etc/nginx/conf.d
      - nginx-proxy-vhost:/etc/nginx/vhost.d
      - nginx-proxy-html:/usr/share/nginx/html
      - nginx-proxy-certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - name: nginx-proxy
    networks_cli_compatible: yes
    state: started
  tags: nginx-proxy

- name: Create docker-gen container
  docker_container:
    name: nginx-proxy-gen
    image: jwilder/docker-gen:git
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart_policy: always
    env:
      TZ: Europe/Paris
    volumes_from:
      - nginx-proxy
    volumes:
      - /home/someuser/nginx-proxy/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - name: nginx-proxy
    networks_cli_compatible: yes
    state: started
  tags: nginx-proxy

- name: Create letsencrypt container
  docker_container:
    name: nginx-proxy-le
    image: nginxproxy/acme-companion
    restart_policy: always
    env:
      TZ: Europe/Paris
      NGINX_PROXY_CONTAINER: nginx-proxy
      NGINX_DOCKER_GEN_CONTAINER: nginx-proxy-gen
      DEFAULT_EMAIL: user@domain.tld
    volumes_from:
      - nginx-proxy
    volumes:
      - nginx-proxy-acme:/etc/acme.sh
      - nginx-proxy-certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - name: nginx-proxy
    networks_cli_compatible: yes
    state: started
  tags: nginx-proxy
```
