### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by kgnfth** [nginx-proxy/nginx-proxy#1582]
i have already searched for the same issue!
it generates the cerst successfully but i can not seem to access `https://pdnsadmin.cool.fun`
and `https://cool.fun` gives 503 error

this is my setup

```yaml
version: '2.1'

services:

  gateway:
    image: jwilder/nginx-proxy:alpine
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/etc/nginx/certs"
    ports:
      - "80:80"
    networks:
      - authoritative

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - gateway
    networks:
      - authoritative

  admin:
    restart: always
    image: chrisss404/powerdns:latest-admin
    depends_on:
      - admin-db
      - authoritative
    environment:
      - VIRTUAL_HOST=pdnsadmin.cool.fun
      - VIRTUAL_PORT=3031
      - LETSENCRYPT_EMAIL=admin@cool.fun
      - LETSENCRYPT_HOST=pdnsadmin.cool.fun
      - ADMIN_PDNS_API_KEY=****
      - ADMIN_USER_PASSWORD=****
      - ADMIN_DB_PASS=****
      - ADMIN_DB_USER=pda
      - ADMIN_DB_NAME=pda
      - ADMIN_DB_HOST=admin-db
    volumes_from:
      - gateway:ro
    networks:
      - admin-db
      - authoritative
    expose:
      - "3031"
    ports:
      - "3031:3031"

  admin-db:
    restart: always
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_DB=pda
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_PASSWORD=****
      - POSTGRES_USER=pda
    volumes:
      - admin-db:/var/lib/postgresql/data
    networks:
      - admin-db

  authoritative:
    restart: always
    image: chrisss404/powerdns:latest-authoritative
    depends_on:
      - authoritative-db
    environment:
      - VIRTUAL_HOST=pdnsauthoritative.cool.fun
      - VIRTUAL_PORT=8081
      - LETSENCRYPT_EMAIL=admin@cool.fun
      - LETSENCRYPT_HOST=pdnsauthoritative.cool.fun
      - AUTHORITATIVE_API=yes
      - AUTHORITATIVE_API_KEY=****
      - AUTHORITATIVE_WEBSERVER=yes
      - AUTHORITATIVE_WEBSERVER_PASSWORD=****
      - AUTHORITATIVE_DB_PASS=****
      - AUTHORITATIVE_DB_USER=pdns
      - AUTHORITATIVE_DB_NAME=pdns
      - AUTHORITATIVE_DB_HOST=authoritative-db
    volumes_from:
      - gateway:ro
    networks:
      authoritative:
        ipv4_address: 172.31.118.118
      authoritative-db:
    expose:
      - "8081"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:8081"

  authoritative-db:
    restart: always
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_DB=pdns
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_PASSWORD=****
      - POSTGRES_USER=pdns
    volumes:
      - authoritative-db:/var/lib/postgresql/data
    networks:
      - authoritative-db

volumes:
  admin-db:
  authoritative-db:

networks:
  admin-db:
  authoritative:
    ipam:
      driver: default
      config:
        - subnet: "172.31.118.0/24"
  authoritative-db:
```
