### ISSUE TITLE
[BUG] Latest image - ENABLE_IPV6 not being honored?

### ISSUE THREAD

**Issue by tnyeanderson** [nginx-proxy/nginx-proxy#1589]
I've used this container for years now. Just this morning, I pulled the latest `:alpine` image and tried to start the container, and I get the following error:

```
ERROR: for proxy  Cannot start service proxy: driver failed programming external connectivity on endpoint nginx-proxy (xxx): Error starting userland proxy: listen tcp6 [::]:443: socket: address family not supported by protocol
```

I have ipv6 disabled on my system, and did not have the `ENABLE_IPV6` environment variable set. I tried to set it to `false` to no avail. I also tried to use the `:1586` image on docker hub, but I have the same issue.

I mount my configs in and none of them contain an ipv6 listener (`[::]:443`). Here's the relevant docker-compose service:

```
proxy:
    image: nginxproxy/nginx-proxy:alpine
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    container_name: nginx-proxy
    environment:
      - ENABLE_IPV6=false
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./client-sites/sites:/client-sites
      - ./proxy/conf.d:/etc/nginx/conf.d:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - ./proxy/certs:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
```

Listeners in my `conf.d` look like:
```
listen 443 ssl http2;
```

Thank you to the team for their hard work on this project! It has worked beautifully for many years, and I hope to have it working again soon :)
