### ISSUE TITLE
Upstream - connect() failed (111: Connection refused) while connecting to upstream

### ISSUE THREAD

**Issue by RafaelHGBotelho** [nginx-proxy/nginx-proxy#1591]
Hey guys.

I implemented Zabbix with Nginx-Proxy and SSL, when I try to run on port 80 or 8080 it displays this error:

`connect() failed (111: Connection refused) while connecting to upstream`

When I try on any other port, it displays this error:

`no live upstreams while connecting to upstream, client:`

I understand that I should really use port 80 on Zabbix, but it doesn't work.

I went up WordPress to test it, and it worked perfectly on port 80. I have Grafana implemented and it also works well, only Zabbix that will not.

My Zabbix Compose:

```
version: '3.5'
services:
 zabbix-server:
  container_name: zabbix-server
  image: zabbix/zabbix-server-mysql:alpine-5.2-latest
  restart: always
  ports:
   - "10051:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - /opt/zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
   - /opt/zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - /opt/zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
   - /opt/zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - /opt/zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - /opt/zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - /opt/zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
   - /opt/zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
  links:
   - mysql-server:mysql-server
  env_file:
   - .env_db_mysql
   - .env_srv
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
   - MYSQL_ROOT_PASSWORD
  depends_on:
   - mysql-server
  networks:
   zbx_net_backend:
     aliases:
      - zabbix-server
      - zabbix-server-mysql
      - zabbix-server-alpine-mysql
      - zabbix-server-mysql-alpine
   zbx_net_frontend:
  stop_grace_period: 30s
  sysctls:
   - net.ipv4.ip_local_port_range=1024 65000
   - net.ipv4.conf.all.accept_redirects=0
   - net.ipv4.conf.all.secure_redirects=0
   - net.ipv4.conf.all.send_redirects=0
  labels:
   com.zabbix.description: "Zabbix server with MySQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-server"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "alpine"

 zabbix-web-apache-mysql:
  container_name: zabbix-frontend
  image: zabbix/zabbix-web-apache-mysql:alpine-5.2-latest
  restart: always
  links:
   - mysql-server:mysql-server
   - zabbix-server:zabbix-server
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - /opt/zbx_env/etc/ssl/apache2:/etc/ssl/apache2:ro
   - /opt/zbx_env/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
  env_file:
   - .env_db_mysql
   - .env_web
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
  depends_on:
   - mysql-server
   - zabbix-server
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:8080/"]
   interval: 10s
   timeout: 5s
   retries: 3
   start_period: 30s
  environment:
   VIRTUAL_HOST: dominio.com
   LETSENCRYPT_HOST: dominio.com
   LETSENCRYPT_EMAIL: email@dominio.com
  expose:
   - 80
  networks:
   default:
   zbx_net_backend:
    aliases:
     - zabbix-web-apache-mysql
     - zabbix-web-apache-alpine-mysql
     - zabbix-web-apache-mysql-alpine
   zbx_net_frontend:
  stop_grace_period: 10s
  sysctls:
   - net.core.somaxconn=65535
  labels:
   com.zabbix.description: "Zabbix frontend on Apache web-server with MySQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-frontend"
   com.zabbix.webserver: "apache2"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "alpine"

 zabbix-agent:
  container_name: zabbix-agent2
  image: zabbix/zabbix-agent2:alpine-5.2-latest
  restart: always
  ports:
   - "10050:10050"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - /opt/zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
   - /opt/zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - /opt/zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - /opt/zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
  links:
   - zabbix-server:zabbix-server
  env_file:
   - .env_agent
  privileged: true
  pid: "host"
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-agent
     - zabbix-agent-passive
     - zabbix-agent-alpine
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix agent"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-agentd"
   com.zabbix.os: "alpine"

 mysql-server:
  container_name: zabbix-mysql
  image: mysql:8.0
  restart: always
  command:
   - mysqld
   - --character-set-server=utf8
   - --collation-server=utf8_bin
   - --default-authentication-plugin=mysql_native_password
  volumes:
   - /opt/zbx_env/var/lib/mysql:/var/lib/mysql:rw
  env_file:
   - .env_db_mysql
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
   - MYSQL_ROOT_PASSWORD
  stop_grace_period: 1m
  networks:
   zbx_net_backend:
    aliases:
     - mysql-server
     - zabbix-database
     - mysql-database

 db_data_mysql:
  image: busybox
  volumes:
   - /opt/zbx_env/var/lib/mysql:/var/lib/mysql:rw

 zabbix-proxy-mysql-a:
  container_name: zabbix-proxya
  image: zabbix/zabbix-proxy-mysql:alpine-5.2-latest
  restart: always
  ports:
   - "10071:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - /opt/proxy/zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - /opt/proxy/zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - /opt/proxy/zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - /opt/proxy/zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - /opt/proxy/zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
   - /opt/proxy/zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
  links:
   - zabbix-server:zabbix-server
  env_file:
   - .env_db_mysql_proxy
   - .env_prxa
   - .env_prx_mysql
  depends_on:
   - mysql-server
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
   - MYSQL_ROOT_PASSWORD
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-proxy-mysql
     - zabbix-proxy-alpine-mysql
     - zabbix-proxy-mysql-alpine
   zbx_net_frontend:
  stop_grace_period: 30s
  labels:
   com.zabbix.description: "Zabbix proxy with MySQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-proxy"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "alpine"

 zabbix-proxy-mysql-b:
  container_name: zabbix-proxyb
  image: zabbix/zabbix-proxy-mysql:alpine-5.2-latest
  restart: always
  ports:
   - "10072:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - /opt/proxy/zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - /opt/proxy/zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - /opt/proxy/zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - /opt/proxy/zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - /opt/proxy/zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
   - /opt/proxy/zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
  links:
   - zabbix-server:zabbix-server
  env_file:
   - .env_db_mysql_proxy
   - .env_prxb
   - .env_prx_mysql
  depends_on:
   - mysql-server
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
   - MYSQL_ROOT_PASSWORD
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-proxy-mysql
     - zabbix-proxy-alpine-mysql
     - zabbix-proxy-mysql-alpine
   zbx_net_frontend:
  stop_grace_period: 30s
  labels:
   com.zabbix.description: "Zabbix proxy with MySQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-proxy"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "alpine"

networks:
  default:
    external:
      name: nginx-proxy
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/24
  zbx_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.20.1.0/24

secrets:
  MYSQL_USER:
    file: ./.MYSQL_USER
  MYSQL_PASSWORD:
    file: ./.MYSQL_PASSWORD
  MYSQL_ROOT_PASSWORD:
    file: ./.MYSQL_ROOT_PASSWORD
```
