### ISSUE TITLE
Nginx authentication not working on root page (HTTPS)

### ISSUE THREAD

**Issue by TannerGabriel** [nginx-proxy/nginx-proxy#1596]
## Bugs or Features

I have configured Nginx auth using the following code and it shows me some odd behavior.

```
server {
  listen 5000;

  server_name localhost;

  location / {
    proxy_pass http://frp_server:4200;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
    auth_basic "Administrator Area";
    auth_basic_user_file /etc/nginx/.htpasswd; 
  }

  location /axis1/ {
    proxy_pass http://frp_server:4200;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
    auth_basic "Administrator Area";
    auth_basic_user_file /etc/nginx/.htpasswd; 
  }
}
```

The authentication window is shown when accessing the root domain through https://$DOMAIN/, but the user saved in the .htpasswd file is not recognized when logging in. Once I put the application on another URL (/axis1/ in the following example), the authentication works all of a sudden.

The authentication also does not work when adding a slash behind the port of the service (`http://frp_server:4200/`):

```
location /axis1/ {
    proxy_pass http://frp_server:4200/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
    auth_basic "Administrator Area";
    auth_basic_user_file /etc/nginx/.htpasswd; 
}
```

## Nginx-Proxy config

Nginx Proxy docker-compose:

```
version: '2'
services:
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/certs"
      - "./proxy.conf:/etc/nginx/proxy.conf"
  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"
```

Nginx docker-compose:

```
  axis_nginx:
    image: "nginx:mainline"
    ports:
      - 5000:5000
    restart: on-failure
    volumes:
      - ./.nginx/axis/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.nginx/.htpasswd:/etc/nginx/.htpasswd
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - VIRTUAL_HOST=axis.DOMAIN.COM
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=axis.DOMAIN.COM
```

**Comment by tkw1536** [comment]
I am not sure why exactly authentication isn't working. It might be that the [default basic authentication support](https://github.com/nginx-proxy/nginx-proxy#basic-authentication-support) is interfering with your custom configuration. 

If you want to protect an entire domain, could you try to just place the htpasswd file under `/etc/nginx/htpasswd/axis.DOMAIN.COM` ? That should automatically add the configuration without needing to modify `default.conf`.

**Comment by TannerGabriel** [comment]
You are right. That sounds reasonable. I just tried it out and the authentication window opened whenever I accessed `axis.DOMAIN.COM`, but the user saved in the `.htpasswd` file is not recognized when logging in. I tried creating a new file and adding a new user to the existing one using the following commands.

``` 
htpasswd /usr/local/etc/apache/.htpasswd test
htpasswd -c ./.htpasswd test123
``` 

I even tried the exact same file using normal Nginx without the Nginx-Proxy and it worked fine. This time I added the file to the `nginx-proxy` container instead of the `axis_nginx` container since that one has nothing to do with the domain name. The file was added using the following volume - also checked it is copied correctly and available in the container.

```
version: '2'
services:
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/certs"
      - "./proxy.conf:/etc/nginx/proxy.conf"
      - "./.nginx/.htpasswd:/etc/nginx/htpasswd/axis.DOMAIN.COM"
```

Here are the logs that I receive:

``` 
2021/04/26 12:36:27 [error] 493#493: *274 user "test123": password mismatch, client: IP_ADDRESS, server: axis.DOMAIN.COM, request: "GET / HTTP/2.0", host: "axis.DOMAIN.COM", referrer: "https://DOMAIN.COM/"
```
