### ISSUE TITLE
ERR_HTTP2_PROTOCOL_ERROR with Symfony API container

### ISSUE THREAD

**Issue by jordan-schnur** [nginx-proxy/nginx-proxy#1639]
I have built a docker-compose file using this image for a reverse proxy to map the host to a local dev environment.

I have everything working correctly except this strange error in chrome. However, it has no errors in firefox. 
![Screen Shot 2021-05-23 at 00 33 12](https://user-images.githubusercontent.com/1748414/119248337-7b024b80-bb5e-11eb-8068-7a304a5a788c.png)

When I remove the `http2` from `listen 443 ssl http2 ;` in the server section of the _default.conf_ file it works correctly. 
 

```
version: '3.9'
services:
    backend:
        build:
            context: .
            dockerfile: ./myme.al-backend/Dockerfile.symfony
        environment: 
            APP_ENV: dev
            DATABASE_URL: mysql://root:XXXX@mysql:3306/mymeal?server_version=5
            VIRTUAL_HOST: api.myme.test
            VIRTUAL_PORT: 8000
        expose:
            - 8000
        volumes:
            - ./myme.al-backend:/var/www/backend:delegated
        depends_on: 
            - mysql
        ports:
            - 8000:8000
    nginx-proxy:
        build:
            context: .
            dockerfile: ./nginx-proxy/Dockerfile.nginx
        image: jwilder/nginx-proxy:alpine
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./certs:/etc/nginx/certs
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./nginx-proxy/logs:/var/log/nginx/
            - ./nginx-proxy/config:/etc/nginx/conf.d/
            - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d/:ro
        restart: unless-stopped
        depends_on: 
            - frontend
            - backend
            - mysql

```

I have this api.myme.test file in vhost.d. The proxy buffer lines are needed for the symfony backend to load at all. 

```
server_tokens off;
gzip off;
proxy_max_temp_file_size 0;
proxy_buffer_size          128k;
proxy_buffers              4 256k;
proxy_busy_buffers_size    256k;
large_client_header_buffers 4 512k;
```

Finally my generated default.conf
```
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Apply fix for very long server names
server_names_hash_bucket_size 128;
# Default dhparam
ssl_dhparam /etc/nginx/dhparam/dhparam.pem;
# Set appropriate X-Forwarded-Ssl header based on $proxy_x_forwarded_proto
map $proxy_x_forwarded_proto $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
		ssl_prefer_server_ciphers off;
resolver 127.0.0.11;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	server_tokens off;
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
# api.myme.test
upstream api.myme.test-upstream {
				## Can be connected with "mymeal_default" network
			# mymeal_backend_1
			server 172.22.0.4:8000;
}
server {
	server_name api.myme.test;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	# Do not HTTPS redirect Let'sEncrypt ACME challenge
	location ^~ /.well-known/acme-challenge/ {
		auth_basic off;
		auth_request off;
		allow all;
		root /usr/share/nginx/html;
		try_files $uri =404;
		break;
	}
	location / {
		return 301 https://$host$request_uri;
	}
}
server {
	server_name api.myme.test;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/api.myme.test.crt;
	ssl_certificate_key /etc/nginx/certs/api.myme.test.key;
	add_header Strict-Transport-Security "max-age=31536000" always;
	include /etc/nginx/vhost.d/api.myme.test;
	location / {
		proxy_pass http://api.myme.test-upstream;
	}
}
# myme.test
upstream myme.test-upstream {
				## Can be connected with "mymeal_default" network
			# mymeal_frontend_1
			server 172.22.0.3:3000;
}
server {
	server_name myme.test;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	# Do not HTTPS redirect Let'sEncrypt ACME challenge
	location ^~ /.well-known/acme-challenge/ {
		auth_basic off;
		auth_request off;
		allow all;
		root /usr/share/nginx/html;
		try_files $uri =404;
		break;
	}
	location / {
		return 301 https://$host$request_uri;
	}
}
server {
	server_name myme.test;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/myme.test.crt;
	ssl_certificate_key /etc/nginx/certs/myme.test.key;
	add_header Strict-Transport-Security "max-age=31536000" always;
	include /etc/nginx/vhost.d/myme.test;
	location / {
		proxy_pass http://myme.test-upstream;
	}
}
```

I am truly lost and above my head with some of this nginx stuff. Please let me know what you need from me and thank you.
