### ISSUE TITLE
I SET VIRTUAL_PATH,BUT not work

### ISSUE THREAD

**Issue by wangshenglong** [nginx-proxy/nginx-proxy#1647]
my docker-compose.yml like this

```
proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    environment:
     - SSL_POLICY=Mozilla-Old
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/mime.types:/etc/nginx/mime.types
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
unifyauth.api:
    image: xsj:unifyauth.api
    container_name: unify
    environment:
      - VIRTUAL_HOST=xsj.rayscloud.cn
      - VIRTUAL_PATH=/unify
      - VIRTUAL_DEST=/
      - TZ=Asia/Shanghai
    ports:
      - 7000:80
    restart: always
```

But I cannot xsj.raycloud.cn/unify, and i see nginx.tmpl has no  VIRTUAL_PATH
