### ISSUE TITLE
"File not found" for NGINX Proxy & wordpress:5.7.2-php7.4-fpm

### ISSUE THREAD

**Issue by PeterTucker** [nginx-proxy/nginx-proxy#1651]
I'm wondering if this setup might be possible: a single NGINX Proxy with docker-gen & nginx companion in one docker-compose file using nginx.tmpl. And then separate WordPress containers all in separate docker-compose files linking back to the Nginx Proxy.  So far I have not been able to get this to work, and when I go to example.com or example2.com I receive the message "File not found."

I've also tried to implement fpm_workaround_location.conf, which I read is a solution to fpm not playing well with NGINX. No go.
[https://github.com/tkw1536/nginx-proxy-fpm-workaround/blob/main/fpm_workaround_location.conf](https://github.com/tkw1536/nginx-proxy-fpm-workaround/blob/main/fpm_workaround_location.conf)

If anyone knows what a working configuration would be, or what I'm missing, your help would be greatly appreciated.

Directory structure:
```
docker folder
     nginx
         docker-compose.yml
         nginx.tmpl 
     example.com
         docker-compose.yml
     example2.com
         docker-compose.yml
```

nginx: docker-compose.yml
```
version: '3'

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./fpm_workaround_location.conf:/etc/nginx/vhost.d/example.com_location:ro
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro

  docker-gen:
    image: jwilder/docker-gen
    container_name: nginx-proxy-gen
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx-proxy
    volumes:
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"


  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment: 
       NGINX_DOCKER_GEN_CONTAINER: nginx-proxy-gen
   
volumes:
  conf:
  vhost:
  html:
  certs:
  acme:

networks:
  default:
    external:
      name: nginx-proxy
```
fpm_workaround_location.conf
```
fastcgi_param SCRIPT_FILENAME $request_filename;
```
example.com(...and example2.com): docker-compose.yml
```
version: '3'

services:

   my_db_mysql:
     #image: mysql:5.7
     image: akoller/low-memory-mysql:latest
     volumes:
        - ./my_db:/var/lib/mysql
     restart: always
     environment:
        MYSQL_RANDOM_ROOT_PASSWORD: '1'
        MYSQL_DATABASE: my_db
        MYSQL_USER: my_admin
        MYSQL_PASSWORD: password
     container_name: my_db

   my_site:
     depends_on:
        - my_db_mysql
     image: wordpress:latest
     image: wordpress:5.7.2-php7.4-fpm
     volumes:
        - ./wp-content:/var/www/html/wp-content
        - ./site/:/var/www/html/
     expose:
        - 80
     restart: always
     environment:
        VIRTUAL_HOST: example.com
        VIRTUAL_PROTO: fastcgi
        VIRTUAL_PORT: 9000
        VIRTUAL_ROOT: /var/www/html
        LETSENCRYPT_HOST: example.com
        LETSENCRYPT_EMAIL: user@example.com
        WORDPRESS_DB_HOST: my_db_mysql
        WORDPRESS_DB_NAME: my_db
        WORDPRESS_DB_USER: my_admin
        WORDPRESS_DB_PASSWORD: password
     container_name: my_site

volumes:
  my_db:
  
networks:
  default:
    external:
      name: nginx-proxy

```
