### ISSUE TITLE
Usage with acme-companion: certifcates are generated, but docker-gen creates a return 500 entry in default.conf

### ISSUE THREAD

**Issue by gabrieletassoni** [nginx-proxy/nginx-proxy#1657]
I always get a privacy error on browser when trying to use the nginx-proxy and acme-companion.

The docker-compose.yml file I use is:

```yaml
version: '3.7'

networks:
  default:
    external:
      name: webproxy

# /home/docker/persistence/nginx-data/ 
services:
  nginx:
    restart: always
    # image: nginxproxy/nginx-proxy
    build: .
    container_name: nginx-proxy
    hostname: nginx-proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/docker/persistence/nginx-data/certs:/etc/nginx/certs
      - /home/docker/persistence/nginx-data/vhost.d:/etc/nginx/vhost.d
      - /home/docker/persistence/nginx-data/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
  letsencrypt:
    restart: always
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-letsencrypt
    hostname: nginx-proxy-letsencrypt
    depends_on:
      - "nginx"
    volumes:    
      - /home/docker/persistence/nginx-data/certs:/etc/nginx/certs
      - /home/docker/persistence/nginx-data/vhost.d:/etc/nginx/vhost.d
      - /home/docker/persistence/nginx-data/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/docker/persistence/nginx-data/acme:/etc/acme.sh
    environment: 
      DEFAULT_EMAIL: ced@bancolini.com
```

The build: . just copies some additional config files for tuning timeout and upload size.

The generated entry in default.conf is (it looks like it tries to use self signed certificates instead of the letsencrypt ones and returns a 500 error by default), is:

```nginx
pstream devops.bancolini.com-upstream {
	## Can be connected with "webproxy" network
	# abs-gitlab
	server 172.20.0.2:8181;
	# Fallback entry
	server 127.0.0.1 down;
}
server {
	server_name devops.bancolini.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	include /etc/nginx/vhost.d/default;
	location / {
		proxy_pass http://devops.bancolini.com-upstream;
		include /etc/nginx/vhost.d/default_location;
	}
}
server {
	server_name devops.bancolini.com;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	return 500;
	ssl_certificate /etc/nginx/certs/default.crt;
	ssl_certificate_key /etc/nginx/certs/default.key;
}
```

The gitlab instance is reachable on port 8181:

```bash
$ telnet 172.20.0.2 8181
Trying 172.20.0.2...
Connected to 172.20.0.2.
Escape character is '^]'.
^]
telnet> quit
Connection closed.
```

And the relevant docker-compose.yml file for gitlab is:

```yaml
version: "3.7"

services:
  abs-gitlab-runner:
    image: "gitlab/gitlab-runner:latest"
    depends_on:
      - "gitlab-letsencrypt"
    container_name: abs-gitlab-runner
    restart: always
    volumes:
      - "/home/docker/persistence/gitlab-runners-data:/etc/gitlab-runner"
      - "/var/run/docker.sock:/var/run/docker.sock"

  gitlab-letsencrypt:
    build: .
    container_name: abs-gitlab
    restart: always
    hostname: devops.bancolini.com
    volumes:
      - '/home/docker/persistence/gitlab-data/config:/etc/gitlab'
      - '/home/docker/persistence/gitlab-data/data:/var/opt/gitlab'
    restart: always
    expose:
      - "8181"
    ports:
      - '5050:5050'
      - '22:22'
    environment:
      VIRTUAL_HOST: devops.bancolini.com
      VIRTUAL_PORT: 8181
      LETSENCRYPT_HOST: devops.bancolini.com
      LETSENCRYPT_EMAIL: ced@bancolini.com
      GITLAB_OMNIBUS_CONFIG: |
        external_url "https://devops.bancolini.com"
        registry_external_url "https://devops.bancolini.com:5050"

        # Disable monitoring to save CPU
        prometheus['enable'] = false
        node_exporter['enable'] = false
        redis_exporter['enable'] = false
        # Using external NGINX
        nginx['enable'] = false
        # nginx['listen_port'] = 80
        # nginx['listen_https'] = false
        
        gitlab_rails['trusted_proxies'] = [ '192.168.0.0/24', '172.20.0.0/16' ]
        gitlab_workhorse['enable'] = true
        gitlab_workhorse['listen_network'] = "tcp"
        gitlab_workhorse['listen_addr'] = "0.0.0.0:8181"
        # puma['enable'] = true
        # puma['listen'] = '0.0.0.0'
        # puma['port'] = 8181

        gitlab_rails['gitlab_shell_ssh_port'] = 22
        gitlab_rails['packages_enabled'] = true
        gitlab_rails["incoming_email_enabled"] = true
        gitlab_rails["incoming_email_address"] = [REDACTED]
        gitlab_rails["incoming_email_email"] = [REDACTED]
        gitlab_rails["incoming_email_password"] = [REDACTED]
        gitlab_rails["incoming_email_host"] = [REDACTED]
        gitlab_rails["incoming_email_port"] = 993
        gitlab_rails["incoming_email_ssl"] = true
        gitlab_rails["incoming_email_start_tls"] = false
        gitlab_rails["incoming_email_mailbox_name"] = [REDACTED]
        gitlab_rails["incoming_email_idle_timeout"] = 60
        gitlab_rails["incoming_email_expunge_deleted"] = true
        gitlab_rails["smtp_enable"] = true
        gitlab_rails["smtp_address"] = [REDACTED]
        gitlab_rails["smtp_port"] = 587
        gitlab_rails["smtp_authentication"] = false
        gitlab_rails['ldap_enabled'] = true
        gitlab_rails['prevent_ldap_sign_in'] = false
        gitlab_rails['ldap_servers'] = {
          'main' => {
            'label' => 'LDAP',
            'host' =>  [REDACTED],
            'port' => 389,
            'uid' => 'uid',
            'encryption' => 'plain',
            'verify_certificates' => false,
            'bind_dn' => [REDACTED]
            'password' => [REDACTED],
            'timeout' => 10,
            'active_directory' => false,
            'allow_username_or_email_login' => false,
            'block_auto_created_users' => false,
            'base' => [REDACTED],
            'user_filter' => '',
            'attributes' => {
              'username' => ['uid'],
              'email' => ['mail'],
              'name' => 'cn',
              'first_name' => 'givenName',
              'last_name' => 'sn'
            },
            'lowercase_usernames' => false
          }
        }

networks:
  default:
    external:
      name: webproxy
```

The acme-companion seems to generate the right certificates in the relevant acme.sh subdirectory: 

```bash
drwxr-xr-x 2 root root 4096 giu  3 09:43 backup
-rw-r--r-- 1 root root 3751 giu  3 09:43 ca.cer
-rw-r--r-- 1 root root 2204 giu  3 09:43 devops.bancolini.com.cer
-rw-r--r-- 1 root root  952 giu  3 09:43 devops.bancolini.com.conf
-rw-r--r-- 1 root root 1683 giu  3 09:43 devops.bancolini.com.csr
-rw-r--r-- 1 root root  215 giu  3 09:43 devops.bancolini.com.csr.conf
-rw-r--r-- 1 root root 3243 giu  3 09:43 devops.bancolini.com.key
-rw-r--r-- 1 root root 5955 giu  3 09:43 fullchain.cer
```

I cannot understand how to debug and resolve this, from a configuration point of view it looks ok to me, but the default.conf generated by nginx-proxy just looks wrong, why it is generated like that? How can I fix it?

Thank you very much,
Gabriele

**Comment by rene-gomez** [comment]
Hello @gabrieletassoni 
I saw your website and works fine, i have the same problem, can you support the community and share with us your workaround? 

Thanks in advance.

Regards,

**Comment by buchdag** [comment]
I believe this was solved in https://github.com/nginx-proxy/acme-companion/issues/824

**Comment by gabrieletassoni** [comment]
> Hello @gabrieletassoni
> I saw your website and works fine, i have the same problem, can you support the community and share with us your workaround?
> 
> Thanks in advance.
> 
> Regards,

Hi, as stated by @buchdag , I solved it by using the suggestion in the last line of this comment, specifically: https://github.com/nginx-proxy/acme-companion/issues/824#issuecomment-858809761

**Comment by rene-gomez** [comment]
> 
> 
> I believe this was solved in [nginx-proxy/acme-companion#824](https://github.com/nginx-proxy/acme-companion/issues/824)

Hello.

This solution doesn't work for me, maybe i need open a new issue.

Regards.

**Comment by swayok** [comment]
In my case it was because of CERT_NAME environment option in my project behind proxy. It had empty value. Proxy received all the certs from LetsEncrypt, but did not use them falling back to default certs with `return 500;`. 

Interesting note: this same config worked correctly on staging, but had this issue on prod. I tried everything related to proxy configs, nothing worked. Then I started deleting environment options one by one and CERT_NAME was the reason.

BAD config:

docker-compose.yml:
```
services:
  caddy:
    ...
    environment:
      ...
      VIRTUAL_HOST: ${NGINX_PROXY_HOSTS}
      VIRTUAL_PORT: 80
      VIRTUAL_NETWORK: proxy
      CERT_NAME: ${NGINX_SHARED_CERTIFICATE_NAME}
```
.env:
```
NGINX_PROXY_HOSTS=your-domain.com
NGINX_SHARED_CERTIFICATE_NAME=
```
Even empty value in `NGINX_SHARED_CERTIFICATE_NAME` env causes this problem for some reason.


Solution: delete CERT_NAME from environment:

docker-comose.yml:
```
services:
  caddy:
    ...
    environment:
      ...
      VIRTUAL_HOST: ${NGINX_PROXY_HOSTS}
      VIRTUAL_PORT: 80
      VIRTUAL_NETWORK: proxy
```
