### ISSUE TITLE
503 is served for unknown hosts when HTTP is used, but a random container is served for unknown hosts when HTTPS is used

### ISSUE THREAD

**Issue by Jolt151** [nginx-proxy/nginx-proxy#1664]
Say I have two services:

```
version: '2'                                    
services:                                       
  kanboard:                                     
    image: kanboard/kanboard:latest             
    volumes:                                    
      - ./kanboard_data:/var/www/app/data       
      - ./kanboard_plugins:/var/www/app/plugins 
      - ./kanboard_ssl:/etc/nginx/ssl           
    networks:                                   
      - nginx_nginx-proxy                       
    environment:                                
      - VIRTUAL_HOST=kanboard.example.com
  homer:                            
    image: b4bz/homer:latest        
    volumes:                        
      - ./assets:/www/assets        
    networks:                       
      - nginx_nginx-proxy           
    environment:                    
      - VIRTUAL_HOST=homer.example.com
networks:                                       
  nginx_nginx-proxy:                            
    external: true                              
```

Assume these are in two separate docker compose files. If `homer` is down, then navigating to `http://homer.example.com` will return a 503 page, while navigating to `https://homer.example.com` will actually return the contents of `https://kanboard.example.com`! 

I am using a single wildcard cert, with the files `example.com.crt` and `example.com.key`.

I suspect this is because of the default configuration, where the default listener is added for port 80 but not for port 443:

```
server {                                                                                            
        server_name _; # This is just an invalid value which will never trigger on a real hostname. 
        server_tokens off;                                                                          
        listen 80;                                                                                  
        access_log /var/log/nginx/access.log vhost;                                                 
        return 503;                                                                                 
}                                                                                                   
```
