### ISSUE TITLE
Env in docker-compose

### ISSUE THREAD

**Issue by coaperator** [nginx-proxy/nginx-proxy#1678]
### Discussed in https://github.com/nginx-proxy/nginx-proxy/discussions/1674

<div type='discussions-op-text'>

<sup>Originally posted by **coaperator** June 20, 2021</sup>
I have files with environment
```
.env_prod
VIRTUAL_HOST: api.site.com

.env_local
VIRTUAL_HOST: api.localhost.local
```
docker-compose has a variable VIRTUAL_HOST 
```
version: '3.5'

services:
  distance:
    container_name: ides-back_distance
    # image: almazweb/distance
    depends_on:
      - postgres
      - redis
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      postgres_URL: postgresdb://postgres:5432
      REDIS_HOST: redis
    ports:
      - 3001:3001
    volumes:
      - ./:/app
```
i run
`docker-compose -f .\docker-compose.staging.yml --env-file ./config/.env_local up`
and I get the error in nginx-proxy container
`invalid number of arguments in "server_name" directive in /etc/nginx/conf.d/default.conf:78`

in general, nginx naturally does not pick up the domain name

what can you think of to get out of the situation?</div>
