### ISSUE TITLE
503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [nginx-proxy/nginx-proxy#1687]
Hi guys,

thank you for the amazing repo. I would like to apologize in advance, I am not an nginx expert. So I am trying to run the image on a raspberry pi

```
version: "3.8"
services:
 
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=whoami.local
      - VIRTUAL_PORT=8000


networks:
  default:

```

If I try to go to my local pi IP I got

![image](https://user-images.githubusercontent.com/15908060/125335002-50f22c00-e34c-11eb-932e-6acac62c72b3.png)

This is the generated config

```
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Apply fix for very long server names
server_names_hash_bucket_size 128;
# Default dhparam
ssl_dhparam /etc/nginx/dhparam/dhparam.pem;
# Set appropriate X-Forwarded-Ssl header based on $proxy_x_forwarded_proto
map $proxy_x_forwarded_proto $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
                ssl_protocols TLSv1.2 TLSv1.3;
                ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
                ssl_prefer_server_ciphers off;
resolver 127.0.0.11;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        return 503;
}
```

I also noticed that the `jwilder/whoami` was stopped after a couple of seconds.

To my understanding version 3 is not supported (is there a way to make it work with v3?), I've also tried with version 2 but the same error. Could you please help me out?

Thank you.

Francesco

**Comment by buchdag** [comment]
> I also noticed that the jwilder/whoami was stopped after a couple of seconds.

If jwilder/whoami crashes, there won't be anything to proxy to and you'll get the catch-all at the end of config.

> To my understanding version 3 is not supported (is there a way to make it work with v3?), I've also tried with version 2 but the same error. Could you please help me out?

Compose version 3 is supported without any issue, but the docs aren't up to date (yet).

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @buchdag, thank you for the super fast reply! I am trying with another image but I don't quite understand how the internal networking works

```
version: "3.8"
services:

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    #   - ./nginx/.htpasswd:/etc/nginx/htpasswd

  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - VIRTUAL_PORT=7567

    volumes:
      - ./heimdall/config:/config
    ports:
      - 7567:80
      # - 443:44x3
    restart: unless-stopped
 

networks:
  default:
```
The config generated is the same, so no service is proxed. In this case, connecting to the right port works because the port is exposed to the external network. I really don't understand how to configure this correctly, a minimum working example with maybe my configuration will help me a lot! Thanks

**Comment by buchdag** [comment]
> `VIRTUAL_PORT=7567`

[Check the doc for `VIRTUAL_PORT`.](https://github.com/nginx-proxy/nginx-proxy#virtual-ports)

> When your container exposes only one port, nginx-proxy will default to this port, else to port 80.

You are most probably in this case and don't need `VIRTUAL_PORT`.

Your container also probably don't publish port `7567` on the Docker network (publishing and exposing aren't the same), and trying to force `VIRTUAL_PORT` to a port that the container does not publish logically result in a non working configuration. You're basically telling nginx-proxy that the backend communication should happen on a port the proxied container isn't listening on.

You don't need

```yaml
networks:
  default:
```

If everything is on the same compose file, `docker compose up` will automatically create a docker network and connect those containers to it.

**Comment by FrancescoSaverioZuppichini** [comment]
Okay, so by placing the `VIRTUAL_PORT=80` (even if I don't need it) it's working

```
version: "3.8"
services:

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks: 
      - proxy

  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - VIRTUAL_HOST=heimdall.local
      - VIRTUAL_PORT=80
    volumes:
      - ./heimdall/config:/config
    # ports:
    #   - 7567:80
      # - 443:44x3
    networks: 
      - proxy
    restart: unless-stopped

networks:
  proxy:

```

```curl -H "Host: heimdall.local" localhost```

Correctly returns me the HTML page. 

Now I am wondering is there a way to specify the `location` directive? I would like to access my running `heimdall` from my local network, so I would like to do something like `<IP>/heimdall`.  My idea, correctly If I am wrong, is to have all the traffic proxied by nginx but still be able to access my containers from the internet
