### ISSUE TITLE
[BUG] Unable to parse template: template: nginx.tmpl:185: unexpected "=" in operand

### ISSUE THREAD

**Issue by samuelkristianto** [nginx-proxy/nginx-proxy#1741]
> Unable to parse template: template: nginx.tmpl:185: unexpected "=" in operand

https://github.com/nginx-proxy/nginx-proxy/blob/8adbea8aec3e58faaccf07d947bd5b293fab7e79/nginx.tmpl#L185
https://github.com/nginx-proxy/nginx-proxy/blob/8adbea8aec3e58faaccf07d947bd5b293fab7e79/nginx.tmpl#L190
https://github.com/nginx-proxy/nginx-proxy/blob/8adbea8aec3e58faaccf07d947bd5b293fab7e79/nginx.tmpl#L197

i think this should be
`{{ $server_found := "true" }}`

**Comment by buchdag** [comment]
Hi

> i think this should be `{{ $server_found := "true" }}`

Nope, we're assigning a value to an already declared variable, not declaring a new variable.

> For bugs, the easier you make it to reproduce the issue you see, the easier and faster it can get fixed.  If you can provide a script or docker-compose file that reproduces the problems, that is very helpful.

**Comment by samuelkristianto** [comment]
i see,
i thought i need to use `:=` for both already declared variable and new variable.

i dont know why it doesnt work, the only error i got is  

> Unable to parse template: template: nginx.tmpl:185: unexpected "=" in operand

and i didnt change the script (nginx.tmpl)

this is my docker-compose file

```
version: "3.9"

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      - nginx-network
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro

  docker-gen:
    image: jwilder/docker-gen
    container_name: nginx-proxy-gen
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - conf:/etc/nginx/conf.d
      - certs:/etc/nginx/certs:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"
    networks:
      - nginx-network
    depends_on:
      - nginx-proxy

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vhost:/etc/nginx/vhost.d:rw
      - html:/usr/share/nginx/html
    networks:
      - nginx-network
    depends_on:
      - docker-gen
networks:
  nginx-network:
    name: nginx-network
    external: false
volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
```
