### ISSUE TITLE
BUG - VIRTUAL_PATH routes to multiple containers

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [nginx-proxy/nginx-proxy#1783]
## Bugs

I love this project since it suites very well.
I want to route for example ```/api``` to container A and  ```/app``` to container B.
The problem is, that these request will alternate. I used VIRTUAL_HOST and VIRTUAL_PATH. Hopefully i just made a mistake.

docker-compose.yaml
```
version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  app:
    image: jwilder/whoami
    expose:
      - "7000"
    environment:
      - VIRTUAL_HOST=192.168.178.35
      - VIRTUAL_PATH=/app
      - VIRTUAL_PORT=7000
      - PORT=7000


  whoami:
    image: jwilder/whoami
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=192.168.178.35
      - VIRTUAL_PATH=/api
      - VIRTUAL_PORT=8000
      - PORT=8000
```
