### ISSUE TITLE
Multiple Nginx-Proxy's not working as though

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [nginx-proxy/nginx-proxy#1785]
I wanted to create a subdirectoy routing with multiple nginx-proxy's. 
I create two docker-compose similar to this scheme here, but it does not work as intendet. I don't know if this either a bug, feature request or just something else.

A: nginx-proxy listens on 80
- networks:
   - topDomain

different Docker-compose file.
B: nginx-proxy
- VIRTUAL_HOST=localhost
- VIRTUAL_PATH=/serviceA
- networks:
   - topDomain:
      - external: true

C: backendservice
- VIRUAL_HOST=localhost
- VIRTUAL_PATH=/serviceA/backend

**Comment by junderw** [comment]
switch the order of those two services in your compose file.

**Comment by NilsBaumgartner1994** [comment]
docker-compose.yaml of toplevel proxy
```
version: '2'

services:
  nginx-proxy:
    env_file: .env
    image: nginxproxy/nginx-proxy:dev
    ports:
      - "80:80"
    restart: always
    logging:
      driver: local #or "none" or "local"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro # allow to read running dockers
      #- ./nginx/test:/etc/nginx/conf.d # to see the config output
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    name: topDomainProxy
```



docker-compose.yaml of sub containers:
```
version: '3'
services:

  app:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=192.168.178.35
      - VIRTUAL_PATH=/studip/app
    networks:
      - mycustomNetwork

  innerProxy:
    image: nginxproxy/nginx-proxy:dev
    expose:
      - "80"
    restart: always
    environment:
      - VIRTUAL_HOST=192.168.178.35
      - VIRTUAL_PATH=/studip
    logging:
      driver: local #or "none" or "local"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro # allow to read running dockers
    networks:
      - mycustomNetwork
      - topDomainProxy

networks:
  mycustomNetwork:
  topDomainProxy:
    external: true
```

**Comment by NilsBaumgartner1994** [comment]
> switch the order of those two services in your compose file.

Sadly its still not working

**Comment by NilsBaumgartner1994** [comment]
Fixed it using ```DEFAULT_HOST````

docker-compose.yaml
```
version: '2'

services:

  outer:
    container_name: outer
    env_file: .env
    image: nginxproxy/nginx-proxy:dev
    ports:
      - "80:80"
    restart: always
    environment:
      - DEFAULT_HOST=outer.bar.com
    logging:
      driver: local #or "none" or "local"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro # allow to read running dockers
      #- ./nginx/test:/etc/nginx/conf.d # to see the config output
    networks:
      - reverse-proxy

  innter:
    container_name: innter
    env_file: .env
    image: nginxproxy/nginx-proxy:dev
    expose:
      - "80"
    restart: always
    environment:
      - DEFAULT_HOST=inner.bar.com
      - VIRTUAL_HOST=outer.bar.com
      - VIRTUAL_PATH=/proxy
    logging:
      driver: local #or "none" or "local"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro # allow to read running dockers
      #- ./nginx/test:/etc/nginx/conf.d # to see the config output
    networks:
      - reverse-proxy

  app:
    container_name: app
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=inner.bar.com
      - VIRTUAL_PATH=/proxy/app
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    name: topDomainProxy
```
