### ISSUE TITLE
On boot exit 2 after that no problem

### ISSUE THREAD

**Issue by wassereimer86** [nginx-proxy/nginx-proxy#1809]
Hi,

i hope that somebody can help me. When i reboot/start my server, all Containers start, except nginx-proxy.  There i get an "Exited (2)" in the status. After i make an "docker-compose up -d" it starts und runs without any problems. The logs don´t tell my anything (at least for me as a docker beginner).

`SIGQUIT: quit
PC=0x46b9e1 m=0 sigcode=0

goroutine 34 [syscall]:`

And than a lot of goroutine´s.

![WindowsTerminal_2021-10-09_19-43-58](https://user-images.githubusercontent.com/22779744/136670145-490e28b5-6d94-4dd0-856e-505da4640cc3.png)

![WindowsTerminal_2021-10-09_19-46-12](https://user-images.githubusercontent.com/22779744/136670146-836f576a-940b-4d87-ade8-e3cd07701584.png)

[log.txt](https://github.com/nginx-proxy/nginx-proxy/files/7316176/log.txt)

**Comment by wassereimer86** [comment]
Still wasn´t able to test this because of a lack in my skills.

**Comment by buchdag** [comment]
@wassereimer86 sorry I was pretty sure I answered your last question ☹️ 

You just have to replace the nginx-proxy image you're using in your Docker Compose file with `nginxproxy/nginx-proxy:1809`, then do `docker-compose down` and `docker-compose up -d`. Docker Compose will automatically pull the image for you.

**Comment by wassereimer86** [comment]
No problem, i´m happy for every help and such tools that are open source. :)

Sadly it didn´t fix the problem. Still the same issue. I restarted multiple times to test it. If i start it manually it´s working.

**Comment by wassereimer86** [comment]
Still the same problem. Just want to let you know. Any other ideas on this issue?

**Comment by wassereimer86** [comment]
Hey there! Do you have any new informations on the topic? 🙂

**Comment by buchdag** [comment]
@wassereimer86 I'm still completely unable to reproduce this issue.

Could you share more informations about your setup ? What host and OS you are running Docker on, which version of Docker, the compose files you are using to run nginx-proxy, etc (I'll add to the list if something comes to my mind).

**Comment by buchdag** [comment]
I just realised your issue is caused by `forego` and not by `docker-gen` as I originally thought 🤦‍♂️ 

My request for additional information still stands.

In the meantime, trying the [separate containers setup](https://github.com/nginx-proxy/nginx-proxy#separate-containers) (replacing the `nginx-proxy` image with the base `nginx` image + the `docker-gen` image) should solve your issue.

**Comment by wassereimer86** [comment]
@buchdag I can´t use the separate container setup at the moment. I have too much things running and i´m not an docker expert. Please let me know if you need anything else or if i can help you with anything.

General:
```
x86_64 Host (Shuttle DS81D) 
Ubuntu 20.04.3 LTS
Kernel 5.4.0-92-generic
```

Docker:
```
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:42 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Docker Compose File:

```
services:

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - xxx
      - xxx
    ports:
      - xxx
    restart: always
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - VIRTUAL_HOST=xxx
      - LETSENCRYPT_HOST=xxx
    depends_on:
      - esphome

  esphome:
    container_name: esphome
    image: esphome/esphome
    devices:
      - /dev/ttyUSB1:/dev/ttyUSB1
    volumes:
      - xxx
      - xxx
    ports:
      - xxx
      - xxx
    restart: always
    environment:
      - NETWORK_ACCESS=internal
      - ESPHOME_DASHBOARD_USE_PING=true

  octoprint:
    container_name: octoprint
    image: octoprint/octoprint
    restart: always
    ports:
      - xxx
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/video0:/dev/video0
      - /dev/snd/controlC1:/dev/snd/controlC1
      - /dev/video1:/dev/video1
      - /dev/input/event8:/dev/input/event8
    volumes:
      - xxx
      - xxx
    environment:
      - VIRTUAL_HOST=xxx
      - LETSENCRYPT_HOST=xxx
      - ENABLE_MJPG_STREAMER=true
      - MJPG_STREAMER_INPUT=-r 1920x1080 -f 30
      - NETWORK_ACCESS=internal

  nginx-proxy:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - xxx/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
      - xxx/vhost:/etc/nginx/vhost.d
      - xxx/html:/usr/share/nginx/html
      - xxx/certs:/etc/nginx/certs:ro
    depends_on:
      - homeassistant
      - octoprint
      - wordpress

  acme-companion:
    image: nginxproxy/acme-companion
    restart: always
    container_name: nginx-proxy-acme
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - xxx/acme:/etc/acme.sh
      - xxx/vhost:/etc/nginx/vhost.d
      - xxx/html:/usr/share/nginx/html
      - xxx/certs:/etc/nginx/certs:rw
    environment:
      - DEFAULT_EMAIL=xxx
      - NGINX_PROXY_CONTAINER=nginx-proxy
    depends_on:
      - nginx-proxy

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    ports:
      - xxx
    volumes:
      - xxx
      - xxx
    environment:
      - NETWORK_ACCESS=internal
      - MYSQL_ROOT_PASSWORD=xxx

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - xxx
    environment:
      - PMA_HOST=mariadb
      - HIDE_PHP_VERSION=true
      - NETWORK_ACCESS=internal
    volumes:
      - xxx
    depends_on:
      - mariadb

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    ports:
      - xxx
    environment:
      - VIRTUAL_HOST=xxx
      - LETSENCRYPT_HOST=xxx
    volumes:
      - xxx
      - xxx
    depends_on:
      - mariadb

  wireguard:
    container_name: wireguard
    image: weejewel/wg-easy
    restart: always
    ports:
      - xxx
      - xxx
    environment:
      - WG_HOST=xxx
      - PASSWORD=xxx
      - WG_PORT=xxx
    volumes:
      - xxx
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```
