### ISSUE TITLE
Documentation: customize nginx.tmpl

### ISSUE THREAD

**Issue by capc0** [nginx-proxy/nginx-proxy#1817]
I could not find any documentation on how to customize the template file. So I want to let others know how I did it.

The file seems to be located within `/app` and can be overwritten with a simple mount option.

```yml
version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.tmpl:/app/nginx.tmpl
```
