### ISSUE TITLE
Support limit_except to filtering  by http methods for allowlist / blocklist. 

### ISSUE THREAD

**Issue by pythonwood** [nginx-proxy/nginx-proxy#1822]
## Features

How about to support like

```
version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=whoami.local
      - VIRTUAL_PORT=8000
      # for allowlist / blocklist.
      # - METHODS_BLOCK=PUT,POST
      - METHODS_ALLOW=GET,HEAD
```

I has find disscusstion [Basic auth for all http verbs except GET and OPTIONS #1813 ](https://github.com/nginx-proxy/nginx-proxy/discussions/1813), would you like to think about together ?

thanks you.
