### ISSUE TITLE
empty upstream when upgrading to docker for mac 4.3.0

### ISSUE THREAD

**Issue by Iv4nS** [nginx-proxy/nginx-proxy#1869]
It seems like nginx-proxy is failing to detect the containers and create the upstream configuration on the default.conf file.

Using this fails in Docker Desktop for Mac4.3.0 but succeeds on 4.2.0:

```
version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local
```

the container returns:
```
Creating network "docker-test_default" with the default driver
Creating docker-test_nginx-proxy_1 ... done
Creating docker-test_whoami_1      ... done
Attaching to docker-test_whoami_1, docker-test_nginx-proxy_1
nginx-proxy_1  | WARNING: /etc/nginx/dhparam/dhparam.pem was not found. A pre-generated dhparam.pem will be used for now while a new one
nginx-proxy_1  | is being generated in the background.  Once the new dhparam.pem is in place, nginx will be reloaded.
whoami_1       | Listening on :8000
nginx-proxy_1  | forego     | starting dockergen.1 on port 5000
nginx-proxy_1  | forego     | starting nginx.1 on port 5100
nginx-proxy_1  | dockergen.1 | 2022/01/13 15:52:51 Generated '/etc/nginx/conf.d/default.conf' from 2 containers
nginx-proxy_1  | dockergen.1 | 2022/01/13 15:52:51 Error running notify command: nginx -s reload, exit status 1
nginx-proxy_1  | dockergen.1 | 2022/01/13 15:52:51 Watching docker events
nginx-proxy_1  | dockergen.1 | 2022/01/13 15:52:51 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx-proxy_1  | 2022/01/13 15:52:57 [emerg] 50#50: no servers are inside upstream in /etc/nginx/conf.d/default.conf:58
nginx-proxy_1  | nginx: [emerg] no servers are inside upstream in /etc/nginx/conf.d/default.conf:58
nginx-proxy_1  | Generating DSA parameters, 4096 bit long prime
nginx-proxy_1  | dhparam generation complete, reloading nginx
```
