### ISSUE TITLE
Lots of timeouts and "No route to host" errors

### ISSUE THREAD

**Issue by johnhamelink** [nginx-proxy/nginx-proxy#191]
Hi there,

I'm using nginx-proxy to proxy a connection between the outside world and a rails app using puma. However the connection is very intermittent and I get a lot of the following messages:

```
2015/07/02 15:41:31 [error] 48#48: *4484 connect() failed (113: No route to host) while connecting to upstream, client: 82.23.149.132, server: api.example.com, request: "GET /users/devices/mine.json HTTP/1.1", upstream: "http://172.17.1.13:3000/users/devices/mine.json", host: "blah.example.com"
```

My docker-compose.yml looks like this (private images names have been redacted):

``` yaml
web:
  image: example/rails-app:latest
  ports:
    - "3000:3000"
  links:
    - redis
  volumes:
    - "./log:/var/www/log"
    - "./assets:/var/www/public/assets"
  env_file: .env
  restart: always

nginx:
  image: jwilder/nginx-proxy:latest
  ports:
    - "80:80"
  volumes:
    - /var/run:/tmp
  restart: always

sidekiq:
  image: example/rails-app:latest
  links:
    - redis
  volumes:
    - "./sidekiq_log:/var/www/log"
  env_file: .env
  restart: always
  command: bundle exec sidekiq

redis:
  image: redis
  ports:
    - "6379:6379"
  volumes:
    - "./redis_data:/data"

rpush:
  image: example/rails-app:latest
  volumes:
    - "./rpush_log:/var/www/log"
  env_file: .env
  restart: always
  command: bundle exec rpush start -e production -f

logs:
  image: progrium/logspout
  restart: always
  hostname: example-app
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  command: syslog://logs3.papertrailapp.com:19957
  restart: always
```
