### ISSUE TITLE
No error logs!

### ISSUE THREAD

**Issue by averri** [nginx-proxy/nginx-proxy#1970]
`nginx-proxy/nginx-proxy` is returning an HTTP 500 with no traces of errors. It has been very difficult to understand what is going on.

`docker-compose.yaml` for the backend services:

```yaml
version: '2.2'
services:
  http-echo:
    image: mendhak/http-https-echo:23
    ports:
      - "8585:8080"
    network_mode: bridge
    environment:
      VIRTUAL_HOST: mydomain.com
      VIRTUAL_PORT: 8585
      LETSENCRYPT_HOST: mydomain.com
      LETSENCRYPT_EMAIL: myemail@mydomain.com
```

`docker-compose.yaml` for the nginx-proxy and the acme-companion:

```yaml
version: '2.2'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - HSTS=off
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge
    environment:
      DEFAULT_EMAIL: me@mydomain.com

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:
```

The container related to the image `mendhak/http-https-echo:23` is responsible for echoing HTTP requests.

Start all containers above using `docker-compose`.

Hitting the URL http://mydomain.com:8585 in the browser returns the HTTP echo correctly (it's bypassing nginx-proxy, accessing the backend container directly, so this service is working fine):

![image](https://user-images.githubusercontent.com/1898447/164892755-0184d8a9-4952-4b3b-be95-f7478fa0e2e2.png)

But, hitting the URL https://mydomain.com in the browser returns HTTP 500:

![image](https://user-images.githubusercontent.com/1898447/164892261-ff9693e3-7a2d-4523-89d2-5f9497741006.png)

There are no error logs in `/var/log/nginx/error.log`.

Please let me how to enable error logs. It's impossible to know what's going on.

**Comment by DatAres37** [comment]
The logs are the standard logs of your docker container. 

Did you read the docs? You're not even exposing any ports of your service.

**Comment by tkw1536** [comment]
Duplicate of #654

**Comment by averri** [comment]
@DatAres37, the port of my service is exposed, please see the pictures attached showing the service working on port 8585. 

I read the docs, spent few hours reading and didn't find anything. Please let me know if there is any other document.

There is nothing in the Docker logs of any of the containers above related to the error 500.

**Comment by DatAres37** [comment]
You're publishing ports, not exposing them.
It's also a better idea to use a dedicated docker network for the proxy and the services behind it.

**Comment by averri** [comment]
@DatAres37, thank you so much for your time answering my questions. I agree with you about using a dedicated Docker network, but for some unknown reason, this configuration was not working. After researching on the internet, I've found other users suggesting the use of `network_mode: bridge`. It works, but I don't like it for obvious reasons. 

All this saga started when I introduced WordPress behind `nginx-proxy`, which gives errors 500 and 502, and it's been difficult to troubleshoot because there are no error logs on `nginx-proxy`. 

About exposing the port, I have added the `expose` to `docker-compose.yaml`, but the issue with error 500 still persists.

```yaml
version: '2.2'
services:
  http-echo:
    image: mendhak/http-https-echo:23
    ports:
      - "8585:8080"
    expose:
      - "8585"
    network_mode: bridge
    environment:
      VIRTUAL_HOST: mydomain.com
      VIRTUAL_PORT: 8585
      LETSENCRYPT_HOST: mydomain.com
      LETSENCRYPT_EMAIL: myemail@mydomain.com
```
