### ISSUE TITLE
VIRTUAL_PATH Error

### ISSUE THREAD

**Issue by linrong** [nginx-proxy/nginx-proxy#2003]
hi, i use nginx-proxy and acme-companion with version like:
```
nginxproxy/acme-companion   2.2.1
nginxproxy/nginx-proxy      1.0.1 
```
I want to use VIRTUAL_PATH  for forwarding my request
The configuration in docker-compose is as follows：
```
 cloud-web:
    environment:
      VIRTUAL_PROTO: uwsgi
      VIRTUAL_HOST: xxxxx.cn
      VIRTUAL_PORT: 8000
      VIRTUAL_PATH: /api
      LETSENCRYPT_HOST: xxxxx.cn
      LETSENCRYPT_EMAIL: test@gmail.cn
    image: django:1.8
```
And I add a configuration file to the vhost directory：
```
# xxxxx.cn
location / {
    try_files $uri $uri/ @router;
    index index.html index.htm;
}

location @router {
     rewrite ^.*$ /index.html last;
}
```
I'm going to use nginx config file to handle location / and use docker-compose to automatically generate location /api
But nginx-proxy runs wrong
I see the default.conf,I found that this repeatedly generates a location /
```
server {
        server_name xxxxx.cn;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        include /etc/nginx/vhost.d/xxxxx.cn;
location /api {
                include uwsgi_params;
                uwsgi_pass uwsgi://xxxxx.cn-ada91241341ae792ecf0a59cad28616a77bab856;
                include /etc/nginx/vhost.d/xxxxx_location;
}
                        location / {
                                return 404;
                        }
}
```
This location / is repeated. I checked the documentation and issue and I can't seem to find a solution. How should I configure it?
