### ISSUE TITLE
Template error messages in logs

### ISSUE THREAD

**Issue by Arkemlar** [nginx-proxy/nginx-proxy#2041]
## Bug

My docker container logs contains many of these messages:
`dockergen.1 | 2022/08/21 21:47:19 Template error: open /etc/nginx/certs: no such file or directory`

I think it writes right, I not configured any certificates but it is normal use case, why it scolding into log about that?

My docker-compose config:
```
services:
  entrypoint:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  default:
    name: entrypoint
    external: true
```

No matter how many and what proxied containers I have, this logging message has no relation to that.
