### ISSUE TITLE
unknown volume for /etc/nginx/dhparam/

### ISSUE THREAD

**Issue by MaxPowers1337** [nginx-proxy/nginx-proxy#2043]
## Bug

Hi all, 

im running the following service and docker is creating an unknown volume for ```/etc/nginx/dhparam/```.

As far as i understood the documentation, it's completly optional to use a mount for the dhparam-directory to overwrite the default key (similiar to the option for htpasswd).  But in this case i don't want to.

Did I do something wrong or is my understanding wrong of how docker works?

Thank you in advance!

```
ls -l /var/lib/docker/volumes/817916e0ac46aa6d5d78abb9826b44b2b789e6f4ceee39223958125d3511717a/_data/dhparam.pem
-rw-r--r-- 1 root root 1525 Aug 24 10:00 /var/lib/docker/volumes/817916e0ac46aa6d5d78abb9826b44b2b789e6f4ceee39223958125d3511717a/_data/dhparam.pem
```

```
version: '3.3'

networks:
  docker_network:
    name: docker_network
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24

volumes:
        vhost:
        acme:
        html:
        certs:
        htpasswd:

services:

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: proxy
    networks:
      - docker_network
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - htpasswd:/etc/nginx/htpasswd:ro
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d:rw
      - html:/usr/share/nginx/html:rw
```
