### ISSUE TITLE
Subdomain only works through port (Electric boogaloo)

### ISSUE THREAD

**Issue by dequeues** [nginx-proxy/nginx-proxy#2049]
Similar: #632

Maybe I am overlooking something, but I'm not sure of the solution for this. If I visit hxxp://grafana.home.lan, I received a 110 connection timed out error on some assets which does not allow the application to work correctly, in this case, Grafana.

```
nginx.1     | 2027/05/23 10:59:12 [error] 35#35: *267 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.1.238, server: grafana.home.lan, request: "GET /api/search?limit=30&starred=true HTTP/1.1", upstream: "http://192.168.160.5:3000/api/search?limit=30&starred=true", host: "grafana.home.lan", referrer: "http://grafana.home.lan/?chunkNotFound&orgId=1"
````

If I visit hxxp://grafana.home.lan:3000, the content loads with absolutely zero issues.
```
nginx.1     | grafana.home.lan 192.168.1.238 - - [23/May/2027:10:59:12 +0000] "GET /api/live/ws HTTP/1.1" 400 12 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" "192.168.160.5:3000"

```

nginx-proxy docker-compose.yml
```yml
version: '3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf/proxy.conf:/etc/nginx/proxy.conf:ro
    environment:
      DEBUG: true

networks:
  default:
    name: nginx-proxy
    external: true
```

Grafana config can be found here:

https://github.com/dequeues/monitor-stack/blob/979c0118004a16d7d742b5df1e9e505ffcfeacca/docker-compose.yml#L48-L61

Generated nginx config:

https://gist.github.com/dequeues/4e98ae023f74697157c770b03074887d
