### ISSUE TITLE
The symbol VIRTUAL_HOST=_ is not working for catching all servers 

### ISSUE THREAD

**Issue by miglio-dev** [nginx-proxy/nginx-proxy#2056]
When using the server name it works fine but not for the _ that in nginx means catch 
using nginx-proxy: latest

docker-compose.yaml

```yaml
version: '3'
services:
  proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginxProxy
    restart: always
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
nginx:
    image: nginx
    container_name: nginxServer
    volumes:
      - /var/www/html:/usr/share/nginx/html:ro
    expose:
      - 8000
    environment:
      - VIRTUAL_HOST=_
      - VIRTUAL_PATH=/
      - VIRTUAL_POST=8000
    restart: always
```
