### ISSUE TITLE
[NextCloud Docker + nginx proxy] Can't access Nextcloud from local network

### ISSUE THREAD

**Issue by GreatNewHope** [nginx-proxy/nginx-proxy#2116]
Hello! Thanks for this amazing tool and for answering questions here.

My main computer (`192.168.1.149`) is running docker with four containers running Nextcloud, MariaDB, nginx-proxy and letsencrypt. I followed [this guide](https://linuxhandbook.com/install-nextcloud-docker/) in case of needing more info.

The problem that I have encountered is that I am able to access Nextcloud from my dynDNS (say, `wonderfuldns.ddns.net`) and it works flawlessly, but I am completely unable to access Nextcloud from neither my local network (any other computer pointing to 192.168.1.149) nor my external ip (say `207.188.666.666`). And this even though my dyndns correctly points to this external ip when asking for my `ddns.net`. My main concern is with not being able to access Nextcloud from my local network though.

In both cases I get `503 Service Temporarily Unavailable`.

There's a weird behaviour. When I change the env variable `VIRTUAL_HOST` of NextCloud container from `wonderfuldns.ddns.net` to `wonderfuldns.ddns.net,207.188.666.666` the error that I get from accessing NextCloud from the external raw ip changes from 503 to `500 Internal Server Error`.

I have also changed internal Nextcloud variables like trusted_domains and trusted_proxies in case it was Nextcloud's fault, with no luck.

This is the docker-compose.yaml for nginx and letsencrypt
```yaml
version: "3.3"

services:

    NginxProxy:
        image: "jwilder/nginx-proxy:latest"

        volumes:
            - "NPhtml:/usr/share/nginx/html"
            - "NPdhparam:/etc/nginx/dhparam"
            - "NPvhost:/etc/nginx/vhost.d"
            - "NPcerts:/etc/nginx/certs:ro"
            - "/var/run/docker.sock:/tmp/docker.sock:ro"
            - "./client_max_upload_size.conf:/etc/nginx/conf.d/client_max_upload_size.conf"

        labels:
            - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
        restart: "on-failure"
        networks: ["net"]

        ports:
            - "80:80"
            - "443:443"

    LetsencryptCompanion:
        image: "jrcs/letsencrypt-nginx-proxy-companion:latest"

        volumes:
            - "LCacme:/etc/acme.sh"
            - "NPvhost:/etc/nginx/vhost.d"
            - "NPcerts:/etc/nginx/certs"
            - "NPhtml:/usr/share/nginx/html"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"

        environment:
            - DEFAULT_EMAIL

        depends_on: ["NginxProxy"]
        restart: "on-failure"
        networks: ["net"]


volumes:
    NPhtml:
    NPdhparam:
    NPvhost:
    NPcerts:
    LCacme:

networks:
    net:
        external: true
```
And this is the docker-compose.yaml for Nextcloud and MariaDB

```yaml
version: "3.7"

services:

    NCDatabase:
        image: "mariadb:latest"
        
        volumes:
            - "NCMariaDB:/var/lib/mysql"

        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_RANDOM_ROOT_PASSWORD
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD

        restart: "on-failure"
        networks: ["common"]

    NCFrontend:
        image: "nextcloud:latest"

        volumes: 
          - "NCData:/var/www/html"
          - "E:\\:/prodDrive"

        environment:
            - LETSENCRYPT_HOST
            - VIRTUAL_HOST
            - TRUSTED_PROXIES
            - OVERWRITEPROTOCOL
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_HOST
            - SMTP_HOST
            - SMTP_PORT
            - SMTP_NAME
            - SMTP_PASSWORD
            - MAIL_FROM_ADDRESS
            - NEXTCLOUD_TRUSTED_DOMAINS
            - NEXTCLOUD_ADMIN_USER
            - NEXTCLOUD_ADMIN_PASSWORD

        depends_on:
            - "NCDatabase"
        restart: "on-failure"
        networks: ["net", "common"]

volumes:
    NCMariaDB:
    NCData:

networks:
    net:
        external: true
    common:
        internal: true

```
Where env variables are these
```
MYSQL_ROOT_PASSWORD=<password>
MYSQL_DATABASE=NC
MYSQL_USER=nextcloud
MYSQL_PASSWORD=<password>
MYSQL_HOST=NCDatabase
LETSENCRYPT_HOST=wonderfuldns.ddns.net
VIRTUAL_HOST=wonderfuldns.ddns.net
TRUSTED_PROXIES=172.18.0.0/16
OVERWRITEPROTOCOL=https
NEXTCLOUD_TRUSTED_DOMAINS=wonderfuldns.ddns.net
```
