### ISSUE TITLE
no live upstreams while connecting to upstream. 502 Bad Gateway

### ISSUE THREAD

**Issue by Di-Mon** [nginx-proxy/nginx-proxy#2126]
### Discussed in https://github.com/nginx-proxy/nginx-proxy/discussions/2125

I've created a config in Nginx and everything works as expected, so something is wrong on nginx-proxy side

<div type='discussions-op-text'>

<sup>Originally posted by **Di-Mon** December 28, 2022</sup>
Hi everyone,

I am trying to get a container working behind an nginx-proxy, but I am getting 502 Bad Gateway when running container with docker-container.yml

when I am running like this, everything working perfectly:

```
docker run \
-e VIRTUAL_HOST=domain.com \
-v 'pwd'/app:/usr/share/nginx/html \
-p 8080:80 \
--name domain.com \
nginx:alpine
```

but when I am launching similar config with docker compose up I get 502 Bad Gateway error when opening a domain in browser.
Here is my docker-container.yml

```
version: '3'
services:
  web:
    image: nginx:alpine
    container_name: domain.com
    environment:
    - VIRTUAL_HOST=domain.com
    volumes:
    - ./app:/usr/share/nginx/html
    ports:
      - "8080:80"
  ```

In logs I see following error:
`[error] 123#123: *66 no live upstreams while connecting to upstream, client: 52.47.45.89, server: domain.com, request: "GET / HTTP/1.1", upstream: "http://domain.com/", host: "domain.com"`

What am I missing?</div>
