### ISSUE TITLE
dockergen.1: invalid value for containers which should be ignored

### ISSUE THREAD

**Issue by QuAzI** [nginx-proxy/nginx-proxy#2165]
I am playing with Prometheus and I found that nginx-proxy always flood when it starts or stops
```log
nginx-proxy                | dockergen.1 | 2023/02/09 10:38:55 Received event die for container dd6fa4697fa9
nginx-proxy                | dockergen.1 | 2023/02/09 10:38:55 Received event die for container e046a6256eec                                                                                  nginx-proxy                | dockergen.1 | 2023/02/09 10:38:55 Received event stop for container dd6fa4697fa9
nginx-proxy                | dockergen.1 | 2023/02/09 10:38:55 Received event stop for container e046a6256eec                                                                                 nginx-proxy                | dockergen.1 | 2023/02/09 10:38:56 invalid value
nginx-proxy                | dockergen.1 | 2023/02/09 10:38:56 invalid value
nginx-proxy                | dockergen.1 | 2023/02/09 10:38:56 invalid value
nginx-proxy                | dockergen.1 | 2023/02/09 10:38:56 invalid value
nginx-proxy                | dockergen.1 | 2023/02/09 10:38:56 invalid value
nginx-proxy                | dockergen.1 | 2023/02/09 10:38:56 invalid value
nginx-proxy                | dockergen.1 | 2023/02/09 10:38:56 invalid value
nginx-proxy                | dockergen.1 | 2023/02/09 10:38:56 invalid value
nginx-proxy                | dockergen.1 | 2023/02/09 10:38:56 invalid value
...
nginx-proxy                | dockergen.1 | 2023/02/09 10:38:56 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
```
and if Prometheus started earlier, nginx-proxy crashes on start

Problematic docker-compose.yml for Prometheus
```yml
version: '3.9'

services:
  prometheus:
    image: prom/prometheus:v2.42.0
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: alertmanager
    restart: always
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager:/config
      - alertmanager-data:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug
    depends_on:
      - prometheus
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis
      - prometheus
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379

volumes:
  prometheus_data:
  alertmanager-data:
```
