### ISSUE TITLE
bad upstream server in swarm mode ?

### ISSUE THREAD

**Issue by dugravot6** [nginx-proxy/nginx-proxy#2167]
Hi all,
In swarm mode (only one node for the moment), i create a stack of 3 services : 
- nginx-proxy
- whoami
- acme-letsencrypt (not important)

When i try to reach the whoami container through nginx, i get an error like : 
```
nginx_nginx-proxy.1.i4lo6342kqgk@minipc1    | nginx.1     | 2023/02/12 10:43:43 [error] 74#74: *5 upstream timed out (110: Operation timed out) while connecting to upstream, client: 10.0.0.2, server: whoami.local, request: "GET / HTTP/1.1", upstream: "http://10.0.0.254:8000/", host: "whoami.local"
nginx_nginx-proxy.1.i4lo6342kqgk@minipc1    | nginx.1     | whoami.local 10.0.0.2 - - [12/Feb/2023:10:43:43 +0000] "GET / HTTP/1.1" 504 167 "-" "curl/7.74.0" "10.0.0.254:8000"
```

When i try to reach the whoami container on his publish port (8001), it's ok : 
```
curl -H "Host: whoami.local" 127.0.0.1:8001
I'm b62b642227f6
```

The problem is that nginx try to reach container via ingress network, not on the dedicated overlay (attachable) network (my-network) i setup before. We can see that it refers to the wrong network (ingress) in nginx configuration file : 

```
upstream whoami.local {
    # Container: nginx_whoami.1.n4m2w81avbf4r0nzq9dw9ksnn
    #     networks: 
	#       ingress (reachable)
    #       my-network (ignored; reachable but redundant) 
    #     IP address: 10.0.0.254
    server 10.0.0.254:8000;
}
```

Here is my stack definition : 

```
version: '3.4'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    networks:
      - my-network
    ports:
      - "80:80"
        #      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/DOCKER/NGINX/data/certs:/etc/nginx/certs
      - /home/DOCKER/NGINX/data/vhost.d:/etc/nginx/vhost.d
      - /home/DOCKER/NGINX/data/html:/usr/share/nginx/html
        #      - /home/DOCKER/NGINX/data/nginx.tmpl:/app/nginx.tmpl:ro
    deploy:
      mode: replicated
      replicas: 1
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"

  whoami:
    image: jwilder/whoami
    networks:
      - my-network
    ports:
      - "8001:8000"
    depends_on:
      - nginx-proxy
    environment:
      - "VIRTUAL_HOST=whoami.local"
      - "LETSENCRYPT_HOST=whoami.local"
      - "LETSENCRYPT_EMAIL=stephane@example.com"

  acme-companion:
    image: nginxproxy/acme-companion
    networks:
      - my-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/DOCKER/NGINX/data/certs:/etc/nginx/certs
      - /home/DOCKER/NGINX/data/vhost.d:/etc/nginx/vhost.d
      - /home/DOCKER/NGINX/data/html:/usr/share/nginx/html
      - /home/DOCKER/ACME-COMPANION/data/acme/acme.sh:/etc/acme.sh
    depends_on:
      - nginx-proxy
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - "DEFAULT_EMAIL=stephane@example.com"

networks:
  my-network:
    external: true
```

I don't know why nginx cannot join whoami container on the IP 10.0.0.254, and why i can't use my-network. Did you know what i have to do to nginx proxy works in swarm mode ?
Thank you.
