### ISSUE TITLE
Invalid value spam

### ISSUE THREAD

**Issue by stnfrd** [nginx-proxy/nginx-proxy#2177]
dockergen spams the logs with "invalid value" when something happens.
It makes it pretty hard to see what is happening when you are debugging your docker-compose stack.

```
nginx-proxy           | dockergen.1 | 2023/02/16 18:43:05 Received event die for container ee7bafb9e4f2
nginx-proxy           | dockergen.1 | 2023/02/16 18:43:05 invalid value
nginx-proxy           | dockergen.1 | 2023/02/16 18:43:05 invalid value
nginx-proxy           | dockergen.1 | 2023/02/16 18:43:05 invalid value
.
.
.
.
nginx-proxy           | dockergen.1 | 2023/02/16 18:43:05 invalid value
nginx-proxy           | dockergen.1 | 2023/02/16 18:43:05 invalid value
nginx-proxy           | dockergen.1 | 2023/02/16 18:43:05 Generated '/etc/nginx/conf.d/default.conf' from 5 containers
nginx-proxy           | dockergen.1 | 2023/02/16 18:43:05 Running 'nginx -s reload'
nginx-proxy           | nginx.1     | 2023/02/16 18:43:05 [notice] 17#17: signal 1 (SIGHUP) received from 101, reconfiguring
nginx-proxy           | nginx.1     | 2023/02/16 18:43:05 [notice] 17#17: reconfiguring
nginx-proxy           | nginx.1     | 2023/02/16 18:43:05 [notice] 17#17: using the "epoll" event method
nginx-proxy           | nginx.1     | 2023/02/16 18:43:05 [notice] 17#17: start worker processes
nginx-proxy           | nginx.1     | 2023/02/16 18:43:05 [notice] 17#17: start worker process 102
nginx-proxy           | nginx.1     | 2023/02/16 18:43:06 [notice] 100#100: gracefully shutting down
nginx-proxy           | nginx.1     | 2023/02/16 18:43:06 [notice] 100#100: exiting
nginx-proxy           | nginx.1     | 2023/02/16 18:43:06 [notice] 100#100: exit
nginx-proxy           | nginx.1     | 2023/02/16 18:43:06 [notice] 17#17: signal 17 (SIGCHLD) received from 100
nginx-proxy           | nginx.1     | 2023/02/16 18:43:06 [notice] 17#17: worker process 100 exited with code 0
nginx-proxy           | nginx.1     | 2023/02/16 18:43:06 [notice] 17#17: signal 29 (SIGIO) received
letsencrypt           | 2023/02/16 18:43:10 Debounce minTimer fired
letsencrypt           | 2023/02/16 18:43:10 invalid value
letsencrypt           | 2023/02/16 18:43:10 invalid value
letsencrypt           | 2023/02/16 18:43:10 invalid value
letsencrypt           | 2023/02/16 18:43:10 invalid value
letsencrypt           | 2023/02/16 18:43:10 invalid value
letsencrypt           | 2023/02/16 18:43:10 invalid value
```

docker-compose file
```
    nginx-proxy:
        image: "nginxproxy/nginx-proxy:1.2-alpine"
        container_name: "nginx-proxy"
        volumes:
            - ./proxy/certs:/etc/nginx/certs
            - ./proxy/vhost:/etc/nginx/vhost.d
            - ./proxy/html:/usr/share/nginx/html
            # - "./proxy/custom.conf:/etc/nginx/conf.d/custom.conf"
            - "/run/docker.sock:/tmp/docker.sock:ro"
        environment:
            ENABLE_IPV6: "true"
        restart: "always"
        ports:
            - "80:80"
            - "443:443"



    letsencrypt:
        image: "nginxproxy/acme-companion:2.2"
        container_name: "letsencrypt"
        volumes:
            - ./proxy/certs:/etc/nginx/certs
            - ./proxy/vhost:/etc/nginx/vhost.d
            - ./proxy/html:/usr/share/nginx/html
            - "/run/docker.sock:/var/run/docker.sock:ro"
        environment:
            NGINX_PROXY_CONTAINER: "nginx-proxy"
            DEFAULT_EMAIL: "me@example.org"
        restart: "always"
        depends_on: ["nginx-proxy"]
```
