### ISSUE TITLE
How to enable CORS for subdomain?

### ISSUE THREAD

**Issue by chedched** [nginx-proxy/nginx-proxy#2181]
### Discussed in https://github.com/nginx-proxy/nginx-proxy/discussions/2180

<div type='discussions-op-text'>

<sup>Originally posted by **chedched** February 17, 2023</sup>
I'm stuck for days with enabling CORS for all subdomains. I'm pretty new to this topic.

The [documentation](https://github.com/nginx-proxy/nginx-proxy#per-virtual_host-location-default-configuration) is pretty clear about how to achieve this: 

> add those settings to the /etc/nginx/vhost.d/default_location file

There is also a pretty detailed and long [issue](https://github.com/nginx-proxy/nginx-proxy/issues/804) about the topic that provides various solutions:

- Creating a file `/etc/nginx/vhost.d/default_location` and adding it to the vhost volume
- Creating a file `example.com` and attaching it to `/etc/nginx/vhost.d/example.com`
- Small working example provided by another user: https://github.com/wildsurfer/stackoverflow-12173990

However, I just don't get it to work.

The relevant parts of my `docker-compose.yml` are:

```
services:
    backend:
      depends_on:
        database:
          condition: service_healthy
      environment:
        - LETSENCRYPT_HOST=api.example.com
        - VIRTUAL_HOST=api.example.com
        - VIRTUAL_PATH=/
      image: registry.gitlab.com/user/project/backend
      networks:
        - fullstack
      ports:
        - 8000:8000
      restart: unless-stopped

    nginx-proxy:
      environment:
        - TRUST_DOWNSTREAM_PROXY=false
      image: nginxproxy/nginx-proxy:alpine
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./auth:/etc/nginx/htpasswd
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - ./proxy.conf:/etc/nginx/proxy.conf
        - certs:/etc/nginx/certs
        - vhost:/etc/nginx/vhost.d
        - html:/usr/share/nginx/html
        - ./default_location:/etc/nginx/vhost.d/default_location

    networks:
      fullstack:
        driver: bridge

    volumes:
      acme:
      certs:
      vhost:
      html:
      database:
        driver: local
```

And the content of the default_location file is this:

```
if ($http_origin ~* (.*\.example.com)) {
    add_header 'Access-Control-Allow-Origin' "$http_origin";
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, DELETE, PUT';
    add_header 'Access-Control-Allow-Credentials' 'true';
    add_header 'Access-Control-Allow-Headers' 'User-Agent,Keep-Alive,Content-Type';
}
if ($request_method = OPTIONS) {
    return 204;
}
```

What I also tried the volumes section of the `nginx-proxy container` in the `docker-compose.yml`:
- ./default_location.conf:/etc/nginx/vhost.d/default_location
- ./api.example.com:/etc/nginx/vhost.d/api.example.com
- ./api.example.com_location:/etc/nginx/vhost.d/api.example.com_location

Of course it could also be the backend ([gin gonic](https://github.com/gin-gonic/gin)) that is blocking access, but we've a running instance of that on another server (we want to migrate that into a docker container). I can connect to the backend running on another server from the frontend inside the docker-container. Hence I'm confident I'm messing up the nginx proxy settings somehow.

Am I somehow not understanding how to "attach"/"add" a file to a volume? </div>
