### ISSUE TITLE
How to set X-Script-Name header for virtual path?

### ISSUE THREAD

**Issue by champli** [nginx-proxy/nginx-proxy#2242]
I have the following compose file:

```
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    restart: always
    environment:
      - DEFAULT_ROOT: 301 https://some.where
      - TRUST_DOWNSTREAM_PROXY=false
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - acme_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - ./htpasswd:/etc/nginx/htpasswd

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - LANG=en_US.utf8
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_INITDB_ARGS=--locale-provider=icu --icu-locale=en-US
    volumes:
      - ./../no_backup/postgresql_data/fast:/var/lib/postgresql/data
      - ./../no_backup/postgresql_data/slow:/slowdata
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -t 5"]
      interval: 10s
      timeout: 5s
      retries: 12

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=me@mail.post
      - PGADMIN_DEFAULT_PASSWORD=another_secret
      - VIRTUAL_PROTO=http
      - VIRTUAL_HOST=my.domain
      - VIRTUAL_PORT=80
      - VIRTUAL_PATH=/pgadmin
      - LETSENCRYPT_HOST=my.domain
    expose:
      - "80"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  acme_certs:
  nginx_vhost:
  nginx_html:

networks:
  default:
    external: true
    name: nginx-proxy

```

When invoking the pgadmin (http://my.domain/pgadmin) I get a http-404. The pgadmin page says that if it is reverse proxied to a virtual path, the proxy shall add proxy_set_header X-Script-Name /pgadmin . See here, in section HTTP via Nginx: https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html

How to set this header just for this path? I prefer a solution that does not introduce another file that would be mounted into the nginx proxy, since part of the overall setup is the appealing fact that you can have anything in just one file.
