### ISSUE TITLE
Header Access-Token missing on backend

### ISSUE THREAD

**Issue by gammore** [nginx-proxy/nginx-proxy#2260]
Hello!

I think i'm encountering a weird issue i hope you can help me solve.

I have a pretty standard config. I'm using flask to create an API and nginx-proxy to expose it.

nginx-proxy version:    nginx/1.25.0
                        built by gcc 10.2.1 20210110 (Debian 10.2.1-6)

Nginx -t output attached in a comment next.

Docker-compose file:
```yaml
version: '3.9'
services:
  reverse-proxy:
    image: nginxproxy/nginx-proxy
    container_name: reverse-proxy
    ports:
      - "80:80"      # HTTP Traffic
      - "443:443"    # HTTPS Traffic
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  backend:
    image: bakend:latest
    container_name: backend
    ports:
      - 3000:3000
    environment:
      - VIRTUAL_HOST=backend.127.0.0.1.nip.io
      - VIRTUAL_PORT=3000
      - MONGODB_USERNAME=example
      - MONGODB_PASSWORD=example
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=example
      - MONGO_INITDB_ROOT_PASSWORD=example
```

The requests to the backend go authenticated with the header "access_token" with a long token. As you can see the backend is exposed through nginx proxy with the hostname "backend.127.0.0.1.nip.io" (that always resolves to localhost) and through the 3000 port.

On my app, i have defined flask's `before_request` decorator:
```python
@app.before_request
def print_headers():
  print(dict(request.headers))
```

This way, when the requests arrives, the headers get printed on the console. If I make a request using postman, with the header set I can see:
- Requesting to http://localhost:3000/list (does not go through nginx) the header access_token is not here:
```
{'Host': 'backend.127.0.0.1.nip.io', 'Connection': 'close', 'X-Real-Ip': '172.19.0.1', 'X-Forwarded-For': '172.19.0.1', 'X-Forwarded-Host': 'backend.127.0.0.1.nip.io', 'X-Forwarded-Proto': 'http', 'X-Forwarded-Ssl': 'off', 'X-Forwarded-Port': '80', 'X-Original-Uri': '/list', 'User-Agent': 'PostmanRuntime/7.32.2', 'Accept': '*/*', 'Postman-Token': 'xxxxx', 'Accept-Encoding': 'gzip, deflate, br', 'Cookie': 'session=xxxx'}
```

- Requesting to http://backend.127.0.0.1.nip.io/list (goes through nginx) you can see the header is here:
```
{'Access-Token': 'xxxxx', 'User-Agent': 'PostmanRuntime/7.32.2', 'Accept': '*/*', 'Postman-Token': 'xxxx', 'Host': 'localhost:3000', 'Accept-Encoding': 'gzip, deflate, br', 'Connection': 'keep-alive', 'Cookie': 'session=xxxx'}
```

Do you have any idea what i might have wrong? All other requests that not require authentication work well (p.e. login) but all that require that header are not working if they go through nginx.

Thank you!
