### ISSUE TITLE
I come in search of guidance, friendly url!

### ISSUE THREAD

**Issue by arcanisgk** [nginx-proxy/nginx-proxy#2290]
I come in search of guidance, friendly url!

i have this implementation working:

![Diapositiva1](https://github.com/nginx-proxy/nginx-proxy/assets/1207306/9d83c7bf-551c-46f0-9b03-1a89aa4ae427)

i can get my web server live, but i get error when use friendly URL:

_laragon nginx:_

```
server {
    server_name lh-2.dck;

    location / {
        proxy_pass http://localhost:8081;
        proxy_redirect off;
        proxy_cache off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header Connection "Keep-Alive";
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
    }
}
```

_vhost in web server docker:_

```
<VirtualHost *:80>
    ServerName lh-2.dck
    ServerAlias *.lh-2.dck
    DocumentRoot "/var/www/html/public/"
    <Directory "/var/www/html/public/">
        Options Indexes FollowSymLinks Includes ExecCGI
        AllowOverride All
        Require all granted
        Allow from all
    </Directory>
</VirtualHost>
```

_.htaccess in project_

```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /

    RewriteCond %{REQUEST_URI} ^.*setup.*\$ [NC]
    RewriteRule ^(.*)$ /setup.php [L,R=301]

</IfModule>
```

docker yml file to construct enviroment:

```
version: "3.8"

services:
  reverse-proxy:
    container_name: LH-2-Proxy-Server
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "8081:80"
    networks:
      - lamp-network
    extra_hosts:
      - "lh-2.dck:127.0.0.1"
      - "lh-2.pma.dck:127.0.0.1"
  webserver:
    container_name: LH-2-Web-Server
    build:
      context: ./bin/php81
    restart: always
    expose:
      - 80
    ports:
      - "8082:80"
    networks:
      - lamp-network
    depends_on:
      - database
    volumes:
      - ./../:/var/www/html:rw
      - ./../public:/var/www/html/public:rw
      - ./config/vhosts/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./logs/apache2:/var/log/apache2
    environment:
      VIRTUAL_HOST: "lh-2.dck"
      WEB_MASTER: "********"
      HOST_MACHINE_MYSQL_PORT: "3307"
      MYSQL_DATABASE: "lh-2"
      MYSQL_ROOT_PASSWORD: "********"
      MYSQL_USER: "********"
      MYSQL_PASSWORD: "********"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  database:
    build:
      context: ./bin/mysql8
    container_name: LH-2-mysql8
    restart: always
    networks:
      - lamp-network
    ports:
      - "127.0.0.1:3307:3307"
    volumes:
      - ./config/initdb:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "********"
      MYSQL_DATABASE: "lh-2"
      MYSQL_USER: "********"
      MYSQL_PASSWORD: "********"
  phpmyadmin:
    container_name: LH-2-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - database
    environment:
      VIRTUAL_HOST: "lh-2.pma.dck"
      PMA_HOST: "database"
      PMA_PORT: "3306"
      PMA_USER: "********"
      PMA_PASSWORD: "********"
      MYSQL_ROOT_PASSWORD: "********"
      MYSQL_USER: "********"
      MYSQL_PASSWORD: "********"
      UPLOAD_LIMIT: 512M
      MEMORY_LIMIT: 512M
    volumes:
      - /sessions
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    networks:
      - lamp-network
networks:
  lamp-network:
    driver: bridge
```

host file:

```
127.0.0.1		www.lh-2.dck			lh-2.dck
127.0.0.1		www.lh-2.pma.dck		lh-2.pma.dck

# Added by Docker Desktop
192.168.0.5 host.docker.internal
192.168.0.5 gateway.docker.internal
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```

Error:

![image](https://github.com/nginx-proxy/nginx-proxy/assets/1207306/bfa359a2-11de-4ca9-9721-94a0fb584b62)

logs:

> lh-2.dck:80 172.25.0.2 - - [28/Aug/2023:04:57:35 +0000] "GET /setup HTTP/1.1" 404 450 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"

and:

> [Mon Aug 28 04:17:28.457418 2023] [negotiation:error] [pid 17] [client 172.23.0.2:34798] AH00687: Negotiation: discovered file(s) matching request: /var/www/html/public/setup (None could be negotiated).

I only wanted that when opening this url: `lh-2.dck/setup` the file is loaded: `lh-2.dck/setup.php` without the extension.

but i am stuck here not knowing what is going on or how many things i need to do to find the problem and fix it.
