### ISSUE TITLE
Issue with Bookstack urls being re-written to http not https

### ISSUE THREAD

**Issue by MayContainVennom** [nginx-proxy/nginx-proxy#2334]
Hello

I'm trying to put bookstack behind the Nginx Proxy. So far I have managed to get the page to load but it is not pulling through the CSS. When I check the console from the browser I can see the following:
![image](https://github.com/nginx-proxy/nginx-proxy/assets/5930954/58dae5ee-1129-4eb6-affa-9398fbb5fa88)

On further inspection, it looks like the page is being re-written but to http not https:

![image](https://github.com/nginx-proxy/nginx-proxy/assets/5930954/852d6414-73b9-4da3-9a40-6d78fcb9c202)

### Nginx docker-compose:

```
version: '3.8'

services:
  nginx-proxy:
    build: ./proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    networks:
    - bookstack_nw

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=example@example.com
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - FILES_UID=1000
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    network_mode: bridge

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:

networks:
  bookstack_nw:
    name: bookstack_nw
    external: true
```
### bookstack docker compose:
```
version: '2'

services:
  bookstack:
    image: nikolausc/bookstack-pi:latest
    container_name: bookstack_app2
    expose:
    - 80
    environment:
    - DB_HOST=bookstack_db
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=secret
    - VIRTUAL_HOST=[redacted]
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=[redacted]
    - LETSENCRYPT_EMAIL=[redacted]
    volumes:
    - uploads:/var/www/bookstack/public/uploads
    - storage:/var/www/bookstack/public/storage
    networks:
      - nw


networks:
  nw:
    name: bookstack_nw
    external: true
volumes:
  uploads:
    name: bookstack_uploads
    external: true
  storage:
    name: bookstack_storage
    external: true
```

Could anyone help me with this please?
