### ISSUE TITLE
Problem Nginx to Apache container

### ISSUE THREAD

**Issue by fgirardey** [nginx-proxy/nginx-proxy#234]
Hi,

I'm not sure if it's a bug but i've got a docker-compose.yml file with the following content :

``` yml
data:
  image: groupeforum/data

proxy:
  image: jwilder/nginx-proxy
  hostname: local.dev
  ports:
    - "80:80"
    - "443:443"

wordpress:
  image: groupeforum/wordpress
  links:
    - db:mysql
    - maildev:maildev
  volumes:
    - ./app:/var/www/html
  environment:
    VIRTUAL_HOST: local.dev
    APP_ENV: local
  restart: always

db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: database
    MYSQL_USER: user
    MYSQL_PASSWORD: password
  volumes_from:
    - data
  ports:
    - "3306:3306"
  restart: always

maildev:
  image: djfarrelly/maildev
  ports:
    - "1080:80"
    - "1025:25"
```

To be short, the [groupeforum/wordpress](https://hub.docker.com/r/groupeforum/wordpress/) image is a simple PHP/Apache installation for my WordPress Workflow.

So i can't understand why when i type `http://local.dev` i only got the "Welcome to nginx!" web page.

Do i need to use Nginx on my [groupeforum/wordpress](https://hub.docker.com/r/groupeforum/wordpress/) image ?

**Comment by jmparra** [comment]
i think you need expose port 80 in wordpress

**Comment by idef1x** [comment]
Setting the hostname on the proxy to local.dev AND as VIRTUAL_HOST to wordpress doesn't seem right to me.. I can imagine that nginx will forward requests for local.dev to itself..hence the welcome to nginx result...
And as kmparra mentioned: the Dockerfile of the wordpress image you're using doesn't contain an EXPOSE entry..

**Comment by fgirardey** [comment]
I need to `EXPOSE 80` Even if the `FROM` image does it already ?

**Comment by thomasleveil** [comment]
try this:

    data:
      image: groupeforum/data

    proxy:
      image: jwilder/nginx-proxy
      ports:
        - "80:80"
        - "443:443"

    wordpress:
      image: groupeforum/wordpress
      links:
        - db:mysql
        - maildev:maildev
      volumes:
        - ./app:/var/www/html
      environment:
        VIRTUAL_HOST: local.dev
        APP_ENV: local
      restart: always
      expose:
        - "80"

    db:
      image: mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: database
        MYSQL_USER: user
        MYSQL_PASSWORD: password
      volumes_from:
        - data
      ports:
        - "3306:3306"
      restart: always

    maildev:
      image: djfarrelly/maildev
      ports:
        - "1080:80"
        - "1025:25"

**Comment by md5** [comment]
> I need to EXPOSE 80 Even if the FROM image does it already ?

@fgirardey No, that should mean it's already exposed. There's something else going on here.

The Nginx welcome page generally only shows when the config file generated by `nginx-proxy` is broken in some way.

**Comment by md5** [comment]
@fgirardey I notice you aren't mounting the `docker.sock` into your `nginx-proxy` container. That's likely the source of your problem. If you look at the output of `docker logs`, you'll likely see an error message from `docker-gen`.

**Comment by fgirardey** [comment]
Ah ? So i have to mount a volume like that : ?

```yaml
data:
  image: groupeforum/data

proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

wordpress:
  image: groupeforum/wordpress
  links:
    - db:mysql
    - maildev:maildev
  volumes:
    - ./app:/var/www/html
  environment:
    VIRTUAL_HOST: local.dev
    APP_ENV: local
  restart: always
  expose:
    - "80"

db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: database
    MYSQL_USER: user
    MYSQL_PASSWORD: password
  volumes_from:
    - data
  ports:
    - "3306:3306"
  restart: always

maildev:
  image: djfarrelly/maildev
  ports:
    - "1080:80"
    - "1025:25"
```
