### ISSUE TITLE
Cannot reach container in IPv6 network

### ISSUE THREAD

**Issue by Cilenco** [nginx-proxy/nginx-proxy#2351]
I'm trying to setup this container using an IPv6 network. When using it with a self created IPv4 network everything works fine. As soon as I enable IPv6 for the network my other containers are no longer reachable. Here is my nginx-proxy setup:

```yaml
version: '2'

services:
  nginx:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    environment:
      - ENABLE_IPV6=true
    networks:
      - nginx_ip6_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config:/etc/nginx/conf.d
      - certs:/etc/nginx/certs:ro
 
networks:
  nginx_ip6_network:
    name: nginx_ip6_network
    enable_ipv6: true
    ipam:
      config:
        - subnet: "fd00:4a82:739b::/64"
          gateway: "fd00:4a82:739b::ca0e:14ff:fe8d:8d84"
```
If I look at the network IPv6 is enabled, the IP addresses for IPv4 and IPv6 are correct and the driver is set to bridge. My other container looks like this:

```yaml
version: "3.8"

services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    networks:
      - nginx_ip6_network
    ports:
      - "853:853/tcp"
      - "853:853/udp"
      - "3000:3000"
    environment:
      VIRTUAL_HOST: "dns.domain.tld"
      VIRTUAL_PORT: 80
    volumes:
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf

networks:
  nginx_ip6_network:
    external: true
```
On my host IPv6 is working without issues. I can also see `listen [::]:80, listen [::]:443` in the default config. As soon as I comment out the IPv6 config on the network above everything work great again. What is the problem here (apart from me)?  Any help would be appreciated.
