### ISSUE TITLE
Regression in Behavior with Fix #2186 Affecting SSL Connections

### ISSUE THREAD

**Issue by vincent-herlemont** [nginx-proxy/nginx-proxy#2353]
## Description

After applying fix #2186, I've encountered a regression affecting SSL connections to localhost. Using entries in `/etc/hosts` pointing to `127.0.0.1`, such as `example.com.test` and `localhost`, I observed different behaviors between versions of `nginxproxy/nginx-proxy`.

### Environment

- **Hosts file entries**: `example.com.test` and `localhost` pointing to `127.0.0.1`
- **Web content**: `./html/index.html`

### Observed Behavior

With `nginxproxy/nginx-proxy:1.2.0`, both URLs (`https://example.com.test/` and `https://localhost/`) correctly display the content from `./html/index.html` :heavy_check_mark: 

However, after upgrading to `nginxproxy/nginx-proxy:1.2.3`:
- `https://example.com.test/` works fine and displays the expected content.
- `https://localhost/` fails to load with an `ERR_SSL_PROTOCOL_ERROR` :x: 

### Steps to Reproduce

1. Set up the `/etc/hosts` file with `127.0.0.1 example.com.test localhost`.
2. Run `nginxproxy/nginx-proxy:1.2.0` and observe both URLs working correctly.
3. Upgrade to `nginxproxy/nginx-proxy:1.3.0`.
4. Notice `https://localhost/` now results in a SSL protocol error.

### Additional Information

I used the following command to generate certificates:
```bash
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ${CN}.key -out ${CN}.crt -subj "/C=${C}/ST=${ST}/L=${L}/O=${O}/OU=${OU}/CN=${CN}"
```

Here is the `docker-compose.yml` file I used with `nginxproxy/nginx-proxy:1.2.0` or `nginxproxy/nginx-proxy:1.3.0`:
```yml
version: '3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.2.0
    container_name: nginx-proxy
    ports:
        - "80:80"
        - "443:443/tcp"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - proxy-network

  web:
    image: nginx
    container_name: nginx-static
    volumes:
      - ./html:/usr/share/nginx/html:ro
    environment:
      VIRTUAL_HOST: 'example.com.test'
      VIRTUAL_PORT: '80'
      VIRTUAL_PROTO: 'http'
    depends_on:
      - nginx-proxy
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge

volumes:
  certs:
  html:
```
