### ISSUE TITLE
connect() failed (111: Connection refused) while connecting to upstream

### ISSUE THREAD

**Issue by fractalf** [nginx-proxy/nginx-proxy#2374]
I know there are a couple of other (closed) issues existing, but neither seems to be related og fixing my issue ...

nginx-proxy

```yml
version: "3.7"

services:
    nginxproxy:
        container_name: nginx-proxy
        image: nginxproxy/nginx-proxy
        volumes:
            - certs:/etc/nginx/certs
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - /var/run/docker.sock:/tmp/docker.sock:ro
        environment:
            TRUST_DOWNSTREAM_PROXY: false
        ports:
            - 80:80
            - 443:443
        labels:
            - com.github.nginx-proxy.nginx

    nginxproxyacme:
        container_name: nginx-proxy-acme
        image: nginxproxy/acme-companion
        volumes:
            - certs:/etc/nginx/certs
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - acme:/etc/acme.sh 
        environment:
            DEFAULT_EMAIL: <email>
        depends_on:
            - nginxproxy

networks:
    default:
        name: proxy
        external: true

volumes:
    certs:
        driver_opts:
            type: none
            o: bind
            device: /home/alf/docker-data/nginx-proxy/certs
    vhost:
        driver_opts:
            type: none
            o: bind
            device: /home/alf/docker-data/nginx-proxy/vhost
    html:
        driver_opts:
            type: none
            o: bind
            device: /home/alf/docker-data/nginx-proxy/html
    acme:
        driver_opts:
            type: none
            o: bind
            device: /home/alf/docker-data/nginx-proxy/acme
```

Plain nginx app
```yml
version: "3.7"

services:
    matrix:
        container_name: matrix
        image: nginx:latest
        environment:
            # For ngix-proxy:
            VIRTUAL_HOST: <redacted host>
            VIRTUAL_PORT: 5110
            LETSENCRYPT_HOST: <redacted host>
        ports:
            - 5110:80
        restart: always

networks:
    default:
        name: proxy
        external: true
```

Error
```
nginx.1     | 2024/01/15 00:33:26 [error] 278#278: *88 connect() failed (111: Connection refused) while connecting to upstream, client: <ip>, server: <host>, request: "GET / HTTP/2.0", upstream: "http://172.18.0.4:5110/", host: "<host>"
nginx.1     | <host> <ip> - - [15/Jan/2024:00:33:26 +0000] "GET / HTTP/2.0" 502 157 "-" "curl/7.58.0" "172.18.0.4:5110"
```

Generated nginx
```nginx
# <redacted host>/
upstream <redacted host> {
    # Container: matrix
    #     networks:
    #         proxy (reachable)
    #     IP address: 172.18.0.4
    #     exposed ports: 80/tcp
    #     default port: 80
    #     using port: 5110
    server 172.18.0.4:5110;
}
server {
    server_name <redacted host>;
    access_log /var/log/nginx/access.log vhost;
    listen 80 ;
    # Do not HTTPS redirect Let's Encrypt ACME challenge
    location ^~ /.well-known/acme-challenge/ {
        auth_basic off;
        auth_request off;
        allow all;
        root /usr/share/nginx/html;
        try_files $uri =404;
        break;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}
server {
    server_name <redacted host>;
    access_log /var/log/nginx/access.log vhost;
    http2 on;
    listen 443 ssl ;
    ssl_session_timeout 5m;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;
    ssl_certificate /etc/nginx/certs/<redacted host>.crt;
    ssl_certificate_key /etc/nginx/certs/<redacted host>.key;
    ssl_dhparam /etc/nginx/certs/<redacted host>.dhparam.pem;
    ssl_stapling on;
    ssl_stapling_verify on;
    ssl_trusted_certificate /etc/nginx/certs/<redacted host>.chain.pem;
    set $sts_header "";
    if ($https) {
        set $sts_header "max-age=31536000";
    }
    add_header Strict-Transport-Security $sts_header always;
    include /etc/nginx/vhost.d/default;
    location / {
        proxy_pass http://<redacted host>;
        set $upstream_keepalive false;
    }
}
```

Thanks for any input, I'm stuck :)

**Comment by buchdag** [comment]
Hi
```yaml
version: "3.7"

services:
    matrix:
        container_name: matrix
        image: nginx:latest
        environment:
            # For ngix-proxy:
            VIRTUAL_HOST: <redacted host>
            VIRTUAL_PORT: 5110
            LETSENCRYPT_HOST: <redacted host>
        ports:
            - 5110:80
        restart: always

networks:
    default:
        name: proxy
        external: true
```

`VIRTUAL_PORT` should be the port your container is listening on (`80`), not the port you're publishing to on the host (`5110`).
