### ISSUE TITLE
FastCGI not working properly

### ISSUE THREAD

**Issue by fauzanelka** [nginx-proxy/nginx-proxy#2496]
Tried to set up php fpm + nginx proxy stack with docker compose

`docker-compose.yaml`
```yaml
x-default-policy: &default-policy
  restart: always 
  logging:
    driver: "json-file"
    options:
      max-size: "2048m"
  networks:
    - default

networks:
  default:

volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /etc/nginx/certs
  vhost:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /etc/nginx/vhost.d
  html:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /usr/share/nginx/html
  acme:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /etc/acme.sh
  mariadb_data:
  app_data:

services:
  mariadb:
    <<: *default-policy
    image: docker.io/bitnami/mariadb:11.2
    environment:
      - MARIADB_USER=wordpress
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-wordpress}
      - MARIADB_DATABASE=wordpress
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
  php-fpm:
    image: docker.io/bitnami/php-fpm:8.3
    environment:
      - VIRTUAL_PROTO=fastcgi
      - VIRTUAL_PORT=9000
      - VIRTUAL_ROOT=/var/www/html
      - VIRTUAL_HOST=mydomain.ltd
    volumes:
      - 'app_data:/var/www/html'
  nginx-proxy:
    <<: *default-policy
    image: docker.io/nginxproxy/nginx-proxy:1.6
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
    environment:
      - HTTPS_METHOD=redirect
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
  acme-companion:
    <<: *default-policy
    image: docker.io/nginxproxy/acme-companion:2.4
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

Error:
```bash
docker compose exec nginx-proxy nginx -T
```

```text
2024/07/29 15:25:40 [emerg] 43#43: open() "/etc/nginx/fastcgi.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:134
nginx: [emerg] open() "/etc/nginx/fastcgi.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:134
nginx: configuration file /etc/nginx/nginx.conf test failed
```

Current Workaround
Download: https://github.com/nginx/nginx/raw/master/conf/fastcgi.conf
Mount directly

`docker-compose.yaml`
```yaml
...
  nginx-proxy:
    <<: *default-policy
    image: docker.io/nginxproxy/nginx-proxy:1.6
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
    environment:
      - HTTPS_METHOD=redirect
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - fastcgi.conf:/etc/nginx/fastcgi.conf
...
```
