### ISSUE TITLE
Multiport does not support multi host

### ISSUE THREAD

**Issue by beartastic** [nginx-proxy/nginx-proxy#2543]
nginx-proxy version: 1.6.3

Trying to convert old VIRTUAL_HOST and VIRTUAL_PORT into multi ports for same container.

However, I think "multi host support" is missing in current implementation of VIRTUAL_HOST_MULTIPORTS.

My old code is:
```
VIRTUAL_HOST: sample.com,www.sample.com
VIRTUAL_PORT: 8069
```

What I want to do is to keep the same VIRTUAL_HOST names (in this case its multi host to a single container), and have multiple ports access that same container. So basically the function is multi host names and multi ports to one container.

The following code is something I tried, but does not work:

```
VIRTUAL_HOST_MULTIPORTS: |-
        sample.com,www.sample.com:
          "/":
            port: 8069
          "/websocket":
            port: 8072

```

I then tried doing the following, but it creates 2 separate sessions to the container instead of the original functionality:

```
VIRTUAL_HOST_MULTIPORTS: |-
        sample.com:
          "/":
            port: 8069
        www.sample.com:
          "/":
            port: 8069
          "/websocket":
            port: 8072

```

The readme file does not document the use case of multi host and multi port.

Additionally, I use the "Cert_name" of sample.com as well, I am not sure if this affects anything.

Is there a workaround, or is this something missing?

**Comment by SchoNie** [comment]
The [docs](https://github.com/nginx-proxy/nginx-proxy/tree/main/docs#multiple-ports) do describe a setup with multiple hostnames (I think you mean that with "multi host")?

I tried to reproduce your scenario and I can make a working config:
```yaml
      VIRTUAL_HOST_MULTIPORTS: |-
        sample.com:
          "/":
            port: 8069
            dest: "/"
          "/websocket":
            port: 8072
            dest: "/websocket"
        www.sample.com:
          "/":
            port: 8069
            dest: "/"
          "/websocket":
            port: 8072
            dest: "/websocket"
```

**Comment by beartastic** [comment]
> The [docs](https://github.com/nginx-proxy/nginx-proxy/tree/main/docs#multiple-ports) do describe a setup with multiple hostnames (I think you mean that with "multi host")?
> 
> I tried to reproduce your scenario and I can make a working config:
> 
> ```yaml
>       VIRTUAL_HOST_MULTIPORTS: |-
>         sample.com:
>           "/":
>             port: 8069
>             dest: "/"
>           "/websocket":
>             port: 8072
>             dest: "/websocket"
>         www.sample.com:
>           "/":
>             port: 8069
>             dest: "/"
>           "/websocket":
>             port: 8072
>             dest: "/websocket"
> ```

I have tried implementing your solution, but I am still getting an undesired effect. It seperates the session of sample.com and www.sample.com . To better explain what I mean is that if i go to sample.com, I reach my container in a logged in state. If I then open a new tab on my browser to go to www.sample.com, it goes to a login page. So it isn't attaching itself to the same session.

In my old code of VIRTUAL_HOST=sample.com,www.sample.com , both of those URLS go to the same session where I am already logged in.

I do believe this is something that needs to be addressed to adhere to original behavior. Or is there another solution I should be looking at?

I am using nginx-proxy for Odoo. Odoo uses 2 ports: 8069 and 8072.

**Comment by SchoNie** [comment]
nginx is not keeping login sessions. Its a proxy server and forwarding request to and from an upstream container handling that logic. If your logged in session is destroyed it is more likely a cookie configuration in your application.

So it sounds quite normal for me. It is related to browser's way how it deals with cookies.
If you change domain (www is really a different domain), the cookie is valid only for that domain and they won't get combined. They are different domains to the browser, which is why you're getting different data.
You can see in your browser DevTools what cookies are set for which Domain.

The best thing to do is decide which you want to use, www or non-www, and then 301 redirect all traffic to that one.

**Comment by beartastic** [comment]
> nginx is not keeping login sessions. Its a proxy server and forwarding request to and from an upstream container handling that logic. If your logged in session is destroyed it is more likely a cookie configuration in your application.
> 
> So it sounds quite normal for me. It is related to browser's way how it deals with cookies. If you change domain (www is really a different domain), the cookie is valid only for that domain and they won't get combined. They are different domains to the browser, which is why you're getting different data. You can see in your browser DevTools what cookies are set for which Domain.
> 
> The best thing to do is decide which you want to use, www or non-www, and then 301 redirect all traffic to that one.

This makes a lot of sense, I am not sure why I wasn't seeing the same behavior as original.

Is it possible you can point in the the right direction on how to most efficiently add onto what I already have to redirect sample.com to www.sample.com ?

Many thanks

**Comment by buchdag** [comment]
@beartastic on top of @SchoNie explanations, I just tested and those two configurations:

```yaml
services:
  test:
    image: nginx:1.27-alpine
    environment:
      VIRTUAL_HOST: nginx-proxy.tld,www.nginx-proxy.tld
```

```yaml
services:
  test:
    image: nginx:1.27-alpine
    environment:
      VIRTUAL_HOST_MULTIPORTS: |-
        nginx-proxy.tld:
          "/":
            port: 80
        www.nginx-proxy.tld:
          "/":
            port: 80
```

produces 100% identical nginx configurations.
