### ISSUE TITLE
How can we scapre metrics from nginx-proxy container

### ISSUE THREAD

**Issue by kranthikirang** [nginx-proxy/nginx-proxy#2588]
Hi, We would like understand if there is anyway to scrape prometheus metrics from the nginx-proxy container using /stub_status or something? Please share the information.

**Comment by barnes-c** [comment]
Hello @kranthikirang,

I'm using the [NGINX Prometheus Exporter](https://github.com/nginx/nginx-prometheus-exporter) to get my metrics into prometheus. 

This is how I use it. Pretty simple:

```yaml
version: '3.7'
services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
      - com.centurylinklabs.watchtower.scope=infrastructure
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - cache:/var/cache/nginx 
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf/uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf
      - ./conf/headercustomconf.conf:/etc/nginx/conf.d/headercustomconf.conf
      - ./conf/nginx-stubs.conf:/etc/nginx/conf.d/nginx-stubs.conf 
      ENABLE_IPV6: 'True'
      DEFAULT_HOST: "barnes.biz"


  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx-prometheus-exporter
    labels:
      - com.centurylinklabs.watchtower.scope=infrastructure
    restart: always
    command:
      - '--nginx.scrape-uri=http://nginx-proxy/nginx_status'
    ports:
      - "9113:9113"
    depends_on:
      - nginx-proxy
```

And then you have to define a job for prometheus to scrape:

```yaml
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - nginx-prometheus-exporter:9113
```

Hope this helps
