### ISSUE TITLE
[feature request] Support multiple entries in VIRTUAL_PATH

### ISSUE THREAD

**Issue by ddelange** [nginx-proxy/nginx-proxy#2595]
Hi 👋

Currently `VIRTUAL_PATH` only supports a single location block ([docs](https://github.com/nginx-proxy/nginx-proxy/blob/1.7.0/docs/README.md#path-based-routing)).

Our ingress in production uses multiple prefix blocks per service, and I'm running into issues translating this into docker compose.

I would like to pass a (newline separated) list of (regular) prefix paths to the `VIRTUAL_PATH` environment variable, because squashing them into a single regex as suggested by the docs is impossible:

- some backend prefixes in production:
  ```sh
    ...
  /r
    ...
  /t/engagement
  /t/insights
  /t/send-product-sample
  /tv
    ...
  ```
- some frontend prefixes in production:
  ```sh
  /  # catches homepage, and acts as the catch-all fallback prefix
    ...
  /r/capper
  /r/connected-accounts
  /refund-policy
    ...
  /t
    ...
  ```

When squashing these multiple (regular) prefix paths into two regex patterns, routing gets broken.
```
# backend VIRTUAL_PATH
~^(/r|/t/engagement|/t/insights|/t/send-product-sample|/tv)($|/)
# frontend VIRTUAL_PATH
~^(/r/capper|/r/connected-accounts|/refund-policy/t|/.*)($|/)
```
- The `($|/)` group is necessary to emulate prefix behaviour: no partial matches, e.g. `/t` (frontend) should not catch `/tv` (backend).
- The `/.*` clause in frontend emulates the `/` (regular) path prefix: homepage + catch-all fallback.
- Since nginx regex matching stops at the first match found (the order of regex location blocks matters), either the `/r` fallback or the `/t` fallback is erroneously/greedily chosen.
- I can't control the order of location blocks using env vars either: although the frontend service comes first in docker-compose.yml, `/r/connected-accounts` gets erroneously routed to the backend.
- I need a longest match wins approach, like is the case with multiple (regular) prefix paths.
- If I can specify multiple (regular) prefix paths in `VIRTUAL_PATH`, for instance newline separated, I can completely eliminate this regex hack from docker-compose.yml (we don't use regex whatsoever in production), and I can preserve the production routing behaviour.

**Comment by ddelange** [comment]
Hi @buchdag 👋 

Taking the liberty to ping you here as main maintainer. Any thoughts?

**Comment by buchdag** [comment]
Hi @ddelange 👋 

It's already possible to have multiple regular virtual paths per container when using [`VIRTUAL_HOST_MULTIPORTS`](https://github.com/nginx-proxy/nginx-proxy/tree/main/docs#multiple-ports), is that what you are looking for ? 🤔 

example:
```yaml
r_service:
  image: some/image
    environment:
      VIRTUAL_HOST_MULTIPORTS: |-
        www.your-app.tld:
          /r:

t_service:
  image: some/image
    environment:
      VIRTUAL_HOST_MULTIPORTS: |-
        www.your-app.tld:
          /t/engagement:
          /t/insights:
          /t/send-product-sample:

tv_service:
  image: some/image
    environment:
      VIRTUAL_HOST_MULTIPORTS: |-
        www.your-app.tld:
          /tv:
```
