### ISSUE TITLE
How to disable cache?

### ISSUE THREAD

**Issue by agostop** [nginx-proxy/nginx-proxy#2618]
So many error log like "1235 mkdir() "/var/cache/nginx/proxy_temp/9/58" failed (28: No space left on device) while reading upstream",
I must remove the container that can reslove it.

Are there have some environment variables to control this?

**Comment by buchdag** [comment]
Hi.

Could you please provide a bit more context on this issue ?
- what version of nginx-proxy are you using ?
- what is your nginx-proxy setup ? Could you provide a docker compose file ?
- _"I must remove the container that can reslove it."_ : which container are you talking about ?
- _"are there have some environment variables to control this?"_ : to control what ? 🤔

**Comment by agostop** [comment]
@buchdag 
thank you for reply.

**what version of nginx-proxy are you using ?**
I'm using the latest version of nginx-proxy.

**what is your nginx-proxy setup ? Could you provide a docker compose file ?**
I use nginx-proxy with acme-companion, I really like this combination, the compose file like blow:
```
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "20443:443"
    volumes:
      # The vhost and conf volumes are only required
      # if you plan to obtain standalone certificates
      - ./vhost:/etc/nginx/vhost.d
      # - conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - docker_internal

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      DEFAULT_EMAIL: someone@email.com
      ACME_CHALLENGE: DNS-01
      ACMESH_DNS_API_CONFIG: |-
          DNS_API: dns_cf
          CF_Token: xxx
          CF_Zone_ID: xxx
          CF_Account_ID: xxx
    volumes_from:
      - nginx-proxy
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - ./acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - docker_internal
```

**"I must remove the container that can reslove it." : which container are you talking about ?**
I often use this to provide file download service, after a while, my server's disk will be full. After my investigation, it was caused by the nginx-proxy container, I found the volumn of nginx-proxy using 80% disk space, so I used 'docker-compose stop nginx-proxy && docker-compose rm nginx-proxy && docker-compose up -d', then disk usage has returned to normal.


 **"are there have some environment variables to control this?" : to control what ?**
I mean, is there an environment variable that can control this disk cache function?
