### ISSUE TITLE
Issue while migrating from working 2 containers to 3 separate containers.

### ISSUE THREAD

**Issue by Bob-le-pirate** [nginx-proxy/nginx-proxy#2629]
Dear all,

I face some issues while trying to migrate an existing and working 2 containers nginx-reverse-proxy to a 3 separate containers.

Please find bellow my compose file:

```
services:
  # Nginx
  nginx-reverse-proxy:
    image: nginx:stable-alpine
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 128M
        reservations:
          memory: 64M
    labels:
        - "com.github.nginx-proxy.nginx-proxy.nginx"
    container_name: nginx-reverse-proxy
    restart: always
    ports:
        - "192.168.1.x:x:80"
        - "192.168.1.x:x:A"
    environment:
        - HTTPS_PORT=A
        - DEFAULT_ROOT=403
        - TRUST_DOWNSTREAM_PROXY=false
        - SSL_POLICY=Mozilla-Modern
        - LOG_FORMAT=$$host $$remote_addr - $$remote_user [$$time_local] "$$request" $$status $$body_bytes_sent "$$http_referer" "$$http_user_agent" "$$upstream_addr" $$ssl_protocol $$ssl_cipher "$$sent_http_content_type" $$request_time
        - DHPARAM_SKIP=true
    volumes:
        - ./conf:/etc/nginx/conf.d:ro
        - ./certs:/etc/nginx/certs:ro
        - ./vhost.d:/etc/nginx/vhost.d
        - ./htpasswd:/etc/nginx/htpasswd
        - html:/usr/share/nginx/html
        - ./log:/var/log/nginx/
        - ./dockergen_files/network_internal.conf:/etc/nginx/network_internal.conf
    networks:
        reverse_proxy:
            ipv4_address: 172.28.5.0 #nginx-reverse-proxy

  # Let's Encrypt
  letsencrypt-companion:
    image: nginxproxy/acme-companion:${TAG_LETSENCRYPT}
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 128M
        reservations:
          memory: 64M
    restart: always
    container_name: letsencrypt
    environment:
        - NGINX_PROXY_CONTAINER=nginx-reverse-proxy
        - LETSENCRYPT_HOST=foo.fr
        - LETSENCRYPT_EMAIL=x@y.fr
        - DEFAULT_EMAIL=x@y.fr
        - NGINX_DOCKER_GEN_CONTAINER=dockergen
    volumes_from:
        - nginx-reverse-proxy
    volumes:
        - ./certs:/etc/nginx/certs
        - /var/run/docker-userns.sock:/var/run/docker.sock:ro
        - ./acme:/etc/acme.sh
    networks:
        reverse_proxy:
            ipv4_address: 172.28.5.1 #letsencrypt

  # Docker-gen
  dockergen:
    image: nginxproxy/docker-gen
    container_name: dockergen
    command: -notify-sighup nginx-reverse-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
        - nginx-reverse-proxy
    volumes:
        - /var/run/docker-userns.sock:/tmp/docker.sock:ro
        - ./dockergen_files/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
        - ./conf:/etc/nginx/conf.d
    networks:
        - backend

volumes:
  conf:
  vhost.d:
  certs:
  htpasswd:
  acme:
  html:
  log:
  dockergen_files:

networks:
  reverse_proxy:
    external: true
  backend:
    internal: true
```
First of all, some remarks that could be added in the documentation:
1. network_internal.conf must be mounted in nginx container if you want to use `NETWORK_ACCESS=internal`
2. the command in docker-gen container `command: -notify-sighup nginx-reverse-proxy -watch...` must reflect the exact name of nginx container (here nginx-reverse-proxy)

Unfortunately, this compose doesn't work, absolutely no connection default.conf was correctly build, but it seems that nginx doesn't start correctly ? (for example open ports are 80, 443 instead of 80, A inside the container `netstat -tlnp`).

Can someone help me ?
