### ISSUE TITLE
directive "proxy_pass" is not terminated by ";" in /etc/nginx/conf.d/default.conf:42

### ISSUE THREAD

**Issue by casertap** [nginx-proxy/nginx-proxy#303]
I am using nginx-proxy with docker-compose but I get this error:

```
nginxproxy_1 | nginx.1    | 2015/11/26 19:41:18 [emerg] 13#13: directive "proxy_pass" is not terminated by ";" in /etc/nginx/conf.d/default.conf:42
```

So it fail at startup and exit the nginx-proxy container.

my docker-compose is pretty simple:

```
nginxproxy:
    image: jwilder/nginx-proxy
    ports:
        - "80:80"
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro

backup:
    image: busybox
    volumes:
        - $PWD/backup:/backup

mysqldata:
    image: busybox
    volumes:
        - /var/lib/mysql

mysql:
    image: mysql:5.7
    volumes_from:
        - mysqldata
        - backup
    env_file:
        - .env

wpprogdata:
    image: busybox
    volumes:
        - /var/www/html
wpprog:
    image: wordpress
    volumes_from:
        - wpprogdata
        - backup
    links:
        - mysql
    environment:
        - WORDPRESS_DB_NAME=prog
        - VIRTUAL_HOST=docker1.com
    env_file:
        - .env
    expose:
        - "80"
    #ports:
    #    - "8080:80"

wptraddata:
    image: busybox
    volumes:
        - /var/www/html
wptrad:
    image: wordpress
    volumes_from:
        - wptraddata
        - backup
    links:
        - mysql
    env_file:
        - .env
    environment:
        - WORDPRESS_DB_NAME=trad
        - VIRTUAL_HOST=docker2.com
    expose:
        - "80"
    #ports:
    #    - "8081:80"

```

**Comment by wader** [comment]
Can you paste the generated conf somewhere? `docker exec -ti <nginx-proxy-container> cat /etc/nginx/conf.d/default.conf`

**Comment by casertap** [comment]
impossible ngnix-proxy does not even start.
Here is the default.conf using the docker run command:

````
docker run -ti jwilder/nginx-proxy cat /etc/nginx/conf.d/default.conf                                                                       
ERROR: you need to share your Docker host socket with a volume at /tmp/docker.sock
Typically you should run your jwilder/nginx-proxy with: `-v /var/run/docker.sock:/tmp/docker.sock:ro`
See the documentation at http://git.io/vZaGJ
server {
    listen       80;
    server_name  localhost;

    #charset koi8-r;
    #access_log  /var/log/nginx/log/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
   #                                                                                                                                                                                                [11/64]
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    #location ~ \.php$ {
    #    root           html;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #    include        fastcgi_params;
   #}

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}
````

**Comment by wader** [comment]
Ah yeah... and that is probably just the default.conf that gets overwritten. But try this:

    docker run \
        -ti --rm \
        -v /etc/nginx-proxy/certs:/etc/nginx/certs:ro \
        -v ...cert volume etc... \
        nginx-proxy docker-gen -only-exposed /app/nginx.tmpl

That should print out the config on stdout

**Comment by casertap** [comment]
I did 
````
docker run \
    -ti --rm \
    -v /var/run/docker.sock:/tmp/docker.sock:ro \
    jwilder/nginx-proxy docker-gen -only-exposed /app/nginx.tmpl
````
here is the result:
````
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server                                                                                                                                         
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        return 503;
}
upstream docker1.com {
                        # wpprog
                        server 172.17.0.4:80;
}
server {                                                                                                                                                                                              
        server_name docker1.com;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://docker1.com;
        }
}
upstream docker2.com {
                        # wptrad
                        server 172.17.0.5:80;
}
server {
        server_name docker2.com;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://docker2.com;
        }
}

**Comment by casertap** [comment]
something strange happen because it is working now. I need to investigate this case a little more

**Comment by casertap** [comment]
Ho yes I change one thing in the mean time. I gave every container the name of the docker-compose bloc like this:
````
mysql:
    image: mysql:5.7
    container_name: mysql
    volumes_from:
        - mysqldata
        - backup
    env_file:
        - .env
````
