### ISSUE TITLE
Domain certificate & default_host

### ISSUE THREAD

**Issue by rgarrigue** [nginx-proxy/nginx-proxy#356]
Hello

I'm running a ghost blog container behind nginx-proxy. I recently added letsencrypt companion to give me some certificate and run into some trouble.

There's a certificate for my `domain.tld` which I gave to nginx proxy. Which default_host to `blog.domain.tld`, which got his own subdomain certificate. When I load `domain.tld`, Firefox tells me that the webpage is using `blog.domain.tld`.

I worked around this giving domain.tld's certificate directly to blog.domain.tld. But I'ld like to know if I missed a tweak in the configuration somewhere ?

**Comment by jwilder** [comment]
Maybe you need to specify `CERT_NAME`?  https://github.com/jwilder/nginx-proxy#sni

**Comment by rgarrigue** [comment]
Finally I made it work like this


```
proxy:
    environment:
    - DEFAULT_HOST=blog.${DOMAIN}

# Ghost blog
blog:
    ...
    environment:
    - VIRTUAL_HOST=blog.${DOMAIN}
    - LETSENCRYPT_HOST=${DOMAIN},blog.${DOMAIN}
```

Now I got a blog.domain.tld certificate which include domain.tld. I feel I
could have achieve that more elegantly, for now it'll do.


2016-02-01 16:31 GMT+01:00 Jason Wilder <notifications@github.com>:
