### ISSUE TITLE
Proxy sporadicly misses VIRTUAL_HOSTs

### ISSUE THREAD

**Issue by rwrnet** [nginx-proxy/nginx-proxy#360]
We came accross a serious issue. When starting multiple container with docker-compose, sporadicly nginx-proxy seems to miss one or more of the virtual host. In one of our environments, this happens in 3 out of 4 cases. Unfortunately, I wasn't able to reproduce the same consistent fail in a synthetic test environment. But still 1 out of 10 start ups lead to a missing host in the default.conf.

In order to demonstrate it, here is my test docker-compose.yml

```
proxy:
  image: jwilder/nginx-proxy
  volumes:
   - /var/run/docker.sock:/tmp/docker.sock:ro
  ports:
   - "81:80"
  environment:
   - DEFAULT_HOST=www.example.com

www1:
  image: httpd
  environment:
   - VIRTUAL_HOST=www.example.com

www2:
  image: httpd
  environment:
   - VIRTUAL_HOST=www.example.org
```

To observe the results I run a lookup on the proxys  default.conf:

```
watch -n1 'docker exec -it test_proxy_1 cat /etc/nginx/conf.d/default.conf | grep proxy_pass'
```

while constantly starting and stopping the containers:

```
while true; do docker-compose stop && sleep 2 && docker-compose up -d && sleep 5; done
```

With some patience, you will hopefully observe ending up with just the first of the two hosts. I even observed, having had both in it at the beginning, but then one disappeared. Seems like, sometimes event handling runs into race conditions. But this is just an educated guess.

Enviroment:

```
# docker-compose --version
docker-compose version 1.6.0, build d99cad6
# docker --version
Docker version 1.10.0, build 590d5108
```
