### ISSUE TITLE
invalid number of arguments in "upstream" directive in /etc/nginx/conf.d/default.conf

### ISSUE THREAD

**Issue by Nasjoe** [nginx-proxy/nginx-proxy#375]
Hi ! 
I work with you project and docker-letsencrypt-nginx-proxy-companion in order to use letsencrypt ssl.
(https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion)

It's work very well on 3 of my server, but crash into one.

It seem that one docker start with two arguments in the VIRTUAL_HOST env. like that :
`Docker run -ti -e VIRTUAL_HOST="www.foo.com www.bar.com"`

Unfortunately, the {{ $host }} variable in your nginx.tmpl just after the "upstream", in line 80, seem in cause. 
Nginx crash in the first line of the generated conf :

```
upstream www.foo.com www.bar.com {
            # foo
            server 172.17.0.3:80;
}
server {
    server_name  www.foo.com www.bar.com;
    listen 80 ;
    access_log /var/log/nginx/access.log vhost;
    include /etc/nginx/vhost.d/default;
    location / {
        proxy_pass http:// www.foo.com www.bar.com;
    }
}
```

Is there a solution to use the first argument within the nginx.tmpl ? On must i have to use always one dns in my VIRTUAL_HOST env ?

Many thanks,
Jonas

**Comment by jwilder** [comment]
@Nasjoe Separate your hosts w/ a comma, not spaces.  i.e. 
```
docker run -ti -e VIRTUAL_HOST="www.foo.com,www.bar.com"
```

**Comment by Nasjoe** [comment]
Oh, great ! 
Many Thanks Jwilder.

**Comment by pablorsk** [comment]
@Nasjoe I have the same problem but I'm using `docker-compose`, and my vhost file says:

```
access_log /var/log/nginx/access.log;
error_log   /var/log/nginx/error.log;

server {
	listen 0.0.0.0:80;
	server_name localhost;
	root /var/www/html/web/;

	rewrite ^/app\.php/?(.*)$ /$1 permanent;
	try_files $uri @rewriteapp;
	location @rewriteapp {
		rewrite ^(.*)$ /app.php/$1 last;
	}
    location ~ ^/(app)\.php(/|$) {
		fastcgi_split_path_info ^(.+\.php)(/.*)$;
		fastcgi_param HTTPS off;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		include       /etc/nginx/fastcgi_params;

		fastcgi_index index.php;
		send_timeout  1800;
		fastcgi_read_timeout 1800;
		fastcgi_pass  phpfpm:9000;
	}

	location  /php/fpm/status {
		fastcgi_pass   phpfpm:9000;
		fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
		include        /etc/nginx/fastcgi_params;
	}

	location /php/fpm/ping {
		fastcgi_pass   phpfpm:9000;
		fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
		include        /etc/nginx/fastcgi_params;
	}
}
```
And logs says:
```
nginx-proxy_1        | forego     | starting dockergen.1 on port 5000
nginx-proxy_1        | forego     | starting nginx.1 on port 5100
nginx-proxy_1        | nginx.1    | 2017/05/31 17:50:48 [emerg] 22#22: invalid number of arguments in "upstream" directive in /etc/nginx/conf.d/default.conf:49
nginx-proxy_1        | forego     | starting nginx.1 on port 5200
nginx-proxy_1        | forego     | sending SIGTERM to dockergen.1
nginx-proxy_1        | forego     | sending SIGTERM to nginx.1
```

any ideas?

**Comment by deepeeess** [comment]
@pablorsk I've received that error on a couple of different occasions and I have no idea why. It seems like removing the `jwilder/nginx-proxy` image and rebuilding helps.

**Comment by vella-nicholas** [comment]
The solution suggested by @deepeeess worked for me too. Stopped the container, removed the image and re-created the containers.

**Comment by renepardon** [comment]
I receive the same error `2019/05/06 06:56:38 [emerg] 1#1: invalid number of arguments in "upstream" directive in /etc/nginx/conf.d/default.conf:62` when running in swarm mode.

I deploy the following configuration:

```yaml
version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /srv/www/nginx-proxy/conf.d:/etc/nginx/conf.d
      - /srv/www/nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - /srv/www/nginx-proxy/html:/usr/share/nginx/html
      - /srv/www/nginx-proxy/certs:/etc/nginx/certs:ro
      - /srv/www/nginx-proxy/htpasswd:/etc/nginx/htpasswd
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /srv/www/nginx-proxy/conf.d:/etc/nginx/conf.d
      - /srv/www/nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - /srv/www/nginx-proxy/html:/usr/share/nginx/html
      - /srv/www/nginx-proxy/certs:/etc/nginx/certs:ro
      - /srv/www/nginx-proxy/htpasswd:/etc/nginx/htpasswd
      - /srv/www/nginx-proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    volumes:
      - /srv/www/nginx-proxy/conf.d:/etc/nginx/conf.d
      - /srv/www/nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - /srv/www/nginx-proxy/html:/usr/share/nginx/html
      - /srv/www/nginx-proxy/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  smtp:
    image: mwader/postfix-relay
    container_name: smtp
    restart: always
    expose:
      - 25
    environment:
      - POSTFIX_myhostname=smtp.example.com
      - OPENDKIM_DOMAINS=smtp.example.com
    deploy:
      replicas: 2
      restart_policy:
        condition: any

networks:
  default:
    external:
      name: nginx-proxy
```

with this command:

    docker stack deploy --compose-file `pwd`/docker-compose.yml nginx-proxy
