### ISSUE TITLE
docker ip is not generated in the /etc/nginx/conf.d/default.conf file

### ISSUE THREAD

**Issue by odedpriva** [nginx-proxy/nginx-proxy#380]
I started the proxy container using the following command
`docker run -d -p 80:80 --net=node_default --name proxy -v /var/run/docker.sock:/tmp/docker.sock -t jwilder/nginx-proxy`

I started a simple node container 

```
FROM node:4.2
WORKDIR /srv
ADD ./package.json /srv/package.json
RUN npm install
ADD . /srv
EXPOSE 3000
CMD node app.js
```

my docker-compose file 

```
version: "2"

services:
  worker:
    image: docker-node-meetup9
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: node app.js
    hostname: docker-node-meetup9
    environment:
      - VIRTUAL_HOST=myapp1.dev
```

here is what was generated in the /etc/nginx/conf.d/default.conf file
`
upstream myapp1.dev {
            # node_worker_1
            server :3000;
}
server {
    server_name myapp1.dev;
    listen 80 ;
    access_log /var/log/nginx/access.log vhost;
    location / {
        proxy_pass http://myapp1.dev;
    }
}
`

the container ip is missing. 

any idea why? 

```
➜  node git:(master) ✗ docker version
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Fri Feb 12 22:11:40 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      linux/amd64
```

```
➜  node git:(master) ✗ docker-compose version
docker-compose version 1.6.0, build unknown
docker-py version: 1.7.0
CPython version: 2.7.10
OpenSSL version: OpenSSL 0.9.8zg 14 July 2015
```
