### ISSUE TITLE
New docker-compose syntax ?

### ISSUE THREAD

**Issue by prigal** [nginx-proxy/nginx-proxy#448]
Hello,

Can someone please provide a clean docker-compose syntax example since release 0.3.0  ?

I have multiple projects on my machine, I have to run a container doing proxy but how can I describe each of my docker-compose.yml ?

This is on of mine for an old php53 app : 

```
version: '2'
services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: mydb
            MYSQL_USER: myuser
            MYSQL_PASSWORD: mypass
    php:
        build: ./config/docker/docker-php-5.3
        expose:
            - "9000"
        volumes:
            - .:/var/www/html
        links:
            - db
    nginx:
        build: ./config/docker/nginx
        expose:
            - "80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
        environment:
            VIRTUAL_HOST: 'www.myapp.dev' 

```

I have to do docker-compose up and then start the proxy to have it redirecting me to my app, but I think there is something wrong because nginx container can't catch the domain name. (My nginx vhost isn't working, default nginx page is displayed. I suppose domain name isn't understood by my nginx container. I may have an config error on my nginx container but before I want to be sure my docker-compose is OK.)

Thank you !
