### ISSUE TITLE
Pass in basic auth via BASIC_AUTH env var

### ISSUE THREAD

**Issue by bhurlow** [nginx-proxy/nginx-proxy#456]
I think it would be super convenient to be able to dynamically pass in basic auth credentials via a `BASIC_AUTH=foo:bar` environment variable. This way you could open and close access to virtual hosts without altering the proxy. You could also rotate credentials quickly. 

Obviously there are some security considerations here. Also not sure if nginx requires that basic auth be read from disk a la apache.

Thoughts?

**Comment by wodzik** [comment]
I made something similar for nginx, but i have no idea how to merge with docker-gen templates. Probably docker-gen can check if exist .htpasswd-${domain} file, but i have no idea how to generate htpasswd files. 

My entrypoint for nginx: https://github.com/droptica/docker-images/blob/master/nginx/entrypoint.sh

**Comment by kachkaev** [comment]
Agree that this would be a pretty useful feature! For me this image is a part of `nginx-proxy/docker-gen/letsencrypt-companion` bundle, behind which I'd like to keep various websites and services such as [`netdata`](https://github.com/firehol/netdata). I've seen a few cases when web-based endpoints expect to run behind a reverse-proxy, which is not a part of them. And the tutorials suggest setting up the domain, the auth and the certs outside those services as this not really their job (`netdata` [does this](https://github.com/firehol/netdata/wiki/Running-behind-nginx#enable-authentication), for instance).

Currently it seems necessary to have two reverse-proxies in front of a dockerized app that does not support simple auth out-of-box. Being able to pass `HTTP_LOGIN` and `HTTP_PASSWORD` as env variables the same way as `HOST` etc. feels like a natural thing.

**Comment by kachkaev** [comment]
It's not just `netdata` and similar tools actually. Another common use case is any staging website, which needs to be protected from accidental indexing and visits by strangers. I actually keep a few of such websites behind HTTP auth at the moment, but have to enable it in a custom way. Here is my typical `docker-compose` for a small pre-build Node.js webapp:

```yml

version: "2"
services:
  web:
    build: .
    environment:
      - VIRTUAL_HOST=${SUBDOMAIN}.${ROOT_HOST},www.${SUBDOMAIN}.${ROOT_HOST}
      - VIRTUAL_PORT=80
      - VIRTUAL_NETWORK=proxy
      - LETSENCRYPT_HOST=${SUBDOMAIN}.${ROOT_HOST},www.${SUBDOMAIN}.${ROOT_HOST}
      - LETSENCRYPT_EMAIL=admin@${ROOT_HOST}
      - HTTP_AUTH_LOGIN
      - HTTP_AUTH_PASSWORD
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external:
      name: proxy
```
(some env variables are taken from `.env` in the same folder)

To enable `HTTP_AUTH` now I have to have a custom entry point similar to the one by @wodzik in every project:

```
#build.sh
#!/bin/bash

if [ "${HTTP_AUTH_PASSWORD}" != "" ]; then
  sed -i "s/#auth_basic/auth_basic/g;" /etc/nginx/nginx.conf
  rm -rf /etc/nginx/.htpasswd
  echo -n $HTTP_AUTH_LOGIN:$(openssl passwd -apr1 $HTTP_AUTH_PASSWORD) >> /etc/nginx/.htpasswd
  echo "Basic auth is on for user ${HTTP_AUTH_LOGIN}..."
else
  echo "Basic auth is off (HTTP_AUTH_PASSWORD not provided)"
fi

nginx -g "daemon off;"
```
Inside `nginx.conf`:

```

  server {
    listen 80;
    root /usr/share/nginx/html;
    #auth_basic "";
    #auth_basic_user_file /etc/nginx/.htpasswd;

    # ↑ the above lines are uncommented by start.sh when needed

    # .... (other stuff)
}
```

So just to turn on the auth there is now a need to create a custom `Dockerfile` and to keep a copy of this `start.sh` in every new project. It would be much better to have `HTTP_AUTH_LOGIN` and `HTTP_AUTH_PASSWORD` handled by the reverse-proxy automatically. At least this feels to me like a very natural thing.

@jwilder how about considering this feature in one of the next minor versions? Feel free to re-use my scripts if you want.
