### ISSUE TITLE
nginx-proxy doesn't https 301 auto redirect

### ISSUE THREAD

**Issue by sandrodz** [nginx-proxy/nginx-proxy#461]
I'm facing weird issue, all other sites are properly redirected with 301 via nginx-proxy. but 1 domain returns 200 instead of 301.

```
curl -k --head portfolio.sandrophoto.com
HTTP/1.1 200 OK
Server: nginx/1.9.12
Date: Tue, 17 May 2016 12:36:49 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
X-Powered-By: PHP/5.6.21
X-Pingback: https://portfolio.sandrophoto.com/xmlrpc.php

curl -k --head sandrophoto.com          
HTTP/1.1 301 Moved Permanently
Server: nginx/1.9.12
Date: Tue, 17 May 2016 12:37:15 GMT
Content-Type: text/html
Content-Length: 185
Connection: keep-alive
Location: https://sandrophoto.com/
```

```
VIRTUAL_HOST: |
      sandrophoto.com,
      www.sandrophoto.com,
      portfolio.sandrophoto.com
LETSENCRYPT_HOST: |
      sandrophoto.com,
      portfolio.sandrophoto.com
```

I don't see anything alarming in logs neither of nginx-proxy nor the nginx-webserver. Is there any reason why it would fail redirect?

btw, going to https directly works fine, so ssl keys are generated and ready.

p.s. redirect atm is done via php, this is why I'm checking headers with curl. something seems off.

**Comment by wader** [comment]
Hi, can you provide more config and generated nginx config? no `HTTPS_METHOD=noredirect` involved? can you clarify what you mean by redirect is done via php? the http -> https redirect?

**Comment by sandrodz** [comment]
```
webserver
  image: nginx:latest
  container_name: webserver
  ports:
    - "127.0.0.1::80"
    - "127.0.0.1::443"
  links:
    - php5-fpm
    - php7-fpm
  restart: always
  environment:
    VIRTUAL_HOST: |
      www.sandrophoto.com,
      portfolio.sandrophoto.com
    LETSENCRYPT_HOST: |
      sandrophoto.com,
      portfolio.sandrophoto.com
    LETSENCRYPT_EMAIL: support@weare.de.com
  volumes:
    - ./sites:/etc/nginx/sites
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./nginx-wp-common.conf:/etc/nginx/nginx-wp-common.conf
    - ./nginx-php-common.conf:/etc/nginx/nginx-php-common.conf
    - /srv/www:/www

nginx-proxy:
  image: jwilder/nginx-proxy
  container_name: nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  restart: always
  environment:
    - DEFAULT_HOST=njord.weare.de.com
  volumes:
    - /srv/certs:/etc/nginx/certs:ro
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./vhost.d:/etc/nginx/vhost.d
    - /usr/share/nginx/html


nginx-certs:
  image: jrcs/letsencrypt-nginx-proxy-companion
  container_name: nginx-certs
  volumes:
    - /srv/certs:/etc/nginx/certs:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
  volumes_from:
    - nginx-proxy
```
nginx default
```
upstream 
portfolio.sandrophoto.com
 {
				## Can be connect with "bridge" network
			# webserver
			server 172.17.0.8:80;
}
server {
	server_name 
portfolio.sandrophoto.com
;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	include /etc/nginx/vhost.d/default;
	location / {
		proxy_pass http://portfolio.sandrophoto.com;
	}
}
upstream 
sandrophoto.com {
				## Can be connect with "bridge" network
			# webserver
			server 172.17.0.8:80;
}
server {
	server_name 
sandrophoto.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	return 301 https://$host$request_uri;
}
server {
	server_name 
sandrophoto.com;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA;
	ssl_prefer_server_ciphers on;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_certificate /etc/nginx/certs/sandrophoto.com.crt;
	ssl_certificate_key /etc/nginx/certs/sandrophoto.com.key;
	ssl_dhparam /etc/nginx/certs/sandrophoto.com.dhparam.pem;
	add_header Strict-Transport-Security "max-age=31536000";
	include /etc/nginx/vhost.d/default;
	location / {
		proxy_pass http://sandrophoto.com;
	}
}
```
