### ISSUE TITLE
My default.conf is always deleted when restart

### ISSUE THREAD

**Issue by Quentinvarquet** [nginx-proxy/nginx-proxy#470]
Hello,

I am using a custom default.conf file in /etc/nginx/conf.d/default.conf

But every time I restart (docker-compose restart) my default.conf file (volume) is back with the default configuration

Do you know how to fix it ? It's the first time I have this problem.

**Comment by wader** [comment]
You have `/etc/nginx/conf.d/default.conf` on volume and edit it manually? you should probably have a custom `nginx.tmpl` or put custom things in `conf.d` etc.
Can you give more information about your setup?

**Comment by Quentinvarquet** [comment]
Hello,

My configuration is very simple, here is my docker-compose file  : 


```
nginxproxy:
  image: jwilder/nginx-proxy
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d
   - ./nginx-proxy/cache:/var/cache/nginx
   - ./nginx-proxy/certs:/etc/nginx/certs
   - /var/run/docker.sock:/tmp/docker.sock
   - ./nginx-proxy/conf.d/default.conf:/etc/nginx/conf.d/default.conf
```

When I update my default.conf from my server and then I connect in the container : service nginx reload. The configuration is updated and my modification in default.conf works.

But if I restart my container : docker-compose restart. My default.conf is back with the default configuration.

For your information, I am using an old version of your container (june or may 2015, maybe you fixed it in your last version :-) )
