### ISSUE TITLE
Wrong choose of SSL certificate with DEFAULT_HOST (support multiple certificates for one backend container)

### ISSUE THREAD

**Issue by iBobik** [nginx-proxy/nginx-proxy#497]
I want to send all traffic without specific container on one conteiner where are multiple virtual hosts:

```
proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  environment:
    DEFAULT_HOST: sites.example.com
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

static:
  image: teonite/nginx-dynamic-sites
  environment:
    VIRTUAL_HOST: sites.example.com

app:
  image: app
  environment:
    VIRTUAL_HOST: app.com
```

If there is request to app.com it will be send to app container and chosen app.com.crt. But if there will be request to something.com it will be send to static container, but it will use sites.example.com.crt (=> not valid certificate for hostname).

So it seems proxy will choose certificate by DEFAULT_HOST not by hostname from request.
