### ISSUE TITLE
Cannot run on multiple containers in docker cloud

### ISSUE THREAD

**Issue by mrsimonemms** [nginx-proxy/nginx-proxy#549]
Hi

I'm using this on Docker Cloud and it works pretty well (thanks) when I'm running everything on a single machine (node, in Cloud terminology). However, I'm having a problem when I scale beyond a single node.

My stackfile (similar to compose.yml) is.

``` yml
content:
  image: tutum/hello-world:latest
  environment:
    - VIRTUAL_HOST=hello-world.example.com
  tags:
    - one

nginx:
  image: jwilder/nginx-proxy:latest
  links:
    - content
  ports:
    - 80:80
    - 443:443
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  sequential_deployment: true
  tags:
    - one
```

I've got a cluster of two machines, each with a tag of "one" and "two".  When I run the `nginx` and `content` containers on the same physical machine, it works fine. However, when I put it on a separate machine (change the tag to "two"), it doesn't configure correctly.

I've done a bit of digging and it appears that the nginx `default.conf` file is built differently.

**default.conf** - both on the "one" container

```
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        return 503;
}
upstream hello-world.example.com {
                    ## Can be connect with "bridge" network
                # content-1.test.56b60b84
                server 172.17.0.6:80;
                    ## Can be connect with "dockercloud" network
                # content-1.test.56b60b84
                server 10.7.0.2:80;
}
server {
        server_name hello-world.example.com;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
            proxy_pass http://hello-world.example.com;
        }
}
```

**default.conf** - nginx on "one" and content on "two" container

```
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        return 503;
}
```

As you can see, putting it on different machines means that the conf file loses the `upstream` and second `server` part of the conf file.  

Can anyone explain why and how I might be able to fix this?

I should point out that all the environment variables are being set correctly and the two machines can physically talk to each other as I would expect.

Thanks

**Comment by amegianeg** [comment]
Hi riggerthegeek,
my guess is that this is not a DC issue, this is a `nginx-proxy` issue. `nginx-proxy` is the aggregation of a Nginx server and `docker-gen` container, this last creates Nginx configurations based on what it reads from the Docker socket. So if there are containers with ports exposed (like `tutum/hello-world`, port 80), it reads it from the mounted socket and generates the configuration for the Nginx server. This works for the first approach where both containers in your stackfile are in the same node. When you deploy them in different nodes, the `docker-gen` container is not able to read the Docker socket from the other node, so it does not generate the configuration file for the `hello-world` container.
The way I'm thinking of solving this, DC based, is using the overlay network we provide to connect all your nodes to perform service discovery and build that config file.
Hope it helps!

**Comment by riggerthegeek** [comment]
I've opened up a ticket with Docker Cloud and they've confirmed that the stacks work in the same way as overlay networking so your suggestion is what I'm already doing.

I've also done some hacking with the [dockercloud-haproxy](https://github.com/docker/dockercloud-haproxy) container and I think you're right that it's an `nginx-proxy` issue.

These both use the `/var/run/docker.sock` socket underneath to discover linked containers and the HAproxy container works as across machines.

```yml
lb:
  image: 'dockercloud/haproxy:latest'
  links:
    - web1
  ports:
    - '8080:80'
  tags:
    - one
web1:
  image: 'dockercloud/hello-world:latest'
  tags:
    - two
```

As with the `nginx-proxy` example, the two containers are sat are two physically different machines and they are talking perfectly happy with each other (see http://lb.test.eb2acdf2.svc.dockerapp.io:8080 for proof).

So, my question is this - where can I find how the `docker.sock` is consumed by `nginx-proxy` and what documentation is out there for out to use it?  I've had a (cursory) look and couldn't find much.

Ultimately, I'd like to create a pull request with a fix that works across the Docker ecosystem.

**Comment by riggerthegeek** [comment]
I've come up with a workaround for this problem. It's not a fix as such, but it's probably a better solution. The basic idea is to add `deployment_strategy: every_node` to every instance of the nginx proxy. A working configuration might then be:

```
content:
  image: tutum/hello-world:latest
  environment:
    - VIRTUAL_HOST=hello-world.example.com
  tags:
    - one

nginx:
  image: jwilder/nginx-proxy:latest
  deployment_strategy: every_node
  links:
    - content
  ports:
    - 80:80
    - 443:443
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  sequential_deployment: true
```

The only practical difference becomes that you have to run the nginx-proxy on every node (notice I've gotten rid of the `tag` in the nginx-proxy config).

Although this is a fix for me, it might be worth keeping this issue open.
