### ISSUE TITLE
Running virtual hosts on different ports of the same container

### ISSUE THREAD

**Issue by dcerecedo** [nginx-proxy/nginx-proxy#560]
I'm trying to run sonatype/nexus3 behind jwilder/nginx-proxy. I made it work without problems as nexus.mydomain.com over TSL using letsencrypt certificates:

`docker run --restart=always --name nginx -d -p 80:80 -p 443:443 -v /root/certs/:/etc/nginx/certs -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy`

`docker run --restart=always -d -p 8081:8081  --name nexus -e VIRTUAL_HOST=nexus.mydomain.com -v /root/nexus-data:/nexus-data sonatype/nexus3`

Then I realized that to get a docker private repository running I needed to expose another port. So I created the docker repo on port 8082 and recreated the container using the saved configuration, exposing the new port and with two subdomains:

`docker run --restart=always -d -p 8081:8081 -p 8082:8082 --name nexus -e VIRTUAL_HOST=nexus.mydomain.com,docker.mydomain.com -v /root/nexus-data:/nexus-data sonatype/nexus3`

I'd like to get nginx proxying nexus subdomain to port 8081 of the nexus container and proxying docker subdomain to port 8082 of the same container. Is this possible? 

I have tried overriding nginx configuration mounting a volume on `/etc/nginx/vhost.d` with no success. Any clues?

**Comment by mohamed-el-habib** [comment]
Multi port cantainers is not supported by nginx-proxy.
To have a nexus3 work throw nginx-proxy, i used an other nginx container that expose the port 8082

``

	touch ./conf.d/default.conf.disabled

	cat > ./conf.d/docker.mydomain.com.conf <<- EOF
	server {
		listen 8082;
		server_name nexus-proxy;

		client_max_body_size 0;

		location / {
			proxy_set_header   X-Real-IP \$remote_addr;
			proxy_set_header   Host      \$http_host;
			proxy_pass         http://nexus:8082;
			proxy_read_timeout 900;
		}
	}
	EOF

	docker run --restart=always --name nginx-proxy -d -p 80:80 -p 443:443 -v /root/certs/:/etc/nginx/certs -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy

	docker run -d
			--restart=always
			--expose 8082 --link nexus 
			--name nexus-proxy
			-v ./conf.d:/etc/nginx/conf.d 
			-e "VIRTUAL_HOST=docker.mydomain.com" -e "VIRTUAL_PORT=8082"  
			nginx

	docker run --restart=always -d -p 8081:8081 --name nexus -e VIRTUAL_HOST=nexus.mydomain.com -v /root/nexus-data:/nexus-data sonatype/nexus3	

``

**Comment by captncraig** [comment]
I would also like this feature. I was able to hack it into a template by specifying virtual hosts in format `VIRTUAL_HOST=hosta.com:8087,hostb.com:8086`. Split the host into parts on `:`, use the first part as the hostname, and if there are more parts, use the other one as the port later in the block. It is super counterintuitive though, because the port is not the port to host on, but the internal container port to bind that host to.

I would have liked to define something like
```
VIRTUAL_HOST=hosta.com,hostb.com
VIRTUAL_PORT=8087,8086
```
But I had severe trouble splitting the ports and matching them back to the corresponding indexed host inside the template. I fear at least on new helper function would be needed to support something like that.

**Comment by dcerecedo** [comment]
@captncraig I don't think it's counter intuitive at all. In fact you can see in the same `docker run` command that you are binding a subdomain to an exposed port in that container.
For me it makes all the sense.
Do you have a public image for this? I'd like to use it. Or better, make a pull request to nginx-proxy. This is indeed a very useful feature!

**Comment by gallexme** [comment]
need this aswell

**Comment by captncraig** [comment]
@dcerecedo I actually implemented similar functionality for a similar container I made for [caddy](https://caddyserver.com). The structure of the template is largely similar, and you may be able to back port it. Here's my template: https://github.com/captncraig/caddy-docker-proxy/blob/master/caddyfile.tpl#L21

**Comment by jgangemi** [comment]
this has been raised in #59 and there has been no movement in it what so ever which is very disappointing b/c it's preventing me from rolling out nexus 3 as well.

**Comment by alash3al** [comment]
I'm the author of droxy, and It supports this feature as well as multiple containers with the same hostname so it distributes the traffic between them, just take a look [here](https://github.com/alash3al/droxy/blob/master/README.md) .

**Comment by montoyaedu** [comment]
Hello all!

I think a possible solution could be mounting a custom nginx.tmpl as a volume for the nginx-proxy container.

In that way, we would not need to wait for this feature to be added within the mainstream nginx-proxy.

I will try to POST an example as soon as possible!

**Comment by jonovate** [comment]
For anyone still needing an out-of-box solution - maybe it'll give you new ideas:

Odoo (OpenERP) has a requirement where one container exposes 2 ports to the Network - and the 2nd port [8072] should only be used for a location /longpolling. 
Basically I created a new container which forwards the port back to the main, Nginx running container.  
The main Nginx container has just the one VIRTUAL_HOAT/VIRTUAL_PORT 
This new Container has the VIRTUAL_HOST/VIRTUAL_PORT so its picked up and an upstream is created for it.

What I did was create a new container - webchat/Dockerfile:
`#webchat
FROM alpine
RUN apk add --update socat && rm -rf /var/cache/apk/*
`
My Docker-Compose:
`...
  webchat:
    build:
      context: webchat
    command: socat TCP-LISTEN:8072,fork TCP:web:8072
    environment:
      - VIRTUAL_HOST=webchat
      - VIRTUAL_PORT=8072
    ports:
      - 8072
`
This then creates an upstream called http://webchat. (along with a server { } but its not a big deal)

Then via the vhost.d to add the location and pass to this new upstream:
```
location /longpolling {
        proxy_pass http://webchat;
    }
```

**Comment by dementor5** [comment]
I need too an opportunity on different ports of the same container to hang up different hosts.
Please merge this request.

> For anyone still needing an out-of-box solution - maybe it'll give you new ideas:
> 
> Odoo (OpenERP) has a requirement where one container exposes 2 ports to the Network - and the 2nd port [8072] should only be used for a location /longpolling.
> Basically I created a new container which forwards the port via socat back to the main, Nginx running container.
> 
> * The main Nginx container has just the one VIRTUAL_HOST/VIRTUAL_PORT
> * This new Container has the 2nd port's VIRTUAL_HOST/VIRTUAL_PORT so its picked up and an upstream is created for it.
> 
> What I did was create a new container - webchat/Dockerfile:
> 
> ```
> FROM alpine
> RUN apk add --update socat && rm -rf /var/cache/apk/*
> ```
> My Docker-Compose:
> 
> ```
>   webchat:
>     build:
>       context: webchat
>     command: socat TCP-LISTEN:8072,fork TCP:web:8072
>     environment:
>       - VIRTUAL_HOST=webchat
>       - VIRTUAL_PORT=8072
>     ports:
>       - 8072
> `    networks: 
>       - frontend
>     depends_on:
>       - web
> 
> web:
>     build:
>       args:
>         - ODOO_CONFIG=config/odoo.conf.pro
>     environment:
>       - VIRTUAL_HOST=odoo
>       - VIRTUAL_PORT=8069
>     ports:
>       - 8069
>       #- 8072   Is exposed internally by Dockerfile
>     networks:
>       - frontend
> ```
> This then creates an upstream called http://webchat. (along with a server { } but its not a big deal)
> 
> Then via the vhost.d, I add the location and pass to this new upstream:
> 
> ```
> location /longpolling {
>         proxy_pass http://webchat;
>     }
> ```

Thanks for this life hack.
I use it for BrowserSync:
```
bsui:
  image: alpine/socat
  command: TCP-LISTEN:3001,fork TCP:node:3001
  environment:
    - VIRTUAL_HOST=ui.bs.localhost
  expose:
    - "3001"

```

**Comment by JOduMonT** [comment]
I'm might be tired but where did you put this snippet ?

> location /longpolling {
>         proxy_pass http://webchat;
>     }

I means which directory ?
how nginx-proxy load it ?
;)

**Comment by jonovate** [comment]
@JOduMonT 
In your NGINX config you've customized (and that's where I suspect you will have the learning curve).

Search for "Per-VIRTUAL_HOST" in the main README.md.  It explains the concept but assumes you are very familiar with Docker and Docker-Compose. 

Here is what I ended up having (that snippet was in myodoo.com file below):

Files and Folders:
```
docker-compose.yml
/proxy/vhost.d/myodoo.com
/webchat/Dockerfile
```

Docker-Compose:
```
version: "3.7"

services:

  web:
    build:
      args:
    environment:
      - VIRTUAL_HOST=${ODOO_DOMAIN:-myodoo.com}
      - VIRTUAL_PORT=8069
      - LETSENCRYPT_HOST=${ODOO_DOMAIN:-myodoo.com}
      - LETSENCRYPT_EMAIL=admin@myodoo.com
    ports:
      - 8069
    networks:
      - frontend
    restart: always

  webchat:
    build:
      context: webchat
    command: socat TCP-LISTEN:8072,fork TCP:web:8072
    environment:
      - VIRTUAL_HOST=odoochat.myodoo.com
      - VIRTUAL_PORT=8072
    ports:
      - 8072
    networks: 
      - frontend
    depends_on:
      - web
    restart: always

  proxy:
    image: jwilder/nginx-proxy
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
    environment:
      - DEFAULT_HOST=${ODOO_DOMAIN:-myodoo.com}
      - SSL_POLICY=Mozilla-Modern
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy/certs:/etc/nginx/certs:ro
      - ./proxy/conf.d/overrides.conf:/etc/nginx/conf.d/overrides.conf:ro
      - ./proxy/vhost.d:/etc/nginx/vhost.d/:ro
      - ./proxy/html:/usr/share/nginx/html:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
    depends_on:
      - web
      - webchat
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./proxy/certs:/etc/nginx/certs
      - ./proxy/vhost.d:/etc/nginx/vhost.d      
      - ./proxy/html:/usr/share/nginx/html
    restart: always
    depends_on:
      - proxy
```

**Comment by Shardj** [comment]
Could I get some advice, I've been having no luck at all with what I'm trying to do. I simply want to map traffic as such:

- mongodb.localhost:27017 -> mongodb container still using 27017
- host.localhost -> host container, mapping ports 80, 443, 8080 or 8081 to the same port within the container
- cms.localhost -> cms container, mapping ports 80, 443, 8080 or 8081 to the same port within the container
- screen.localhost -> screen container, mapping ports 80, 443, 8080 or 8081 to the same port within the container
- backend.localhost:3600 -> backend container, using port 3600 still

But whatever I do I just can't get the ports to work as desired, the nginx-proxy seems to work only for port 80 while I need multiple ports or a port which isn't 80 for each of my containers. I really just want a DNS like reference from the various subdomains to the respective containers, with the port being requested always mapping to the same port in the container.

My docker-compose.yml:

```
version: '3.8'

services:
    proxy:
      container_name: proxy
      image: jwilder/nginx-proxy
      ports:
        - 27017:27017
        - 80:80
        - 443:443
        - 8080:8080
        - 8081:8081
        - 3600:3600
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro

    mongodb.localhost:
      container_name: mongodb
      build:
        context: .
        dockerfile: dockerstuff/modules/mongodb/mongodb.Dockerfile
      ports:
        - 27017
      volumes:
        - mongodb:/data/db
      restart: always
      environment:
        - VIRTUAL_HOST=mongodb.localhost:27017

    host.localhost:
      container_name: host
      build:
        context: .
        dockerfile: dockerstuff/modules/host/host.Dockerfile
      ports:
        - 80
        - 443
        - 8080
        - 8081
      volumes:
        - type: bind
          source: ignored/host
          target: /srv/www
        - type: bind
          source: $HOME/.gitconfig
          target: /home/developer/.gitconfig
        - type: bind
          source: $HOME/.ssh/id_rsa
          target: /home/developer/.ssh/id_rsa
      stdin_open: true
      tty: true
      cap_add:
        - SYS_PTRACE
      environment:
        - VIRTUAL_HOST=host.localhost:80,host.localhost:443,host.localhost:8080,host.localhost:8081

    cms.localhost:
      container_name: cms
      build:
        context: .
        dockerfile: dockerstuff/modules/cms/cms.Dockerfile
      ports:
        - 80
        - 443
        - 8080
        - 8081
      volumes:
        - type: bind
          source: ignored/cms
          target: /srv/www
        - type: bind
          source: $HOME/.gitconfig
          target: /home/developer/.gitconfig
        - type: bind
          source: $HOME/.ssh/id_rsa
          target: /home/developer/.ssh/id_rsa
      stdin_open: true
      tty: true
      cap_add:
        - SYS_PTRACE
      environment:
        - VIRTUAL_HOST=cms.localhost:80,cms.localhost:443,cms.localhost:8080,cms.localhost:8081

    screen.localhost:
      container_name: screen
      build:
        context: .
        dockerfile: dockerstuff/modules/screen/screen.Dockerfile
      ports:
        - 80
        - 443
        - 8080
        - 8081
      volumes:
        - type: bind
          source: ignored/screen
          target: /srv/www
        - type: bind
          source: $HOME/.gitconfig
          target: /home/developer/.gitconfig
        - type: bind
          source: $HOME/.ssh/id_rsa
          target: /home/developer/.ssh/id_rsa
      stdin_open: true
      tty: true
      cap_add:
        - SYS_PTRACE
      environment:
        - VIRTUAL_HOST=screen.localhost:80,screen.localhost:443,screen.localhost:8080,screen.localhost:8081

    backend.localhost:
      container_name: backend
      build:
        context: .
        dockerfile: dockerstuff/modules/backend/backend.Dockerfile
      ports:
        - 3600
      volumes:
        - type: bind
          source: ignored/backend
          target: /srv/www
        - type: bind
          source: $HOME/.gitconfig
          target: /home/developer/.gitconfig
        - type: bind
          source: $HOME/.ssh/id_rsa
          target: /home/developer/.ssh/id_rsa
      stdin_open: true
      tty: true
      cap_add:
        - SYS_PTRACE
      environment:
        - VIRTUAL_HOST=backend.localhost:3600

volumes:
    mongodb:
        driver: local
```
