### ISSUE TITLE
301 Redirect 

### ISSUE THREAD

**Issue by owenhoskins** [nginx-proxy/nginx-proxy#592]
Hello. Firstly thank you for this extremely useful project.

I've got what is likely a simple question:

I am permanently redirecting a now unused subdomain to my root domain. I can achieve this via editing `/etc/nginx/conf.d/default.conf` and adding a server block which specifies a 301 return.

However, each time a stop and run my app's container the default.conf file is regenerated, wiping out my edit.

Could you recommend a route to permanently make this customization? I have previous made a custom Dockerfile to include `proxy_buffer` rules, but I am not sure if that approach would work in this case.

Also, I've read this thread https://github.com/jwilder/nginx-proxy/issues/524 and following one of your responses I attempted to add a `/etc/nginx/vhost.d/my-domain.com` with a server block, but `jrcs/letsencrypt-nginx-proxy-companion` throws an error like "server block not expected in my-domain.com". My guess is I misinterpreted the advice -- perhaps you could offer a further explanation?

Thanks again and looking forward to your reply.

**Comment by kachkaev** [comment]
Why not to run a small container that talks to `nginx-proxy` in a standard way and does the redirect for you? E.g.:

```yml
version: "2"
services:
  root-redirect:
    image: ianneub/redirect
    container_name: root-host-handler
    environment:
      - VIRTUAL_HOST=${HOST},www.${HOST}
      - VIRTUAL_PORT=80
      - VIRTUAL_NETWORK=proxy
      - REDIRECT
      - LETSENCRYPT_HOST=${HOST},www.${HOST}
      - LETSENCRYPT_EMAIL=letsencrypt@${HOST}
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external:
      name: proxy
```

Here I used some [not-very-popular image that I once found on github](https://github.com/ianneub/docker-redirect), but you are free to change this to something better for yourself.
