### ISSUE TITLE
This site can’t be reached when trying https

### ISSUE THREAD

**Issue by ArielGueta** [nginx-proxy/nginx-proxy#627]
I'm trying to use my website with https. I read the docs and the only thing that I see that I need to do is to add:
`- /root/cert:/etc/nginx/certs`

This is my docker compose file, there is something that I am missing?

```yaml
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /root/cert:/etc/nginx/certs
    restart: always
  client:
    build:
      context: .
      dockerfile: DockerfileProdClient
    environment: 
      - NODE_ENV=production
      - VIRTUAL_HOST=mydomain.com,www.mydomain.com
    restart: always
  api:
    build: 
      context: .
      dockerfile: DockerfileProdApi
    environment: 
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo/db
      - VIRTUAL_HOST=api.mydomain.com,api.mydomain.com
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo:3.3
    ports:
      - "27017:27017"
    volumes: 
     - /db/data:/data/db
    restart: always
```
