### ISSUE TITLE
How to route subdirectory of a domain to a separate container or docker host?

### ISSUE THREAD

**Issue by tahir-gvs** [nginx-proxy/nginx-proxy#712]
I see it is possible to add custom virtual host config files by mounting /etc/nginx/vhost.d directory. 
So if we want to manually route a subdomain we can create a subdomain.domain.com.conf file in vhost.d with a proxy_pass directive. 

But what if we want to route subdomain.domain.com to one container and subdomain.domain.com/app to another container or directly to a server running on docker host. Is this possible?

**Comment by NoahO** [comment]
I agree, this is a use case for me too. I have 5 apps on the one box, pairing this with letsencrypt-nginx-proxy-companion means I must have 5 hostnames and 5 letsencrypt certificates for the same proxy server on the one box... It's very wasteful of letsencrypt's resources.

**Comment by bwoodmansee** [comment]
👍, I'm interested in this use case as well

**Comment by hydra1983** [comment]
You mean things like this?

```yaml
- VIRTUAL_HOST=${SUBDOMAIN}.${DOMAIN}
- VIRTUAL_PORT=6203
- VIRTUAL_PATH=~* ^(\/advisor-auth)(\/api)(\/.*)?$$
- VIRTUAL_PATH_REWRITE=^(\/advisor-auth)(\/api)(\/.*)$$ $$2$$3
```

**Comment by skleeschulte** [comment]
@hydra1983 Is there a container where these variables can be used, or did you just make them up?

**Comment by ciokan** [comment]
Anyone managed to get this working?

**Comment by rahimrahman** [comment]
I got this to work but I had to hard-code the `/etc/nginx/vhost.d/{your-virtual-hostname}` file.  So my `docker-compose.yml` file looks like this:

```
version: '3.1'
services:
  web:
    image: username/web:latest
    environment:
      - VIRTUAL_HOST=www.example.com

  api:
    image: fieldops360/app_links:latest
    environment:
      - VIRTUAL_HOST=the_api
      - VIRTUAL_PORT=3000

  nginx-proxy:
    container_name: nginx_proxy
    image: jwilder/nginx-proxy:alpine
    depends_on:
      - web
      - api
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d
```

and my `/etc/nginx/vhost.d/www.example.com` file:

```
        location ^~ /api {
                proxy_pass http://the_api/;
        }
```

`proxy_pass` value of `http://the_api/` and `http://the_api` (note the trailing slash) will yield two different behaviors: first one will take you to the root of `the_api` whereas the second one will pass on as `http://the_api/api`.

Hope that helps somebody.
