### ISSUE TITLE
How to properly tell nginx-proxy to use bridge from docker-compose?

### ISSUE THREAD

**Issue by patakijv** [nginx-proxy/nginx-proxy#729]
When I start nginx-proxy using

`docker run -d -p 80:80 -p 443:443 -v /var/run/docker.sock:/tmp/docker.sock:ro -v /etc/nginx/certs:/etc/nginx/certs:rw --name nginx-proxy jwilder/nginx-proxy`

I see the following network definition for the nginx-proxy container

```
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "c3d28dfbcfe6c8a4dd28f5d782c205f3cafdac990bb1d0685d4b62ba28e98a79",
                    "EndpointID": "6b1c06ecae27fd994d2a12b4d8818aa53b90b4153284af9e97e4396644e66445",
                    "Gateway": "172.24.26.1",
                    "IPAddress": "172.24.26.17",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:18:1a:11"
                }
            }
```

but if I start docker using docker-compose with the following docker-compose.yml file

```
version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    mem_limit: 4g
    `ports:`
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/certs:/etc/nginx/certs
```

if get the following network definition

```
            "Networks": {
                "nginxproxy_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "nginx-proxy",
                        "c091a1b37d8e"
                    ],
                    "NetworkID": "e05cc93cbe94d2bfc2a545df41c490f84be62329736a3ca74fab575ed014379f",
                    "EndpointID": "369993e43d114f2b5763048fc0451671450d8c3d21e93cad2c5428c93a8b5935",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02"
                }
            }
```

The problem is that all of the currently running containers don't have a special network definition and everything works just fine so I assume they are all using the `bridge` network when no configuration is specified and so as soon as I transition `nginx-proxy` to container and it starts using `nginxproxy_default` so now all of the containers are not reachable by the `nginx-proxy`.

I would prefer to have a solution that does not require I modify all of the other containers runtime definition to use a special network, rather I would like to be able to tell `nginx-proxy` to use the same network definition from `docker-compose` as it does when it is started using the `docker run` command above.

How do get `nginx-proxy` running from a `docker-compose` file and have it use the same network as it does when run from `docker run`?

**Comment by thomasleveil** [comment]
An easy way is to use the docker-compose syntax v1 which by default uses the bridge network.

If you must stay with syntax v2, see the [network_mode](https://docs.docker.com/compose/compose-file/#/networkmode) directive.

**Comment by patakijv** [comment]
Thanks! This worked great.
Now I have nginx-proxy and other containers running on the same host using `network_mode: bridge` and it all works great.
However, I am about to create a new project on the same host where I want two services to be able use a network just between each other but one of the services also needs to be routable from the nginx-proxy. So I would want 2 networks defined.

Does the `network_mode: bridge` mean I can't have multiple networks defined in docker-compose where one is the main bridge and another is project specific network just for the two services?

**Comment by thomasleveil** [comment]
It all documented [here](https://docs.docker.com/compose/networking/)

**Comment by nosovk** [comment]
Hello!
I've used different approach.
I've created new external network, not in docker-compose. Just from terminal. 
`docker network create nginx-proxy`
after I've added 
`
networks:
  default:
    external:
      name: nginx-proxy
`
into the end of each docker-compose.yml

that's all. docker-compose will use that network like a hub, and everything will work.

**Comment by kingpalethe** [comment]
I fought with this issue for quite a while. Some notes that might be useful for others: 

I was unable to use the "Multiple Networks" solution explained here:

https://github.com/jwilder/nginx-proxy#multiple-networks

It was unreliable for some reason, and furthermore presented a confusing chicken-or-the-egg problem, because it seems to suggest you need to start a client container (one that will be proxied) *before* you start the ngnix proxy. 

The solution that worked for me was this: https://github.com/jwilder/nginx-proxy/issues/729#issuecomment-286403035

And the `networks:` block needs to go AT THE END of each docker-compose, i.e, on the same level as `services` and not nested.

**Comment by kingpalethe** [comment]
Note, this solution also seems to require me to use links so my web container can still find my database container
https://docs.docker.com/compose/compose-file/#links

**Comment by buchdag** [comment]
This is a docker compose networking issue, not a project related issue.

**Comment by rmaafs** [comment]
Thanks to @nosovk, finally after a lot of hours I fixed it.
Some times we have **cached something**, In my case I deleted all my images, volumes & networks.

1. You need to create a custom network via terminal using:
`docker network create nginx-proxy`

2. Append the default network in your **nginx-proxy** `docker-compose.yml` file (This is my file):
```yaml
version: '3'
services:
  jw-nginx-proxy: # Becareful! Don't use the same name like the previous network created via terminal.
    image: jwilder/nginx-proxy
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /certs:/etc/nginx/certs:ro
    restart: always

# IMPORTANT Append the following lines!
networks:
  default:
    name: nginx-proxy
    external: true
```

### IMPORTANT!!! Use `docker-compose up --force-recreate` !!!

3. In my case, I've a simple service working, so I don't need `network_mode`, only I need `networks` configured. This is my file:
```yaml
version: "3"
services:
  app:
    image: test/myimage:latest
    ports:
      - "20202:20202"
    environment:
      VIRTUAL_HOST: api.mydomain.com # My custom domain!
    restart: always

# IMPORTANT Append the following lines!
networks:
  default:
    name: nginx-proxy
    external: true
```

### IMPORTANT!!! Use `docker-compose up --force-recreate` !!!

So, if I execute https://api.mydomain.com it works perfect!

4. Other example, In my case I've a backend connected to a database, but I need keep the database PRIVATE (only accesible by the backend locally), but I want the backend exposed. This is my file:
```yaml
version: "3"
services:
  mongodb:
    image: "mongo"
    container_name: "mongodb_container"
    volumes:
      - ./mongo-volume:/data/db
    command: mongod --port 21017
    ports:
      - "127.0.0.1:21017:21017" # VERY IMPORTANT! I'm binding this service, It means that only accessible via localhost.

  crypt-backend:
    image: test/mybackend:latest
    ports:
      - "20203:20203"
    environment:
      VIRTUAL_HOST: backend.mydomain.com # Your custom domain
      MONGO_PATH: "mongodb://mongodb:21017" # VERY IMPORTANT! If I want to connect to the MongoDB server, I need use the service name (mongodb), not localhost.
    restart: always
    depends_on:
      - mongodb

# IMPORTANT Append the following lines!
networks:
  default:
    name: nginx-proxy
    external: true
```
### IMPORTANT!!! Use `docker-compose up --force-recreate` !!!

So, if I execute https://backend.mydomain.com it works perfect as well!

I really hope you can solve your problem with my examples, I've been researching and testing a lot of times and it finally works!
I'm finally going to sleep tonight, but not before writing you a comment!
