### ISSUE TITLE
server <ip> down / VIRTUAL_PORT ignored

### ISSUE THREAD

**Issue by stefanfritsch** [nginx-proxy/nginx-proxy#802]
Hi,

how would I go about debugging the container discovery?

I run a gateone server (docker-compose below) and it is no longer recognized by nginx-proxy. It happened after the last nginx-proxy update, but I'm not sure if it is really related to the update.

Basically the server listens on 8701, the docker-compose has an `expose: 8701` and a `VIRTUAL_PORT: 8701` but the `default.conf` has `server <ip> down;`. Otherwise the `default.conf` is entirely correct, ip and everything. And if I change the `default.conf` to `server <ip>:8701;` everything works. But there is no error message in the log and I don't know enough about the way nginx-proxy builds the default.conf to help you with a specific reason.

Thanks,
Stefan

```
version: '2'

networks:
  proxy-tier:
    external:
      name: external

services:
  gateone-server:
    build: ./gateone_statup
    image: stefanfritsch/gateone_statup
    restart: unless-stopped
    container_name: gateone-server
    expose:
    - 8701
    networks:
    - proxy-tier
    environment:
      VIRTUAL_HOST: gateone.example.com
      VIRTUAL_PORT: 8701
      VIRTUAL_NETWORK: proxy-tier
      LETSENCRYPT_HOST: gateone.example.com
      LETSENCRYPT_EMAIL: it@example.com

  gateone-auth:
    image: zappi/oauth2_proxy
    restart: unless-stopped
    container_name: gateone-auth
    networks:
    - proxy-tier
    depends_on:
      - gateone-server
    command: --cookie-secure=true --provider="azure" --upstream="http://gateone-server:8701" --http-address="0.0.0.0:4180" --redirect-url="https://gateone.example.com/oauth2/callback" --email-domain="example.com"
    environment: ...
```

# Versions

```
root@se-dino:/mnt/Container Data/ssl/nginx-proxy# docker version
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64
 Experimental: false
root@se-dino:/mnt/Container Data/ssl/nginx-proxy# docker-compose version  # if you are using docker-compose
docker-compose version 1.11.2, build dfed245
docker-py version: 2.1.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
root@se-dino:/mnt/Container Data/ssl/nginx-proxy# docker images --format "{{.ID}}\t{{.Repository}}:{{.Tag}}" jwilder/nginx-proxy
f2e03275b4ca    jwilder/nginx-proxy:latest
```

# Log

```
root@se-dino:/mnt/Container Data/ssl/nginx-proxy# docker-compose logs nginx-proxy
Attaching to nginx-proxy
nginx-proxy          | forego     | starting dockergen.1 on port 5000
nginx-proxy          | forego     | starting nginx.1 on port 5100
nginx-proxy          | dockergen.1 | 2017/04/27 09:16:50 Generated '/etc/nginx/conf.d/default.conf' from 13 containers
nginx-proxy          | dockergen.1 | 2017/04/27 09:16:50 Running 'nginx -s reload'
nginx-proxy          | dockergen.1 | 2017/04/27 09:16:50 Watching docker events
nginx-proxy          | dockergen.1 | 2017/04/27 09:16:50 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx-proxy          | nginx.1    | 2017/04/27 09:16:54 [error] 75#75: *1 no live upstreams while connecting to upstream, client: 82.135.86.221, server: gateone.example.com, request: "GET /ws HTTP/1.1", upstream: "http://gateone.example.com/ws", host: "gateone.example.com"
nginx-proxy          | nginx.1    | gateone.example.com 82.135.86.221 - fritsch [27/Apr/2017:09:16:54 +0000] "GET /ws HTTP/1.1" 502 576 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
```

# default.conf

```
root@se-dino:/mnt/Container Data/ssl/nginx-proxy# docker exec nginx-proxy cat /etc/nginx/conf.d/default.conf
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Set appropriate X-Forwarded-Ssl header
map $scheme $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        return 503;
}
# gateone.example.com
upstream gateone.example.com {
                                ## Can be connect with "external" network
                # gateone_gateone-server_1
                server 172.20.0.3 down;
}
server {
        server_name gateone.example.com;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        return 301 https://$host$request_uri;
}
server {
        server_name gateone.example.com;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers '...';
        ssl_prefer_server_ciphers on;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/gateone.example.com.crt;
        ssl_certificate_key /etc/nginx/certs/gateone.example.com.key;
        ssl_dhparam /etc/nginx/certs/gateone.example.com.dhparam.pem;
        add_header Strict-Transport-Security "max-age=31536000";
        include /etc/nginx/vhost.d/gateone.example.com;
        location / {
                proxy_pass http://gateone.example.com;
                include /etc/nginx/vhost.d/gateone.example.com_location;
        }
}
```

## gateone.example.com

```
## Start of configuration add by letsencrypt container
location ^~ /.well-known/acme-challenge/ {
    allow all;
    root /usr/share/nginx/html;
    try_files $uri =404;
    break;
}
## End of configuration add by letsencrypt container
  location = /oauth2/auth {
    internal;
    proxy_pass http://gateone-auth:4180;
  }

  location /oauth2/ {
    proxy_pass http://gateone-auth:4180;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme $scheme;
  }
```

## gateone.example.com_location

```
auth_request /oauth2/auth;
error_page 401 = https://gateone.example.com/oauth2/sign_in;
proxy_buffering off;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
```

**Comment by thomasleveil** [comment]
are the nginx-proxy container and the gateone container on the same docker network?

**Comment by stefanfritsch** [comment]
Yes, together with half a dozen more that are found correctly. 

And the gateone container's ip address is found correctly as well; I just have to replace "down" with the port.

**Comment by hanselke** [comment]
having the same issue here. @stefanfritsch does it work relibably after you just edit the default.conf?

**Comment by stefanfritsch** [comment]
It seems to work until something changes that causes nginx-proxy to rebuild the `default.conf`. But until I restart a container or something like that gateone works.

**Comment by psimona** [comment]
Experiencing the same issue with the offical owncloud container.

**Comment by martinalig** [comment]
Same issue here with graylog container.

**Comment by gartz** [comment]
Same issue here using ambassadors to proxy on 80

**Comment by jako512** [comment]
Same issue with discourse container on port 80

**Comment by mateusmaso** [comment]
Same problem here. Downgraded to 0.4.0/0.5.0 but it's still broken.

**Comment by gartz** [comment]
I created another nginx server using the official nginx project, with a constant reverse project to the projects that are having this issue and configured a multiple URL from the nginx-proxy to the other nginx.

It's a workaround, but since I don't know a better way, it's working fine here now.

**Comment by mateusmaso** [comment]
@gartz thanks for sharing your workaround, but for now I'll stick with a lazier one which is to hardcode the port and remove the down with ```vi /etc/nginx/conf.d/default.conf``` and then restarting nginx with ```nginx -t && service nginx reload```

**Comment by gartz** [comment]
@mateusmaso yeah, that solution doesn't work for me, because we start and stop containers as we need for development and the `default.conf` is rebuild from the template. So we would need to edit that file all the time, that's why I did this workaround that is static always working, even if we change docker-compose or stop/start containers.

**Comment by jwilder** [comment]
Can someone provide a self-contained compose file that can reproduce this issue?  I tried w/ the one in the issue description, but it worked for me.

**Comment by jwilder** [comment]
My guess is that the `down` is getting added incorrectly due to this change: https://github.com/jwilder/nginx-proxy/commit/4f5351265ab47111169a8f56b897bac999f86ff6

**Comment by jannikweichert** [comment]
Are there solutions available?

**Comment by smoebody** [comment]
you can explicitly start the container with the port exposed that you want to connect to, e.g.:

    docker run --expose 1234 -e 'VIRTUAL_PORT=1234' -e 'VIRTUAL_HOST=example.com" my/image

**Comment by domikrueger** [comment]
I still have the same problem.
Fortunately I only needed to access one port of my container, so exposing this port (8080:8080) instead of using the VIRTUAL_PORT environment variable worked for me.
However it would be great if someone can fix this.

**Comment by ntnn** [comment]
I'm hitting this issue as well with the znc container.

I suspect this happens because I'm publishing port 6697 on the host (for directo tcp connections to the service) and port 1025 is behind nginx-proxy for TLS. My best guess is, that this confuses the templating to check on port 6697 instead of 1025.

```yaml
---
version: '3.4'

volumes:
  znc-data: {}

networks:
  proxy_backend:
    external: true

services:

  znc:
    image: znc:latest
    environment:
      LETSENCRYPT_EMAIL: mail@example.com
      LETSENCRYPT_HOST: znc.example.com
      VIRTUAL_HOST: znc.example.com
      VIRTUAL_PORT: 1025
    ports:
      - 6697:6697
    networks:
      - proxy_backend
    volumes:
      - znc-data:/znc-data
    deploy:
      mode: global
```

This is the config I'm using with docker swarm. `expose`ing port 1025 doesn't help as it is ignored by docker swarm.

Adding port 1025 to the upstream configuration manually works as well, but is also being changed back to `down` as soon as the template is regenerated.

Hope this helps.

**Comment by Assada** [comment]
Same issue... Some solutions?

**Comment by ntnn** [comment]
@smoebody 
Swarm doesn't act on expose, it only prints a message that this directive isn't required, as all containers within the same network can reach each other.

**Comment by smoebody** [comment]
but the nginx-proxy is acting on expose

**Comment by xoancosmed** [comment]
I am getting a very similar problem. I launch the proxy with:

`sudo docker run -d --name proxy -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy`
`sudo docker network connect proxy_net proxy`

I have some container which I run using the "docker run" command, and they work well.

Now I am trying to launch a service with this "docker-compose":

`version: "2"

services:
  web:
    build: .
    volumes:
      - ./:/app
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST="api.mydomain.com"
      - VIRTUAL_PORT="80"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
networks:
  default:
    external:
      name: proxy_net`

When I go to api.mydomain.com I am getting a 403 error.

**Comment by aaaaahaaaaa** [comment]
Same thing happening when using [this container](https://netdevops.me/2017/flask-application-in-a-production-ready-container/) (uwsgi + nginx + flask). Port 80 is properly exposed.

**Comment by phal0r** [comment]
I was facing the problem and properly using expose in the docker-compose file as mentioned by @smoebody fixed the problem.

**Comment by aaaaahaaaaa** [comment]
It didn't for me unfortunately. I switched to Traefik and it works nicely.

**Comment by weeger** [comment]
Same issue with odoo and phpmyadmin

**Comment by weeger** [comment]
Seems like exposing port solves this problem, but I still have a "502 Bad Gateway" message (working when accessing the service with explicit ip number)

**Comment by weeger** [comment]
For me there are useful only for external ports purpose :)

**Comment by hthieu1110** [comment]
Hi, I still have the problem. 

I'm trying to build a generic Uwsgi Docker image for running python app. And in this Image  I don't have EXPOSE (on Docker document, this is just for documentation) for being flexible.

My docker-compose.yml looks like that:
```
version: '3.0'

networks:
  backend:
  proxy:

volumes:
  mariadb_data:

services:
  proxy-nginx:
    image: jwilder/nginx-proxy:alpine
    depends_on:
      - app-blog
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy
      
  app-blog:
    image: bkinno/uwsgi:latest
    expose:
      - "5001"
    volumes:
      - .:/src
    networks:
      - backend
      - proxy
    environment:
      VIRTUAL_HOST: blog.mydomain.com
      VIRTUAL_PROTO: uwsgi
      VIRTUAL_PORT: 5001
    working_dir: /src
    command: >
      bash -c "pip install -r requirements.txt --user --upgrade
      && uwsgi --socket :5001 \
      --plugins=python3 \
      --module blog.wsgi \
      --static-map /static=/src/static"
```

But I still have server <ip> down :( It works well when I change this to server <ip>:<5001>. When inspecting the container, there is no segment exposedPorts.

Do you have same ideas to make this works  ? :(

**Comment by weeger** [comment]
Did you just tried to remove this part : 
```yml
   expose:
      - "5001"
```

Using `expose` opens the port to the **real world**, but **VIRTUAL_PORT**  indicates which port the proxy have to use internally, in the local network. Basically, I have only one port using server port 80, but I have a bunch of ones using it locally. So they should not be used in the same time.

**Comment by hthieu1110** [comment]
@weeger , hi, thanks for your reply.

On Docker document, expose is used for opening port to linked network only, not to realworld, ports is used instead (if I understand well). I've tried to remove it but no luck :( 

For this moment, I can make this works only by setting publish mode = host. But with this approche, I can have only one container by service, which is not purpose of swarm.

Does your stack work without expose? One thing I've marked in my quedtion above is for being generic, I have not EXPOSE in my Docker image but in compose only. 

Thanks.

**Comment by ItsEcholot** [comment]
> Does your stack work without expose? One thing I've marked in my quedtion above is for being generic, I have not EXPOSE in my Docker image but in compose only.

That is exactly the problem... Using docker swarm it seems the expose setting in the compose file is being ignored. Therefore nginx-proxy will only work if you have an EXPOSE in your Docker image.
Is it possible to fix this somehow? Took ages to figure that one out.

**Comment by weeger** [comment]
Sorry I think you've right, I guess my expose is always set in my dockerfile. My problem was with the port binding system which is not the same problem than expose.

**Comment by hthieu1110** [comment]
Hi, thanks for your replies.

I've figured out that in compose, if I use ports with mode = host instead of expose, it works:
```
    ports:
      - target: ${SOCKET_BLOG}
        published: ${SOCKET_BLOG}
        protocol: tcp
        mode: host
```

But the problem is in this mode, it will work with one one container (due to most host => it shares the same port range).

After all I've decided to switch to Traefik because I've got another problem with https of nginx-proxy :-s
