### ISSUE TITLE
Manually setting upstream

### ISSUE THREAD

**Issue by TroelsL** [nginx-proxy/nginx-proxy#832]
I have a docker container with --net=host as it is a service that sends magic packets for Wake on LAN, and I can't (as far as I understand) from within the docker network.

However, when starting my container, it is generated with an empty upstream block, causing my nginx instance to cease working.

Manually adding
    server 192.168.1.228:10440;

Resolved the issue, but it is obviously not a good soluton as it will be overwritten eventually.

Am I doing something wrong here, is it not supported, or is there any way around it?

Container is run with:

    docker run
         --name wol
         --net=host
         -e "VIRTUAL_HOST=wol.example.com"
         -e "VIRTUAL_PORT=10440"
         -e "LETSENCRYPT_HOST=wol.example.com"
         -e "LETSENCRYPT_EMAIL=someone@example.com"

**Comment by TroelsL** [comment]
Well I found a workaround, but I really don't like it. I've modified nginx.tmpl to allow manual upstream blocks like so:

    # {{ $host }}
    upstream {{ $upstream_name }} {
    {{ if (exists (printf "/etc/nginx/vhost.d/%s_upstream" $host)) }}
    include {{ printf "/etc/nginx/vhost.d/%s_upstream" $host}};
    {{ end }}

I'm sure there is a much better solution, but I can't quite figure out where $container.Addresses and $CurrentContainer.Networks come from.

I can't help but think the correct solution for --net=host would be to use VIRTUAL_PORT and the host's IP address. But the IPv4 doesn't seem to be in the output for docker network inspect, which I assume is there nginx-proxy gets it's values.

Any ideas are more than welcomed.

**Comment by metasim** [comment]
I'm having the same problem Oddly, I have one container with `--net=host` and it *does* work, but the another I can't get to work at all.

**Comment by TroelsL** [comment]
Yeah, it does seem somewhat arbitrary when it works and when it doesn't. I'm sure there's a pattern that I was missing. Anyway, since my update to the template, I haven't had any issues.
I've later had to modify the template heavily anyway to allow auth_rewrite, cors, etc.

Still, a native solution would be better.

**Comment by bjornicus** [comment]
rather than the hosts IP address, which I don't think is available to the nginx-proxy container if it's not running in host mode, you can usually use the default gateway address.  

The caveat is that the container running in host mode needs to be listening on the docker bridge interface; some containers/apps (e.g. consul) bind to specific interfaces only so you have to tell it to listen on all by binding to 0.0.0.0, or at least include the bridge network interface that nginx-proxy is running on.

**Comment by martinvw** [comment]
> Any ideas are more than welcomed.

@TroelsL maybe a little bit late, but what would you think if introducing a VIRTUAL_IP setting and generating it bases on that if its available?

**Comment by TroelsL** [comment]
@martinvw That would be a fine solution as I see it. It is easy to understand and doesn't require people to alter the config files manually, which I assume is why many people use this container.

The port would also need to included.

**Comment by martinvw** [comment]
Yes indeed!

**Comment by danmandle** [comment]
@jwilder Thoughts on this?

**Comment by AxxlFoley** [comment]
I would love that "VIRTUAL_IP" option !

**Comment by blackandred** [comment]
@AxxlFoley I think that VIRTUAL_IP could be pretty easy to implement. I will have to take a look today/tommorow at it and implement such VIRTUAL_IP, so it would allow to set a fixed upstream ip address. Unless this is a issue.

**Comment by blackandred** [comment]
After checking it seems that `network_mode: host` works for me. The nginx is on the host mode, the rest is on the bridge, and the service discovery and proxy is working.

**Comment by cerw** [comment]
So what is the official workaround / fix? I am still struggling.. about to hack the default proxy config to capture my HOST only host.

TA

**Comment by danmandle** [comment]
My workaround was to move to Traefik. 😐

**Comment by TroelsL** [comment]
I moved to Traefik as well. Can't say I regret it.

**Comment by night-gold** [comment]
Interrested in a solution here too... I rooled back from Traefik as the damn thing is completely useless when it comes to whitelist...

**Comment by mrchainman** [comment]
I would love to be able to manually set the upstream, my usecase is the following:
I have webmin running locally (not inside a docker container) and want to redirect webmin.mydomain.com to the local instance.
Reason for it is, that webmin listens on Port 10000 and I often find myself in networks, where I can only access http and https, so the nginxcontainer could redirect it.
I created a dummy container and then changed the upstream, but of course it keeps being overwritten.

**Comment by lucaslgr** [comment]
Hi guys, I'm trying to run `nginx-proxy` container and behind it, I want to run Home Assistant container, that will receive request proxied by my nginx container as other applications also.
I'm trying to configure the Home Assistant container to use network mode as host, and run the shared bridge network for nginx as well but nothing is working.

These are my two docker compose files, if you can help me:

nginx-proxy:
```yml

version: '3.3'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    restart: always
    ports:
      - "80:80"
    environment:
      DEFAULT_HOST: pihole.guimalab.lan
    volumes:
      - ./current/public:/usr/share/nginx/html
      - ./vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    command: "--net host"
networks:
  default:
    external:
      name: nginx-proxy
```

home-assistant:
```yml

version: '3.3'

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - './config:/config'
      - '/etc/localtime:/etc/localtime:ro'
      - '/run/dbus:/run/dbus:ro'
    expose:
      - 8123
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: ha.guimalab.lan
      VIRTUAL_POST: 8123
    privileged: true
    command: "--net host"
    network_mode: host

networks:
  nginx-proxy:
    external: true
```

The way that I'm setting the networks for each container is correct? I was in doubt with the way that I configured the `--net host` was correct too.
