### ISSUE TITLE
Need websockets and multiple virtual ports

### ISSUE THREAD

**Issue by dcplaya** [nginx-proxy/nginx-proxy#911]
I want to use this to proxy a Unifi-Video docker. But I need to also pass through port 7446 in addition to the standard 7080 port. Below is the nginx setup that will work in a normal install (No docker)

``` nginx
server {
        listen 80;
        listen 443 ssl http2;
        listen [::]:443 ssl http2;

        server_name  uvc.net.net;                   #CHANGE THIS
 

      ssl_certificate      /etc/letsencrypt/live/uvc.net.net/fullchain.pem;  #CHANGE THIS
        ssl_certificate_key  /etc/letsencrypt/live/uvc.net.net/privkey.pem;  #CHANGE THIS

        # Logs
        access_log /var/log/nginx/uvc-access.log; #CHANGE THIS
        error_log /var/log/nginx/uvc-error.log; #CHANGE THIS


        # Lets Encrypt Override
        location '/.well-known/acme-challenge' {
                root /var/www/proxy;
                auth_basic off;
        }


        location / {
                # Proxy
                      # Reverse Proxy
                proxy_redirect          off;
                proxy_pass_header       Server;
                proxy_set_header        X-Real-IP $remote_addr;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header        X-Scheme $scheme;
                proxy_set_header        Host $http_host;
                proxy_set_header        X-NginX-Proxy true;
                proxy_connect_timeout   5;
                proxy_read_timeout      240;
                proxy_intercept_errors  on;

                proxy_pass             http://10.10.10.10:7080/; #CHANGE THIS

## WebSockets
        location /ws/ {
    proxy_pass http://10.10.10.10:7080/ws/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}


        # Redirect to HTTPS
                  if ($scheme = http) {
                       return 301 https://$server_name$request_uri; #CHANGE THIS (uncomment) after cert installation
                  }
        }
}

server {
        listen 7446 ssl http2;

        server_name  uvc.20.net.net;                   #CHANGE THIS
  
        ssl_certificate      /etc/letsencrypt/live/uvc.net.net/fullchain.pem;  #CHANGE THIS
        ssl_certificate_key  /etc/letsencrypt/live/uvc.net.net/privkey.pem;  #CHANGE THIS

        # Logs
        access_log /var/log/nginx/uvc-access.log; #CHANGE THIS
        error_log /var/log/nginx/uvc-error.log; #CHANGE THIS

## WebSockets
    location / {
    proxy_pass http://10.10.10.10:7445;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
        }

}
```

My docker setup for Unifi-Video is below (Its an Ansible script but still has all the info, I have edited my TLDN out)

``` yml
  - name: Create and start container
    docker_container:
      name: unifi-video
      image: pducharme/unifi-video-controller
      security_opts:
        - "apparmor:unconfined"
      capabilities:
        - SYS_ADMIN
        - DAC_READ_SEARCH
      published_ports:
        - "7443:7443"
        - "7445:7445"
        - "7446:7446"
        - "7447:7447"
        - "7080:7080"
        - "6666:6666"
      env:
        PUID: "{{uid.stdout}}"
        PGID: "{{gid.stdout}}"
        TZ: America/New_York
        DEBUG: 1
        VIRTUAL_HOST: "security.{{domain}}"
        LETSENCRYPT_HOST: "security.{{domain}}"
        LETSENCRYPT_EMAIL: "{{email}}"
        VIRTUAL_PORT: 7080
        WEBSOCKETS: 1
      volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - "/opt/unifi-video/config:/var/lib/unifi-video"
        - "/mnt/unifi-video:/usr/lib/unifi-video/data/videos"
        - "/opt/unifi-video/logs:/var/log/unifi-video"
      networks:
        - name: cloudbox
          aliases:
            - unifi-video
      restart_policy: always
      state: started
```
