### ISSUE TITLE
Docker Swarm Mode?

### ISSUE THREAD

**Issue by ghost** [nginx-proxy/nginx-proxy#927]
Is there any support for Docker Swarm Mode yet?

**Comment by marcwaz** [comment]
I have the following errors in swarm mode on one node only:

 upstream server temporarily disabled while connecting to upstream

 connect() failed (110: Connection timed out) while connecting to upstream

Have you planned to support swarm mode ?

**Comment by kennethklee** [comment]
works for me on swarm mode, but only with the `latest` and `alpine` images since those are built from `master`.

it's possible the connection timeout is from the ingress network it tries to connect on.

**Comment by biels** [comment]
@kennethklee Did you try it with the proxy and applications in different stacks (deployed using docker stack deploy -c docker-compose.yml). This would be the ideal use case because you can deploy and remove individual stacks without messing with the proxy stack.

**Comment by arefaslani** [comment]
@kennethklee Can you provide an example with compose file for a docker stack with multiple nodes?

**Comment by arefaslani** [comment]
@biels Could you run nginx-proxy in swarm mode with docker stack?

**Comment by loic294** [comment]
@arefaslani Did you figure out how to make it work on multiple nodes in Swarm mode. It only seems to connect to services on the same node.

**Comment by biels** [comment]
I found a service called traefik that does exactly the same and seems to
work a little bit better. However I'm seriously considering switching over
to kubernetes.

**Comment by arefaslani** [comment]
@loic294 All I did was forking the project and manually change [this line](https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L17) to `server {{ .Network.IP }}:3000;` and it works. But the problem is that my API runs on port 3000 and my frontend app server runs on 3001 and in this solution I can't have both. 
After that I thought It's a good idea to use variables instead of hardcoding ports. I don't know much about go and it's templating language, but I thought $CurrentContainer in [this line](https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L1) is a variable and change [this line](https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L17) to `server {{ .Network.IP }}:{{$CurrentContainer}}`. But docker-gen complains that $CurrentContainer is not a variable.

**Comment by loic294** [comment]
@arefaslani I almost changed everything for Kubernetes but got it to work with normal Nginx, but without this library. It's far from optimal but for my use case, it works great. In my `docker_stack.yml` file, I created a `nginx` service:

```
nginx:
    image: nginx:latest
    volumes:
      - ~/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - proxy
    depends_on:
        - metabase
        - api
    deploy:
      placement:
        constraints: [node.role == manager]
```
The placement is important because I manually uploaded the `nginx.conf` file. There is probably a way to sync it between node but it was getting to complex. Now my services in the stack file look something like this (here is the example for metabase):
```
 metabase:
    environment:
      - ...
    image: 'metabase/metabase:latest'
    networks:
      - proxy
      - ...
    depends_on:
      - ...
    ports:
      - 3000:3000 <-- not sure this is required, but I was using it to test
    deploy:
      replicas: 1
      update_config:
        parallelism: 3
        delay: 10s
      restart_policy:
        condition: on-failure
```
Finally the `nginx.conf` look something like this:

```
user  www-data;

events {
    worker_connections  1024;
}

http {

	upstream api-app {
			server api:8500;
	}

	server {
			listen 80;
			server_name api.example.com;

			location /  {
					proxy_pass http://api-app;
					proxy_http_version 1.1;   <-- These lines allow websocket to pass.
					proxy_set_header Upgrade $http_upgrade;
					proxy_set_header Connection "upgrade";
					proxy_read_timeout 86400;
			}
	}
	upstream metabase-app {
			server metabase:3000;
	}

	server {
			listen 80;
			server_name metabase.example.com;

			location / {
					proxy_pass http://metabase-app;
			}
	}

}
```
The super important part is that you need to expose the port of your app in the `Dockerfile`.  For example, my api image has a `EXPOSE 8500`. This allow Nginx to know which port to listen to.

I really hope that nginx-proxy solves the issue because there solution is way cleaner.

**Comment by arefaslani** [comment]
[docker-gen](https://github.com/jwilder/docker-gen) `Network` structure doesn't have `Port` property.
```go
type Network struct {
    IP                  string
    Name                string
    Gateway             string
    EndpointID          string
    IPv6Gateway         string
    GlobalIPv6Address   string
    MacAddress          string
    GlobalIPv6PrefixLen int
    IPPrefixLen         int
}
```
So one solution is to change [these lines](https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L14-L21) in [nginx-proxy](https://github.com/jwilder/nginx-proxy) template to support port through `VIRTUAL_PORT` env variable:
```diff
{{ else if .Network }}
    # {{ .Container.Name }}
    {{ if .Network.IP }}
        {{ if .Container.Env.VIRTUAL_PORT }}
            server {{ .Network.IP }}:{{ .Container.Env.VIRTUAL_PORT }};
        {{ else }}
-          server {{ .Network.IP }} down;
+         server {{ .Network.IP }}:{{ .Container.Env.VIRTUAL_PORT }}; 
        {{ end }}
    {{ else }}
        server 127.0.0.1 down;
    {{ end }}
{{ end }}
```
Then rebuild the image and use `VIRTUAL_PORT` env variable for setting upstreams in swarm mode, correctly. It worked well for me.

**Comment by bfwg** [comment]
Any updates?

**Comment by zodern** [comment]
I am working on a solution for Meteor Up: [nginx-proxy-swarm-upstream](https://github.com/zodern/nginx-proxy-swarm-upstream).

**Comment by arefaslani** [comment]
@zodern This image works well with swarm mode. Formerly I created the [nginx-autoconf](https://github.com/arefaslani/nginx-autoconf) to work with swarm mode. But then I realized that just by changing the original template and rebuilding, this image works well in swarm mode.

**Comment by zodern** [comment]
Thanks @arefaslani. That should work for most apps.

There are two main problems that [nginx-proxy-swarm-upstream](https://github.com/zodern/nginx-proxy-swarm-upstream) solves:
1. Adds support for sticky sessions, which requires each task's ip address to be listed as an upstream server in the nginx config. 
2. Allow nginx-proxy and the service tasks to be on different servers

**Comment by arefaslani** [comment]
@zodern I don't know what sticky session is, but for problem #2 I use nginx proxy and service tasks in different servers (tested in 2 different machines created by docker machine in a swarm)

**Comment by bfwg** [comment]
I end up wrote a customize nginx.conf file alone with `nginx:latest` container. It works perfectly for swarm mode.

**Comment by radyz** [comment]
@arefaslani , care to share examples of your service's configurations to make it work in swarm mode accross different nodes :)

**Comment by arefaslani** [comment]
# Configuration
## Build your custom Nginx Proxy
Create a Dockerfile like this:
```
FROM jwilder/nginx-proxy
COPY nginx.tmpl nginx.tmpl
```
Copy nginx-proxy's nginx.tmpl alongside your docker file and change it as [this comment](https://github.com/jwilder/nginx-proxy/issues/927#issuecomment-391334432). Then name and build your new proxy with the new template file.

## Docker Compose file

```
version: "3.1"

volumes:
  nginx-certs:
  nginx-vhosts:
  nginx-letsencrypt-challenge:

services:
  app:
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 'ssl://0.0.0.0:3000?key=/etc/nginx/certs/beta.chanka.ir.key&cert=/etc/nginx/certs/beta.api.chanka.ir.crt'"
    volumes:
      - nginx-certs:/etc/nginx/certs
    ports:
      - 3000:3000
    environment:
      - RAILS_ENV=production
      - VIRTUAL_HOST=example.com
      - VIRTUAL_PORT=3000
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=example.com
      - LETSENCRYPT_EMAIL=your@email.com

  nginx-proxy:
    image: your/nginx-proxy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-vhosts:/etc/nginx/vhost.d
      - nginx-letsencrypt-challenge:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.8.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhosts:/etc/nginx/vhost.d
      - nginx-letsencrypt-challenge:/usr/share/nginx/html
```

Like the example above add `VIRTUAL_PORT` to your service. Note that I added Letsencrypt conf just because everybody wants to use it. the next thing is that I've added `nginx-certs` volume to the Rails app because Puma needs certs to start with HTTPS.

# How does it work
NOTE: All the things I write next is just to clarify what does these configs if you don't understand some parts. If you understand it, go and config yours.

## Volumes
There are 3 volumes in this compose file:
* **nginx-certs**: Let's Encrypt certificates
* **nginx-vhosts**: configuration of vhosts
* **nginx-letsencrypt-challenge**: Letsencrypt challenge files.
## Services
There are 3 services in this compose file:
1. **app**: The application. In this case a `Rails` application with `Puma` web server.
    * Environment Variables:
      * RAILS_ENV: set to production to force Puma to run in production mode.
      * VIRTUAL_HOST: Name of the virtual host (your domain name)
      * VIRTUAL_PORT: The port in which your application runs
      * VIRTUAL_PROTP: Set to https to force your app to serve https traffic.
      * LETSENCRYPT_HOST: Must be equal to `VIRTUAL_HOST`. Letsencrypt uses this variable to generate certs for the specified domain.
      * LETSENCRYPT_EMAIL: Letsencrypt uses this email to send notifications about your certs
    * Volumes:
      * nginx-certs: certificates generated by letsencrypt. Puma needs these certs to start in ssl mode. If you don't use Puma or Rails, This volume is useless.

2. **nginx-proxy**: The reverse proxy.
    * Volumes:
      * nginx-certs: To use certs generated by Letsencrypt
      * nginx-vhosts: Configuration of vhosts
      * nginx-letsencrypt-challenge: To serve chanllenge files to letsencrypt

3. **letsencrypt**:
    * Volumes:
      * nginx-certs: To create/renew Let's Encrypt certificates
      * nginx-vhosts: To change the configuration of vhosts (needed by Let's Encrypt)
      * nginx-letsencrypt-challenge: To write challenge files.
