### ISSUE TITLE
Frontend and backend run on different ports gets 502 Bad Gateway

### ISSUE THREAD

**Issue by thegenius314** [nginx-proxy/nginx-proxy#939]
Hi Peoples
I'm currently running a container with my web application and it communicates through two ports,
for the frontend and backend. 
When I run the docker compose file (which starts the app and the proxy) it gives me a 502 Bad gateway
when I run with only one port it serves that part of the app.
Im passing the port with the "VIRTUAL_PORT=80" is there a way to pass more than one port or if I make a separate container for the Frontend how would I get the proxy to speak to both containers with one request?
Thank in advance,

docker-compose

`reverseproxy:  
  image: jwilder/nginx-proxy

  ports:
      - "80:80"
      - "8080:8080"
  volumes:
      - /var/run/docker.sock:/tmp/docker.sock

myapp:
  depends_on:
    - reverseproxy
  build: ./app-files
  environment:
     - "VIRTUAL_HOST=my-domain.com"
     - "VIRTUAL_PORT=80,8080"
  expose:
     - 80
     - 8080`

**Comment by kamermans** [comment]
Hi,

> is there a way to pass more than one port?

No, currently you can only expose one port per container.

> if I make a separate container for the Frontend how would I get the proxy to speak to both containers with one request?

One request can only go to one place.  I imagine in this scenario your browsers sends a request to the Frontend, and the Frontend needs to send a request to the Backend.  It would be good practice to separate them anyway, and with `nginx-proxy`, the solution to this problem is to give the Frontend and the Backend different hostnames, like `www.foo.com` and `backend.foo.com`.

Here's an example (untested) based on your config:
```yml
myapp-backend:
    build: ./app-files
    environment:
        - "VIRTUAL_HOST=backend.my-domain.com"
        - "VIRTUAL_PORT=8080"
    expose:
        - 8080

myapp-frontend:
    depends_on:
        - myapp-backend
    build: ./app-files
    environment:
        - "VIRTUAL_HOST=my-domain.com"
        - "VIRTUAL_PORT=80"
    expose:
        - 80

reverseproxy:
    image: jwilder/nginx-proxy
    depends_on:
        - myapp-frontend
        - myapp-backend
    ports:
        - "80:80"
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock
```
